### ISSUE TITLE
How much disk space does wikidata need while importing?

### ISSUE THREAD

**Issue by khanhhung2512** [gnosygnu/xowa#102]
According to home/wiki/Special:XowaDownloadCentral, wikidata needs only about 35 GB. However, the extracted xml file is about 180 GB (.bz is only 10 GB though). So, if it needs another 180 GB while importing, then I'll probably have to buy a new HDD just to import it.

**Comment by gnosygnu** [comment]
Sorry for the late reply. It should only need 45 GB:
* 10 GB for the bz2 file
* 35 GB for the final output

The Import/Offline has an option to "read from compressed file". If this is chosen, then only the bz2 is used; the xml is not unpacked.

Hope this helps. Thanks.

**Comment by gnosygnu** [comment]
I'm marking this issue closed as I think the question is answered. Feel free to reopen if there's anything else. Thanks.
