### ISSUE TITLE
page_load fail

### ISSUE THREAD

**Issue by khanhhung2512** [gnosygnu/xowa#104]
I have:
+ Xowa win x64 3.11.2.2
+ Wikidata 20161101: Imported
+ Wikipedia vn 20161101: Imported
+ Wikipedia en 20161101: Pre-built
![web crawler](https://cloud.githubusercontent.com/assets/23390760/20399898/4c7cc624-ad25-11e6-816f-a5000312a191.jpg)

> 20161117_171702.499 page.load: url=en.wikipedia.org/wiki/Web_crawler
20161117_171702.517 page_load fail: page=Web crawler err=[err 0] <gplx> idx mode not closed
[trace]:
  gplx.core.brys.fmtrs.Bry_fmtr.Compile(Unknown Source)
  gplx.core.brys.fmtrs.Bry_fmtr.Bld_bfr_ary(Unknown Source)
  gplx.core.brys.fmtrs.Bry_fmtr.Bld_bfr_many(Unknown Source)
  gplx.Gfo_usr_dlg_base.Bld_msg_many(Unknown Source)
  gplx.Gfo_usr_dlg_base.Warn_many(Unknown Source)
  gplx.core.brys.Bry_err_wkr.Fail(Unknown Source)
  gplx.core.brys.Bry_err_wkr.Fail(Unknown Source)
  gplx.core.brys.Bry_rdr.Find_fwd(Unknown Source)
  gplx.core.brys.Bry_rdr.Find_fwd_rr(Unknown Source)
  gplx.xowa.htmls.core.wkrs.imgs.atrs.Xoh_img_src_data.Parse(Unknown Source)
  gplx.xowa.addons.wikis.pages.syncs.core.loaders.Xosync_page_loader.Add_img(Unknown Source)
  gplx.xowa.addons.wikis.pages.syncs.core.loaders.Xosync_page_loader.Parse(Unknown Source)
  gplx.xowa.htmls.core.Xow_hdump_mgr__load.Parse(Unknown Source)
  gplx.xowa.htmls.core.Xow_hdump_mgr__load.Load(Unknown Source)
  gplx.xowa.htmls.core.Xow_hdump_mgr__load.Load_by_edit(Unknown Source)
  gplx.xowa.wikis.pages.Xowe_page_mgr.Load_page(Unknown Source)
  gplx.xowa.guis.views.Load_page_wkr.Thread__exec(Unknown Source)
  gplx.core.threads.Gfo_thread_pool.Run_wkr(Unknown Source)
  gplx.core.threads.Gfo_thread_pool.Invk(Unknown Source)
  gplx.Gfo_invk_.Invk_by_msg(Unknown Source)
  gplx.core.threads.Thread_adp.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)

**Comment by gnosygnu** [comment]
Hi! Thanks for the report and the error stack.

I was able to reproduce this on my side. This was a bug in the page sync code. It failed to handle some math images correctly (those with "~{}")

I fixed this and made a preview release. See: https://drive.google.com/open?id=0B9cb52zjL2rINTJ3RUhPdUtvV28 .

Thanks!

**Comment by gnosygnu** [comment]
This item is included in tonight's [v3.12.1.1](https://github.com/gnosygnu/xowa/releases) release. I'm marking this ticket closed, but feel free to reopen if there are issues.

Thanks.
