### ISSUE TITLE
Display issue on Windows 8.1, status bar is masked.

### ISSUE THREAD

**Issue by Cocoa-Cream** [gnosygnu/xowa#105]
Hi, I installed Xowa 32-bit (3.11.2.1, built on 2016-11-14 01:55 ) on Windows 8.1.
Everything is fine except status bar doesn’t display properly and its bottom is truncated (only the top quarter or so of the text appears which makes it unreadable).
It looks as if the quite thicker window borders prevented the display calculations to go well.
I am saying that because it looks like a bug I saw happening with general Windows programming when system metrics are not fully taken into account. But I don’t know about Java.
Anyway I am attaching a screenshot of the application window.
Thanks.
CC
![xowa_bug](https://cloud.githubusercontent.com/assets/23625011/20470964/a40927cc-afad-11e6-96c3-ecf7477d8d07.png)

**Comment by gnosygnu** [comment]
Hi! 

Thanks for the screenshot. This is a known issue which I haven't been able to reproduce.

I'm going to change the layout in the future, but for now, you can use the workaround here:
https://github.com/gnosygnu/xowa/issues/24#issuecomment-141872998

I excerpt again below the break. Let me know if it doesn't work, or if you have any issues.

Thanks!

----

*  Go to home/wiki/Help:Options/Window
* Change "Adjustment type" to "relative"
* Change "Adjustment rect" to "0,0,0,-20". Note that "-20" means make the HTML box 20 pixels shorter, which will bring the progress window into view. Experiment with the "-20" number until it suits your preference.
* Click the Save button -- the floppy disk icon along the middle-right margin of the screen.

**Comment by GitterHubber** [comment]
I can confirm that even I have the same problem, on Xowa 32bit, 3.2.1.1, Windows 7, I guess its something to do with the monitor resolution (just guessing here !) but if you have a 1920 x 1080 monitor handy, probably you could recreate the problem...

**Comment by gnosygnu** [comment]
> but if you have a 1920 x 1080 monitor handy, probably you could recreate the problem...

Thanks! I'll give it a try with that resolution and report back here.

**Comment by gnosygnu** [comment]
This issue is pretty much the same as #24 . It will be resolved in the next release, which is tentatively scheduled for this weekend.

If anyone wants a preview build, let me know which platform, and I'll generate one for you. Otherwise, I'm going to close this out in a few days. Should the problem recur, feel free to reopen, or create a new issue.

Thanks.

**Comment by gnosygnu** [comment]
As mentioned in #24, this was resolved in tonight's 4.3 release. I'm going to mark this ticket closed for now. If it's still a problem on your machine, let me know, and I'll investigate
