### ISSUE TITLE
home/wiki/Help:Wiki_maintenance#cite_note-category_version-6

### ISSUE THREAD

**Issue by AnselmD** [gnosygnu/xowa#11]
home/wiki/Help:Wiki_maintenance#cite_note-category_version-6

The link points to a non existing page (home/wiki/Help:Core/Category)
 ^ Current category level of wiki. Can be either 1 or 2. See Help:Core/Category for more info

**Comment by gnosygnu** [comment]
Thanks! The link should be Help:Category. I changed it now. It'll be part of v2.8.1
