### ISSUE TITLE
sql file not found in dir, during en.wikipedia.org offline import [ xowa_app_windows_64_v3.12.1.1 ]

### ISSUE THREAD

**Issue by XowaWilliam** [gnosygnu/xowa#111]
This is an on-going problem that represented itself in previous version as well, with **en.wikipedia.org** offline import.

My first attempt at offline installation was with **page_props** and **categorylinks** files dated **2006-11-20** which failed after about 1h 20m after xml installation completed.

After the first fail, I renamed the respective files **page_props** and **categorylinks** files as "**latest**" externally and internally of the gz file, and it still failed.
![sql-zipped](https://cloud.githubusercontent.com/assets/12995082/20927200/1e0e26cc-bbc9-11e6-92de-cdc4632f8b6f.jpg)

Finally I tried extracting the files as regular **sql** files and tried again, and it still failed.
![sql-extracted](https://cloud.githubusercontent.com/assets/12995082/20927209/2540ae42-bbc9-11e6-9f6f-c623aff1ff22.jpg)

Session file of last attempt: [session [ version=3.12.1.1 ].txt](https://github.com/gnosygnu/xowa/files/633965/session.version.3.12.1.1.txt)

Hope all this is helpful.

**Comment by gnosygnu** [comment]
Sorry to hear that. 

Offhand, are your category dump files in "E:\Xowa December\wiki\en.wikipedia.org" or in "E:\"? I see your dump file is in "E:\enwiki-20161120-pages-articles.xml". If your category dump files are in E: ("E:\enwiki-latest-categorylinks.sql") then that won't work. XOWA isn't smart enough to check the same directory as the main dump.

If it is in "E:\Xowa December\wiki\en.wikipedia.org" can you try with a smaller wiki like enwikinews? I did the following
* Download the three dump files: 
    * enwikinews-20161101-categorylinks.sql.gz
    * enwikinews-20161101-page_props.sql.gz
    * enwikinews-20161101-pages-articles.xml.bz2
* Put them in C:\xowa\wiki\en.wikinews
* Went to home/wiki/Dashboard/Import/Offline
* Ran the following script
```
// import wiki from dump file
app.setup.cmds.cmd_add("wiki.dump_file", "C:\xowa\wiki\en.wikinews.org\enwikinews-20161101-pages-articles.xml.bz2", "en.wikinews.org", "");
```

**Comment by XowaWilliam** [comment]
For a moment I thought I was loosing my mind because I know in the past I did an offline import with the XML file on another drive, or another completely different directory.

So today I did a test with a much older *xowa_app_windows_64_v3.4.3.1* from April this year, and it worked with the XML file on another drive.

So somewhere between then and now it appears you removed this option, which explain why I had all these recent failures in the past week.

It was a great option for those wanting to build Xowa on a SSD drive with limited space, because the en.wikipedia XML file is pretty big, so it is advantageous to access it from another drive.

Just for clarity, in all the examples described in this post, all 3 SQL files were always placed in *wiki/en.wikipedia.org* folder.

**Comment by gnosygnu** [comment]
> So somewhere between then and now it appears you removed this option, which explains why I had all these recent failures in the past week.

Yeah, sorry about that. The option was omitted in v3.9.2 when I rewrote the Category system. I'll add it back in one of the next few releases.

> Just for clarity, in all the examples described in this post, all 3 SQL files were always placed in wiki/en.wikipedia.org folder.

Not sure I follow. Are you saying that:
* You are using v3.12.1
* You put all three dump files in /xowa/wiki/en.wikipedia.org 
* You ran Import/Offline, and still got the messageBox about the missing .sql files?

If so, can you try with a smaller wiki like enwikinews? This worked on my side.

If enwikinews works for you, but enwiki does not, then I'll run a test with enwiki on my side to see if it might be enwiki specific.

Thanks.

**Comment by XowaWilliam** [comment]
> Yeah, sorry about that. The option was omitted in v3.9.2 when I rewrote the Category system. I'll add it back in one of the next few releases.

I'm glad you confirmed the reason for all these failures of not finding SQL files was a alteration in the script from v3.9.2.
I look forward to it being corrected in the next update. :+1: 


> Not sure I follow. Are you saying that:
•You are using v3.12.1
•You put all three dump files in /xowa/wiki/en.wikipedia.org
•You ran Import/Offline, and still got the messageBox about the missing .sql files?

Yes that what I am saying... 
It could have been assumed that maybe I had placed the three SQL files in the wrong directory that caused the failures. But I am glad the real reason for the failure have been solved. :8ball:

**Comment by gnosygnu** [comment]
>>  Yeah, sorry about that. The option was omitted in v3.9.2 when I rewrote the Category system. I'll add it back in one of the next few releases.

> I'm glad you confirmed the reason for all these failures of not finding SQL files was a alteration in the script from v3.9.2.
> I look forward to it being corrected in the next update.

Actually, it looks like I was wrong. I tried it now and it does work in 3.12.1.  :confused:

When you get a chance, can you try my steps below for enwikinews? It shouldn't take more than 15 min. I just want to make sure we're both seeing the same behavior for the same process.

Thanks.

----
* Download https://github.com/gnosygnu/xowa/releases/download/v3.12.1.1/xowa_app_windows_64_v3.12.1.1.zip
* Unzip to "E:\Xowa Temp"
* Download the following 3 dump files for English Wikinews
    * Page dump: https://dumps.wikimedia.org/enwikinews/20161101/enwikinews-20161101-pages-articles.xml.bz2
    * Category link dump: https://dumps.wikimedia.org/enwikinews/20161101/enwikinews-20161101-categorylinks.sql.gz
    * Page props dump: https://dumps.wikimedia.org/enwikinews/20161101/enwikinews-20161101-page_props.sql.gz
* Place them in "E:\"
* Run xowa_64.exe
* Go to home/wiki/Options/Security and disable "Web Access"
* Go to home/wiki/Dashboard/Import/Offline
* Paste the following code in the textarea
<pre>
// import wiki from dump file
app.setup.cmds.cmd_add("wiki.dump_file", "E:\enwikinews-20161101-pages-articles.xml.bz2", "en.wikinews.org", "");
</pre>
* Press "Run script"
* Wait about 2 minutes for it to complete. You shouldn't get any message boxes about missing SQL

Also, for what it's worth, I also ran these steps after the above:
* Deleted the folder: E:\Xowa Temp\wiki\en.wikinews.org
* Deleted the two category dump files: 
    * E:\enwikinews-20161101-categorylinks.sql.gz
    * E:\enwikinews-20161101-page_props.sql.gz
* Reran the script above. This time I did get a message box about missing SQL.

**Comment by XowaWilliam** [comment]
OK, I followed your instructions and it worked.

It only failed if I separated the XML from the SQL files.

Now I understand that when you rewrote the code, you did it a little differently, because in the past the XML file could be anywhere, but all SQL files in the appropriate wiki folder.

I am fine with leaving it this way, as it would really free up more useable space on a limited Xowa on SSD drive. :8ball:

**Comment by gnosygnu** [comment]
> OK, I followed your instructions and it worked.

> It only failed if I separated the XML from the SQL files.

Cool.

> Now I understand that when you rewrote the code, you did it a little differently, because in the past the XML file could be anywhere, but all SQL files in the appropriate wiki folder.

Yeah, that's a shrewd observation. The current build now forces all the dump files to be in the same folder. That folder can be either "/xowa/wiki/wiki_name" or "/any_other_folder". I think this is clearer, and really doesn't impose too strict a limitation.

Let me know if you have any other thoughts. Otherwise I'll close this ticket out in a few days.

Thanks.

**Comment by gnosygnu** [comment]
As detailed above, XOWA recently forced all dump files to be in the same directory. I'm going to mark this ticket closed as I think that's a workable limitation. Let me know if there's anything else.

Thanks!
