### ISSUE TITLE
Tab switch requires manual refresh

### ISSUE THREAD

**Issue by markusmaresch** [gnosygnu/xowa#117]
Not sure if this is a cosmetic bug, or as intended.
Version: 3.12.1.1
How to reproduce:
- Start Xowa, have one tab "Main Page"
- Open "New Tab" from File Menu.
- In new tab, enter something like "home/wiki/About"  in the URL field
- mouse click on "Main Page" tab: empty page. Click back on "About", also empty.

Clicking into the URL field, placing the cursor at the end and hitting return -- reload works ...

**Comment by gnosygnu** [comment]
Hmmm... I tried this on my side on both Windows and Mac OS X, and I couldn't reproduce.

I attached a simple gif below to show what I did. Let me know if I did something from you.

Thanks.

![test](https://cloud.githubusercontent.com/assets/4994104/21475359/997e1892-caf8-11e6-9420-13a1f7e2668f.gif)

**Comment by markusmaresch** [comment]
Hmm - I can see it working according to the GIF.
However on native OsX: 10.12.2. with Xowa 3.12.1.1 on my system it REQUIRES the manual refresh.
Close if nobody else is seeing it - I can work around it.

**Comment by gnosygnu** [comment]
> However on native OsX: 10.12.2. with Xowa 3.12.1.1 on my system it REQUIRES the manual refresh

Yeah, I'm working on OSX 10.9.5 and 3.12.1.1. I tried again just now and same thing. I don't have a screen capture program set up on the mac, but yeah, the steps are the same.

One other random thought. Can you try with a brand new copy of XOWA elsewhere on your Mac? Just unzip it to somewhere like /Users/your_name/xowa_test . There's a very small chance that there might be an issue with pre-saved options. I can't think of any that would cause your behavior, but I just want to rule it out on a fresh install.

Thanks.

**Comment by markusmaresch** [comment]
Confirmed to work nicely with a clean install of 4.0.0.1701. Consider closing.
Still need to find out WHICH of my old user options is triggering this issue.
Thanks !

**Comment by gnosygnu** [comment]
Cool! Thanks for the follow-up

If you still want to get to the bottom of it, you can send me your old config file. It should be something in: <code>/wherever_xowa_was_not_working/user/anonymous/app/data/cfg</code>. The file is either xowa_user_cfg.bak or xowa_user_cfg.gfs

Once I get that, I can see if reproduce it, or if any particular option caused the problem.

If not, we can treat it as an outlier. Up to you.

Thanks!
