### ISSUE TITLE
Search across all wikis

### ISSUE THREAD

**Issue by markusmaresch** [gnosygnu/xowa#118]
Not sure about this topic - could be a simple user error. In this case I am eager to learn.
Sometimes it would be helpful to search in ALL local xowa wikis, and see what hits I can get.

Setup: Version 3.12.1.1, all english, german wikis and wikidata (and some more)

The case below is intentionally contrived - I used a word from 'true friends' for demonstration: http://www.englisch-hilfen.de/words/true_friends.htm - you get the point.

Example: Am interested in "Experiment", as I don't know too much about it yet.
What I would like to get is something like this:
https://www.google.com/#q=site:*.wikipedia.org+%22experiment%22 
The point is, I want BOTH German and English results (or depending on spelling of term in all wikis). BTW: even google does not show the hit of 'experiment' in wikiquote, at least not with high ranking.

In Xowa tried this:
- start at main page (both top search bar and page search bar): enter "experiment" - don't get much.
- start with de.wikibooks.org, good find something
- go to en.wikiquote.org, find some more
- suspect something in DE, select de.wikipedia.org - ok, find it
- check for EN, select en.wikipedia.org - ok, also find it
- and so on ...

Above is contrived to prove the case, but quite often I had a similar case - I am sure you get the point.
For 'multi-linguals' this may be more of an issue, but even for English only, there is still 'quote', 'source', 'books' ... one has to look for himself.
Maybe a discussion could shed some light on it. Thanks !

:-)

**Comment by gnosygnu** [comment]
Hi! If I understand you correctly, I think this feature already exists in XOWA. Try something like the following:

* Go to home/wiki/Options/Search
* Change "Multi-wiki search wikis" to 
```
<any>|<self>,de.*,en.*
```
* Click "Save"
* Go to "de.wikipedia.org"
* Enter in "experiment" in the Suggest box (the "Volltext" box near the upper right hand corner of the page)
* Press enter. This should take you to a page like de.wikipedia.org/wiki/Spezial:Search?search=experiment&fulltext=y&simple_search=y&go=Ausf%C3%BChren
    * This page will list all the pages in your German and English Wikis with a page title of "experiment"

Let me know if you wanted something else.

Thanks!

**Comment by gnosygnu** [comment]
Cool! Thanks for the confirmation!

> With just "<any>|<self>" it does not work.

Yeah, I tried to explain as much in the help documentation at the bottom of the page. A few random points:
* The default is just to search the current wiki (&lt;self>). This is done for performance (it's faster to search one wiki than many)
* You can add other wikis by specifying domains or wildcards. For example, consider the following:
    * <code>&lt;any>|&lt;self>,de.\*,en.\*</code>: search current wiki (self) and any German wiki (de.\*) or English (en.\*) wiki
    * <code>&lt;any>|&lt;self>,\*.wikipedia,\*.wiktionary</code>: search current wiki (self) and any Wikipedia (\*.wikipedia) or Wiktionary (\*.wiktionary) in another language (English, German, French, etc.)
    * <code>&lt;any>|&lt;self>,en.wikipedia.org</code>: search current wiki (self) and English Wikipedia (en.wikipedia.org)

Hope this helps. Let me know if there's anything more, or else I'll close out the ticket in a few days.

Thanks!

**Comment by gnosygnu** [comment]
As detailed above, multi-wiki search is an existing feature in XOWA. I'm closing this ticket out. Let me know if there's anything else.

Thanks!
