### ISSUE TITLE
home/wiki/Help:Wiki_maintenance wikidata is not visible 

### ISSUE THREAD

**Issue by AnselmD** [gnosygnu/xowa#12]
wikidata is not visible at

home/wiki/Help:Wiki_maintenance

**Comment by gnosygnu** [comment]
Hmmm... Not sure what you mean. I checked now and wikidata does show up. See the screenshot below.

If you get a chance, can you post a picture of your screen?

Thanks.

![wiki_maintenance](https://cloud.githubusercontent.com/assets/4994104/8922365/d55eab96-34af-11e5-9325-e9beee5557af.png)

**Comment by AnselmD** [comment]
I installed wikidatawiki-20150704-pages-**meta-**current.xml.bz2

![screenshot from 2015-07-28 15 07 00](https://cloud.githubusercontent.com/assets/6770907/8931988/7adb2b3c-353a-11e5-9516-489b3c499144.png)
![screenshot from 2015-07-28 15 09 07](https://cloud.githubusercontent.com/assets/6770907/8932018/aa129656-353a-11e5-8ec1-acc6564fee17.png)

**Comment by gnosygnu** [comment]
Cool. Thanks for the screenshots.

Let me try to reproduce on my side. I'll post again later tonight.

**Comment by gnosygnu** [comment]
Sorry, still downloading. Let's try tomorrow night. Thanks.

**Comment by AnselmD** [comment]
Take your time, it is not urgent/important.

**Comment by gnosygnu** [comment]
No luck. I wasn't able to reproduce on my side. See my screenshot below.

I looked at the code and it's fairly basic. It should basically just be listing folders inside /xowa/wiki/

I'll add some debugging code for v2.8.1. I'll post again here after I release.

![wikidata](https://cloud.githubusercontent.com/assets/4994104/8975625/4f66d3be-364f-11e5-92db-5be591779d64.png)

**Comment by gnosygnu** [comment]
I added some debugging code in tonight's release. Feel free to download and try whenever you have some time. You'll see some more logging statements in Special:XowaSystemData?type=log_session after visiting Help:Wiki_maintenance

Thanks.

**Comment by AnselmD** [comment]
Now it works....

**Comment by gnosygnu** [comment]
Strange... I promise I didn't do anything else. :)

If it happens again, you can look at the log, you'll see items like those below.

I'm going to go ahead and close this ticket. If anything happens, let me know and I'll reopen and investigate.

Thanks!

```
20150804_021524.296 maint.wiki_count; count=19
20150804_021524.296 maint.wiki_itm; wiki=home
20150804_021524.296 maint.wiki_itm; wiki=commons.wikimedia.org
```
