### ISSUE TITLE
Minor issues with custom wikis

### ISSUE THREAD

**Issue by lugusto** [gnosygnu/xowa#122]
I'm playing with Xowa and an Intranet wiki, but got some minor issues:

- Language detection don't work even if mapping the wiki to http://pt.wiki.local , defaulting to English instead of Portuguese language. It causes issues with some namespaces, specially Category: and Template:. Please add a way to instruct Xowa what language they should parse the content;

- [[Media:Filename.ext]] didn't generate valid links;

- Xowa expects to get some data based on default MediaWiki setup (TopLevelDomain for main page; /wiki/Pagename; /w/api.php; /w/index.php). My local wiki (and many others) are placed on TopLevelDomain/CUSTOMDIR (TopLevelDomain is a generic HTML page); TopLevelDomain/CUSTOMDIR/index.php/Pagename; TopLevelDomain/CUSTOMDIR/api.php; TopLevelDomain/CUSTOMDIR/index.php. Please add a way to instruct Xowa to find stuff in custom URLs.

Although those issues, Xowa parsers content even better and faster than the MediaWiki engine itself. Congratulations and many thanks for maintaining this amazing software.

**Comment by gnosygnu** [comment]
Hi! Thanks for the interest in XOWA, as well as the well-written bug report!

The short answer is that your points are valid ones. I'll try to make a new build to address them, but I'm currently on vacation and won't be back for another week.

A longer answer follows.

> Language detection don't work even if mapping the wiki to http://pt.wiki.local , defaulting to English instead of Portuguese language. It causes issues with some namespaces, specially Category: and Template:. Please add a way to instruct Xowa what language they should parse the content;

Yeah, XOWA does auto-detect languages for Wikimedia databases. So for something like pt.wikipedia.org, XOWA uses the pt language code for Portuguese

However, for non-Wikimedia wikis (like yours), it just defaults to English. So even something like pt.generic_name.org it will just use English.

I'll add some sort of Option or Special page to customize non-Wikimedia wikis. 

> [[Media:Filename.ext]] didn't generate valid links;

This is an interesting find. I don't remember why this is the case. I believe I was working with an old MediaWiki version that suppressed [[Media]] links.

At any rate, MediaWiki definitely shows them now, and XOWA should as well. This will be part of one of the next few builds.

>  Xowa expects to get some data based on default MediaWiki setup (TopLevelDomain for main page; /wiki/Pagename; /w/api.php; /w/index.php). My local wiki (and many others) are placed on TopLevelDomain/CUSTOMDIR (TopLevelDomain is a generic HTML page); TopLevelDomain/CUSTOMDIR/index.php/Pagename; TopLevelDomain/CUSTOMDIR/api.php; TopLevelDomain/CUSTOMDIR/index.php. Please add a way to instruct Xowa to find stuff in custom URLs.

I think I follow your explanation, but just to be clear, are you expecting XOWA to correctly handle a URL like <code>http://pt.wiki.local/CUSTOMDIR/index.php/Sample_page</code>
* ... when it's entered directly into the GUI address bar
* ... when it's used directly in the page (for example: &lt;a href="http://pt.wiki.local/CUSTOMDIR/index.php/Sample_page" >Sample page&lt;/a>)

The first should be relatively easy to do. The second is harder, as it involves changing the parser. Also, regarding the second, I'm surprised that MediaWiki generates that format. Is this a setting in MediaWiki or are you using a custom extension?

> Although those issues, Xowa parsers content even better and faster than the MediaWiki engine itself. Congratulations and many thanks for maintaining this amazing software.

Cool! Great to hear, and thank you for taking the time to say as much. I did pay a lot of attention to fidelity and performance, so it's really nice to hear that it works well from someone. Thanks!

**Comment by gnosygnu** [comment]
Tonight's release (v4.5.7.1706) fixes the issue with Media links.

As for the other two issues, I'm going to leave them as is until further confirmation / information is provided. This ticket will be closed for the time being, but please feel free to comment within and Ill reopen

Thanks.
