### ISSUE TITLE
How to download all zhwiki required images?

### ISSUE THREAD

**Issue by darkskygit** [gnosygnu/xowa#123]
I have imported zh.wikipedia.org, but the required images need to network view, how to download all the required images?

**Comment by gnosygnu** [comment]
Hi! Thanks for trying out zh.wikipedia.org and XOWA!

Right now, I've fallen behind on generating offline images for a number of wikis. There is a 2015-09 version of offline images at https://archive.org/download/Xowa_zhwiki_latest .

I'm on vacation now, so my availability is a bit spotty. If you can wait a week or two, I'll upload a 2017-01 set.

If you want to try it yourself, you can refer to the instructions at http://xowa.org/home/wiki/Dev/Command-line/Dumps . However, the process is pretty complicated, and needs a good deal of setup.

Hope this helps. Let me know if you need more info.

Thanks!

**Comment by darkskygit** [comment]
Thanks for your reply! I try to download, if successful I will share the relevant documents so that you can update the database:)

**Comment by darkskygit** [comment]
Unfortunately, my HDD space is not enough to store the commons wiki (60g+) and wikidata (130g+) have been imported data, so can only wait for your update :(
Thanks for your update!

**Comment by gnosygnu** [comment]
No problem! Thanks for giving it a look-over.

I uploaded the image databases now. You can download them by doing the following:
* Go to Download Central
    * On XOWA: Tools -> Download Central (also home/wiki/Special:XowaDownloadCentral)
    * ON XOWA Android: Left menu -> XOWA -> Download button
* Look at the "Available" table
* Click the "blue down arrow" all the way to the right
* You'll see a status message in the bottom right about the recent additions
* Change the language to "Chinese"
* Download all the "Image" ones. If you want to try it on Android, also download the "HTML" ones

Let me know if there are any issues. Thanks!

**Comment by darkskygit** [comment]
Thinks! I have successfully downloaded all the zhwiki database, there is a small problem, the download center to provide articles updated on December 1, 2016, I have manually updated from the wiki maintenance, this will not take a lot of time. I can upload the updated database after February 1 if needed :)
![snipaste20170129_094233](https://cloud.githubusercontent.com/assets/25152247/22401334/dcbc2d2a-e609-11e6-8423-76bb6bb1c412.jpg)

**Comment by gnosygnu** [comment]
Hi! Thanks for the info and screenshot, but unfortunately I don't follow.

* It looks like you built "zh.wikipedia.org" on "2016-12-02"
* The images I uploaded to Download Central (home/wiki/Special:XowaDownloadCentral) is "2017-01-01"
* You don't need to update to the latest (2017-01-20) to use the 2017-01 images. Your 2016-12-02 zh.wikipedia.org version will work with the 2017-01-01 images from "Download Central"
* If you're not seeing images, let me know which page and which image and I'll take a look at it on my side.

Hope this helps. Thanks!

**Comment by darkskygit** [comment]
Thanks! My question has been resolved, so I close this issue.

**Comment by gnosygnu** [comment]
Cool! Thanks for the follow-up!
