### ISSUE TITLE
Custom Intranet Wiki: how to import all images?

### ISSUE THREAD

**Issue by electronum** [gnosygnu/xowa#124]
# Introduction
Hello, I have just discovered this tool and wanted to use it with our company´s intranet MediaWiki.
Our wiki is running inside the Intranet at http://172.18.200.40/wiki/

I exported the database with `php dumpBackup.php --full > dump.xml` (https://www.mediawiki.org/wiki/Manual:DumpBackup.php)

XOWA imported the database and it is working fine
![xowa_wikidumps](https://cloud.githubusercontent.com/assets/25344206/22290269/29dfc876-e300-11e6-8876-0a46587f5187.png)

# Image import
As next step I would like to import all the **images**.
Is it possible to export the images from a custom wiki, like in my case?

I have read all the documentation and tried the script:
http://xowa.org/home/wiki/Dev/Command-line/Dumps.html
I replaced all `simple.wikipedia.org` with `172.18.200.40/wiki/`, but with no success (no feedback at all after pressing _Run Script_).
How do I tell the script to download images from http://172.18.200.40/wiki/?

Do I have to use the Python script from WikiTeam?
https://github.com/WikiTeam/wikiteam

Thanks for any suggestions.

**Comment by gnosygnu** [comment]
Hi! Thanks for the excellent write-up!

It is possible, but I only know of it being done twice and the process is not something I test for

For background, you can see the following links:
* Wikia wiki for xenoblade: https://sourceforge.net/p/xowa/discussion/general/thread/91f5df9f/#ed2d
* Nethack wiki: https://github.com/gnosygnu/xowa/issues/5

On your side, you'd have to do the following:
* Run the Python script for images from https://github.com/WikiTeam/wikiteam
     * This will generate some sort of root directory with all your images. You'll have to move them to C:\xowa\wiki\your_wiki_directory_name\file\orig . (or wherever you installed XOWA)
* Download ImageMagick and Inkscape to your machine. If you don't have a portable version installed and you're working on Windows, you can refer to http://xowa.org/home/wiki/Dev/File/Setup/Windows.html
* Add a custom "Script" to home/wiki/Special:XowaCfg?grp=xowa.app.startup . The contents of the script would be something like this
````
app.wikis.get('your_wiki_directory_name').files.wkrs.get('fs.dir') {
        orig_dir        = '~{<>xowa_root_dir<>}wiki/your_wiki_directory_name/file/orig/';
        thumb_dir       = '~{<>xowa_root_dir<>}wiki/your_wiki_directory_name/file/thumbs/';
}
````

Keep in mind the following caveats:
* I haven't tested this process for some time (Wikimedia wikis take up enough time as is). You may run into problems even with the instructions above. If you do, feel free to ping me here. If you want to set aside an hour or so to work on it over IRC, let me know and I'll try to accommodate
* ImageMagick and Inkscape have portable Windows version, but if you're running cross-platform you'll run into issues.
    * For example, you placed your wiki on a USB key, and want to run it on any Windows, Linux, Mac OS X device.
        * Running it on any Windows device will work. You just need to xcopy the portable version to X:\xowa\bin\windows_64\imagemagick and X:\xowa\bin\windows_64\inkscape
        * Running it on any Mac OS X device is possible (I believe there are portable versions of ImageMagick / Inkscape for Mac OS X).
        * Running it on a Linux / Raspberry PI device is probably not possible (requires pre-built binaries per the distribution)
* Android won't work. This requires a separate process that needs to...
    * Generate HTML dumps as per "Command-line/Dumps"
    * Generate XOWA image databases for non-Wikimedia wikis (which is not possible)

With that said, I am curious in the following:
* Are you using any custom extensions in your Wiki? Keep in mind that XOWA only supports extensions used by Wikimedia wikis. I find that custom wikis often use additional extensions that won't work in XOWA
* Does Android / Linux / Raspberry PI need to be supported?

Anyway, hope this is enough information for now. Let me know if there's something else.

Thanks!

**Comment by electronum** [comment]
Thanks for the detailed help. I have made some progress, with some issues still remaining.

# Steps done
Used the pyhton script https://github.com/WikiTeam/wikiteam, downloaded all images and put them into `xowa\wiki\WikiDumps\file\orig\`

Added script to `home/wiki/Special:XowaCfg?grp=xowa.app.startup`
```
app.wikis.get('WikiDumps').files.wkrs.get('fs.dir') {
        orig_dir        = '~{<>xowa_root_dir<>}wiki/WikiDumps/file/orig/';
        thumb_dir       = '~{<>xowa_root_dir<>}wiki/WikiDumps/file/thumbs/';
}
```
I am running Windows 10 64 bit
* Downloaded and installed the image converters as following:
  * ImageMagick-7.0.4-6-portable-Q16-x64.zip <br /> http://www.imagemagick.org/script/download.php
  * Inkscape-0.91-1-win64.7z <br />https://inkscape.org/en/release/0.91/platforms/
* Extracted them to `xowa\bin\windows\inkscape`
![xowa_imagemagick](https://cloud.githubusercontent.com/assets/25344206/22467288/526f6670-e7c4-11e6-9d2e-72e6521374ce.png) 

![xowa_inkscape](https://cloud.githubusercontent.com/assets/25344206/22467293/55323c8e-e7c4-11e6-8b11-f9675f815663.png)

> You just need to xcopy the portable version to X:\xowa\bin\windows_64\imagemagick and X:\xowa\bin\windows_64\inkscape

Or should I put them into `xowa\bin\windows_64\inkscape` (which is not existing yet) like in your example ?

## Raster images
The embedded images are there, the `thumbs` directory is populated correctly, but the image pages `File:ImageXY.jpg/.png` are always empty (see screenshot).
![image_jpg_xowa_missing](https://cloud.githubusercontent.com/assets/25344206/22467254/322ba93c-e7c4-11e6-9c34-f04e49834230.png)

How it should look like:
![image_jpg_original_wiki](https://cloud.githubusercontent.com/assets/25344206/22467265/3b4c30d6-e7c4-11e6-871b-7e3c23dcf241.png)


## SVG images
1. After the first xowa-restart, SVG images were displayed within the page correctly. The image pages `File:ImageXY.svg` were empty though (same as with raster images)
2. After an additional xowa-restart, SVGs disappeared and do not work anymore so far. The `thumbs` directory contains resized versions, but with the wrong .svg-extension now (cannot be opened in Inkscape). I would say, they should be .png instead, after renaming such files to .png, the can be viewed as PNG properly. There is some odd behavior while generating the thumbnails.

## General
One more thing I noticed: xowa re-starts with an empty start page now.
![xowa_start_empty](https://cloud.githubusercontent.com/assets/25344206/22467363/a80e09ce-e7c4-11e6-85f0-ad87845925a9.png)

# Other stuff
> Are you using any custom extensions in your Wiki?

Using the official mediawiki extensions only, everything seems to work so far, with the exception of https://www.mediawiki.org/wiki/Extension:DynamicPageList_(third-party). The parser function delivers no output:
```
[[:Template:#dpl:]] 
```


>Does Android / Linux / Raspberry PI need to be supported?

No, Windows support has highest priority, and Mac OS X would be also fine.

# Question
Is it possible to rename the name of my imported wiki `WikiDumps` (how it appears in xowa)?

**Comment by gnosygnu** [comment]
Hey. Good to hear from you again.

I reply to relevant parts below. Let me know if I missed anything.

Thanks!

----

> Or should I put them into xowa\bin\windows_64\inkscape (which is not existing yet) like in your example ?

Nope. Your <code>windows</code> folder is fine. I generally assume that everyone is on a 64-bit JVM, but it looks like you're on a 32-bit JVM (XOWA creates a <code>windows</code> folder if 32-bit; a <code>windows_64</code> folder if 64-bit). There's no real difference between 32-bit and 64-bit XOWA, so if you want to stay 32-bit that's fine

> but the image pages File:ImageXY.jpg/.png are always empty (see screenshot)

This looks like a bug with XOWA and custom wikis. Let me look at it this week, and get back to you

> After an additional xowa-restart, SVGs disappeared and do not work anymore so far. The thumbs directory contains resized versions, but with the wrong .svg-extension now (cannot be opened in Inkscape). I would say, they should be .png instead, after renaming such files to .png, the can be viewed as PNG properly. There is some odd behavior while generating the thumbnails.

Hmmm.... This is probably also a bug. Let me also take a look at it as well.

> One more thing I noticed: xowa re-starts with an empty start page now.

That's strange. When you can, please try the following:

* Start XOWA. I assume that 0 tabs show.
* Open <code>home/wiki/Main_Page</code>
* Close XOWA
* Start XOWA again. 1 tab should show with <code>home/wiki/Main_Page</code>
* If 0 tabs show, check the following:
    * Go to <code>home/wiki/Special:XowaCfg?grp=xowa.app.startup</code> and make sure "Startup type" is set to "previous"
    * Go to <code>home/wiki/Special:XowaCfg?grp=xowa.dev.general</code> and make sure "Previous list" shows "home/wiki/Main_Page"

If the options are set correctly, then this may be a bug with the custom wiki.

> Using the official mediawiki extensions only, everything seems to work so far, with the exception of https://www.mediawiki.org/wiki/Extension:DynamicPageList_(third-party). The parser function delivers no output:

Yeah, I ported most of the functionality of the Wikimedia Dynamic Page List (https://www.mediawiki.org/wiki/Extension:DynamicPageList_(Wikimedia)). However, this 3rd party version is something different. Unfortunately, XOWA ports all the PHP code to Java. This particular extension has 5,000+ lines of PHP code. I don't think I'll be able to do this -- at least not in the near to mid future

With that said, it looks like this extension is backward compatible with the Wikimedia DPL. If you're using very little of the new "3rd party" functionality, I can add an alias for it to use the Wikimedia version. However, if you're heavily leveraging the new features, then this probably won't help.

> Is it possible to rename the name of my imported wiki WikiDumps (how it appears in xowa)?

You can rename the folder name. However, there look like there are some bugs with it. See https://github.com/gnosygnu/xowa/issues/120#issuecomment-272578109

I'm going to fix this for the next release. If you're feeling adventurous and want to do this manually, you could try the following:
* Manually rename the folder. For example, <code>D:\WikiDumps\xowa\wiki\WikiDumps</code> to <code>D:\WikiDumps\xowa\wiki\your_wiki</code>
* Rename all the files in the folder. For example, <code>WikiDumps-core.xowa</code> to <code>your_wiki-core.xowa</code>
* Open up <code>your_wiki-core.xowa</code> in a sqlite program and run the following SQL: <code>UPDATE xowa_db SET db_url = Replace(db_url, 'WikiDumps', 'your_name');</code>

You can also reimport the wiki again. Just make sure that the XML dump file has the name of the wiki. For example, "your_name.xml"

**Comment by electronum** [comment]
# Image pages
>> but the image pages File:ImageXY.jpg/.png are always empty (see screenshot)
>
>This looks like a bug with XOWA and custom wikis. Let me look at it this week, and get back to you

Image pages would be a "nice to have", so far I am quite satisfied with the principal function.

# SVG images

>> After an additional xowa-restart, SVGs disappeared and do not work anymore so far. The thumbs directory contains resized versions, but with the wrong .svg-extension now (cannot be opened in Inkscape). I would say, they should be .png instead, after renaming such files to .png, the can be viewed as PNG properly. There is some odd behavior while generating the thumbnails.
>
>Hmmm.... This is probably also a bug. Let me also take a look at it as well.

I have to correct my earlier statements after some additional tests, the behavior seems to be like this:
1. After first xowa-restart SVG images disappeared, so I deleted all the thumbnails to kind of force generating them again. Such SVG files (thumbnails which were there, but I deleted them) are not generated anymore.
2. Other SVG images worked properly, after xowa restart they disappeared again. Now after looking at [#125 comment](https://github.com/gnosygnu/xowa/issues/125#issuecomment-276543545), renaming _spaces_  to _underscores_ of the **image folder names** fixes such SVG images back.
3. The .svg extension does not seem to hurt, as the thumbnails are displayed properly.

# Blank start page
> If 0 tabs show, check the following:
Go to home/wiki/Special:XowaCfg?grp=xowa.app.startup and make sure "Startup type" is set to "previous"

This is fixed now, thanks!

# Extension DPL (third party)
> Yeah, I ported most of the functionality of the Wikimedia Dynamic Page List (https://www.mediawiki.org/wiki/Extension:DynamicPageList_(Wikimedia)). However, this 3rd party version is something different. Unfortunately, XOWA ports all the PHP code to Java. This particular extension has 5,000+ lines of PHP code. I don't think I'll be able to do this -- at least not in the near to mid future
With that said, it looks like this extension is backward compatible with the Wikimedia DPL. If you're using very little of the new "3rd party" functionality, I can add an alias for it to use the Wikimedia version. However, if you're heavily leveraging the new features, then this probably won't help.

I am totally fine with the current state, the DPL (third party) just serves as an eye candy on one single page displaying last changes, and is not crucial for an offline installation. I was just wondering about the technical reasons.

# Renaming
> You can rename the folder name. However, there look like there are some bugs with it. See #120 (comment)

I will try it somewhen later. Thanks a lot so far.

**Comment by gnosygnu** [comment]
Hey, thanks for the detailed breakdown.

I uploaded a new build (v4.0.3.1702) that should handle all the issues. See https://drive.google.com/open?id=0B9cb52zjL2rINkhhdVNSVjR5Mms . I give a detailed breakdown below the break. I'll be copy-pasting this to #125 as well.

I also reply to your points below. I'm going to mark the issue resolved, but feel free to comment more.

Finally, I like to give credit to users for reporting bugs. Right now, there is a line in the XOWA Change Log with "Show images in pages within the File namespace {detected by anonymous}". There are a few other lines as well. Let me know if you want to be cited by nickname or would rather remain anonymous

Otherwise, thanks for the great write-up!

----

First, replying to your points:

# Image pages
>> This looks like a bug with XOWA and custom wikis. Let me look at it this week, and get back to you

> Image pages would be a "nice to have", so far I am quite satisfied with the principal function.

Cool. Glad to hear you liked it as it was. However, this is now available in the new build. :)

# SVG images
> 1. After first xowa-restart SVG images disappeared, so I deleted all the thumbnails to kind of force generating them again. Such SVG files (thumbnails which were there, but I deleted them) are not generated anymore.

Not sure how this is happening, but I rewrote a good deal of the image loading code. It's now integrated with the app file cache (home/wiki/Special:XowaCfg?grp=xowa.files.general) Please try it again with the new build, and let me know if it's still happening.

> 2. Other SVG images worked properly, after xowa restart they disappeared again. Now after looking at [#125 comment](https://github.com/gnosygnu/xowa/issues/125#issuecomment-276543545), renaming _spaces_  to _underscores_ of the **image folder names** fixes such SVG images back.

This is also resolved in this build. XOWA now automatically renames files with "spaces" to "underscores". For more info, see below

> 3. The .svg extension does not seem to hurt, as the thumbnails are displayed properly.

Yeah, I looked at the code, and realized this was a hack. This is no longer an issue as the thumbs are now generated directly for the app file cache. So svg thumbs will now have an extension of ".png" instead of ".svg"

# Blank start page

> This is fixed now, thanks!

Cool!

# Extension DPL (third party)
> I am totally fine with the current state, the DPL (third party) just serves as an eye candy on one single page displaying last changes, and is not crucial for an offline installation. I was just wondering about the technical reasons.

Okay. Sounds good.

# Renaming
>> You can rename the folder name. However, there look like there are some bugs with it. See #120 (comment)

> I will try it somewhen later. Thanks a lot so far.

Yeah, you may be better off reimporting the wiki. Up to you.

----

Changes in v4.0.3.1702
* **Images in the File namespace will now show**: For example, https://nethackwiki.com/wiki/File:Keyboard_shortcuts.svg . Note that clicking on an image here will also open it up in your image viewer.
* **File names with spaces are automatically renamed to use underscores**: For example, <code>SpellIcon PsionicBlast.png</code> will be renamed to <code>SpellIcon_PsionicBlast.png</code>
    * This matches online behavior where the url has an "_" not a space. For example, http://vignette3.wikia.nocookie.net/masterofmagic/images/3/33/SpellIcon_PsionicBlast.png/revision/latest?cb=20120115004618
    * A log is generated of all renames and saved to "orig.changes.log"
* **SVG thumbnails will now use ".png" instead of ".svg"**: For example, "C:\xowa\file\nethackwiki.com\thumb\8\3\f\d\Keyboard_shortcuts.svg\800px.png"
* **View HTML will now show the img src and width info**: For example, &lt;img id="xoimg_1" alt="File%3AKeyboard+shortcuts.svg" src="file:///D:/xowa_temp/file/nethackwiki.com/thumb/8/3/f/d/Keyboard_shortcuts.svg/800px.png" width="800" height="293" /&gt;
* **Images are now integrated directly into the app file cache**: See <code>home/wiki/Special:XowaCfg?grp=xowa.files.general</code>. This means that a separate thumbs directory is no longer generated
* **A startup script is no longer needed**: You can (and should) remove the startup script at <code>home/wiki/Special:XowaCfg?grp=xowa.app.startup</code>. XOWA now automatically assumes that all non-WMF wikis will have offline files in the wiki directory. For example, <code>C:\\xowa\\wiki\\your_wiki\\file\\orig\\</code>
* **Updated instructions**: I updated the instructions at http://xowa.org/home/wiki/App/Wiki_types/Wikia.com

**Comment by electronum** [comment]
Thanks a lot for the extensive work.

* First I struggled to get it to work, similar situation as previously: restart XOWA and (even all) pictures disappear again, deleting `^orig_regy.sqlite3` did not help.
* I have made a major mistake: like previously I put the images to `<wiki>\file\orig\`, after paying closer attention to http://xowa.org/home/wiki/App/Wiki_types/Wikia.com and moving all files to `<wiki>\file\orig\images\` everything is now working as promised :relieved: :thumbsup: (what a confusing detail) 

> Let me know if you want to be cited by nickname or would rather remain anonymous.

I am fine with staying anonymous.

# Questions
1. In http://xowa.org/home/wiki/App/Wiki_types/Wikia.com#Part_3a:_Setup_dumpgenerator.py you add some lines to dumpgenerator.py. <br />I got along without modifying the script so far. When do I need it?
2. I would like to shrink the size of my final XOWA package. Are there any files in `imagemagick` and `inkscape` not required by XOWA and can be deleted?

# (Minor) issue
Previously I had put my .xml dump somewhere on the disk, after using the offline import function, the .xml file was deleted, which might be confusing/frustrating. I did not expect it must be put into `\xowa\wiki\<custom_wiki>`, where it is ok to be deleted after finish.

**Comment by gnosygnu** [comment]
> Thanks a lot for the extensive work.

No problem! Thanks for the quick feedback!

> after paying closer attention to http://xowa.org/home/wiki/App/Wiki_types/Wikia.com and moving all files to `<wiki>\file\orig\images\` everything is now working as promised :relieved: :thumbsup: (what a confusing detail) 

Oops sorry about that. I changed that behavior for this build. For the next release, I'll change it back looking at all files in /file/orig/ folder, not just subfolders (/file/orig/images/)

>> Let me know if you want to be cited by nickname or would rather remain anonymous.

> I am fine with staying anonymous.

Cool. Let me know if you ever change your mind.

# Questions
> 1. In http://xowa.org/home/wiki/App/Wiki_types/Wikia.com#Part_3a:_Setup_dumpgenerator.py you add some lines to dumpgenerator.py. <br />I got along without modifying the script so far. When do I need it?

You'd need it primarily for Windows machines b/c of invalid file characters. I was doing dungeon.wikia.com and one of the images had a  "?". The change removes invalid file characters

Also, the script converts spaces to underscores. XOWA also converts spaces to underscores, but I figured it should be handled earlier (at script time) instead of later (at app time)

> 2. I would like to shrink the size of my final XOWA package. Are there any files in `imagemagick` and `inkscape` not required by XOWA and can be deleted?

For imagemagick, XOWA only calls convert.exe and identify.exe. You can probably delete everything else (particularly the /images/ and /www/ folder), but I haven't tested that. :)

For inkscape, XOWA only calls inkscape.exe . However there are a lot of dlls in that directory which are probably needed. You could probably try keeping only the files in that folder, but again, I haven't tested that. :)

# (Minor) issue
> Previously I had put my .xml dump somewhere on the disk, after using the offline import function, the .xml file was deleted, which might be confusing/frustrating. I did not expect it must be put into `\xowa\wiki\<custom_wiki>`, where it is ok to be deleted after finish.

Fair enough. I usually don't delete xml files by default. Let me look at that for the next build.

**Comment by gnosygnu** [comment]
Tonight's release officially includes the fixes listed above. In addition, I also added code to not delete the XML after import

I'm going to go ahead and close this ticket. Let me know if there's anything else. Thanks.
