### ISSUE TITLE
Documentation: correction proposals in Wiki and Readme.md

### ISSUE THREAD

**Issue by electronum** [gnosygnu/xowa#127]
Hello, here some smaller things regarding the documentation:
* http://xowa.org/home/wiki/App/Wiki_types/Wikia.com#Part_3a:_Setup_dumpgenerator.py
  * maybe you could emphasize that as of now the script is working with Python 2.x only.
* https://github.com/gnosygnu/xowa/blob/master/README.md#setup-the-xowa-source
  * there seems to be a typo at _replace "/xowa/dev/150_gfui/lib/swt.jar" with "/bin/windows_64/swt/swt/jar"_, _swt/jar_ should be _swt.jar_
* http://xowa.org/home/wiki/Dev/Command-line/Dumps.html#commons.wikimedia.org_.28thum
  * the section title looks incomplete/weird: _commons.wikimedia.org (thum_

**Comment by gnosygnu** [comment]
Hey, nice catch! I'll fix all of these for the next release. Thanks!

**Comment by gnosygnu** [comment]
All three items have been fixed as advised. I'm going to go ahead and close this ticket. Let me know if there's anything else. Otherwise, thanks again!
