### ISSUE TITLE
previously downloaded wiki files re-appear in download center as avaliable after updating

### ISSUE THREAD

**Issue by TKQ** [gnosygnu/xowa#128]
the wiki files i have downloaded are missing from my "imported" list in the download centre and re-appeared in the "available" list. i updated from 3.10.4.1 to 4.1.0.1702, initially i attempted the update file which failed to run. 

the readme.txt of the update file suggests that if i instead download the entirety of the new version, i can extract the new version directly into the folder of the old version, replacing any files with the same name. this is what i did. it appears to run fine and even has access to wikis which i have previously downloaded, however i am struggling to keep my wikis up to date and download new wikis without duplicating, without being able to see which i have already downloaded.

about half of my hard drive is tied up in wiki archives (zombie apocalypse insurance) so simply duplicating the downloads is something i would really like to avoid as this would take many days and i use them frequently.

i apologise if this is simply a result of my incorrectly updating, i have attempted to follow the instructions given and would appreciate any guidence.
![failedupdatexowa](https://cloud.githubusercontent.com/assets/6924585/22647555/23b69aba-ec6a-11e6-9dca-824aeaf7afdf.png)

**Comment by markusmaresch** [comment]
Concur - the following is offered, and I need to make sure NOT to use it - every time.
English Wikipedia - Image Update (2016-09) [8.2 GB]

Suggestion: Provide a simple means of changing the update related DB, in order to fix this individually, like with SQLiteStudio..
:-)

**Comment by gnosygnu** [comment]
@TKQ : Yeah, if you downloaded the wikis outside of Download Central, then Download Central won't know about them and still show them. I can try to make Download Central smart enough to detect them, but it's not that easy.

For your part, you can ignore the <code>English Wikipedia - Images (2016-06)</code> row. I'll do what @markusmaresch  suggested and add a new button to "ignore" a row and add it to the "Imported" list.

Also, just so you know, you can find out the current wiki date of your wiki by doing the following:

* Go to this page: <code>home/wiki/Dashboard/Wiki_maintenance</code> 
* Look at the line for <code>en.wikipedia.org</code>. it probably has a wiki date of <code>2016-10</code>

If you want, you can update to <code>2016-10</code> by just downloading the <code>English Wikipedia - Articles (2016-12) [49.33 GB]</code> item.

Let me know if there's anything I misunderstood above.

@markusmaresch: I've had a number of todo items for Download Central but have been reluctant to tackle them. Let me try to do a simple ignore button for the next release.

Thanks.

**Comment by TKQ** [comment]
fell asleep at my keyboard with my response written and ready to send off, so if it seems that there is a little overlap in what i'm saying then it's because this was edited from that.

fantastic suggestion @markusmaresch , i would add though that even with this feature i would struggle as i am not sure exactly which files i have already downloaded (though the wiki-maintenance page will be a big help). presumably xowa has some idea if it knows to display content within the files, perhaps there could also be a list of files which are detected by xowa, i imagine this may also be helpful for debugging/error reporting and may encourage the creation and distribution of custom wikis which could be manually installed. i would love it if wikis/files could be easily shared via methods other than the download centre. i am not sure to what extent the wiki-maintenance page does this for files not hosted on the download center.

furthermore if there was a list of detected files, perhaps there could be an option to automatically move detected files from "available" to "imported" following a hash check or something to avoid the accidental moving of wikis which share the same name but may be customised versions of each other.

thank you @gnosygnu for your rapid and helpful response, that maintenance page is verry helpfull and the dates will no doubt help me to discern once you have implemented the "ignore" button though i must say i am a little confused as to what the date next to files in the download centre represents if not the date up to which the changes contained in the patch have occurred.

i was hoping to avoid re-downloading files over 500mb a the moment as i am travelling and using a very slow connection. if i download future wiki patches then do you think they should work fine even though the download centre thinks i don't have the main file?

i know development takes time and that i am not aware of which aspects need to be prioritised. i really appreciate the effort which has already gone into developing this fantastic tool. keep up the good work :D

**Comment by gnosygnu** [comment]
@markusmaresch I added a remove button for the next release. Sorry for the delay. 

@TKQ 
> furthermore if there was a list of detected files, perhaps there could be an option to automatically move detected files from "available" to "imported" following a hash check or something to avoid the accidental moving of wikis which share the same name but may be customised versions of each other.

This is a very sensible feature, but it's actually not that easy to do. Also, I'm thinking of redesigning Download Central and the wiki download process, so a lot may change in the near to mid future.

For now, once the new "ignore" button is available, I'm hoping it'll be enough to manage files

**Comment by markusmaresch** [comment]
Highly appreciated - thanks !

**Comment by gnosygnu** [comment]
I'm marking this item resolved, as it's a lot like #113. To copy-paste my comment from there:

> v4.2.0 adds a "blue minus" icon to Download Central. This will move an item from the Available table to the Imported table

Let me know if there's anything else. Otherwise, I'll close it out in a few days.

**Comment by gnosygnu** [comment]
As per #113, this issue is resolved in v4.2. I'm going to mark this ticket closed. Thanks for the report
