### ISSUE TITLE
Error Running in command mode without GUI

### ISSUE THREAD

**Issue by shopuz** [gnosygnu/xowa#131]
I am trying to get this running on my Ubuntu machine inside Vagrant setup with VirtualBox.

`java -jar /opt/xowa/xowa_linux_64.jar --app_mode cmd --show_license n --show_args n --cmd_text "app.shell.fetch_page('en.wikipedia.org/wiki/Earth' 'html')"`

Error:   

```
app launch failed: [err 0] <gplx> end of stream: excerpt_bgn='l.fetch_page('en.wikipedia.org/wiki/Earth' 'html')' excerpt_end='' pos='58'
[trace]:
  gplx.langs.gfs.Gfs_err_mgr.Fail(Unknown Source)
  gplx.langs.gfs.Gfs_err_mgr.Fail_eos(Unknown Source)
  gplx.langs.gfs.Gfs_parser.Parse(Unknown Source)
  gplx.langs.gfs.Gfs_msg_bldr.Bld(Unknown Source)
  gplx.langs.gfs.Gfs_msg_bldr.Bld(Unknown Source)
  gplx.langs.gfs.Gfs_msg_bldr.ParseToMsg(Unknown Source)
  gplx.xowa.apps.gfs.Xoa_gfs_mgr_.Parse_to_msg(Unknown Source)
  gplx.xowa.apps.gfs.Xoa_gfs_mgr.Run_str_for(Unknown Source)
  gplx.xowa.apps.gfs.Xoa_gfs_mgr.Run_str(Unknown Source)
  gplx.xowa.apps.boots.Xoa_boot_mgr.Run_app(Unknown Source)
  gplx.xowa.apps.boots.Xoa_boot_mgr.Run(Unknown Source)
  gplx.xowa.Xoa_app_.Run(Unknown Source)
  gplx.xowa.Xowa_main.main(Unknown Source)
```

From some of the other threads, I found that it is dependant on `xulrunner` and so tried to run that with  
` /opt/xowa/bin/linux_64/xulrunner_v24/xulrunner -h`

However I received the following error trace:
```XPCOMGlueLoad error for file /opt/xowa/bin/linux_64/xulrunner_v24/libxul.so:
libgtk-x11-2.0.so.0: cannot open shared object file: No such file or directory
Couldn't load XPCOM.```

So I was wondering if we can run XOWA in `cmd` mode without libraries like GTK, GLIB etc.

**Comment by gnosygnu** [comment]
Hi! Thanks for the great detail.

Yeah, my error message is vague. Your statement is actually missing a semicolon at the end. Add a <code>;</code> so it becomes <code>'html');"</code>. Specifically:

```
java -jar /opt/xowa/xowa_linux_64.jar --app_mode cmd --show_license n --show_args n --cmd_text "app.shell.fetch_page('en.wikipedia.org/wiki/Earth' 'html');"
```

I tested it now and was able to reproduce your error as well as the fix.

> So I was wondering if we can run XOWA in `cmd` mode without libraries like GTK, GLIB etc.

It should work in nogui mode. I've broken it in the past a few years ago, but I simulate the test now with the Java JVM argument <code>-Djava.awt.headless=true</code>. As far as I've seen, that's a pretty good simulation of booting Linux with no gui (I last checked on my Linux Mint a few months ago with GRUB_CMDLINE_LINUX_DEFAULT="text")

Hope this helps. Thanks!

**Comment by shopuz** [comment]
Such a silly mistake... I do apologise for this. 
It works after that semicolon :)

Cheers
Suren
