### ISSUE TITLE
Upgrading

### ISSUE THREAD

**Issue by Rokgen44** [gnosygnu/xowa#135]
Hello, so I have been using XOWA for a while now, but I still don't understand how to upgrade the version that I have: 2.5.4.1 to a more current version and having everything that I have on 2.5.4.1 moved to the current version so I don't have to start from scratch. So, if somebody could give me a step by step thing on how to do it, that would be wonderful.

**Comment by gnosygnu** [comment]
Hey, thanks for opening the issue, as well as using XOWA!

XOWA is designed to update by just replacing all files. You should always be able to take the files from any later zip and just unzip them to your directory

With that said, here's the easiest way to update:
* Grab the latest v4.3 version from https://github.com/gnosygnu/xowa/releases
    * For example, if you're running xowa.exe then grab the 32-bit from https://github.com/gnosygnu/xowa/releases/download/v4.3.0.1702/xowa_app_windows_v4.3.0.1702.zip
    * If you're running xowa_64.exe, then grab the 64-bit from https://github.com/gnosygnu/xowa/releases/download/v4.3.0.1702/xowa_app_windows_64_v4.3.0.1702.zip
* Unzip this to wherever you installed XOWA
    * For example, if you've installed to C:\xowa, unzip the files and move them there. You basically want to update your "C:\xowa\xowa.exe" with the one in the zip file
* Run xowa.exe

If this doesn't work, there is a more manual way detailed here: here: http://xowa.org/home/wiki/App/Setup/Update/Manual . Feel free to comment here, if that doesn't work

Also, v4.2 and up has an in-app updater. See: home/wiki/App/Setup/Update/In-app . Hopefully that will make future updates easier.

Let me know if there's anything else. Thanks!

**Comment by gnosygnu** [comment]
I'm marking this question answered for now. Let me know if there's anything else, otherwise I will close it out in the next few days. 

Thanks!

**Comment by gnosygnu** [comment]
As per above, I'm going to close out this issue. If there's anything else, please comment and I'll reopen. Thanks.
