### ISSUE TITLE
Broken download links

### ISSUE THREAD

**Issue by JuzBeKind** [gnosygnu/xowa#147]
Your links for the set of files I was downloading are dead.
I managed to get all of them downloaded before they went dead, except for one.
This is the one I didn't get:
https://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2015-12-06_wiki_text_ns-000_part-1.7z

Could you please provide an alternate link?
I don't have the bandwidth to start downloading a whole new set.

**Comment by gnosygnu** [comment]
Hi! Thanks for the detail, especially the precise name of the missing file.

You're actually pretty lucky as I happened to still have that file on my local disk (it's over a year and a half old). I'm uploading it now and hopefully it should be available sometime tomorrow (the file is 7.4 GB and archive.org is flaky with such large downloads). I'll post again here when it's up.

Let me know if there's anything else. Thanks.

**Comment by gnosygnu** [comment]
The file is now up. See: https://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2015-12-06_wiki_text_ns-000_part-1.7z I'll keep it around for a month, but can't make any promises beyond that. Let me know if you need longer.

I'm going to mark this issue resolved, and will officially close it in a week or so unless there's something else.

Thanks.

**Comment by gnosygnu** [comment]
As per above, the file has been re-uploaded to archive.org. I'm marking this issue closed for now.
