### ISSUE TITLE
xowa error

### ISSUE THREAD

**Issue by ubuntu-r** [gnosygnu/xowa#149]
Sorry! XOWA failed to run!

Please check the TROUBLESHOOTING section in the readme.txt for known issues.

You can also open an issue or send an email with the data below.

Thanks!

----
OS: linux
Java: 1.8.0_131 (64 bit)
Java path: 1.8.0_131
XOWA: 4.5.2.1704
XOWA path: /home/rophine/xowa/xowa_linux_64.jar

Error: java.lang.UnsatisfiedLinkError: org.sqlite.core.NativeDB._open(Ljava/lang/String;I)V
Stack: org.sqlite.core.NativeDB._open(Native Method)
org.sqlite.core.DB.open(DB.java:161)
org.sqlite.core.CoreConnection.open(CoreConnection.java:220)
org.sqlite.core.CoreConnection.<init>(CoreConnection.java:76)
org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:24)
org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:23)
org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:45)
org.sqlite.JDBC.createConnection(JDBC.java:114)
org.sqlite.JDBC.connect(JDBC.java:88)
java.sql.DriverManager.getConnection(DriverManager.java:664)
java.sql.DriverManager.getConnection(DriverManager.java:208)
gplx.dbs.engines.Db_engine_sql_base.Conn__new_by_url_and_props(Unknown Source)
gplx.dbs.engines.sqlite.Sqlite_engine.Conn_make(Unknown Source)
gplx.dbs.engines.Db_engine_sql_base.Conn_assert(Unknown Source)
gplx.dbs.engines.Db_engine_sql_base.New_stmt_exec(Unknown Source)
gplx.dbs.engines.Db_engine_sql_base.Exec_as_int(Unknown Source)
gplx.dbs.engines.Db_engine_sql_base.Exec_as_obj(Unknown Source)
gplx.dbs.Db_conn.Exec_qry(Unknown Source)
gplx.dbs.Db_conn_bldr_wkr__sqlite.New(Unknown Source)
gplx.dbs.Db_conn_bldr.New(Unknown Source)
gplx.dbs.Db_conn_bldr.Get_or_new(Unknown Source)
gplx.xowa.users.data.Xou_db_mgr.Init_by_app(Unknown Source)
gplx.xowa.users.Xoue_user.Init_by_app(Unknown Source)
gplx.xowa.Xoae_app.Init_by_app(Unknown Source)
gplx.xowa.apps.boots.Xoa_boot_mgr.Run_app(Unknown Source)
gplx.xowa.apps.boots.Xoa_boot_mgr.Run(Unknown Source)
gplx.xowa.Xoa_app_.Run(Unknown Source)
gplx.xowa.Xowa_main.main(Unknown Source)

**Comment by ubuntu-r** [comment]
I got this problem when I ran 'sh /home/rophine/xowa/xowa_linux_64.sh
Please give a help, Thanks a lot'

**Comment by gnosygnu** [comment]
That's strange. It looks like SQLite failed to run on Ubuntu.

I've run XOWA on Ubuntu 16.04 live image before without any issues. Is this a fresh install? Can you try a live image on your side?

If not, you can also try this install: https://drive.google.com/open?id=0B9cb52zjL2rIYU83Nl94Qy1XRE0 . This is an alpha version with the latest version of the SQLite jar. I doubt it will work, but it's worthe giving a try.

**Comment by gnosygnu** [comment]
I'm marking this issue closed for now. If you get a chance to try the above, let me know, and I'll reopen for reinvestigation.

Thanks.
