### ISSUE TITLE
Remove use of id=toctitle

### ISSUE THREAD

**Issue by Krinkle** [gnosygnu/xowa#150]
This was for internal use in MediaWiki and deprecated in favour of class=toctitle since https://github.com/wikimedia/mediawiki/commit/1bf5a652.

Any HTML or CSS consumed from Wikipedia after April 2017 will already have both class and ID in both the HTML and the CSS.

The ID will be removed in MediaWiki from the HTML and from CSS in [I43cfffdb0807e8 / https://gerrit.wikimedia.org/r/357770](https://gerrit.wikimedia.org/r/357770) - probably to be deployed next week.

I still see several uses in this search that do not support the class yet. <https://github.com/wikimedia/xowa/search?q=toctitle>

They appear to be used in the creation of an HTML string. I don't know how these are used exactly in the final application, but if the application uses the live stylesheets from Wikipedia, then soon the table of contents may be styled incompletely or incorrectly as the live stylesheets will now only target `class=toctitle`, and no longer to `id=toctitle` as well.

**Comment by gnosygnu** [comment]
Hi! Thanks for the detailed report!

Yup, your deductions are correct. XOWA does build the HTML with an id=toctitle. Of the 4 results returned in your search, two are for unit tests. The other two will need to be changed:

* Formatter used to build TOC for all articles
    * https://github.com/wikimedia/xowa/blob/c50af691f92c0d1de6dd39de87dd69a9c72bc7f7/400_xowa/src/gplx/xowa/htmls/tocs/Xow_toc_mgr.java

* Formatter used to build TOC for Wikidata articles
    * https://github.com/wikimedia/xowa/blob/c50af691f92c0d1de6dd39de87dd69a9c72bc7f7/400_xowa/src/gplx/xowa/xtns/wdatas/hwtrs/Wdata_fmtr__toc.java

I'm planning a minor release in the next two weeks after I fix a few issues with the 2017-06 English Wikipedia dump. I'll include the new class=toctitle then. Let me know if you need a version earlier, and I can upload something to my google drive

>  but if the application uses the live stylesheets from Wikipedia

Yes, XOWA does use the live stylesheet from Wikipedia. If you're interested, the process is as follows:
* User imports a wiki using Import Online / Offline (or command-line)
* User opens an article in that wiki
* If an offline CSS is not available, XOWA connects online to the Main Page for that wiki and scrapes it for CSS urls
* XOWA removes the remote urls from the CSS and saves it offline to something like /xowa/user/anonymous/wiki/name_of_wiki/html

Thanks again for the report! If it weren't for it, it would've come up as a nasty surprise sometime in the next few weeks!

**Comment by gnosygnu** [comment]
Tonight's release (v4.5.7.1706) now includes class=toctitle . As such, I'm marking this issue closed.

Thanks again for the report.
