### ISSUE TITLE
Add customizable footer (Suggestions/Requests/Questions)

### ISSUE THREAD

**Issue by Ope30** [gnosygnu/xowa#155]
Hey. This will be my topic where I post Suggestions, Requests and Questions regarding (not always) Requests. It is not like I could make a big list right now. But if I come up with something this is the place where it is going to be mentioned!

<>So, I know I've told you this already, and I'm not even sure what your last answer was, could you remove, "Generated by XOWA v4.5.7.1706" and replace it with "Privacy policy" "About Wikipedia" "Disclaimers" etc. please, as well as for others in the next XOWA release!?

<>I'm going to remove this Question once you answered. When comparing en.wikipedia.org/wiki/Capture_of_Berwick_(1482) to the online version, how comes the picture has different colors?

**Comment by gnosygnu** [comment]
Sorry for the late reply, but I've been on vacation recently.

> Hey. This will be my topic where I post Suggestions, Requests and Questions regarding (not always) Requests. It is not like I could make a big list right now. But if I come up with something this is the place where it is going to be mentioned!

Cool. Thanks for opening a separate issue. Let's see how this works!

> <>So, I know I've told you this already, and I'm not even sure what your last answer was, could you remove, "Generated by XOWA v4.5.7.1706" and replace it with "Privacy policy" "About Wikipedia" "Disclaimers" etc. please, as well as for others in the next XOWA release!?

Let me look into putting in a config option for the "Generated by XOWA"

If I remember correctly, the "Privacy policy" is a little more complicated as each wiki has different types of boilerplate at the bottom of the page. I'll re-investigate and provide a more thorough answer

> <>I'm going to remove this Question once you answered. When comparing en.wikipedia.org/wiki/Capture_of_Berwick_(1482) to the online version, how comes the picture has different colors?

I compared it now and the colors for the infobox image (as well as the others) look the same. When you get a chance, can you drop off a screenshot?

Thanks!

**Comment by Ope30** [comment]
> Sorry for the late reply, but I've been on vacation recently.

I understand. 👍 


> Let me look into putting in a config option for the "Generated by XOWA"

> If I remember correctly, the "Privacy policy" is a little more complicated as each wiki has different types of boilerplate at the bottom of the page. I'll re-investigate and provide a more thorough answer

Okay. 👍 

> I compared it now and the colors for the infobox image (as well as the others) look the same. When you get a chance, can you drop off a screenshot?

Soz. Here is the XOWA version: https://image.prntscr.com/image/iRRUr2VVQDKPTF7YygaQYg.jpeg
Online: https://image.prntscr.com/image/jApqp8xDRKSAykxdgcuqfQ.jpeg
As you can see, both have different colors. xd

**Comment by gnosygnu** [comment]
>>  If I remember correctly, the "Privacy policy" is a little more complicated as each wiki has different types of boilerplate at the bottom of the page. I'll re-investigate and provide a more thorough answer

> Okay. 👍

I took a look at this, and each wiki does have different footers. So, for example, English Wikipedia has a "Contact Wikipedia" which English Wiktionary and German Wikipedia does not.

With that said, I added some code to have a global footer by config. It definitely won't work for all wikis (see Contact Wikipedia above), but it'll be closer.

> Soz. Here is the XOWA version: https://image.prntscr.com/image/iRRUr2VVQDKPTF7YygaQYg.jpeg
Online: https://image.prntscr.com/image/jApqp8xDRKSAykxdgcuqfQ.jpeg
As you can see, both have different colors.

Thanks. I accidentally was using the online image instead of the one in the .xowa database.

The image was updated on June 12 from "Edouard III devant Berwick.jpg" to "Edouard III devant Berwick.jpg". See: https://en.wikipedia.org/w/index.php?title=Capture_of_Berwick_(1482)&diff=prev&oldid=787464160

It'll match after the July update

> <>Can you add the "Earth icon" into "Coordinates"?

It's a bit difficult as the globe icon is tied to an extension (Wikipedia code) which XOWA doesn't support. I don't have plans on supporting this in the future as the extension embeds an online interactive map (which offline XOWA can never do).

By the way, in case you don't know, instead of \<\> you can use \* to do list items. For example:

* Item 1
* Item 2

----

Source:
```
* Item 1
* Item 2
```

**Comment by gnosygnu** [comment]
By the way, I made a build for the custom footer. Try the following:
* Download the build from my google drive: https://drive.google.com/open?id=0B9cb52zjL2rILVFZRHFIR2xUU1k
* Go to home/wiki/Special:XowaCfg?grp=xowa.html.page
* Change footer to remove the Generated by XOWA line

Hope this works for you.

Thanks.

**Comment by Ope30** [comment]
> I took a look at this, and each wiki does have different footers. So, for example, English Wikipedia has a "Contact Wikipedia" which English Wiktionary and German Wikipedia does not.

> With that said, I added some code to have a global footer by config. It definitely won't work for all wikis (see Contact Wikipedia above), but it'll be closer.

Better than nothing! Thanks for giving it a try.

> Thanks. I accidentally was using the online image instead of the one in the .xowa database.

> The image was updated on June 12 from "Edouard III devant Berwick.jpg" to "Edouard III devant Berwick.jpg". See: https://en.wikipedia.org/w/index.php?title=Capture_of_Berwick_(1482)&diff=prev&oldid=787464160

That declares it. Thanks for your answer!

> It's a bit difficult as the globe icon is tied to an extension (Wikipedia code) which XOWA doesn't support. I don't have plans on supporting this in the future as the extension embeds an online interactive map (which offline XOWA can never do).

Yeah. I understand. I wouldn't mind seeing it. But it definitely does not have to be there.

**Comment by Ope30** [comment]
> By the way, I made a build for the custom footer. Try the following:

> Hope this works for you.

Hey. I tried the build and it does what it's supposed to do! I removed the "Generated by XOWA" line, but then I have something else: https://image.prntscr.com/image/EOIy9cAEQpWiCwZoTUJeQA.jpeg
Is that removable as well?

**Comment by gnosygnu** [comment]
Yeah, you need to remove the entire line.

Try the following:

```
<div id="footer" role="contentinfo">
  <ul id="footer-info">
    <li id="footer-info-lastmod"> ~{page_modified_on_msg}</li>
    <li id="footer-info-copyright">~{<>msgs.get('wikimedia-copyright');<>}
  </ul>  
  <ul id="footer-places">
    <li id="footer-places-privacy"><a href="/wiki/~{<>msgs.get('privacypage');<>}" class="extiw" title="~{<>msgs.get('privacy');<>}">~{<>msgs.get('privacy');<>}</a></li>
    <li id="footer-places-about"><a href="/wiki/~{<>msgs.get('Project:About');<>}" title="Wikipedia:About">~{<>msgs.get('aboutsite');<>}</a></li>
    <li id="footer-places-disclaimer"><a href="/wiki/~{<>msgs.get('disclaimerpage');<>}" title="~{<>msgs.get('Disclaimers');<>}">~{<>msgs.get('Disclaimers');<>}</a></li>    
    <li id="footer-places-developers"><a href="~{<>msgs.get('wikimedia-developers-url');<>}">~{<>msgs.get('wikimedia-developers');<>}</a></li>
    <li id="footer-places-cookiestatement"><a href="https://wikimediafoundation.org/wiki/Cookie_statement">Cookie statement</a></li>
  </ul>
  <ul id="footer-icons" class="noprint" style='height:10px'>
    <li id="footer-copyrightico">
      <a href="https://wikimediafoundation.org/"><img src="~{<>app.fsys.root_dir.to_http_file;<>}/bin/any/xowa/html/css/footer/wikimedia-button.png" width="88" height="31" alt="Wikimedia Foundation"/></a>
    </li>
    <li id="footer-poweredbyico">
      <a href="//www.mediawiki.org/"><img src="~{<>app.fsys.root_dir.to_http_file;<>}/bin/any/xowa/html/css/footer/poweredby_mediawiki_88x31.png" alt="Powered by MediaWiki" width="88" height="31"/></a>
    </li>
  </ul>  
  <div style="clear:both"></div>
</div>
```

**Comment by gnosygnu** [comment]
Hey, I'm just going to rename this issue so I can track them separately. Let me know if multiple issues is a problem, and I'll try to figure something else out.

Thanks!

**Comment by gnosygnu** [comment]
This customizable footer will be included in the next XOWA build (with an estimated release date of late July). In the meantime, I'm going to go ahead and close out this issue
