### ISSUE TITLE
French Wikipedia Small Font Size

### ISSUE THREAD

**Issue by Ope30** [gnosygnu/xowa#157]
https://image.prntscr.com/image/jxUS1lC-RHmYaBW-eKkbEA.jpeg
Can you see it at the left? What happened?

**Comment by gnosygnu** [comment]
Yeah, I think something got messed up in the footer change.

Try the change mentioned here: https://github.com/gnosygnu/xowa/issues/155#issuecomment-313889913

If it doesn't work, copy and paste the "View HTML" here.

Thanks.

**Comment by Ope30** [comment]
> Try the change mentioned here: #155 (comment)

Thank you! I fixed it.

**Comment by gnosygnu** [comment]
As per above, this was a bug related to the first pass at the customizable footer. I'm going to go ahead and mark this issue closed. Let me know if there is anything else.

Thanks.
