### ISSUE TITLE
"Page Was Last Modified" Bug

### ISSUE THREAD

**Issue by Ope30** [gnosygnu/xowa#158]
Hey. I noticed that "This page was last modified on" freezes. Let's say you firstly open XOWA (or however you're going to get to the first article) and your first article (the last time you closed XOWA) is "15th century", and you switch to "16th century", the "Page Was Last Modified" is still the same. Doesn't matter to what article you get, it will always be the same! I first noticed this in the German Wikipedia. It is the same in the English Wikipedia. I believe it is not a Wiki issue, I think it has something to do with the Fonter we changed last time? I'm not sure.

Edit: Yeah. I'm 99.99% sure it is a XOWA issue.

**Comment by gnosygnu** [comment]
Hey, thanks for the detailed report. And yes, it's related to the footer change from the last build.

I made a new build now that fixes it. You can download it from here: https://drive.google.com/open?id=0B9cb52zjL2rIaWFMX0pnUHpGMVk

Let me know if there's anything else.

Thanks!

**Comment by gnosygnu** [comment]
As detailed above, this was a transient error in between two debug builds. Tonight's release (4.5.15.1709) will not have this issue
