### ISSUE TITLE
Bug Report: Article missing Wikidata

### ISSUE THREAD

**Issue by Ope30** [gnosygnu/xowa#163]
en.wikipedia.org/wiki/Richard_Haddock is missing Wikidata, at the very bottom. But as always, this could be me, only. Same for you? I do not know what's causing this, reloading the page doesn't change anything.

**Comment by gnosygnu** [comment]
Hmm... I do have a Wikidata section at the very bottom. Can you try the following?

* Does this url exist in XOWA?: www.wikidata.org/wiki/Q3430835
* If it doesn't exist, then go to home/wiki/Special:XowaDiag?type=fs.check&wiki=www.wikidata.org and post the contents below.

Thanks!

**Comment by Ope30** [comment]
> Does this url exist in XOWA?: www.wikidata.org/wiki/Q3430835

It kind of does. But here is how it looks like: https://image.prntscr.com/image/0bJE1u0SQz2685nYAgCNgg.jpeg

> If it doesn't exist, then go to home/wiki/Special:XowaDiag?type=fs.check&wiki=www.wikidata.org and post the contents below.

scanning: E:\XOWA\XOWA67839393\wiki\www.wikidata.org\
fil|www.wikidata.org-core.wbase.xowa|5142351872|20170620 231438.000
fil|www.wikidata.org-core.xowa|2335797248|20170527 221042.000
fil|www.wikidata.org-file-core.xowa|57344|20161118 102253.684
fil|www.wikidata.org-file-user.xowa|57344|20161118 102253.684
fil|www.wikidata.org-text-ns.000-db.002.xowa|2061488128|20170620 231848.000
fil|www.wikidata.org-text-ns.000-db.003.xowa|2112319488|20170620 231946.000
fil|www.wikidata.org-text-ns.000-db.004.xowa|2096680960|20170620 232044.000
fil|www.wikidata.org-text-ns.000-db.005.xowa|2077986816|20170620 232142.000
fil|www.wikidata.org-text-ns.000-db.006.xowa|2046550016|20170620 232242.000
fil|www.wikidata.org-text-ns.000-db.007.xowa|2064646144|20170620 232344.000
fil|www.wikidata.org-text-ns.000-db.008.xowa|2050785280|20170620 232442.000
fil|www.wikidata.org-text-ns.000-db.009.xowa|2024681472|20170620 232540.000
fil|www.wikidata.org-text-ns.000-db.010.xowa|2028040192|20170620 232640.000
fil|www.wikidata.org-text-ns.000-db.011.xowa|2032758784|20170620 232740.000
fil|www.wikidata.org-text-ns.000-db.012.xowa|1934061568|20170620 232842.000
fil|www.wikidata.org-text-ns.000-db.013.xowa|2155241472|20170620 232942.000
fil|www.wikidata.org-text-ns.000-db.014.xowa|2079715328|20170620 233040.000
fil|www.wikidata.org-text-ns.000-db.015.xowa|2009231360|20170620 233142.000
fil|www.wikidata.org-text-ns.000-db.016.xowa|2170122240|20170620 233242.000
fil|www.wikidata.org-text-ns.000-db.017.xowa|2093539328|20170620 233344.000
fil|www.wikidata.org-text-ns.000-db.018.xowa|2292834304|20170620 233446.000
fil|www.wikidata.org-text-ns.000-db.019.xowa|2085220352|20170620 233546.000
fil|www.wikidata.org-text-ns.000-db.020.xowa|2506145792|20170620 233646.000
fil|www.wikidata.org-text-ns.000-db.021.xowa|2119966720|20170620 233746.000
fil|www.wikidata.org-text-ns.000-db.022.xowa|2146254848|20170620 233846.000
fil|www.wikidata.org-text-ns.000-db.023.xowa|1581862912|20170620 233944.000
fil|www.wikidata.org-text-ns.000.xowa|1965105152|20170620 231750.000
fil|www.wikidata.org-text-ns.004.xowa|111509504|20170620 231742.000
fil|www.wikidata.org-text-ns.008.xowa|888832|20170620 231746.000
fil|www.wikidata.org-text-ns.010.xowa|3248128|20170620 231842.000
fil|www.wikidata.org-text-ns.012.xowa|4816896|20170620 231842.000
fil|www.wikidata.org-text-ns.014.xowa|765952|20170620 231842.000
fil|www.wikidata.org-text-ns.1198.xowa|25862144|20170620 231842.000
fil|www.wikidata.org-text-ns.120.xowa|9740288|20170620 232236.000
fil|www.wikidata.org-text-ns.2600.xowa|602112|20170620 233338.000
fil|www.wikidata.org-text-ns.828.xowa|950272|20170620 232734.000
fil|www.wikidata.org-xtn.category.core.xowa|73728|20161113 233344.000
fil|www.wikidata.org-xtn.category.link-db.001.xowa|14622720|20161113 233344.000
fil|Xowa_wikidatawiki_2016-11_core.md5|61|20161113 230524.000
fil|Xowa_wikidatawiki_2016-11_core.wbase.md5|67|20161113 230936.000
fil|Xowa_wikidatawiki_2016-11_text_ns.000.md5|68|20161113 231252.000
fil|Xowa_wikidatawiki_2016-11_text_ns.000_db.002.md5|75|20161113 231352.000
fil|Xowa_wikidatawiki_2016-11_text_ns.000_db.003.md5|75|20161113 231452.000
fil|Xowa_wikidatawiki_2016-11_text_ns.000_db.004.md5|75|20161113 231554.000
fil|Xowa_wikidatawiki_2016-11_text_ns.000_db.005.md5|75|20161113 231654.000
fil|Xowa_wikidatawiki_2016-11_text_ns.000_db.006.md5|75|20161113 231756.000
fil|Xowa_wikidatawiki_2016-11_text_ns.000_db.007.md5|75|20161113 231856.000
fil|Xowa_wikidatawiki_2016-11_text_ns.000_db.008.md5|75|20161113 231958.000
fil|Xowa_wikidatawiki_2016-11_text_ns.000_db.009.md5|75|20161113 232100.000
fil|Xowa_wikidatawiki_2016-11_text_ns.000_db.010.md5|75|20161113 232202.000
fil|Xowa_wikidatawiki_2016-11_text_ns.000_db.011.md5|75|20161113 232310.000
fil|Xowa_wikidatawiki_2016-11_text_ns.000_db.012.md5|75|20161113 232420.000
fil|Xowa_wikidatawiki_2016-11_text_ns.000_db.013.md5|75|20161113 232830.000
fil|Xowa_wikidatawiki_2016-11_text_ns.000_db.014.md5|75|20161113 232934.000
fil|Xowa_wikidatawiki_2016-11_text_ns.000_db.015.md5|75|20161113 233038.000
fil|Xowa_wikidatawiki_2016-11_text_ns.000_db.016.md5|75|20161113 233142.000
fil|Xowa_wikidatawiki_2016-11_text_ns.000_db.017.md5|75|20161113 233246.000
fil|Xowa_wikidatawiki_2016-11_text_ns.004.md5|68|20161113 231244.000
fil|Xowa_wikidatawiki_2016-11_text_ns.008.md5|68|20161113 231246.000
fil|Xowa_wikidatawiki_2016-11_text_ns.010.md5|68|20161113 231346.000
fil|Xowa_wikidatawiki_2016-11_text_ns.012.md5|68|20161113 231346.000
fil|Xowa_wikidatawiki_2016-11_text_ns.014.md5|68|20161113 231346.000
fil|Xowa_wikidatawiki_2016-11_text_ns.1198.md5|69|20161113 231346.000
fil|Xowa_wikidatawiki_2016-11_text_ns.120.md5|68|20161113 231750.000
fil|Xowa_wikidatawiki_2016-11_text_ns.2600.md5|69|20161113 232928.000
fil|Xowa_wikidatawiki_2016-11_text_ns.828.md5|68|20161113 232158.000
fil|Xowa_wikidatawiki_2016-11_xtn.category.core.md5|74|20161113 233344.000
fil|Xowa_wikidatawiki_2016-11_xtn.category.link_db.001.md5|81|20161113 233344.000
fil|Xowa_wikidatawiki_2017-02_core.wbase.md5|67|20170228 220750.000
fil|Xowa_wikidatawiki_2017-02_text_ns.000.md5|68|20170228 221102.000
fil|Xowa_wikidatawiki_2017-02_text_ns.000_db.002.md5|75|20170228 221200.000
fil|Xowa_wikidatawiki_2017-02_text_ns.000_db.003.md5|75|20170228 221258.000
fil|Xowa_wikidatawiki_2017-02_text_ns.000_db.004.md5|75|20170228 221354.000
fil|Xowa_wikidatawiki_2017-02_text_ns.000_db.005.md5|75|20170228 221452.000
fil|Xowa_wikidatawiki_2017-02_text_ns.000_db.006.md5|75|20170228 221552.000
fil|Xowa_wikidatawiki_2017-02_text_ns.000_db.007.md5|75|20170228 221650.000
fil|Xowa_wikidatawiki_2017-02_text_ns.000_db.008.md5|75|20170228 221748.000
fil|Xowa_wikidatawiki_2017-02_text_ns.000_db.009.md5|75|20170228 221846.000
fil|Xowa_wikidatawiki_2017-02_text_ns.000_db.010.md5|75|20170228 221946.000
fil|Xowa_wikidatawiki_2017-02_text_ns.000_db.011.md5|75|20170228 222048.000
fil|Xowa_wikidatawiki_2017-02_text_ns.000_db.012.md5|75|20170228 222148.000
fil|Xowa_wikidatawiki_2017-02_text_ns.000_db.013.md5|75|20170228 222248.000
fil|Xowa_wikidatawiki_2017-02_text_ns.000_db.014.md5|75|20170228 222350.000
fil|Xowa_wikidatawiki_2017-02_text_ns.000_db.015.md5|75|20170228 222458.000
fil|Xowa_wikidatawiki_2017-02_text_ns.000_db.016.md5|75|20170228 222602.000
fil|Xowa_wikidatawiki_2017-02_text_ns.000_db.017.md5|75|20170228 222702.000
fil|Xowa_wikidatawiki_2017-02_text_ns.000_db.018.md5|75|20170228 222806.000
fil|Xowa_wikidatawiki_2017-02_text_ns.000_db.019.md5|75|20170228 222904.000
fil|Xowa_wikidatawiki_2017-02_text_ns.004.md5|68|20170228 221054.000
fil|Xowa_wikidatawiki_2017-02_text_ns.008.md5|68|20170228 221056.000
fil|Xowa_wikidatawiki_2017-02_text_ns.010.md5|68|20170228 221152.000
fil|Xowa_wikidatawiki_2017-02_text_ns.012.md5|68|20170228 221152.000
fil|Xowa_wikidatawiki_2017-02_text_ns.014.md5|68|20170228 221152.000
fil|Xowa_wikidatawiki_2017-02_text_ns.1198.md5|69|20170228 221152.000
fil|Xowa_wikidatawiki_2017-02_text_ns.120.md5|68|20170228 221546.000
fil|Xowa_wikidatawiki_2017-02_text_ns.2600.md5|69|20170228 222448.000
fil|Xowa_wikidatawiki_2017-02_text_ns.828.md5|68|20170228 221942.000
fil|Xowa_wikidatawiki_2017-02_xtn.category.core.md5|74|20170228 222928.000
fil|Xowa_wikidatawiki_2017-02_xtn.category.link_db.001.md5|81|20170228 222928.000
fil|Xowa_wikidatawiki_2017-05_core.md5|61|20170527 221042.000
fil|Xowa_wikidatawiki_2017-05_core.wbase.md5|67|20170527 221228.000
fil|Xowa_wikidatawiki_2017-05_text_ns.000.md5|68|20170527 221536.000
fil|Xowa_wikidatawiki_2017-05_text_ns.000_db.002.md5|75|20170527 221632.000
fil|Xowa_wikidatawiki_2017-05_text_ns.000_db.003.md5|75|20170527 221728.000
fil|Xowa_wikidatawiki_2017-05_text_ns.000_db.004.md5|75|20170527 221826.000
fil|Xowa_wikidatawiki_2017-05_text_ns.000_db.005.md5|75|20170527 221924.000
fil|Xowa_wikidatawiki_2017-05_text_ns.000_db.006.md5|75|20170527 222022.000
fil|Xowa_wikidatawiki_2017-05_text_ns.000_db.007.md5|75|20170527 222120.000
fil|Xowa_wikidatawiki_2017-05_text_ns.000_db.008.md5|75|20170527 222218.000
fil|Xowa_wikidatawiki_2017-05_text_ns.000_db.009.md5|75|20170527 222316.000
fil|Xowa_wikidatawiki_2017-05_text_ns.000_db.010.md5|75|20170527 222414.000
fil|Xowa_wikidatawiki_2017-05_text_ns.000_db.011.md5|75|20170527 222512.000
fil|Xowa_wikidatawiki_2017-05_text_ns.000_db.012.md5|75|20170527 222612.000
fil|Xowa_wikidatawiki_2017-05_text_ns.000_db.013.md5|75|20170527 222710.000
fil|Xowa_wikidatawiki_2017-05_text_ns.000_db.014.md5|75|20170527 222808.000
fil|Xowa_wikidatawiki_2017-05_text_ns.000_db.015.md5|75|20170527 222906.000
fil|Xowa_wikidatawiki_2017-05_text_ns.000_db.016.md5|75|20170527 223006.000
fil|Xowa_wikidatawiki_2017-05_text_ns.000_db.017.md5|75|20170527 223108.000
fil|Xowa_wikidatawiki_2017-05_text_ns.000_db.018.md5|75|20170527 223206.000
fil|Xowa_wikidatawiki_2017-05_text_ns.000_db.019.md5|75|20170527 223306.000
fil|Xowa_wikidatawiki_2017-05_text_ns.000_db.020.md5|75|20170527 223406.000
fil|Xowa_wikidatawiki_2017-05_text_ns.000_db.021.md5|75|20170527 223504.000
fil|Xowa_wikidatawiki_2017-05_text_ns.000_db.022.md5|75|20170527 223602.000
fil|Xowa_wikidatawiki_2017-05_text_ns.004.md5|68|20170527 221528.000
fil|Xowa_wikidatawiki_2017-05_text_ns.008.md5|68|20170527 221532.000
fil|Xowa_wikidatawiki_2017-05_text_ns.010.md5|68|20170527 221626.000
fil|Xowa_wikidatawiki_2017-05_text_ns.012.md5|68|20170527 221626.000
fil|Xowa_wikidatawiki_2017-05_text_ns.014.md5|68|20170527 221626.000
fil|Xowa_wikidatawiki_2017-05_text_ns.1198.md5|69|20170527 221626.000
fil|Xowa_wikidatawiki_2017-05_text_ns.120.md5|68|20170527 222016.000
fil|Xowa_wikidatawiki_2017-05_text_ns.2600.md5|69|20170527 223002.000
fil|Xowa_wikidatawiki_2017-05_text_ns.828.md5|68|20170527 222506.000
fil|Xowa_wikidatawiki_2017-06_core.wbase.md5|67|20170620 231438.000
fil|Xowa_wikidatawiki_2017-06_text_ns.000.md5|68|20170620 231750.000
fil|Xowa_wikidatawiki_2017-06_text_ns.000_db.002.md5|75|20170620 231848.000
fil|Xowa_wikidatawiki_2017-06_text_ns.000_db.003.md5|75|20170620 231946.000
fil|Xowa_wikidatawiki_2017-06_text_ns.000_db.004.md5|75|20170620 232044.000
fil|Xowa_wikidatawiki_2017-06_text_ns.000_db.005.md5|75|20170620 232142.000
fil|Xowa_wikidatawiki_2017-06_text_ns.000_db.006.md5|75|20170620 232242.000
fil|Xowa_wikidatawiki_2017-06_text_ns.000_db.007.md5|75|20170620 232344.000
fil|Xowa_wikidatawiki_2017-06_text_ns.000_db.008.md5|75|20170620 232442.000
fil|Xowa_wikidatawiki_2017-06_text_ns.000_db.009.md5|75|20170620 232540.000
fil|Xowa_wikidatawiki_2017-06_text_ns.000_db.010.md5|75|20170620 232640.000
fil|Xowa_wikidatawiki_2017-06_text_ns.000_db.011.md5|75|20170620 232740.000
fil|Xowa_wikidatawiki_2017-06_text_ns.000_db.012.md5|75|20170620 232842.000
fil|Xowa_wikidatawiki_2017-06_text_ns.000_db.013.md5|75|20170620 232942.000
fil|Xowa_wikidatawiki_2017-06_text_ns.000_db.014.md5|75|20170620 233040.000
fil|Xowa_wikidatawiki_2017-06_text_ns.000_db.015.md5|75|20170620 233142.000
fil|Xowa_wikidatawiki_2017-06_text_ns.000_db.016.md5|75|20170620 233242.000
fil|Xowa_wikidatawiki_2017-06_text_ns.000_db.017.md5|75|20170620 233344.000
fil|Xowa_wikidatawiki_2017-06_text_ns.000_db.018.md5|75|20170620 233446.000
fil|Xowa_wikidatawiki_2017-06_text_ns.000_db.019.md5|75|20170620 233546.000
fil|Xowa_wikidatawiki_2017-06_text_ns.000_db.020.md5|75|20170620 233646.000
fil|Xowa_wikidatawiki_2017-06_text_ns.000_db.021.md5|75|20170620 233746.000
fil|Xowa_wikidatawiki_2017-06_text_ns.000_db.022.md5|75|20170620 233846.000
fil|Xowa_wikidatawiki_2017-06_text_ns.000_db.023.md5|75|20170620 233944.000
fil|Xowa_wikidatawiki_2017-06_text_ns.004.md5|68|20170620 231742.000
fil|Xowa_wikidatawiki_2017-06_text_ns.008.md5|68|20170620 231746.000
fil|Xowa_wikidatawiki_2017-06_text_ns.010.md5|68|20170620 231842.000
fil|Xowa_wikidatawiki_2017-06_text_ns.012.md5|68|20170620 231842.000
fil|Xowa_wikidatawiki_2017-06_text_ns.014.md5|68|20170620 231842.000
fil|Xowa_wikidatawiki_2017-06_text_ns.1198.md5|69|20170620 231842.000
fil|Xowa_wikidatawiki_2017-06_text_ns.120.md5|68|20170620 232236.000
fil|Xowa_wikidatawiki_2017-06_text_ns.2600.md5|69|20170620 233338.000
fil|Xowa_wikidatawiki_2017-06_text_ns.828.md5|68|20170620 232734.000

scanning: E:\XOWA\XOWA67839393\file\www.wikidata.org\

scanning: E:\XOWA\XOWA67839393\file\www.wikidata.org\fsdb.main\

scanning: E:\XOWA\XOWA67839393\file\www.wikidata.org\fsdb.user\

scanning: E:\XOWA\XOWA67839393\file\www.wikidata.org\fsdb.update_00\

**Comment by gnosygnu** [comment]
> It kind of does. But here is how it looks like: https://image.prntscr.com/image/0bJE1u0SQz2685nYAgCNgg.jpeg

Hmm... well, it technically exists, but is empty. :)

>>  If it doesn't exist, then go to home/wiki/Special:XowaDiag?type=fs.check&wiki=www.wikidata.org and post the contents below.

> scanning: E:\XOWA\XOWA67839393\wiki\www.wikidata.org

Thanks for the output. For some reason, your core database is smaller than it should be.

Try downloading this file again: https://archive.org/download/Xowa_wikidatawiki_latest/Xowa_wikidatawiki_2017-06_core.zip

When it's done, unzip it and replace your version. The new version should be about 2,370,748,416 bytes.

Hopefully that works.

Thanks.

**Comment by Ope30** [comment]
> Try downloading this file again: https://archive.org/download/Xowa_wikidatawiki_latest/Xowa_wikidatawiki_2017-06_core.zip

Problem solved. Thanks for your help!

**Comment by gnosygnu** [comment]
Cool. Good to hear! I'm going to close out this issue, but feel free to comment if something else comes up.

Thanks!
