### ISSUE TITLE
Changing Bookmarks in the xowa.user.anonymous file

### ISSUE THREAD

**Issue by Ope30** [gnosygnu/xowa#169]
I need help with changing Bookmarks I created using another domain name. I changed all my Wikis folder, for example en.wikipedia.org into Englisch Wikipedia, de.wikipedia.org into Deutsch Wikipedia and so on. I tried changing it in the user file, but after saving it XOWA won't open. What I did is replace everything named "en.wikipedia.org" into Englisch Wikipedia, but I think I hit something I shouldn't hit. Do you have any idea that could help me further?

**Comment by gnosygnu** [comment]
Hey, not sure I understand the issue, so I comment specifically on parts

> I changed all my Wikis folder, for example en.wikipedia.org into Englisch Wikipedia, de.wikipedia.org into Deutsch Wikipedia and so on.

Are you renaming it at the folder level (EX: C:\xowa\wiki\Englisch Wikipedia). If so, you really shouldn't be. Instead, use the Url format option: home/wiki/Special:XowaCfg?grp=xowa.gui.url_bar.

If you are using Url format, then I don't quite see how it would be a problem. Can you attach a screenshot?

> I tried changing it in the user file, but after saving it XOWA won't open.

Do you mean you updated the user-database: xowa.user.anonymous.sqlite3 ? If so, which command did you use? If you don't remember, can you email me your xowa.user.anonymous.sqlite3 and I'll investigate

> What I did is replace everything named "en.wikipedia.org" into Englisch Wikipedia, but I think I hit something I shouldn't hit. Do you have any idea that could help me further?

Yeah, really need more detail. If you're getting an error message, send me a screenshot. If XOWA doesn't open (as indicated above), send me what you changed. You can also send me the latest log files from C:\xowa\user\anonymous\app\tmp\log

Hope that helps.

**Comment by Ope30** [comment]
> Are you renaming it at the folder level (EX: C:\xowa\wiki\Englisch Wikipedia). If so, you really shouldn't be.

Yeah, I did. I wouldn't have done it if I knew that Weblinks, Wikidata and such are not going to work then. :(

> Instead, use the Url format option: home/wiki/Special:XowaCfg?grp=xowa.gui.url_bar.

Hm. What does that do exactly? Does it change Domain-Names without changing the folder names?!

> If you are using Url format, then I don't quite see how it would be a problem. Can you attach a screenshot?

Nah. If I were using URL format everything would be fine!

> Do you mean you updated the user-database: xowa.user.anonymous.sqlite3 ? If so, which command did you use? If you don't remember, can you email me your xowa.user.anonymous.sqlite3 and I'll investigate

I opened the file with Notepad ++, then I replaced every text with "de.wikipedia.org" and "en.wikipedia.org" with German Wikipedia and English Wikipedia. That led to XOWA not working after the change in the file. If that's not enough, I can send you my file. But how do I do that? 

> Yeah, really need more detail. If you're getting an error message, send me a screenshot. If XOWA doesn't open (as indicated above), send me what you changed.

The wikis look like this now: https://image.prntscr.com/image/oEqP_Z8eSIyYkQGoW8rzCQ.jpeg
And due to that, Weblinks do not work. I'm not getting any errors. I'm getting nothing.

**Comment by gnosygnu** [comment]
>> Instead, use the Url format option: home/wiki/Special:XowaCfg?grp=xowa.gui.url_bar.

> Hm. What does that do exactly? Does it change Domain-Names without changing the folder names?!

It changes the domain name that shows in the URL bar. I was hoping it was enough to satisfy your desire to see "English Wikipedia" insead of "en.wikipedia.org"

For more info, click on the blue question mark help icon to the right of "Url format"

With that said, see the answer below.

>> Do you mean you updated the user-database: xowa.user.anonymous.sqlite3 ? If so, which command did you use? If you don't remember, can you email me your xowa.user.anonymous.sqlite3 and I'll investigate

> I opened the file with Notepad ++, then I replaced every text with "de.wikipedia.org" and "en.wikipedia.org" with German Wikipedia and English Wikipedia. That led to XOWA not working after the change in the file. If that's not enough, I can send you my file. But how do I do that? 

Yeah, you can't open a .xowa file in Notepad++. Chances are you corrupted the database.

If you have a backup copy, You should use that. If you don't have a backup copy, well then, you should always backup a file before changing it. ;)

>> Yeah, really need more detail. If you're getting an error message, send me a screenshot. If XOWA doesn't open (as indicated above), send me what you changed.

> The wikis look like this now: https://image.prntscr.com/image/oEqP_Z8eSIyYkQGoW8rzCQ.jpeg
And due to that, Weblinks do not work. I'm not getting any errors. I'm getting nothing.

Ok, I understand. The left-hand navbar does not support folder-renames. Also, "Url format" isn't going to help that either.

For now, there really isn't a workaround. I'd change the names back to en.wikipedia.org, etc.. Domain name is used everywhere, and unfortunately, it's just a hunt and peck game to find all the usages.

Sorry.

**Comment by Ope30** [comment]
> It changes the domain name that shows in the URL bar. I was hoping it was enough to satisfy your desire to see "English Wikipedia" insead of "en.wikipedia.org"

I never know you implemented this. :( However, thanks for telling me!

> Yeah, you can't open a .xowa file in Notepad++. Chances are you corrupted the database.

Understood.

> If you have a backup copy, You should use that. If you don't have a backup copy, well then, you should always backup a file before changing it. ;)

I never edit a file without making a backup first!

> Ok, I understand. The left-hand navbar does not support folder-renames. Also, "Url format" isn't going to help that either.

Damn. Okay. I've thought about this, the function that shows the Domain-Names in XOWA, would that be possible to change without actually editing the real ones? Same as if you were changing an element in Firefox

> For now, there really isn't a workaround. I'd change the names back to en.wikipedia.org, etc.. Domain name is used everywhere, and unfortunately, it's just a hunt and peck game to find all the usages.

Agreed.

**Comment by gnosygnu** [comment]
> Okay. I've thought about this, the function that shows the Domain-Names in XOWA, would that be possible to change without actually editing the real ones? Same as if you were changing an element in Firefox

Not really. I have to change the code so that it knows that "en.wikipedia.org" is "English Wikipedia". Moreover, this would need to be user-customized, as in your case, where you want "Englisch Wikipedia"

Domain name is a fundamental identifier throughout the app. It's not easy to swap out a name for it.

Thanks.

**Comment by gnosygnu** [comment]
I'm marking this issue closed for now. A future enhancement may allow the bookmarks page to support custom wiki names (instead of domain names), but for now it's not posssible.

Thanks.
