### ISSUE TITLE
Error Downloading 3

### ISSUE THREAD

**Issue by francoiscourt** [gnosygnu/xowa#172]
I get the following error trying to download "English Wikipedia - Images: New Users"
 Xowa_enwiki_2017-02-15_file_core.zip ·(1/77)
move failed: file not deleted: url=D:\Xowa\wiki\en.wikipedia.org\en.wikipedia.org-file-core.xowa

**Comment by gnosygnu** [comment]
Hi! This looks a lot like #173 

If there isn't anything different, then I'd like to close this issue. Let me know if there's something else.

Thanks!

**Comment by gnosygnu** [comment]
As mentioned above, this looks related to #173. I'm going to mark this ticket closed for now. Let me know if there's anything else and I'll reopen. Thanks.
