### ISSUE TITLE
Error trying to download "English Wikipedia - Images: New Users"

### ISSUE THREAD

**Issue by francoiscourt** [gnosygnu/xowa#173]
I get the following error trying to download "English Wikipedia - Images: New Users"
Xowa_enwiki_2017-02-15_file_core.zip ·(1/77)
move failed: file not deleted: url=D:\Xowa\wiki\en.wikipedia.org\en.wikipedia.org-file-core.xowa

**Comment by gnosygnu** [comment]
Hi! Thanks for creating the ticket.

It looks like it failed when moving the file. Can you try the following:
* Close all tabs (especially any tabs with English Wikipedia)
* Restart XOWA
* Go to Download Central
* Press the Play button

If that fails, you can try removing them item by clicking the "minus" icon and then re-adding it back.

Finally, if that too fails, you can try downloading the files manually. See: http://xowa.org/home/wiki/Wiki_setup/English_wikis

Hope that helps. Thanks!

**Comment by gnosygnu** [comment]
I'm going to mark this item unreproducible for now. Let me know if it's still an issue, and I'll reopen to investigate. Thanks.

**Comment by EnforcerE** [comment]
It isnt reproducible. It happened to me as well.
