### ISSUE TITLE
Improving XOWA's Internet Download Speed

### ISSUE THREAD

**Issue by Ope30** [gnosygnu/xowa#174]
Does XOWA offer a way to increase its download speed?

**Comment by gnosygnu** [comment]
Not really. In the end download speed is controlled by your ISP and the source server (archive.org / wikimedia.org)

If you're concerned about speed, the best thing to do is to download the urls through your browser and use a download plugin. They do more clever things to maximized download speed.

Thanks.

**Comment by Ope30** [comment]
> Not really. In the end download speed is controlled by your ISP and the source server (archive.org / wikimedia.org)

> If you're concerned about speed, the best thing to do is to download the urls through your browser and use a download plugin. They do more clever things to maximized download speed.

True that. I was talking about Commons though. When downloading images and such. But, still. Don't think it's possible neither

**Comment by gnosygnu** [comment]
Ah, understood. Same applies to Commons as well, especially for single files.

Hope that helps.

Thanks

**Comment by gnosygnu** [comment]
As detailed above, there is no easy way to increase download speeds for Download Central. The best thing would be to download files separately through a web browser and some dedicated download manager extension.

Hope this helps. Thanks.
