### ISSUE TITLE
Bug Report: Bugged Portal (?)

### ISSUE THREAD

**Issue by Ope30** [gnosygnu/xowa#175]
Please check out de.wikipedia.org/wiki/Portal:Kölner_Dom
What's your result? Because, for me, the page is bugged. (See https://image.prntscr.com/image/A_H-8aA6TQC1-sgA2jvdCg.jpeg)
Has it something to do with https://github.com/gnosygnu/xowa/issues/156?

**Comment by gnosygnu** [comment]
Hey, thanks for the details. 

The problem is that the page uses the User namespace which are not part of the HTML database downloads.

You can build it on your own, but it's a bit complicated. You'd have to do an offline import of home/wiki/Dashboard/Import/Offline using a meta-current dump. For example: https://dumps.wikimedia.org/dewiki/20170801/dewiki-20170801-pages-meta-current.xml.bz2

```
{{Benutzer:Anitagraser/Textbox
|BILD=Aldus leaf unicode2619.svg
|TITEL=Willkommen im Portal Kölner Dom!
|editpage=Portal:Kölner Dom/Willkommen
|INHALT=Willkommen
|COLOR=#f8f3ec
}}
```

Let me know if you have any other questions.

Thanks!

**Comment by Ope30** [comment]
> The problem is that the page uses the User namespace which are not part of the HTML database downloads.

> You can build it on your own, but it's a bit complicated. You'd have to do an offline import of home/wiki/Dashboard/Import/Offline using a meta-current dump. For example: https://dumps.wikimedia.org/dewiki/20170801/dewiki-20170801-pages-meta-current.xml.bz2

Ah. Damn.. Is there a way to import every single User namespace article, also known as Portal?

> {{Benutzer:Anitagraser/Textbox
|BILD=Aldus leaf unicode2619.svg
|TITEL=Willkommen im Portal Kölner Dom!
|editpage=Portal:Kölner Dom/Willkommen
|INHALT=Willkommen
|COLOR=#f8f3ec
}}

Do I have to do something with that code?

**Comment by gnosygnu** [comment]
> Ah. Damn.. Is there a way to import every single User namespace article, also known as Portal?

Yeah, you have to do the import manually. Specifically: 

* Download a meta-current dump. For example, https://dumps.wikimedia.org/dewiki/20170801/dewiki-20170801-pages-meta-current.xml.bz2
* Go to home/wiki/Dashboard/Import/Offline
* Follow the instructions at the bottom of the page and do an import

> Do I have to do something with that code?

Nah, that was just an example.

> Yeah. Can you explain to me how to download new wikis on my own?

You can start off with the manual import above. Let me know how it goes, and we'll take it from there.

Thanks!

**Comment by Ope30** [comment]
I tried to do it on my own today, and it worked. I thought it was way harder, but it's actually pretty easy!

Unfortunately, I forgot a file or something, because after the Import it said "Missing a file in dir, import not fully completed) or something. I think it's referring to full-text-search? Because I can't use it

Also, articles are missing images. So yeah. I forgot something.

Here's the log. Hopefully you'll find out what I forgot and how to avoid it next time:

scanning: E:\XOWA\XOWA Test Folder\wiki\de.wikipedia.org\
fil|de.wikipedia.org-core.xowa|656211968|20170817 114638.243
fil|de.wikipedia.org-file-core.xowa|57344|20170817 114957.631
fil|de.wikipedia.org-file-user.xowa|798720|20170817 114957.631
fil|de.wikipedia.org-text-ns.000-db.002.xowa|1955287040|20170817 114228.025
fil|de.wikipedia.org-text-ns.000-db.003.xowa|1951305728|20170817 114228.026
fil|de.wikipedia.org-text-ns.000-db.004.xowa|410198016|20170817 114228.028
fil|de.wikipedia.org-text-ns.000.xowa|1851420672|20170817 114227.817
fil|de.wikipedia.org-text-ns.001.xowa|1508245504|20170817 114227.818
fil|de.wikipedia.org-text-ns.002.xowa|563695616|20170817 114227.817
fil|de.wikipedia.org-text-ns.003.xowa|1571377152|20170817 114227.819
fil|de.wikipedia.org-text-ns.004.xowa|923688960|20170817 114227.818
fil|de.wikipedia.org-text-ns.005.xowa|214962176|20170817 114227.820
fil|de.wikipedia.org-text-ns.006.xowa|42995712|20170817 114227.962
fil|de.wikipedia.org-text-ns.007.xowa|1040384|20170817 114228.022
fil|de.wikipedia.org-text-ns.008.xowa|544768|20170817 114227.964
fil|de.wikipedia.org-text-ns.009.xowa|2277376|20170817 114228.020
fil|de.wikipedia.org-text-ns.010.xowa|54976512|20170817 114227.963
fil|de.wikipedia.org-text-ns.011.xowa|16945152|20170817 114228.023
fil|de.wikipedia.org-text-ns.012.xowa|1728512|20170817 114227.823
fil|de.wikipedia.org-text-ns.013.xowa|5570560|20170817 114227.961
fil|de.wikipedia.org-text-ns.014.xowa|44859392|20170817 114228.023
fil|de.wikipedia.org-text-ns.015.xowa|8798208|20170817 114228.025
fil|de.wikipedia.org-text-ns.100.xowa|43548672|20170817 114227.820
fil|de.wikipedia.org-text-ns.101.xowa|64237568|20170817 114227.962
fil|de.wikipedia.org-text-ns.828.xowa|782336|20170817 114228.027
fil|de.wikipedia.org-text-ns.829.xowa|57344|20170817 114228.027
fil|de.wikipedia.org-xtn.category.core.xowa|4820992|20170817 114957.631
fil|de.wikipedia.org-xtn.category.link-db.001.xowa|1124573184|20170817 114957.631
fil|de.wikipedia.org-xtn.search.core.xowa|234262528|20170817 114227.278
fil|de.wikipedia.org-xtn.search.link-title-ns.000-db.001.xowa|302465024|20170817 113800.338
fil|de.wikipedia.org-xtn.search.link-title-ns.999-db.001.xowa|209833984|20170817 114124.823
fil|dewiki-20170801-pages-meta-current.xml|28476697938|20170817 104046.876

scanning: E:\XOWA\XOWA Test Folder\file\de.wikipedia.org\
dir|thumb\

scanning: E:\XOWA\XOWA Test Folder\file\de.wikipedia.org\fsdb.main\

scanning: E:\XOWA\XOWA Test Folder\file\de.wikipedia.org\fsdb.user\

scanning: E:\XOWA\XOWA Test Folder\file\de.wikipedia.org\fsdb.update_00\

**Comment by gnosygnu** [comment]
> I tried to do it on my own today, and it worked. I thought it was way harder, but it's actually pretty easy!

Cool. Good to hear.

> Unfortunately, I forgot a file or something, because after the Import it said " .sql file not found in dir". I think it's referring to full-text-search? However, I know why. I did not download every file that was provided. I only downloaded one specific file that you mentioned. Next time I'm going to download all files.

Yeah, you need a few other files. From the instructions ;)

* Download two additional files for the category system:
    * wiki-date-categorylinks.sql.gz
    * wiki-date-page_props.sql.gz.
* Download an additional file for sorting search results by PageRank
    * wiki-date-pagelinks.sql.gz.

> Though, articles are missing images. I think this has nothing to do with the fact that I did not download the complete set, because just to be sure I downloaded a small wiki with all files, and it was missing images (compared it to the online version). 

When you use the offline option, you still need to download the images. The offline import doesn't download images. If you do want images, the process is more intricate, as you would need to do command-line: http://xowa.org/home/wiki/Dev/Command-line/Dumps

> Whatever. Could you include the User namespace Article for future wikis (2017-08 or -09 German, English Commons)? That would be great, I'd look after to download Wikis on my own, but fully working.

Sorry, but I don't have plans to do this. The User namespace literally doubles the processing time and space requirements. For English Wikipedia, it would jump from 100 GB to 200 GB and would take one week to build. If someone wants to do this, they can try going thru the command-line option above. Otherwise, it really isn't worth the effort.

> Curious about this: Let's say you fix a bunch of bugs in Commons, and I download it on my own, do these fixes still apply? Or do I have to download your set? 

In most cases, you would have to download another set.

> And what about your download speed when you download wikis at their Dump Site? It takes way longer than downloading it at archives.org

archive.org is a free community resource, but unfortunately it is not fast. Unfortunately, there's really nothing to do about it.

**Comment by Ope30** [comment]
> Yeah, you need a few other files. From the instructions ;)

Yoah. The thing is, I downloaded these files when I was downloading the one wiki for testing, you know. I downloaded hi.wikibooks, though I don't have full-text-search. As it says in the instructions, I have to start the dump with "hiwikibooks-20170801-pages-meta-current", which I did. After the dump is complete, these files you listed above get deleted automatically. Maybe the wiki doesn't support full-text-search yet, or so. Not even the original one. Not sure.

> When you use the offline option, you still need to download the images. The offline import doesn't download images. If you do want images, the process is more intricate, as you would need to do command-line: http://xowa.org/home/wiki/Dev/Command-line/Dumps

That looks.... Ugh.. Okay. Will look at it

> Sorry, but I don't have plans to do this. The User namespace literally doubles the processing time and space requirements. For English Wikipedia, it would jump from 100 GB to 200 GB and would take one week to build. If someone wants to do this, they can try going thru the command-line option above. Otherwise, it really isn't worth the effort.

Really? I did not know it would make such a big difference. But okay. I understand.

> archive.org is a free community resource, but unfortunately it is not fast. Unfortunately, there's really nothing to do about it.

True.... :(

**Comment by gnosygnu** [comment]
> Yoah. The thing is, I downloaded these files when I was downloading the one wiki for testing, you know. I downloaded hi.wikibooks, though I don't have full-text-search. As it says in the instructions, I have to start the dump with "hiwikibooks-20170801-pages-meta-current", which I did. After the dump is complete, these files you listed above get deleted automatically. Maybe the wiki doesn't support full-text-search yet, or so. Not even the original one. Not sure.

Yeah, full-text search needs to be done through the command-line. There's no GUI for it.

> Can you include 2017-08 (or 9, up to you) German Wiki as well, along with Commons? I think I'll stop downloading wikis for a while, of course if there's nothing that forces me to redownload!

Let's try 2017-09 German Wikipedia.

Thanks.

**Comment by gnosygnu** [comment]
I think this issue was related to the missing User namespace for German Wikipedia. As such, I'm marking this issue closed for now. Let me know if there's anything else, and I'll reopen.

Thanks.
