### ISSUE TITLE
Searching for an empty string produces an edit page for Special:Search

### ISSUE THREAD

**Issue by bilde2910** [gnosygnu/xowa#19]
See title. If you search for an empty string in the search box, an edit page for Special:Search appears.

**Comment by gnosygnu** [comment]
Thanks for the catch! This broke in v2.8.1. I'll fix it in v2.8.3 so that an empty string returns no results.

**Comment by gnosygnu** [comment]
This was fixed in v2.8.3. I confirmed with the following url within XOWA: https://en.wikipedia.org/wiki/Special:Search?search=&fulltext=y
