### ISSUE TITLE
Android v0.1: simple wiki: earth: right side is cut off and I am unable to scroll vertically

### ISSUE THREAD

**Issue by AnselmD** [gnosygnu/xowa#2]
Hi,
my first try to make an issue, after you start to move to github

xowa_v0.1.apk

at the earth page, sometimes the right side is cut off at my devices with a small display and I am not able to scroll horizontally:

![img_3938_](https://cloud.githubusercontent.com/assets/6770907/8276636/26999aa6-18b9-11e5-8493-a39cef2053e3.jpg)
![img_3939](https://cloud.githubusercontent.com/assets/6770907/8276654/4dc007aa-18b9-11e5-9cf9-1e39279cef65.JPG)

**Comment by gnosygnu** [comment]
Hey! Good to see you here! And thanks for coming over so quickly. :)

This is an issue with Android. I have a Froyo (like my Samsung Galaxy S) and it gets cut off like yours. However, on my KitKat device, it is scrollable. I assume the WebView browser was upgraded to handle horizontal scrolling in tables during one of the Android releases.

Also, as an FYI, the Mobile Wikipedia website hides these boxes. You can see at https://simple.m.wikipedia.org/wiki/Earth . I'm showing them for now, but will probably put a config option later to hide them.

I'm going to mark this closed for now. Let me know if you feel differently and I'll reopen.

Thanks!
