### ISSUE TITLE
wikilinks mimor error

### ISSUE THREAD

**Issue by pirate486743186** [gnosygnu/xowa#22]
when you have a wikilink like this "[[monster]]s".
The "s" is not part of the blue link as it should be, it's just black text.

**Comment by gnosygnu** [comment]
Hey, thanks for the example.

This is a bug affecting non-WikiMedia wikis. (in this case, the nethackwiki). I'll fix this for v2.8.4 this Sunday.

**Comment by gnosygnu** [comment]
This is fixed in tonight's release. I confirmed with the Main Page of the nethack wiki and the "[[Monster]]s" panel in the lower-right.
