### ISSUE TITLE
XOWA doesnt accept folder shortcuts

### ISSUE THREAD

**Issue by EnforcerE** [gnosygnu/xowa#233]
I have noticed that installing wikipedia to xowa takes approximately 100gb of storage. I have enough storage but it makes my computer practically unusable. Anyway I was attempting to move folder ...\XOWA\wiki to my home server and making a shortcut named wiki instead of that folder that points to my server. However XOWA didnt show any wikis downloaded locally. Also when I tryed to change my download location in download central to my server I found out that you cannot freely write the destination folder (as in \\192.168.0.something\some folder). I think that this, if not a bug is at least a problem.

**Comment by gnosygnu** [comment]
Hi! Thanks for the detailed ticket.

I think there are two issues here:
* You're using Windows shortcuts to try to get XOWA to point to another folder. If you are using Windows folder shortcuts then they won't work. Linux shortcuts work but Windows will not and I don't think there's anything XOWA can do to help out here (it's an OS level issue). 
* You're trying to change the download location for Download Central. If so, then no, that is not possible. Download Central will download to a specific folder underneath that wiki (C:\xowa\wiki\en.wikipedia.org\tmp) and this can't be modified.

Sorry if the above is the case. Let me know if there is anything else!

**Comment by EnforcerE** [comment]
Well can they (windows shortcuts) be made to work in a future update or manually?

**Comment by EnforcerE** [comment]
That is incorrect. I solved my issue with symlinks. They are simply hidden from everyones eyes. I used command mklink /J
