### ISSUE TITLE
"Next 200" concerning huge Categories (EN-Wikipedia)

### ISSUE THREAD

**Issue by Ope30** [gnosygnu/xowa#237]
Hey.

I'm not awaiting an immediate fix or anything in the coming days or weeks, this is just for the sake of your information!

Unfortunately, using the function "Next 200" in huge Categories is not working, example is en.wikipedia.org/wiki/Category:20th-century_American_male_actors or en.wikipedia.org/wiki/Category:All_stub_articles?pagefrom=A%2Btu%2Bregreso#mw-pages

GIF:

![honeycam 2018-08-14 23-16-36](https://user-images.githubusercontent.com/19750226/44119014-335d3c90-a018-11e8-9a58-8841ee1af15b.gif)

I think Wikimedia slightly screwed up the Category-System.

**Comment by gnosygnu** [comment]
Thanks for the gif. The category system has always been complicated. I'll try to take a look a this, but it may be a difficult fix

**Comment by desb42** [comment]
I have been looking at this problem. It's down to a sorting problem with ICU (International Components for Unicode)
The version currently used by en.wikipedia.org (look at https://en.wikipedia.org/wiki/Special:Version) is 57.1
Xowa currently ships with 4.8 (a bit of a difference)

Downloading icu4j-57_1.jar and rebuilding makes it work

I first tried with latest version 63.1 - but this is also incompatible - must stay in lockstep with wikipedia.
I have not looked at any other wikipedia to see if an ICU version check might be necessary - I hope not.

**Comment by gnosygnu** [comment]
> Downloading icu4j-57_1.jar and rebuilding makes it work

Nice! Thanks for figuring this out. I'll give this a try when I get back from vacation next week

**Comment by gnosygnu** [comment]
Pushed changes as recommended. Will keep an eye out for this after I build the next enwiki. Thanks again for the fix, as well as the reminder.

**Comment by gnosygnu** [comment]
I've verified that the fix works with 2019-05 English Wikipedia. Thanks again @desb42 for the fix
