### ISSUE TITLE
Can't access my downloaded pages

### ISSUE THREAD

**Issue by RogerGodzilla** [gnosygnu/xowa#240]
I am using windows 10 64 bit on a 64 bit machine with java 64 bit and xowa 64 bit for windows. I have downloaded en.wikipedia.org (text only), but can't access it. When I try to access it, there is a short piece of text in the bottom left that says "could not find name in wiki: en.wikipedia.org/" although I can view the files in file explorer or in xowa. Any ideas?

**Comment by gnosygnu** [comment]
Hi,

Thanks for the details. It sounds like you downloaded the 2018-07 text databases from here: https://archive.org/download/Xowa_enwiki_latest/ . Here's a few things I can think of:

* Did you download "Xowa_enwiki_2018-07_core.zip" as well? You need this file no matter what
* Did you unzip all the files? They should be ".xowa", not ".zip"
* Are they placed in the right folder? If you put XOWA at C:\xowa, then the files need to go to C:\xowa\wiki\en.wikipedia.org

If the above still doesn't work, then go to the following pages and copy-paste the text here:
* The log file: home/wiki/Special:XowaSystemData?type=log_session
* The en.wiki folder: home/wiki/Special:XowaDiag?type=fs.check&wiki=en.wikipedia.org

Hope this helps. Thanks!

**Comment by RogerGodzilla** [comment]
Gnosygnu: I download it from the built in download central section... It doesn't have the core.zip file though. I'll try that.

**Comment by RogerGodzilla** [comment]
This worked. I downloaded only the core file mentioned above, and put the unzipped file into the en.wikipedia.com folder on my computer.
