### ISSUE TITLE
Wikimedia

### ISSUE THREAD

**Issue by shapeshifter910** [gnosygnu/xowa#25]
Hi,
I've downloaded and installed Xowa and wikipedia with the images.
But I still get the notice that I need Wikimedia.
But there is no wikimedia download.

I'm quite confused by the "download wikis" page.
What is the html section? Do I need that?

Third question.
Are updates cumulative or do I need to download all updates?
My wiki download is the one from 2015-06-02. So do I need the images updates 2015-08-05 and 2015-09-01 or just the 2015-09-01?

Thanks for Xowa. It's nice to have an off-line wikipedia.

**Comment by shapeshifter910** [comment]
Ok, I've noticed the updates overwrite previous files. So that answers my third question.

**Comment by gnosygnu** [comment]
Hi! Thanks for the interest in XOWA. 

> But I still get the notice that I need Wikimedia.

Hmm... Are you getting this message when clicking on an image? It shouldn't happen with a recent version of XOWA (anything > v2.7).

If you're not getting this message when clicking on an image, can you detail your steps or post a screenshot? I can't think of anything that directly needs Wikimedia content after a wiki is set up

> I'm quite confused by the "download wikis" page.
> What is the html section? Do I need that?

The HTML databases are for the XOWA Android Alpha. https://github.com/gnosygnu/xowa/releases/tag/v0.1 Right now, the Alpha can only read pre-generated HTML. If you're not using Android, you can skip them.

> Are updates cumulative or do I need to download all updates?
> Ok, I've noticed the updates overwrite previous files. So that answers my third question.

Yup, updates are incremental. I start off with a base set (2015-06) and publish updates every month (2015-08, 2015-09). Each update should be installed in order, and any newer files should overwrite older ones.

Hope this helps!

**Comment by shapeshifter910** [comment]
Thank you for the explanation.
I suppose the wikimedia message is not really an error message but rather an informative message.
The steps to get it are:
Open Xowa which opens to a Main Page. Then I click on "en.wikipedia.org" on the left side bar under Wikis
From there I go to any page with an image.
The below is an image that appeared right on the Main Page.
When I click on it, I get the following message
======================================================
File:Cullerlie-Circle.jpg
From XOWA: a free, open-source, offline wiki application
	

This offline page is a reduced version of the online one: https://commons.wikimedia.org/wiki/File:Cullerlie-Circle.jpg.

If you want XOWA to show an offline page just like the online version, you should download commons.wikimedia.org at Import online.

    This wiki will use at least another 20 GB of disk space.
    This wiki only provides wikitext. No extra images are downloaded. Note that the total size of images for commons.wikimedia.org would be too large (approximately 22 TB).
=======================================================
So that explains that full resolution images are not included in Xowa.

One further question I have is:
Under Wikis on the left sidebar on the Main Page I have two links
commons.wikimedia.org
en.wikipedia.org

the en.wikipedia.org works and takes me to the wikipedia
but the commons.wikimedia.org doesn't do anything. When clicked it says on the status bar "Could not find: commons.wikimedia.org/

**Comment by gnosygnu** [comment]
> The steps to get it are:

Thanks for the steps! And yes, you're right. This is not an error message, but just an information message.

XOWA shows a basic version of https://commons.wikimedia.org/wiki/File:Cullerlie-Circle.jpg . If you want an offline version that looks like the online one (with the "Summary" and "Licensing" sections), then you need to download commons.wikimedia.org from home/wiki/Help:Import/List . For 95% of users, the current version should be enough.

> So that explains that full resolution images are not included in Xowa.

Yeah, full resolution versions of images would easily be many TB. You can download a full resolution version of the image you're interested in by clicking on the image within XOWA. For example, if you click on any part of the picture (say, somewhere within the circle of stones), then XOWA will download the full resolution version from Wikimedia and put it in /xowa/wiki/en.wikipedia.org/en.wikipedia.org-file-user.xowa

> but the commons.wikimedia.org doesn't do anything.

Ah! That's a bug on my side. I usually keep the "Wikis" section collapsed. Thanks for reporting it!

I usually like to credit users with finding bugs. Right now, there'll be a line in the Change Log that says something like "Do not show commons.wikimedia.org if it has not been imported {detected by anonymous}". Let me know if you would like to be cited with a certain nickname, or would remain anonymous.

Thanks!

**Comment by shapeshifter910** [comment]
Thanks for the explanation.
It looks like my install of Xowa is running good now.
Next I'll try the Android version on my tablet.

You can credit to anonymous.

**Comment by gnosygnu** [comment]
No problem! Thanks for the follow-up. Let me know if you need any pointers with Android.

**Comment by gnosygnu** [comment]
"commons.wikimedia.org" no longer shows in the sidebar unless the wiki is imported.

I'm closing this ticket for now. Let me know if there's anything else.

Thanks!
