### ISSUE TITLE
non existent file check

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#251]
In the file Cldr_name_loader.java are the lines (line 41)

		// get file
		Io_url url = (Io_url)urls_hash.Get_by_or_fail(lang_key);
		byte[] json = Io_mgr.Instance.LoadFilBry(url);
		if (json == null) {
			Gfo_usr_dlg_.Instance.Warn_many("", "", "no cldrName file exists for lang; lang=~{lang}", lang_key);
			return null;
		}

In the call to Io_mgr.Instance.LoadFilBry
If the file does not exists (because I was using an older version of the data), in my version I get a zero length byte object (not a null)
So the 'json == null' check does not seem to be the right check.
Is this just me?

**Comment by gnosygnu** [comment]
Just doing some clean-up to better track open issues. I'm marking this issue closed now b/c of the commit above. Let me know if there's anything else, and I'll reopen. Thanks
