### ISSUE TITLE
help out Convert_page function

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#252]
I would like to suggest a small change to xowa.gfs to help out the Convert_page function in Http_server_wrk.java

I do not know where you keep those assets.
So in the version of xowa.gfs I have (part of release v4.5.26.1810) on line 154

         <li  id="ca-nstab-main" class="~{portal_ns_subj_cls}"><span><a id="ca-nstab-main-href"  href="~{portal_ns_subj_href}" ...

swapping the id and href fields in the achor

         <li  id="ca-nstab-main" class="~{portal_ns_subj_cls}"><span><a href="~{portal_ns_subj_href}" id="ca-nstab-main-href" ...

will help the convert function (as it is looking for `<a href=` etc)

This is specifically an http_server issue; however in the tests I have run it has had no impact on anything else

**Comment by gnosygnu** [comment]
Ah, nice catch. I'll make a change for this sometime later this week. Thanks

**Comment by gnosygnu** [comment]
[FYI: Still on vacation, but spent some time yesterday setting up git on my laptop as well as basic dev environment. I'm going to close out whatever issues I can over the next few days. Feel free to comment / reopen anything improperly closed]

I fixed this in the commit above. Thanks again for the catch
