### ISSUE TITLE
extra http headers

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#255]
Having found that this project has a web server interface (ie http_server), I have been looking at how to make that interface work for me.
It is a great starting point.
To that end I decided to hook the http_server to a proxy server to support other things I am doing.

The proxy I use is nginx

When accessing the web server via the proxy a number of error messages started appearing for each request. These were related to the extra http headers nginx was adding.

Actually one of the http headers was contributed by Chrome

To 'suppress' these http header errors I have changed Http_request_parser.java

(see my nginx branch)

**Comment by desb42** [comment]
For my own purposes (purely academic) I prefer to use a web server approach - as I use a network of machines.
As a very small point I use Remote Desktop Connection for most of my work and although subtle, the Gui is just a bit blurry compared to Chrome. (not sure why)
I am also a bit twitchy about xulrunner - I not sure Modzilla is doing anything more with it. (hence Electron, etc)
As for Java - my skills in that area are modest. On the whole I am a C and Python person (occasionally C# if I have to).
However I am happy to turn my hand to anything (programming that is)
I can see that you have spent a great deal of effort on this project, and would again complement you on that effort (end of backslapping)

Not that it seems to matter, but I use Apache Netbeans IDE 9.0 with JDK 1.8 and all seems to be working fine for me.

**Comment by gnosygnu** [comment]
> For my own purposes (purely academic) I prefer to use a web server approach - as I use a network of machines.
> As a very small point I use Remote Desktop Connection for most of my work and although subtle, the Gui is just a bit blurry compared to Chrome. (not sure why)

Cool. Good to know.

> I am also a bit twitchy about xulrunner - I not sure Modzilla is doing anything more with it. (hence Electron, etc)

Yeah, I'm still a little miffed that Mozilla dropped all XULRunner support. I want to use Firefox as an embedded browser, but now Chrome is my only real recourse.

> As for Java - my skills in that area are modest. On the whole I am a C and Python person (occasionally C# if I have to).
> However I am happy to turn my hand to anything (programming that is)

Honestly, you've done pretty well going through my code. Although I did try to make things as simple as possible, my approach is sometimes unique, and many different areas are touched (Java; MediaWiki; javascript / AJAX; css; sqlite; etc). I'm pretty impressed that you were able to navigate all the complexity and make contributions in many disparate areas (ICU for instance).

Anyway, end of backslapping here. :)

> I can see that you have spent a great deal of effort on this project, and would again complement you on that effort (end of backslapping)

Yup, spent a lot of time on the project and will probably spend a lot more. Thanks for the kind words!

> Not that it seems to matter, but I use Apache Netbeans IDE 9.0 with JDK 1.8 and all seems to be working fine for me.

Yup, I'm using Eclipse Neon with JDK 1.8. I'll probably move to IntelliJ Community Edition in the future.

**Comment by gnosygnu** [comment]
Also, added http_headers as requested above. Thanks again!
