### ISSUE TITLE
Support Edit / View HTML, Popups, and Search for HTTP_Server [Some changes for http_server]

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#264]
In my branch action I am proposing some changes.
1) how the Edit and View Html tabs work
2) make popups work
3) not implemented - make search suggestions work for webserver

For these to work changes to xowa.gfs are required - I dont know how to suggest changes to that file.
Also, additional .js files are required (I have crudely called them myscript.js and mypopup.js) - again I dont know where to add them

What do you think?

**Comment by gnosygnu** [comment]
Cool! I think it looks good, though honestly, I just took a quick look: https://github.com/desb42/xowa/commits/action . Let me do a pull later and see how it pans out.

Regarding xowa.gfs and the other js files: I really should have added them to the repo. Right now, the only authoritative copies are in the releases zip: https://github.com/gnosygnu/xowa/releases

I'll add them to the repo when I get back from vacation. I'm thinking of something like https://github.com/gnosygnu/xowa/res/xowa.gfs and https://github.com/gnosygnu/xowa/res/bin/any/xowa/html/res/src/xowa/popups

For now, you can add them as attachments to this issue, and I'll merge later.

Finally, I'd like to give credit to contributors for their work. You'd get a line in the XOWA change log with something like "{contributed by desb42}". Let me know if you'd like to be listed as a different name, or would rather be anonymous.

Thanks!

**Comment by desb42** [comment]
OK

[bits.zip](https://github.com/gnosygnu/xowa/files/2528902/bits.zip)

This contains my version of xowa.gfs and two .js files

There is some problem with my modification to the popup logic - although this will popup a panel, there are some circumstances where the panel will not disappear. And others where the panel will not reappear. still working on that

crediting desb42 is fine with me

**Comment by gnosygnu** [comment]
> bits.zip

Nice. Downloaded it today and got it going on my side. Works great!

> There is some problem with my modification to the popup logic - although this will popup a panel, there are some circumstances where the panel will not disappear. And others where the panel will not reappear. still working on that

I was able to reproduce the panel not disappearing. I made a minor tweak to fix this in ```reallyHide```. (the javascript console log was showing undef errors there). You can try my version out in the attached.

[mypopups.zip](https://github.com/gnosygnu/xowa/files/2538455/mypopups.zip)

I wasn't able to reproduce the non-reappearance. Let me know if you have a series of steps for that, and I'll take a look at it here.

> crediting desb42 is fine with me

Cool. desb42 it is.

**Comment by gnosygnu** [comment]
Also, forgot to mention that the Edit and View HTML works as well. Thanks again!

**Comment by gnosygnu** [comment]
Sorry for the long delay, but I've been catching up on both jet lag and day-work.

I've been refactoring popups.js in the meantime. Unfortunately, what started as a simple clean-up has morphed to a full rewrite. I post the current version if you're interested below.

I'm about 80% done, but still have another few hours to finish up. Once I'm done with that, I'll move on to the other changes.

[xo.popup.js.zip](https://github.com/gnosygnu/xowa/files/2570387/xo.popup.js.zip)

**Comment by gnosygnu** [comment]
I finally pushed the changes for popups. There are a bunch of changes as I rewrote the main popups.js script to make it more readable. Hopefully this will pay off in the future whenever I need to add more functionality (Read more; show image?).

I'm probably going to be unavailable for most of the day, but will comment on the other 3 uncommented issues sometime in my late evening.

Thanks.

**Comment by desb42** [comment]
Having integrated the rearranged code I discovered that the Special: pages did not work (so I changed the code to effectively pass any querystring on unchanged)
Also I have some logic that can handle the drop down search using the form `en.wikidata.org/search/abc` where `abc` is the search term

My mods are in the action2 branch

**Comment by gnosygnu** [comment]
As always, apologies for the late follow-up. This is an old issue which I believe can be closed out as of tonight. The last piece (search suggestions) was added in #489 

Let me know if there's anything else.

Thanks!
