### ISSUE TITLE
Script error: No such module

### ISSUE THREAD

**Issue by XowaWilliam** [gnosygnu/xowa#271]
Upon opening a new page titled Bill Graham, I immediately noticed text in red that said "Script error: No such module"

If you type this in the address bar, the problem should be replicated:
en.wikipedia.org/wiki/Billy_Graham

![script-error](https://user-images.githubusercontent.com/12995082/47952047-ffc1f580-df71-11e8-9e17-a66a8234eeed.png)

**Comment by gnosygnu** [comment]
Hey, thanks for the detail.

Unfortunately, I couldn't reproduce it. I'm using the 2018-10 version of English Wikipedia and the XOWA binary from xowa_app_windows_64_v4.5.26.1810 .

Are you using 2018-11 English Wikipedia or a version earlier than v4.5.26.1810? If you're not, then we're going to have to dig deeper.

**Comment by XowaWilliam** [comment]
The problem occurred on the previous platform version xowa_app_windows_v4.5.21.1808, as well as the latest  platform xowa_app_windows_v4.5.26.1810

The wiki text I am using is from you last update Xowa_enwiki_2018-07

**Comment by XowaWilliam** [comment]
I did some more digging myself and discovered something that might explain this "Script error: No such module" message.

I kept a backup of my older Xowa from 2017, and this does not replicate the problem, so I compared the pages, and the only difference is this:

The 2017 text has the link mark KBE only once in the opening lines. ( Image below )
The 2018 July the link mark KBE is found twice, in the opening text, and the is a second link above the image of Billy Graham.

So I assume there might be a conflict because of a double link to the same page.

And just by the way, the page of link KBE in the 2018 July text does exist:
en.wikipedia.org/wiki/Order_of_the_British_Empire.

![script-error-002](https://user-images.githubusercontent.com/12995082/47961440-cb067a80-e013-11e8-8534-754433a8989c.jpg)

**Comment by XowaWilliam** [comment]
I made a comment and deleted because my description of my finding were not accurate.

Here is what I found, I leave you to sort out why, and how to address this problem.

This is the script in 2017 text which has no script error message.
[[Order of the British Empire|KBE]]

This is the script in 2018 text which has script error message.
{{post-nominals|country=GBR|KBEh}}

By the way, I have seen the same problem on other pages and ignored at first.
I will see if I can find links to other pages and post later.

Hope this helps.

**Comment by XowaWilliam** [comment]
This script error is found in the following links as well, so it is wide ranged.

en.wikipedia.org/wiki/Paul_McCartney
en.wikipedia.org/wiki/Ringo_Starr
en.wikipedia.org/wiki/George_Harrison
en.wikipedia.org/wiki/John_Lennon

**Comment by desb42** [comment]
Hello,
Like @gnosygnu, I cannot replicate this issue
It smacks of a version mismatch somewhere

Would it be possible for you to show the files you have imported from
home/wiki/Special:XowaDownloadCentral
(at the bottom of the page)

Mine looks like this
![imported](https://user-images.githubusercontent.com/861631/48063853-23797b80-e1be-11e8-8e7b-05ba0a131733.jpg)

**Comment by XowaWilliam** [comment]
I think I know where the problem might be.

To save data, I do not use **Download Central** to download my text files from Xowa.
I download the **enwiki-20180720-pages-articles.xml** file directly from Wikipedia, and I generate the text files with Xowa.

**Comment by XowaWilliam** [comment]
I think I know where the problem possibly lies.

I do not use **Download Central** to download my text files, I generate them using Xowa after I downloaded the **enwiki-20180720-pages-articles.xml** text file.

This enwiki-20180720-pages-articles.xml file was generated using previous platform xowa_app_windows_v4.5.21.1808

**Comment by XowaWilliam** [comment]
I downloaded the latest English Wiki [ Nov 2018 ] from Wikipedia, and this "Script error: No such module" has gone away.

How bits of "0" and "1" can plague my mind from time to time, and increase the grey hairs on my head, is a never ending story.

You can close this issue 271, the problem was obviously on my side.
