### ISSUE TITLE
Missing external link icon

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#274]
The icon ![external-link-ltr-icon](https://user-images.githubusercontent.com/861631/48065493-cb914380-e1c2-11e8-9ad0-c79d1e0349ac.png)
Does not seem to be appearing on external links

eg for Hermann Göring
en.wikipedia.org gives
![hg_wiki](https://user-images.githubusercontent.com/861631/48066042-5de61700-e1c4-11e8-8691-38fdc73bc4e3.jpg)
and Xowa gives
![hg_xowa](https://user-images.githubusercontent.com/861631/48066053-6a6a6f80-e1c4-11e8-89e2-8a44ad70914d.jpg)

On investigating this it appear that mediawiki wrap the page content in another div `<div class="mw-parser-output">`

When I modifiy xowa.gfs (page_read section)
change
`~{page_data}`
to
`<div class="mw-parser-output">~{page_data}</div>`

I get
![hg_xowa_fix](https://user-images.githubusercontent.com/861631/48068175-08ad0400-e1ca-11e8-83c8-80ca58f578fc.jpg)

Which (I believe) is the correct behaviour

**Comment by gnosygnu** [comment]
Nice catch. MediaWiki has changed CSS behavior at times, so this likely was broken recently.

I'll take a closer look at the change later, but otherwise, I'll probably end up merging later this week.

Thanks.

**Comment by gnosygnu** [comment]
Oops. Forgot about this. Thanks for the bump! Fixed with the commit above
