### ISSUE TITLE
luaj version

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#280]
I have just looked at your luaj-xowa project and noticed that the last commit was this year.
The luaj jar file that is bundled with the xowa releases is dated 5th dec 2017 - meaning that it does not have the latest commit.
Is this an issue?

**Comment by gnosygnu** [comment]
Yeah, back in October, I made an emergency but unofficial release to handle a breaking luaj bug: https://github.com/gnosygnu/xowa/releases/tag/v4.5.26.1810

The jar here is dated 2018-10-07 and incorporates the commit from here: https://github.com/gnosygnu/luaj_xowa/commit/e05a41a8f7717f4f1abbca8a6f29753ab7884e9c

I'm planning on an official XOWA release sometime before the year. Time permitting....
