### ISSUE TITLE
Can XOWA handle www.wikidata.org of 1.6 TB? (was "size of en.wikidata")

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#284]
Have you seen the size of en.wikidata?

I just looked at the 2018-11-01 dump and the pages-articles bz2 file is 54GB!
Having downloaded this (that took some time), I have extracted it and have got an XML file that is 1.6TB in size.
My rough calculation shows that to build a xowa version I will need at least another 1.6TB
I'm going to need a considerably bigger disk.

I also looked at the 2018-09-01 dump and the file is 52GB - wow, a growth of 2GB (compressed) in two months.

This is just an observation, I not sure what con be done about it (or should be)

**Comment by gnosygnu** [comment]
Yeah, I don't think much can be done about it.

The wikidata dump tends to be very verbose as it has the full JSON. I think the 1.6 TB compresses down considerably, though I really should confirm this.

I'm pulling down 2018-11 wikidata tonight and will see what the size is for the resulting www.wikidata.org. Will report back tomorrow.

Thanks.

**Comment by gnosygnu** [comment]
So, in short, XOWA does handle the 1.6 TB file.

In longer form:

I ran the import yesterday. The 54 GB .bz2 file with its compressed 1.6 TB resulted in 144 GB .xowa files.

XOWA has logic to auto-unzip the file after download. This can be suppressed in command-line by adding an unzip flag like the following

```
add     ('www.wikidata.org' , 'util.download')         {dump_type = 'pages-articles'; unzip = 'n';}
```

In addition, XOWA has automatic logic to read directly from a zip / bz2 file if the uncompressed form is not available. This will be slower, but it does complete.

Hope this helps.

Thanks.
