### ISSUE TITLE
View HTML does not work in HTTP server and other cases

### ISSUE THREAD

**Issue by gnosygnu** [gnosygnu/xowa#288]
The View HTML tab does not work in the following situations:
* When run from HTTP_Server
* When run from XOWA app and
  * Launching XOWA and restoring a tab with ?action=html
  * Switching from Edit to View HTML (the View HTML will show the contents of the Edit tab, not the Read tab)

Most of the issue is with old optimization code that tries to reuse the HTML in the SWT browser: https://github.com/gnosygnu/xowa/blob/master/400_xowa/src/gplx/xowa/htmls/Xoh_page_wtr_wkr.java#L62

This function will have to be rewritten to regen the HTML for the "Read" tab instead of using the optimization

**Comment by desb42** [comment]
I am not getting the behaviour you describe.
With both the http_server and gui versions when I click on the 'View HTML' tab, I get the html of the 'Read' tab's html

Or am I missing something?

**Comment by gnosygnu** [comment]
Marking this unreproducible for now. Tracking any future issues with Read / Edit / HTML in #392
