### ISSUE TITLE
build errors with latest codebase

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#289]
I have just re-synced my version of xowa and tried to build it from the git repository.
Unfortunately I am getting two (related) errors

    D:\xowa_20181126\400_xowa\src\gplx\xowa\htmls\Xoh_page_wtr_wkr.java:115: error: method Init_dflts in class Xoh_head_mgr cannot be applied to given types;
    		, page.Html_data().Head_mgr().Init(app, wiki, page).Init_dflts()
    		                                                   ^
      required: byte
      found: no arguments
      reason: actual and formal argument lists differ in length
    D:\xowa_20181126\400_xowa\src\gplx\xowa\htmls\Xoh_page_wtr_wkr.java:123: error: method Div_view_bry in class Xow_portal_mgr cannot be applied to given types;
    		, portal_mgr.Div_view_bry(wiki.Utl__bfr_mkr(), html_gen_tid, page.Html_data().Xtn_search_text())
    		            ^
      required: Bry_bfr_mkr,byte,byte[],Xoa_ttl
      found: Bry_bfr_mkr,byte,byte[]
      reason: actual and formal argument lists differ in length

Xoh_head_mgr.java and Xow_portal_mgr .java have been updated to handle extra args Xoh_page_wtr_wkr.java has not
Line 115 should read as:

    , page.Html_data().Head_mgr().Init(app, wiki, page).Init_dflts(html_gen_tid)
and Line 123:

    , portal_mgr.Div_view_bry(wiki.Utl__bfr_mkr(), html_gen_tid, page.Html_data().Xtn_search_text(), page_ttl)

**Comment by gnosygnu** [comment]
Sorry about that. I was still working on integrating the search commits.

I pushed them now. I'll work on integrating search next, but unfortunately, I'm dinged pretty hard at work this week. May not get a chance until the weekend, if even.

Thanks.

**Comment by desb42** [comment]
Sorry, that was me jumping the gun - I had got it into my head that you had made a further release. (That was in October)

**Comment by gnosygnu** [comment]
Yup, no worries.

Closing this issue now and will track further progress on HTML commits in other thread. Thanks.
