### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by MDE186** [gnosygnu/xowa#29]
Where can I email a crash report.

**Comment by gnosygnu** [comment]
Hey, you can email to gnosygnu at gmail dot com

However, I got a copy of the report when you first posted it. The failure is somewhere in SQLite, so it's a bit hard to debug. A few questions:

* Were in HTTP Server mode, or the regular GUI?
* What page was opening at the time?
* Is this the first time you've seen this? (I've not seen such a report below)

In the end, this may be rare SQLite behavior related to multiple simultaneous requests. I can try to put better guards to throttle the number of requests to SQLite

Thanks.

**Comment by MDE186** [comment]
Hey,

1. Yes I was in HTTP Server mode
2. Not sure on the page as it's based on a community network
3. I've never seen it before, thought I'd just let you know.

There is a mdump file but it's 750mb big. And Notepad++ won't open it
because it's too large.

**Comment by gnosygnu** [comment]
Cool. Thanks for the follow-up

If you want, you can try a new feature for limiting concurrent requests. By default, XOWA accepts as many concurrent requests as possible. I recently added a feature to limit this number. See https://github.com/gnosygnu/xowa/issues/23#issuecomment-141872508

If you see this error more often, you can try limiting the number, depending on how many "concurrent" connections you're supporting. This should reduce possibility of a failure at SQLite level. I believe 5 or so is generally considered the limit for SQLite databases.

Hope this helps.

**Comment by gnosygnu** [comment]
I'm going to close this ticket as unreproducible. If this is still occurring often, let me know, and I'll reinvestigate. Thanks.
