### ISSUE TITLE
Android Application: download from github?

### ISSUE THREAD

**Issue by AnselmD** [gnosygnu/xowa#3]
Where can I find the android application for download at github?

BTW: the links in the new xowa version 2.6.4.1 at home/wiki/Help:Android/Alpha are pointing to the old empty position

**Comment by AnselmD** [comment]
How should i deal with questions here at github? This looks more like bugs.

**Comment by gnosygnu** [comment]
> Where can I find the android application for download at github?

Yeah, I didn't have time to do so last week. I'll definitely add that sometime this week.

> BTW: the links in the new xowa version 2.6.4.1 at home/wiki/Help:Android/Alpha are pointing to the old empty position

Cool. I'll update them when I'm done. The Android thread will probably become a link to a page on the xowa github wiki here.

> How should i deal with questions here at github? This looks more like bugs.

Well, github has labels. There is a default label for "question". I'll classify them accordingly, but for now don't worry about it.

Thanks!

**Comment by gnosygnu** [comment]
Okay. I see the problem. I hid the support category, thereby rendering all links dead.

I unhid it now. I'll post the Android alpha and the supporting files here on Github sometime before the next release.

Thanks for the catch

**Comment by AnselmD** [comment]
>Okay. I see the problem. I hid the support category, thereby rendering all links dead.

>I unhid it now.

I am blind, I can not find the support category. Can you give me a hint, please.

**Comment by gnosygnu** [comment]
Sorry. Should have left the url: https://sourceforge.net/projects/xowa/files/support/

**Comment by gnosygnu** [comment]
I uploaded the android apk to github now. See https://github.com/gnosygnu/xowa/releases/tag/v0.1

Thanks!
