### ISSUE TITLE
Setting up XOWA wikis (7z)

### ISSUE THREAD

**Issue by yss11** [gnosygnu/xowa#30]
Hello

Xowa looks so nice and useful but I can’t get it to work.

I unzipped the application zip and got a file C:\xowa/xowa_64.exe

I got the dumps from arcive.org and unzipped them with winrar so they became .xowa. When i try to import offline I get a message that it has to be b2z or xml.

I tried the simple wiki first and he is in C:\gplx\xowa\wiki\simple.wikipedia.org.
I actually want to do it all (including images and other wikis) on an external HD. 
It is a windows 8.1
I’m no computer wizard so I need foolproof guidance please

Thanks a million.

**Comment by gnosygnu** [comment]
Hi! Thanks for the details.

Try the instructions below. If you think they're still too complicated, or your .7z dumps are different, let me know, and I'll adjust.

* Download the latest text English Wikipedia (no images) from within XOWA. This wiki will be as of 2015-10-06.
    * Run XOWA
    * Use the menu bar and do Tools -> Import Online. Or use the address bar and go to "home/wiki/Help:Import/List"
    * Click the "download" link next to en.wikipedia.org (it's the 8th row down)
    * Wait about 2 hours for the wiki to download
    * Wait another 2 hours for XOWA to build the wiki
    * When you're done you'll have all of English Wikipedia, but without the images

* Download the images from archive.org. This part is longer and may take many hours (it's about 80 GB). You may have some of these already.
    * First download these links to get all the images as of 2015-06-02.
        * https://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2015-06-02_file_v2b_core.7z
        * https://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2015-06-02_file_v2b_ns-000_part-1.7z
        * https://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2015-06-02_file_v2b_ns-000_part-2.7z
        * https://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2015-06-02_file_v2b_ns-000_part-3.7z
        * https://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2015-06-02_file_v2b_ns-000_part-4.7z
        * https://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2015-06-02_file_v2b_ns-000_part-5.7z
        * https://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2015-06-02_file_v2b_ns-000_part-6.7z
        * https://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2015-06-02_file_v2b_ns-000_part-7.7z
        * https://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2015-06-02_file_v2b_ns-000_part-8.7z
        * https://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2015-06-02_file_v2b_wiki_file_ns-100.7z
    * Then download these updates to get your wiki up to date with 2015-09-01
        * https://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2015-08-05_file_v2b.7z
        * https://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2015-09-01_file_v2b.7z

**Comment by gnosygnu** [comment]
Also, I posted this here just now: https://sourceforge.net/p/xowa/discussion/general/thread/efdc78ce/?limit=25, but I'll post it here as well

Hi! I just posted a simpler set of instructions: https://github.com/gnosygnu/xowa/issues/30 . Can you take a look at them and let me know if there's anything that needs further clarification?

Regarding your question:

* .bz2 files are files from Wikimedia's dump site. They are always the "latest", but need to be "built". Also, they don't have images. Basically, the process is the following:
    * Download a database dump bz2 file from http://dumps.wikimedia.org/backup-index.html
    * Import it at  "home/wiki/Help:Import/Script"
* .7z files are files I post to https://archive.org/search.php?query=xowa . These files are not always the "latest", but they have images and are already built. Basically, the process is the following:
    * Download a file from https://archive.org/details/Xowa_enwiki_latest . You may want to refer to https://github.com/gnosygnu/xowa/issues/30 for a list
    * Unzip the .7z file in the root directory of XOWA. Assuming your XOWA is at C:\xowa, files will be unzipped to C:\xowa\wiki\en.wikipedia.org\

Let me know if that helps

**Comment by banditmeerkat** [comment]
Hi
I have the same problem. I have downloaded 7z files which I unzipped to the root folder of Xowa. Now I have xowa files in C:\xowa_app_windows_64_v2.10.2.1\wiki\en.wikipedia.org (I didn't download simple wiki). How do I import these files into Xowa? I can find nothing in the help file or on the internet for importing 7z files and Xowa will only accept bz2 or xml files.

**Comment by banditmeerkat** [comment]
![capture5](https://cloud.githubusercontent.com/assets/16741827/12376807/f8635c9e-bd0e-11e5-94dd-0191d0d49ba8.PNG)
these are the files I have downloaded

**Comment by gnosygnu** [comment]
Hi! The 7z files are for compression to save bandwidth. You need to unzip them, using [7-zip](http://www.7-zip.org/).

After you're done unzipping them, move them into the en.wikipedia.org directory. You should have files like this:

* C:\xowa_app_windows_64_v2.10.2.1\wiki\en.wikipedia.org\en.wikipedia.org-core.xowa
* C:\xowa_app_windows_64_v2.10.2.1\wiki\en.wikipedia.org\en.wikipedia.org-file-ns.000-db.001.xowa
* C:\xowa_app_windows_64_v2.10.2.1\wiki\en.wikipedia.org\en.wikipedia.org-text-ns.000.xowa
* etc.

Let me know if there's still any confusion, and I'll try to help out.

Thanks!

**Comment by banditmeerkat** [comment]
![capture5](https://cloud.githubusercontent.com/assets/16741827/12376807/f8635c9e-bd0e-11e5-94dd-0191d0d49ba8.PNG)
these are the files I have downloaded

**Comment by banditmeerkat** [comment]
Yes, I realise that, how do I load these files into Xowa? Xowa only accepts xml and bz2 files. I noticed there is a file "enwiki-latest-pages-articles.xml" in the "en.wikipedia.org" directory so I loaded that  and something happened; I can see a random page and a few links from there and that is it. Most of the files that were copied into that directory have also gone missing now.
I have not finished downloading the second group of files so do not have "en.wikipedia.org-file-ns.000-db.001.xowa" in the folder in question.

**Comment by gnosygnu** [comment]
> Yes, I realise that, how do I load these files into Xowa? Xowa only accepts xml and bz2 files

The .xowa files don't need to be imported. They can be just placed in C:\xowa_app_windows_64_v2.10.2.1\wiki\en.wikipedia.org\ and XOWA will read them.

In other words, XOWA can set up English Wikipedia in two ways:
- Download a xml / bz2 file and build the .xowa databases. This is done through Main menu -> Tools -> Import online (or Import offline)
- Download pre-built .xowa databases. This is done through the archive.org links.

In your case, you've downloaded the pre-built .xowa databases, so you just need to place them in C:\xowa_app_windows_64_v2.10.2.1\wiki\en.wikipedia.org\. XOWA will do the rest automatically. If pages don't come up, go to Main menu -> Help -> System data -> Session log

> I noticed there is a file "enwiki-latest-pages-articles.xml" in the "en.wikipedia.org" directory so I loaded that and something happened; I can see a random page and a few links from there and that is it. 

I'm going to guess that you tried Import online, and then stopped the process. This will result in a smaller "enwiki-latest-pages-articles.xml" which is giving you just a few links.

> I have not finished downloading the second group of files so do not have "en.wikipedia.org-file-ns.000-db.001.xowa" in the folder in question

You can still use the text version now, and drop the file databases afterwards.

Hope this helps. Thanks.

**Comment by banditmeerkat** [comment]
Okay, looks like something went wrong so I extracted all the xowa files into the root directory, started Xowa again and now it is working. Why it didn't work properly first time around and deleted most of the xowa files I don't know. I have two more parts of the  image files to download and then I will extract them to the root directory again.
I have downloaded a LOT of data from Africa on a SIM so it would have been a disaster if this didn't work, thanks for all your help!

**Comment by gnosygnu** [comment]
> I have downloaded a LOT of data from Africa on a SIM so it would have been a disaster if this didn't work, thanks for all your help!

Cool! Thanks for the follow-up. Hope you don't run into any other issues. Let me know if something comes up!

**Comment by WaymondLu** [comment]
I do have all the 7z files: Xowa_enwiki_2015-06-02_file_v2b_ns-000_part-1.7z .. part8.7z downloaded
I do unzip all the 7z files and get all the en.wikipedia.org-file-ns.000-db.001.xowa ... 049-db.001.xowa

Then what; I got stuck now. I have all the *.xowa in the "..\wiki\en.wikipedia.org\" and nothing showing up on the main page. I try to Tools->Wiki Maintenance or restart the XOWA and still no luck.
Please tell me what to do after I have 67 Gb for 7z files. How do I get XOWA to use these 67 Gb *.7z? 
Thank you for your attension.

**Comment by gnosygnu** [comment]
Hi! Thanks for the detailed report.

"Xowa_enwiki_2015-06-02_file_v2b_ns-000_part-1.7z .. part8.7z" are just the image databases. You actually need the wikitext databases. They are in the 1st row of archive.org, but you can use these links also:

* https://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2015-12-06_wiki_core.7z
* https://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2015-12-06_wiki_text_ns-000_part-1.7z
* https://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2015-12-06_wiki_text_ns-000_part-2.7z
* https://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2015-12-06_wiki_text_ns-100.7z
* https://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2015-12-06_wiki_xtn_search.7z
* https://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2015-12-06_wiki_xtn_category.7z

After you download and unzip them, place all these xowa files in the \wiki\en.wikipedia.org directory.

You can also build these wikitext databases yourself by going to home/wiki/Help:Import/List and clicking "download" for the "http://en.wikipedia.org" row.

If it's still not loading, post the contents of "home/wiki/Special:XowaSystemData?type=log_session" . I'll let you know if anything else is amiss.

Thanks!

**Comment by WaymondLu** [comment]
Thank you for the quick response. I did try the links just now. I got "page not found" error:
https://ia802300.us.archive.org/20/items/Xowa_enwiki_latest/Xowa_enwiki_2015-09-01_wiki_core.7z

https://ia802300.us.archive.org/20/items/Xowa_enwiki_latest/Xowa_enwiki_2015-09-01_wiki_xtn_category.7z

I also downloaded this big file: "enwiki-latest-pages-articles.xml.bz2"

It seems to work with many missing link error; I put all 53 files which amount to 77.5 Gb image files in
\wiki\en.wikipedia.org directory and XOWA cannot load them still.

The log-session file is long and I try again from the beginning to see if I have better luck next time.
Thank for helping out.

Best Regards,
Ray

**Comment by gnosygnu** [comment]
Ah, I see what you mean now. I updated the links at https://archive.org/details/Xowa_enwiki_latest but forgot to update them at home/wiki/Help:Download and at https://gnosygnu.github.io/xowa/image_dbs.html .

I updated them right now. You can use the links in any of the following:

* https://gnosygnu.github.io/xowa/image_dbs.html
* https://archive.org/details/Xowa_enwiki_latest 
* https://github.com/gnosygnu/xowa/issues/30#issuecomment-174719348

> It seems to work with many missing link error; 

Yeah, it sounds like something is wrong. Try to do one of the following:

* Download the pre-made XOWA wikitext databases from archive.org. You can use any set of links from above. This is easier, as you just have to download the 7z files, unzip them, and place them in ..\wiki\en.wikipedia.org
* Make your wiki by using "enwiki-latest-pages-articles.xml.bz2". This will probably be quicker, as you've already downloaded the "enwiki-latest-pages-articles.xml.bz2" file.
    * Go to home/wiki/Help:Import/Script
    * Change Wiki from "Simple English" to "English"
    * Change "download" to "read from file"
    * In the next box to the left, choose the "enwiki-latest-pages-articles.xml.bz2"
    * Click "Import Now"

Let me know if there's still any problems

Thanks!

**Comment by gnosygnu** [comment]
I think all the issues above were caused by bad urls on my side. These have since been fixed. Let me know if any are missing and I'll reinvestigate. Thanks.
