### ISSUE TITLE
Page titles with leading slash

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#301]
This is a problem specifically with the http_server not the gui
In the 2018-11-01 enwiki there are 29 pages (across all namespaces) that start with a slash `/`
That is:
main

    //
    //Khara_Hais_Local_Municipality
    /2016ALBUM/
    /=
    /Drive
    /Film
    /\
    /b/
    /boot/
    /dev/full
    /dev/random
    /dev/zero
    /pol/
    /r/
    /r/IAmA
    /r/The_Donald
    /r/changemyview
    /r/science
    /rif
    /s/
    /usr/bin/god
    /æ/_raising
    /ð?'bæz?t?/

Template:

    /doc
    /meta/color
    /meta/shortname
    /sandbox
    /testcases
    /æ/_raising_in_North_American_English
When presented to the the http_server the url is in the form
`/en.wikipedia.org/wiki//dev/full` - note the double slash

Gfo_url_parser.Parse is called in Http_url_parser.Parse to parse `/en.wikipedia.org/wiki//dev/full`
Gfo_url_parser.Parse is also called indirectly from Http_server_mgr.Parse_page_to_html to parse `/dev/full`

Unfortunately the coding of Gfo_url_parser.Parse strips any leading slashes.
This is OK for the gui as the second call is not made

I have modified Http_server_mgr to recreate the original url for the second call to Parse - this seems to fix it
please see my branch leading-slash

**Comment by gnosygnu** [comment]
Thanks for the well-written defect report. Your [fix](https://github.com/desb42/xowa/commit/7eef134794b25817a1edc83867935c76b065f6ed) is very much on the mark. I'll push it sometime tomorrow or Friday. Thanks!

**Comment by gnosygnu** [comment]
Sorry for the late reply. Personal matters on my side (family member with emergency surgery).

Not sure how time will be over next few weeks. Pushed the above and tested with http://localhost:8080/en.wikipedia.org/wiki//dev/full 

Thanks again for the report
