### ISSUE TITLE
internal links misbehaving

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#303]
If I parse the following wikitext of internal links

    [[abcd-link|xclass]]
    [[abcd-link|class]]
    [[abcd-link|classx]]
    [[abcd-link|style]]
    [[abcd-link|alt]]
    [[abcd-link|title]]
I get (in html)

    <a href="/en.wikipedia.org/wiki/Abcd-link" id="xolnki_2" title="Abcd-link">xclass</a>
    <a href="/en.wikipedia.org/wiki/Abcd-link" id="xolnki_3" title="Abcd-link">abcd-link</a>
    <a href="/en.wikipedia.org/wiki/Abcd-link" id="xolnki_4" title="Abcd-link">classx</a>
    <a href="/en.wikipedia.org/wiki/Abcd-link" id="xolnki_5" title="Abcd-link">style</a>
    <a href="/en.wikipedia.org/wiki/Abcd-link" id="xolnki_6" title="Abcd-link">abcd-link</a>
    <a href="/en.wikipedia.org/wiki/Abcd-link" id="xolnki_7" title="Abcd-link">title</a>
However I expect
    
    <a href="/en.wikipedia.org/wiki/Abcd-link" id="xolnki_2" title="Abcd-link">xclass</a>
    <a href="/en.wikipedia.org/wiki/Abcd-link" id="xolnki_3" title="Abcd-link">class</a>
    <a href="/en.wikipedia.org/wiki/Abcd-link" id="xolnki_4" title="Abcd-link">classx</a>
    <a href="/en.wikipedia.org/wiki/Abcd-link" id="xolnki_5" title="Abcd-link">style</a>
    <a href="/en.wikipedia.org/wiki/Abcd-link" id="xolnki_6" title="Abcd-link">alt</a>
    <a href="/en.wikipedia.org/wiki/Abcd-link" id="xolnki_7" title="Abcd-link">title</a>
That is, 'class' and 'alt' are not appearing as themselves but as the name of the link

I suspect that it is related to the fact that if this where a File: link then there are many more options to parse.
I would say this is a parsing issue
[BTW I came across this problem in en.wikibooks.org/wiki/C_Sharp_Programming
So I do not know how widespread this issue could be]
I suggest (but have no idea how to code) that only if the link is in File namespace apply extra parsing

**Comment by gnosygnu** [comment]
Thanks. I think your recommendation is probably correct, but it's relatively easy to add some extra logic to treat empty "class" and "alt" options as captions.

I pushed the commit above. Hope that helps.

Thanks.

**Comment by desb42** [comment]
I have come across further examples of misbehaviour
Looking at en.wikipedia.org/wiki/Template:Scinote, there is a table where `sup` and `sub` appear as
`Template:Sup` and `Template:Sub` respectively

The actual template is `tlbare`
Such that
[[tlbare:sub]] should produce \<a href="Template:Sub">sub\</a>

It looks like other keywords need to be treated in the same way as class and alt

Not exhaustive, however this list produces the wrong effect

    {{tlbare|sup}}
    [[Template:sup|sup]]
    {{tlbare|sub}}
    {{tlbare|bottom}}
    {{tlbare|frame}}
    {{tlbare|middle}}
    {{tlbare|left}}

**Comment by gnosygnu** [comment]
Cool. I changed the logic to ignore these keywords if not the File / Media namespace. Also, I expanded the list of keyless keywords. See commit above.

Thanks!
