### ISSUE TITLE
Xobldr__link__link_score.java duplicate line?

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#305]
In the java file lines 178 and 179 seem to be the same

		else if	(ctx.Match(k, Invk__delete_plink_db_))			delete_plink_db = m.ReadYn("v");
		else if	(ctx.Match(k, Invk__delete_plink_db_))			delete_plink_db = m.ReadYn("v");

Is this intended?

**Comment by gnosygnu** [comment]
Oops. Thanks for the catch! Removed it just now.
