### ISSUE TITLE
xowa_common.css setup

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#307]
I have started to work with a new (to me) wiki, en.wikiversity.org
Having built this from the wiki data dumps, I looked at the internet.txt file for the build run.
This showed the following line:

    20181221_162743.505 download fail: src='https:// //upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Gtk-media-rewind-ltr.svg/24px-Gtk-media-rewind-ltr.svg.png ' trg='g:/xowa/user\anonymous\wiki\en.wikiversity.org\html\ \\upload.wikimedia.org\wikipedia\commons\thumb\8\8a\Gtk-media-rewind-ltr.svg\24px-Gtk-media-rewind-ltr.svg.png ' error='g:\xowa\user\anonymous\wiki\en.wikiversity.org\html\ \upload.wikimedia.org\wikipedia\commons\thumb\8\8a\Gtk-media-rewind-ltr.svg\24px-Gtk-media-rewind-ltr.svg.png  (The system cannot find the path specified)'

Looking in the corresponding xowa_common.css, I came across this line:

    background: url(" //upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Gtk-media-rewind-ltr.svg/24px-Gtk-media-rewind-ltr.svg.png ") left no-repeat;

I thought I would add some code to Xoa_css_img_downloader.java to trim the spaces from the url string
It took me a while to understand how xowa constructed xowa_common.css and xowa_wiki.css
(It is done in the build phase)
Please see my branch css
as a possible solution

**Comment by gnosygnu** [comment]
Nice. Thanks for the thorough documentation.

I pushed a commit with the same approach as yours, except I used XOWA utility methods for trimming whitespace from a byte array.

Other details below in case you're curious.

Thanks!

----

Yeah, regarding construction of xowa_common.css / xowa_wiki.css, the main class is Xoa_css_extractor . As a broad overview:
* It downloads the main_page of the wiki
* It scrapes the html for css urls
* It downloads the css for those css urls
* It recursively scrapes these css for other urls

In this case:
* The main css url link is
https://en.wikiversity.org/w/load.php?debug=false&lang=en&modules=site.styles&only=styles&skin=vector
* Which has a reference to this css: https://en.wikiversity.org/w/index.php?title=MediaWiki:Common.css/Slideshows.css&action=raw&ctype=text/css
* Which has the offending urls with whitespace
```
	background: url( //upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Gtk-media-rewind-ltr.svg/24px-Gtk-media-rewind-ltr.svg.png ) left no-repeat;
```
