### ISSUE TITLE
subpage link ref

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#308]
If you were to look at en.wikiversity.org/wiki/Computer-aided_design/Software
![subpage](https://user-images.githubusercontent.com/861631/50376076-e6e3d100-05ff-11e9-9324-443cc40e1e8d.jpg)

This is considered a sub page to 'Computer-aided_design' and a link to reflect this is just under the header title.
The link itself behaves correctly; however the visual representation has underscores where it should not.
My fix (rather crude) is to replace underscores with space
Please see my branch subpage
I suspect there is a better fix

**Comment by gnosygnu** [comment]
Cool. I actually think your fix is spot-on in terms of approach. I ended up changing the API call to one off of Xoa_ttl which I use specifically for converting spaces to underscores and vice-versa.

Thanks!

**Comment by desb42** [comment]
I suspected there would be a function to do the conversion.
That has correct the reported issue; however ...

taking the page en.wikiversity.org/wiki/Web_Science/Part2:_Emerging_Web_Properties/MoocIndex
which effectively drops down another level.
There is a subtle difference between wiki and xowa 
![subpage2](https://user-images.githubusercontent.com/861631/50420531-0ca2ed00-082f-11e9-82f6-6df3da97e64e.gif)
Which, on tracking down, is the fact that xowa is putting the different segments on different lines
Removing the line-feed (and spaces) `\n  ` from line 64 makes them the same

**Comment by gnosygnu** [comment]
Nice catch. I made the change as you suggested and visually inspected on my machine.

Also, ignore the ```a4ff8f7``` entry. I corrected it, and rebased it out of git history: https://github.com/gnosygnu/xowa/commits. However, I didn't realize it would still show here. Should have tested before pushing. ¯\\_(ツ)_/¯
