### ISSUE TITLE
Search placeholder

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#313]
When I was describing an issue in #308, I used an animated gif to show the difference in sublinks.
One other thing I noticed was that the search preference also differed.
![subpage2](https://user-images.githubusercontent.com/861631/50534894-53e4f280-0b3b-11e9-9715-02d2349e4a56.gif)

Xowa has 'Search' and wiki has 'Search Wikiversity' depending on the wiki

Please see my branch search-placeholder for a suggestion

**Comment by gnosygnu** [comment]
Cool, thanks for the commit. Looks perfect
