### ISSUE TITLE
parsing POST content

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#315]
I have been attempting to do some previewing of wikitext from the http_server side (rather than the gui) and noticed that I was loosing the line-feeds.
So the generated html was not right.

This requires a small change in Http_request_parser.java
Line 129

    tmp_bfr.Add(line)
should be changed to

    tmp_bfr.Add(line).Add_byte_nl();
to retain the linefeed (newline) character for onward processing

**Comment by gnosygnu** [comment]
Hmm.... Didn't realize new-line needed to be preserved. The changed test looks weird: https://github.com/gnosygnu/xowa/blob/master/400_xowa/src/gplx/core/net/Http_request_parser_tst.java#L44,L45

That said, I made the change as per your recommendation. Let me know if there's anything else.

Thanks!
