### ISSUE TITLE
Support Special:WhatLinksHere

### ISSUE THREAD

**Issue by and00r** [gnosygnu/xowa#32]
SF discussion board was so much better, github is very fruity, like a hipster platform.
but anyway, whats up? 

what happened to maintaining wiki downloads? >_>

**Comment by gnosygnu** [comment]
Well, hi again. :) Honestly, don't agree with you on github vs sourceforge, as I do like parts of github's design better. But to each their own.

Not sure what you're asking about maintaining wiki downloads. I've fallen a little behind schedule recently, but am trying to update all the wikis. See http://xowa.sourceforge.net/image_dbs.html . Is there a specific wiki you're interested in? Or is there something else?

**Comment by and00r** [comment]
yeah, enwiki of course... 

but you really like github?
you dont think its trying to be something like an elitist facebook? 
you dont think this is pathetic?  you are ok with this? 

think about it ;)

**Comment by gnosygnu** [comment]
Yeah, I'm skipping enwiki for November, b/c it only has < 3 thousand images. It didn't seem worth it to generate yet another download. There will be one for December of course.

I'm not particularly attached to github. If they ever adopt questionable policy, then I'll pack up my bags and look elsewhere. For now, they're sufficient, and that's all I care about.

**Comment by and00r** [comment]
ahaha, ok ok
ok

ok

how is everything else with you?

**Comment by gnosygnu** [comment]
Eh, as well as can be expected, I suppose. Let me know if anything else is up. Thanks.

**Comment by and00r** [comment]
good to hear things are doing good, you are my number one favorite developer. sorry for some reason i feel the need to ask about personal life here, it must be a social media thing, lol

an extremely important feature for doing independent research on wikipedia is using the "what links here" tool.
i cannot stress how immensely important this tool is, do you think you can incorporate this feature within xowa? 

i am also curious as to which database dump would contain such information.
thanks.

**Comment by gnosygnu** [comment]
K. Thanks for the concern. I'm generally pretty private, so I don't have much to add on social news. :)

The page-to-page link info is in the pagelinks dump. See the following url for this month's dump: http://dumps.wikimedia.org/enwiki/20151102/enwiki-20151102-pagelinks.sql.gz.

I've been playing with the pagelinks dump, for other purposes. A What Links Here tool is doable, but it requires downloading a big dump (4.6 GB) and probably about several hours of dev on my side. I'll add it to my queue, but I've been burning a lot of time on Android, so I can't make any promises....

**Comment by and00r** [comment]
yes please, incorporate whatever use for pagelinks you can. it's definitely worth it IMO, its a necessity which would really make your software stand out more so than it already does. i understand you goal was to create a comprehensive wiki reader, why cut it short?

**Comment by gnosygnu** [comment]
Well, pagelinks are high on my list as I'd like to use it for Android. It allows a better way of ranking "Search suggestions" than the current version. I'll look at What Links Here after I incorporate the dump, and post more here. It may be a few weeks though.

**Comment by and00r** [comment]
how are you on the andriod progress? i'm much more comfortable with android and linux now, if you may remember my first ever android device was purchased relatively recently in my life, but i'm also thinking of picking up an android tablet or chromebook this holiday. so i would be eager to try xowa there, rather than on my dinky little cell phone.

**Comment by gnosygnu** [comment]
I'm actually rewriting the Android version of XOWA. I'm trying to get another alpha out within a month's time. It's my top priority now, so I'm hoping a month is possible and that there won't be any distractions. Let me know if you wanted other info.

**Comment by and00r** [comment]
what happened with the old version?

**Comment by gnosygnu** [comment]
Still exists. Still works. However, there didn't seem to be much interest and the UI needed a lot more work. My new approach involves using the UI from the Wikipedia Mobile App. Unfortunately, this required the current rewrite

**Comment by and00r** [comment]
Oh, trust me, if you build it, they will come. I'm wondering how the Wikimedia foundation feels about this. Weather they can handle the needed bandwidth gained through popularity of your app. There are many technological enthusiasts that would at the very least love playing with this or keeping a copy of wiki backed up, which is a very useful thing to have weather anyone actually uses it or not. I can definitely see the potential for this to grow. The Wikimedia foundation actually has a lot of money, they are doing very well even though they still uphold donation drives, so there is no question about if they can actually afford this or not. I feel this is part of the reason why things have slowed down. But anyway, your reader is a lot more useful than kiwix, the article LWN,net was written by an idiot. 

But anyway, you sound hesitant and unenthusiastic with the xowa project now, as if its more of a chore or something. I don't understand why you feel this way,  i'm sure you had an understanding of the entire scope of what you were taking on, had the project overwhelmed you?

**Comment by gnosygnu** [comment]
> Oh, trust me, if you build it, they will come....

Thanks for the high hopes. I'd like to think there is much potential for XOWA, but at the same time, I feel it's premature to expect an overwhelming response. That said, it would be nice if it felt like I was reaching more users.

> the article LWN,net was written by an idiot.

FWIW, I thought the lwn.net article was mostly fair though I wish it would have mentioned more of XOWA's features (https://lwn.net/Articles/601055/)

> You sound hesitant and unenthusiastic with the xowa project now, as if its more of a chore or something. 

Honestly, my progress has been slower than I wanted, so I guess that's what you're hearing. Hopefully things will change once I get Android done, as well as some other features down the pipe. I'm not overwhelmed, so no need to worry. :)

**Comment by and00r** [comment]
anyway, the app UI sounds GREAT. cant wait for a proper release :)

and i hope wiki foundation will support more users downloading their DB
i really feel they have some part in holding the offline readers back (i noticed this with kiwix)
which is upsetting because they really do have a vast amount of funds, there should be no issues with sharing their DB. it's little things like this which makes me scrutinize their motives and how the foundation is being ran.

iv'e noticed other little things here and there too..
you might laugh at this, but there used to be a particular global infobox template which a certain heading or titlebox background color which got changed a while back, the color was extremely appropriate for certain subjects and it was changed to something which just didn't fit at all. there was some type of vote among admins to change the color, and the vote was not open to the public, as typical for global settings.

but this simple change of color can really highlight what is going on internally with wikipedia.
at least for me it does ;)

**Comment by gnosygnu** [comment]
> anyway, the app UI sounds GREAT. cant wait for a proper release :)

Yup. Targeting something for simple wiki in the next few weeks. english wikipedia soon afterwards

> and i hope wiki foundation will support more users downloading their DB

Well, they are working on "broadening" their dump architecture, so I believe everything should be in good faith. See https://phabricator.wikimedia.org/T114019

> but there used to be a particular global infobox template which a certain heading or titlebox background color which got changed a while back,

Hmm... Sounds somewhat interesting. Got a link? :)

**Comment by and00r** [comment]
yeah its taken a while for xowa to come this far,
something like xowa should have been completed years ago.

the priority of developing an app which would grant more people access to the DB hasn't really been high on anyones list. 
i feel like cost has been the larger concern and placed above 'knowledge' which is a cardinal sin, and goes against what the organization is supposed to stand for.
there are legitimate practical reasons why something like xowa wouldn't be a decent priority, but again this falls to the cardinal principals of sharing information and accessibility to this information, which have really been violated.

back in the day, the color of a titlebar used to be red for articles related to ancient rome. this color was used for other articles but it really held the most with rome, as if none of the other subjects were important. i found this simple little infobox bar of color to have such a profound effect. it was just perfect in its simplicity and aesthetics. then one day the color was globally changed to purple. such a small change but it seemed to wrong. 

here's an example article using the purple bar
the size of the bar may have also changed, and become thinner.

https://en.wikipedia.org/wiki/Mithridates_VI_of_Pontus

the old size and color of the red bar was just mathematically perfect. >_>

**Comment by and00r** [comment]
also, i dont think that infobox class is used anymore
thats probably one of the few remaining articles which uses that type of infobox

**Comment by gnosygnu** [comment]
> the priority of developing an app which would grant more people access to the DB hasn't really been high on anyones list...

I agree with you that offline access should have been a higher priority. For the most part though, I can understand why their efforts are focused elsewhere, especially considering efforts like Wikidata, Wikipedia Mobile, etc. Wikimedia still gets my benefit of the doubt with regards to these initiatives. As long as they continue generating database dumps (even the imperfect ones in XML form), I don't have much cause for complaint

> back in the day, the color of a titlebar used to be red for articles related to ancient rome...

Ah, that does seem a bit willful and unintuitive. For what its worth, I do agree that red would have been more appropriate. I don't know why they would have chosen purple, but Wikipedia editors have been known to do worse...

**Comment by gnosygnu** [comment]
I worked quite a bit with pagelinks in the last release. (If you're curious, I needed it to calculate PageRank for each Wikipedia page)

I think there's a problem with doing Special:WhatLinksHere and pagelinks. The PageLinks database is very large. To give you an idea, English Wikipedia has over 1 billion entries and the resulting database would be 40+ GB. I don't know if most users would want to take up yet another large chunk for this feature. I'm also not fond of the idea of uploading a 40 GB file up to archive.org (there are considerable logistic issues)

I'm going to mull this over some more, but I think this feature may wait longer -- at least until I get more demand from others.

Let me know if you think otherwise. Thanks.

**Comment by and00r** [comment]
well, pagelinks are important. again it's really up to you and your goal of how comprehensive you wish your app to be. i certainly wouldn't recommend uploading a pagelinks xowa file to archive.org, but perhaps a special pagelinks import feature specifically tailored for integrating pagelinks would be best? for users to import their own copy. i would imagine this taking a reasonably small amount of effort to program.

**Comment by gnosygnu** [comment]
Okay, thanks for the feedback. Let me think about it some more. XOWA can download and parse all the data now, so it's just a matter of formalizing the database schema and putting up a UI

I don't think it will be as full-featured as https://en.wikipedia.org/wiki/Special:WhatLinksHere/Main_Page. I'm imagining something like a simple list of pages with links for (links, edit). In other words, no Namespace filtering, no redirects, no transclusions, simple paging, etc.. Let me know if that is sufficient or if there's something else that would be necessary. Thanks.

**Comment by XowaWilliam** [comment]
I thought I would just second the statement by "**and00r**" that Github is ideed very intimidating with the new format that is so vastly different to **Sourceforge**. It might be better, but it takes courage and determination to familiarize ones self with new territory.

**Comment by and00r** [comment]
haha, im just messing around because im bored. don't get me wrong, i mean github is a little fruity, but it provides good service. its just silly how the internet is corralled like a heard of sheep whenever the top executive leaders of the net get together and decide where the next hip station for open source should be. god forbid anyone use sorceforge after they fiercely violated everyone with adware. i mean, lets just ignore all those years sourceforge has been hosting great content like a bunch of ingrates because github is really special ;)

**Comment by gnosygnu** [comment]
I'm marking this issue closed for now. As with all future enhancements, I will come back to this item later, but I just want to remove it from the list of open items. Thanks.
