### ISSUE TITLE
message key lastmodifiedat

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#321]
At the bottom of most pages is a date of last modification. An example on enwiki:
![lastmod](https://user-images.githubusercontent.com/861631/50733249-41de0200-1182-11e9-8b25-681e01f33398.jpg)

xowa is a bit different

In my branch lastmodifiedat is a suggested change to bring xowa closer to how wiki does it

I have needed to update en.json (therefore other language files ought to be changed as well)
Also enwiki has a MediaWiki:Lastmodifiedat key that overrides the one in en.json
And one other change to only display a date if it is valid

**Comment by gnosygnu** [comment]
Cool. Thanks again for the commits. I pushed it as per above.
