### ISSUE TITLE
minor logging issue when building xowa

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#322]
I have been building a number of wikis over the past few days and on reviewing the session log file I have come across entries of the form:

    20190107_160557.105 inserting cat_link row: 200,000

Every 100,000 rows.
This is most noticeable in the commons build as there are over 337,700,000 rows
I think the notification should be to the console, not the log
(but as I said - a very minor issue)

**Comment by gnosygnu** [comment]
Fair point. I don't remember why I thought this statement was worth logging. Changed it to write progress statements only. Thanks.
