### ISSUE TITLE
bad wikidata requests abort 

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#333]
Following on from #332 
If a request is made for a property (or any other entity) that does not exist xowa stack dumps

This is due to the fact that even though the item is not found, it still tries to process the json (that is not there)
A rather crude fix in Wdata_wiki_mgr.java is to replace Write_json_as_html with

    public void Write_json_as_html(Bry_bfr bfr, Xoa_ttl page_ttl, byte[] data_raw) {
        Hwtr_mgr_assert();
        if (data_raw[0] == Byte_ascii.Apos) // '''Page not found'''
            bfr.Add(data_raw);
        else {
            Wdata_doc wdoc = Doc_mgr.Get_by_exact_id_or_null(page_ttl.Full_db());
            hwtr_mgr.Init_by_wdoc(wdoc);
            bfr.Add(hwtr_mgr.Write(wdoc));
        }
    }

**Comment by gnosygnu** [comment]
Thanks again for detail. However, when I tried ```http://www.wikidata.org/wiki/Q14860476```, the failure was in [Popup_text](https://github.com/gnosygnu/xowa/blob/0ecb31575f198d82e304fd93f3847e02dd352790/400_xowa/src/gplx/xowa/xtns/wbases/Wdata_wiki_mgr.java#L123) not Write_json_as_html

I made the commit above which handles Popup_text (it won't keep showing "retrieving data", but will just show an XOWA popup with no data). I also put in an early-exit for Write_json_as_html. Let me know if I'm still missing something. Thanks.
