### ISSUE TITLE
template/module can only be used on pages in the Category: namespace

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#338]
While working on #337, my mouse hovered over Mauritian Creole nouns (I was moving the page using the pgup and pgdn keys) and got
![strange](https://user-images.githubusercontent.com/861631/51553604-299d0100-1e6b-11e9-85a9-81aa716fecb9.jpg)
Clicking through to the page seems OK
Only the preview seems to cause this
I wonder if the preview does not realise its in namespace Category

Another way to overcome this is to not trigger the popup for Category pages

**Comment by gnosygnu** [comment]
[Trying a new experiment by abusing labels for project management. Hopefully this gives a better idea of where my head is at.]

Thanks for the example. This is an issue with Scribunto and popups. Something like the following happens:
* When the page first loads, it sets the current_title to "dada" on a Scribunto manager object (Scrib_core)
* The page then parses the wikitext for "dada", and anytime Scribunto is called, it treats the page is "dada"
* Unfortunately, when hovering over the popup for "Category:Maritian_Creole_Names", Scrib_core still thinks the page is "dada"

I think this is a minor change, so will try to get it done in the next few days.
