### ISSUE TITLE
do not trigger popup for Category page links

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#339]
I think the type of pages that trigger hover should be further restricted.
There is a line in xo.popup.js that I think should be

    XoPopupMgr.ProtocolPattern = /^(((http|https|ftp|mailto):)|(javascript:|xowa-cmd:|.*\/wiki\/(File|Image|Category|Talk|User|Special):)|#cite_|\/fsys)/;
This might help #338,

**Comment by gnosygnu** [comment]
Yeah, Category is problematic. I think I can fix #338 "correctly", but even then, it will only parse the wikitext on the page. Most Category pages probably don't have wikitext.

I figure these are the two possibilities:
#### Allow popups on Category
* Will show blank on most Category pages, b/c most Category pages don't have wikitext
  * Cannot "preview" subcategory, page, file b/c
    * Popup hash limited space to show this data
    * Would have to change popup implementation (it only knows about wikitext; it doesn't know how to get category data)
* Will show some text for Category pages, but this text is probably not useful for a popup purpose

#### Do not allow popups on Category
* Filter it out as suggested above.

I'm leaning towards "Do not allow" but just wanted to explain my reasoning. If you don't have objections then I'll fix #338 and address this shortly afterwards. Thanks.

**Comment by gnosygnu** [comment]
So, decided to go for the "Do not allow" route. Thanks for handling the extra cases in ProtocolPattern . I really should handle File|Category|Talk for other languages, but for now, I'll have to remember to come back to that later.
