### ISSUE TITLE
Lua errors in www.wikidata.org/wiki/Help:Items

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#340]
On www.wikidata.org/wiki/Help:Items in xowa there are a number of lua errors
![help_items](https://user-images.githubusercontent.com/861631/51685970-5aa24080-1fe7-11e9-9c5a-8a4afaa994e4.jpg)

examining the wikitext of the page `Module:Wikidata label` a simple piece of wikitext can be crafted to trigger this issue

    {{#invoke:wikidata label | getLabel | item=Q7186 | lang=fr}}

Looking at the `Module:Wikidata label` at line 60

    lang = string.lower(lang) or 'en'
    local langList = mw.language.getFallbacksFor(lang)
    table.insert(langList, 1, lang)

I think the call to mw.language.getFallbacksFor is causing this issue
This function is in 400_xowa\src\gplx\xowa\xtns\scribunto\libs\Scrib_lib_language.java lines 154-158
Line 156 reads

    Xol_lang_itm lang = core.App().Lang_mgr().Get_by(lang_code); if (lang == null) return rslt.Init_many_empty();	// lang is not valid; return empty array per MW;

With lang=fr (French), this piece of code is returning rslt.Init_many_empty() (that is, the language is not found)
This empty value is passed back to Lua and then the Lua code tries to do a table.insert, and then the error message.
Returning an empty table should be fine.
I wonder if the table.insert logic is expecting something?

However on further investigation I have found that changing this same line (changing `.Get_by` to `.Get_by_or_new` (or possibly `.Get_by_or_load`) gives appropriate values to the Lua function

that is
![help_items2](https://user-images.githubusercontent.com/861631/51688573-ca66fa00-1fec-11e9-84ff-5cb4e9da790f.jpg)

**Comment by gnosygnu** [comment]
Looked at it further, and it turns out MediaWiki returns "en" if the language is unknown. See [Language.php](https://github.com/wikimedia/mediawiki/blob/master/languages/Language.php#L4565)

I updated the code accordingly and tested with http://www.wikidata.org/wiki/Help:Items

Thanks!
