### ISSUE TITLE
xowa_get_and_make.sh need further tweeks

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#345]
I have just re-synced my copy of xowa and found the latest version of  xowa_get_and_make.sh
when I run this again in my xowa_dev environment I get 

    mkdir: cannot create directory ‘src’: File exists
    mv: cannot move 'src/res/bin' to './bin': Directory not empty
    mv: cannot move 'src/res/dev' to './dev': Directory not empty
    mv: cannot move 'src/res/user' to './user': Directory not empty
    Error: JAVA_HOME is not defined correctly.
      We cannot execute java
    Error: JAVA_HOME is not defined correctly.
      We cannot execute java

I think that the script should have some deletions eg

    rm -r src
    rm -r bin
    rm -r dev
    rm -r user

And the JAVA_HOME environment variable only works if I tag'export' to the begging of it

**Comment by gnosygnu** [comment]
Fair point. I originally intended for this script to be run only once for initial setup, but there's no reason not to change it so it can be run multiple times.

I'll incorporate your changes above some time in the next few days, and may also do some minor reorganizing. Ideally, I'd also like to provide a git counterpart of the curl step as git will allow a developer to revert any unintended bad commits.
