### ISSUE TITLE
qid not found in wikidata

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#354]
I have been investigating one of the reasons why this error is occurring in the dewiki html build.
The not founds of the form

    qid=Veröffentlichungsdatum page=OS/2
    qid=Version page=OS/2
seem to be related to the lua function call mw.wikibase.resolvePropertyId
This can be found in Modul:Wikidata p.claim
Looking at the PHP code the formal parameter name seems to give a clue `$propertyLabelOrId`
That is, Label or Id.
Somehow `Veröffentlichungsdatum` and `Version`are being translated to P577 and P348 respectively
I suspect with the judicious use of wbase_pid table in www.wikidata.org-core.wbase.xowa this can be achieved

**Comment by desb42** [comment]
with yet further investigation I believe that the function ResolvePropertyId should behave in this manner
(pseudo code)

    get the xid from the first argument or return nill
    make sure first letter is capital
    if xid starts with a 'P'
      lookup in core 'page' table (page_title=xid and page_namespace=Property)
      if found return xid with capital p

    lookup xid and wiki language in wbase_pid (src_ttl=xid and src_lang= en/de etc)
    if found return trg_ttl with capital p 

    return nill
I don't know how to code the database access for this

**Comment by gnosygnu** [comment]
Yup, looks good. I'll put in a fix over the next few days before I kick off the official February builds. Thanks.

**Comment by desb42** [comment]
To hopefully help with this I have come up with this replacement code for ResolvePropertyId

    byte[] xid_bry = args.Pull_bry(0); if (Bry_.Len_eq_0(xid_bry)) return rslt.Init_ary_empty();
    if (xid_bry[0] == Byte_ascii.Ltr_P || xid_bry[0] == Byte_ascii.Ltr_p) {
        // should check for only digits (and that it is a valid property)
        // assume that if first char after the 'p' is a digit they all are
        if (xid_bry.length > 1 && xid_bry[1] >= Byte_ascii.Num_0 && xid_bry[1] <= Byte_ascii.Num_9) {
            xid_bry[0] = Byte_ascii.Ltr_P;
            return rslt.Init_obj(xid_bry);
        }
    }
    Xowe_wiki wiki = core.Wiki();
    Wdata_wiki_mgr wdata_mgr = wiki.Appe().Wiki_mgr().Wdata_mgr();
    int pid_int = wdata_mgr.Pid_mgr.Get_pid_or_neg1(wiki.Wdata_wiki_lang(), xid_bry);
    if (pid_int == Wbase_pid.Id_null) return rslt.Init_ary_empty();
    // convert to bytes
    Bry_bfr tmp_bfr = Bry_bfr_.New();
    tmp_bfr.Add_byte(Byte_ascii.Ltr_P);
    tmp_bfr.Add_long_variable(pid_int);
    return rslt.Init_obj(tmp_bfr.To_bry_and_clear_and_rls());

It does not address the issue of checking for a valid Property code but I think that is minor

**Comment by gnosygnu** [comment]
Thanks again for the guidance, and sorry for letting this slip under the radar for a while.

I pushed a fix with the commit above. 

Other testing notes below.

Thanks!

---

* Loading de.wikipedia.org/wiki/OS/2 and checking session.txt
* Running ```=mw.wikibase.resolvePropertyId('publisher')``` and other variants in the console at https://en.wikipedia.org/w/index.php?title=Module:Sandbox/Gnosygnu&action=edit
