### ISSUE TITLE
unknown key for property

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#361]
I have just been building the html for enwiki and although it did not complete successfully (see #360)
I suspect it has done 99% of the work.
Reviewing the err.txt file there are a number of lines with the above error (although it seems to affect only 3 pages - 2 of which have been change since the 2019-01-01 dump)

If you type the following into wikipedia Sandbox:

    {{#property:P17 | from={{#invoke:WikidataIB |getQid |qid=Q840814 }}}}
then you will get the result

    Belgium

Try the same in xowa, nothing is displayed and the above error is written to the logs
It seems that `#property:` has a special (rarely used) `from=`

**Comment by gnosygnu** [comment]
Have to run out. Will fix tonight. Here's the problem: https://github.com/gnosygnu/xowa/blob/master/400_xowa/src/gplx/xowa/xtns/wbases/pfuncs/Wdata_pf_property_data.java#L38

And here's the quick paste of the change. Note the ```key_bgn = Bry_find_.Find_fwd_while_space_or_tab```

```
			// get key; EX: "of=", "q=", "from="
			Arg_itm_tkn nde_key = nde.Key_tkn();
			int key_bgn = nde_key.Src_bgn(), key_end = nde_key.Src_end();
			if (key_bgn == key_end && key_bgn == -1) continue;	// null arg; ignore, else will throw warning below; EX: {{#property:p1|}}; DATE:2013-11-15
			key_bgn = Bry_find_.Find_fwd_while_space_or_tab(src, key_bgn, key_end);
			byte key_tid = atrs_hash.Get_as_byte_or(src, key_bgn, key_end, Byte_.Max_value_127);
```

**Comment by gnosygnu** [comment]
Pushed a fix with a test. Also removed some mistaken commits due to weird git command-line behavior on Windows.
