### ISSUE TITLE
invoke failed: Portal:Germany {{#invoke:Selected current events|main}}

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#367]
Second follow up from #365 

the subsequent error text is `@ustring.lua:47 bad argument #1 to 'len' (string expected, got nil)`

I have tracked this to Module:Selected_current_events
from line 57

    local title = mw.title.new("Portal:Current events/" .. date)
    local raw = title:getContent()
    local lines = mw.text.split( raw , '\n')

In 2019-01-01 enwiki dump the only `Portal:Current events/2019 ...` page is `Portal:Current events/2019_January_1`

I tried some debug on title of the form

    dbg('title', mw.dump_table(title))
But this just caused xowa to lock up (not sure why)

However a

    dbg('raw', raw)
on the following line gave the result `nil`

Experimenting I have found that `mw.text.split` is 'happy' if presented with a zero length string`''` but not happy about `nil`

I am not sure if `title:getContent` should return an empty string or if `mw.text.split` should cope with `nil`

**Comment by gnosygnu** [comment]
Thanks again for the write-up.

This issue is harder. I verified that both behaviors are the same across MediaWiki and XOWA
* title:getContent() returns nil if page is not found
* mw.text.split fails if passed a nil

See the excerpt at the bottom of the page.

The mw.dump_table(title) bug is unfortunate. This mw.dump_table is an XOWA function, and it probably can't cope with cyclic dependencies. I'll look at this later but this is most likely a problem in my implementation (it's only about 20 or so lines of simple lua code in mw.lua)

When you get a chance, can you put up the full stack trace? I don't think it will yield anything useful, but just want to check.

Otherwise, I'll have to try the reproduce the error on my side and figure out the actual cause.

---

```
-- test with {{#invoke:Test|test23}}
function p.test23(frame)
  local title = mw.title.new("abcdefgh")
  local raw = title:getContent()
  return raw.length --fails with attempt to index local 'raw' (a nil value).
end

-- test with {{#invoke:Test|test24}}
function p.test24(frame)
  local raw = nil
  return mw.text.split( raw , '\n') --fails with bad argument #1 to 'len' (string expected, got nil).
end
``

**Comment by desb42** [comment]
There is another possibility
Mediawiki _always_ maintains a Portal:Current_events/currentday

As of today 24 Feb 2019, the latest Portal:Current_events page is
en.wikipedia.org/wiki/Portal:Current_events/2019_February_25
![feb25](https://user-images.githubusercontent.com/861631/53297751-e7286480-381a-11e9-9136-7ac99dd33289.jpg)

Mediawiki have all sorts of daily bots running

I have just tried the lua excerpts in my own local version of mediawiki and can reproduce those errors
![preview](https://user-images.githubusercontent.com/861631/53298077-12fa1900-3820-11e9-9f8f-29a840baafb3.jpg)

So I'm going with a daily bot

for your info the stack trace is as follows

    20190223_070122.634 invoke failed: Portal:Germany {{#invoke:Selected current events|main}}
     [err 0] <gplx> @ustring.lua:47 bad argument #1 to 'len' (string expected, got nil)
      stack traceback:
      mw.text.lua:220: in function <mw.text.lua:219>
      mw.text.lua:212: in function '__index'
      Module:Selected current events:57: in function <Module:Selected current events:56>
      Module:Selected current events:115: in function '__index'
      Module:Selected current events:142: in function <Module:Selected current events:141>
      mw.lua:531: in function <mw.lua:530>
      [Java]: in function '__index'
      g:/xowa_dev/bin/any/xowa/xtns/Scribunto/engines/Luaj/MWServer.lua:75:
       in function <g:/xowa_dev/bin/any/xowa/xtns/Scribunto/engines/Luaj/MWServer.lua:74>
      
      [Java]: in ?: ttl=Germany excerpt={{#invoke:Selected current events|main}}
      [trace]:
        gplx.xowa.xtns.scribunto.Scrib_core.Handle_error(Unknown Source)
        gplx.xowa.xtns.scribunto.engines.luaj.Luaj_engine.Dispatch_as_kv_ary(Unknown Source)
        gplx.xowa.xtns.scribunto.engines.luaj.Luaj_engine.CallFunction(Unknown Source)
        gplx.xowa.xtns.scribunto.Scrib_core.Invoke(Unknown Source)
        gplx.xowa.xtns.scribunto.Scrib_invoke_func.Func_evaluate(Unknown Source)
        gplx.xowa.parsers.tmpls.Xot_invk_tkn_.Eval_func(Unknown Source)
        gplx.xowa.parsers.tmpls.Xot_invk_tkn.Tmpl_evaluate(Unknown Source)
        gplx.xowa.parsers.tmpls.Xot_defn_tmpl.Tmpl_evaluate(Unknown Source)
        gplx.xowa.parsers.tmpls.Xot_invk_tkn.Tmpl_evaluate(Unknown Source)
        gplx.xowa.parsers.tmpls.Xot_tmpl_wtr.Write_tkn(Unknown Source)
        gplx.xowa.parsers.tmpls.Xot_tmpl_wtr.Write_tkn(Unknown Source)
        gplx.xowa.parsers.tmpls.Xot_tmpl_wtr.Write_all(Unknown Source)
        gplx.xowa.parsers.Xop_parser.Expand_tmpl(Unknown Source)
        gplx.xowa.parsers.Xop_parser.Expand_tmpl(Unknown Source)
        gplx.xowa.parsers.Xop_parser.Parse_text_to_wdom(Unknown Source)
        gplx.xowa.parsers.Xow_parser_mgr.Parse(Unknown Source)
        gplx.xowa.wikis.pages.Xowe_page_mgr.Load_page(Unknown Source)
        gplx.xowa.guis.views.Load_page_wkr.Thread__exec(Unknown Source)
        gplx.core.threads.Gfo_thread_pool.Run_wkr(Unknown Source)
        gplx.core.threads.Gfo_thread_pool.Invk(Unknown Source)
        gplx.Gfo_invk_.Invk_by_msg(Unknown Source)
        gplx.core.threads.Thread_adp.run(Unknown Source)
        java.lang.Thread.run(Thread.java:748)

**Comment by gnosygnu** [comment]
> So I'm going with a daily bot

Cool. Yeah, I'd say that is the most likely culprit.  If it recurs, I'll look into it more.

> for your info the stack trace is as follows

Thanks. As expected, nothing leaps out at me.

I'm going to mark this item as non-reproducible and will close in a few days. Let me know if there's anything else.

**Comment by desb42** [comment]
I would not call it unreproducible, invoke Module:Selected_current_events and it will happen  a few days after the dump.
I think its a case of just living with the (hopefully very minor) issue

Maybe described in a FAQ (or more likely Infrequently Asked Question)

**Comment by gnosygnu** [comment]
Sounds good. I added it the FAQ in the home wiki. See http://xowa.org/home/wiki/Help/FAQs#Why_are_some_date-related_pages_empty_or_show_error_messages.3F
