### ISSUE TITLE
Support Mouse Buttons 4, 5; Support Pocketbook  (Xowa doesn't start with non-latin characters in the path name)

### ISSUE THREAD

**Issue by AdmiralAnimE** [gnosygnu/xowa#37]
>Sorry! XOWA failed to run!
----
OS: windows
Java: 1.8.0_66 (64 bit)
Java path: C:\Program Files\Java\jre1.8.0_66
XOWA: 3.1.1.1
XOWA path: G:\Инсталации\Програми\Информация\xowa_app_windows_64_v3.1.1.1\xowa_windows_64.jar

>Error: XPCOM error 0x80004005
Stack: org.eclipse.swt.browser.Mozilla.error(Unknown Source)
org.eclipse.swt.browser.Mozilla.initXULRunner(Unknown Source)
org.eclipse.swt.browser.Mozilla.create(Unknown Source)
org.eclipse.swt.browser.Browser.<init>(Unknown Source)
gplx.gfui.Swt_html.<init>(Unknown Source)
gplx.gfui.Swt_kit.New_html(Unknown Source)
gplx.xowa.guis.views.Xog_tab_itm.Make_html_box(Unknown Source)
gplx.xowa.guis.views.Xog_tab_mgr.Tabs_new(Unknown Source)
gplx.xowa.guis.views.Xog_tab_mgr.Tabs_new_init(Unknown Source)
gplx.xowa.guis.views.Xog_launcher_tabs.Launch_tab(Unknown Source)
gplx.xowa.guis.views.Xog_launcher_tabs.Restore_tabs(Unknown Source)
gplx.xowa.guis.views.Xog_launcher_tabs.Launch(Unknown Source)
gplx.xowa.guis.views.Xog_tab_itm_read_mgr.Launch(Unknown Source)
gplx.xowa.guis.Xoa_gui_mgr.Run(Unknown Source)
gplx.xowa.apps.boots.Xoa_boot_mgr.Run_app(Unknown Source)
gplx.xowa.apps.boots.Xoa_boot_mgr.Run(Unknown Source)
gplx.xowa.Xoa_app_.Run(Unknown Source)
gplx.xowa.Xowa_main.main(Unknown Source)

I am on Windows 7 64 bit

**Comment by gnosygnu** [comment]
Hi! Thanks for the detailed bug report!

Unfortunately, this is a know issue with SWT. See these links:

* https://bugs.eclipse.org/bugs/show_bug.cgi?id=443044
* http://sourceforge.net/p/xowa/discussion/defects/thread/a67a426e/?limit=25#d247

There's not much I can do until SWT fixes it. In the meantime, can you use a path with English characters only?

Let me know if you need other info. Thanks again.

**Comment by AdmiralAnimE** [comment]
Yes, for now I'll have to move it to another folder. It is a great program, only could use some ui polish. Can you answer me a few questions?:
1. Downloading "online" from inside the program downloads much smaller files than the archives from "download", what is the difference? For example, every listed wiki part in "download" for bulgarian is 4.4gb, but the downloaded data from "online" is 1gb.
2. Is the translation from here http://sourceforge.net/p/xowa/tickets/34/ updated? I started translating in bulgarian, but noticed that maybe there are missing things.
3. The buttons on my mouse for forward and back are not working, but it uses the same shortcut as Firefox?
4. Is it possible to open system pages like settings in a new tab when I open them, not in the active that I'm browsing the wiki?

**Comment by gnosygnu** [comment]
> It is a great program, only could use some ui polish. 

Thanks for the praise! I'm interested in what could be polished in terms of UI? Please tell!

> Can you answer me a few questions?:

Of course. :)

>  1. Downloading "online" from inside the program downloads much smaller files than the archives from "download", what is the difference? For example, every listed wiki part in "download" for bulgarian is 4.4gb, but the downloaded data from "online" is 1gb.

The 4.4 GB Bulgarian download (https://archive.org/details/Xowa_bgwiki_latest) includes all the **text** for the Bulgarian wikis: 
* https://bg.wikipedia.org
* https://bg.wiktionary.org
* https://bg.wikisource.org
* https://bg.wikiquote.org
* https://bg.wikibooks.org
* https://bg.wikinews.org

In addition, it also has all the **images** for these wikis.

The 1 GB download is only for the **text** of Bulgarian Wikipedia.

> 2. Is the translation from here http://sourceforge.net/p/xowa/tickets/34/ updated? I started translating in bulgarian, but noticed that maybe there are missing things.

Hey, if you could add a translation, that would be great!

The ticket is probably about 90% but it's missing a few items. Let me compile a new list, and I'll post it here by tomorrow.

> 3. The buttons on my mouse for forward and back are not working, but it uses the same shortcut as Firefox?

Unfortunately, XOWA runs on Java, and Java only supports 3 buttons. I'd have to include custom support for 5 buttons (which I assume is what your forward and back buttons map to).

I know there's Java Interop to handle this, but I've been reluctant to add platform-specific code. I can take a look at this again if you think this is important.

> 4. Is it possible to open system pages like settings in a new tab when I open them, not in the active that I'm browsing the wiki?

You can always middle-click links to open pages in a new tab. In addition, right-clicking links will give you a small sub-menu.

If you're trying to open something from the Main Menu (like Help -> System Data -> Session Log), then I usually just use keyboard shortcuts:
* Press Ctrl + T (to open a new tab)
* Press Alt + H to drop down the menu
* Press S for System Data
* Press S for Session Log

You can also do it by mouse
* Right-click in the HTML view 
* Choose "Tabs" -> "New Tab" 
* Choose "Help" -> "System Data" -> "Session Log"

Hope this helps.

**Comment by gnosygnu** [comment]
> The ticket is probably about 90% but it's missing a few items. Let me compile a new list, and I'll post it here by tomorrow.

I took a look at it today, and it should be complete. Keep in mind, the translation primarily affects UI items like the menu as well as HTML text like "Read", "Edit", etc.. If you don't see something being translated, please let me know, and I'll investigate. Thanks.

**Comment by AdmiralAnimE** [comment]
I found a file:
XOWA\bin\any\xowa\cfg\lang\util\i18n
Is this file the translation? It has a few more lines than the one in sourceforge. Can use it instead of the other one? Can I replace that file to test the translation?

About the wikipedia download, I understand that I have to download Commons. Is it possible to download only the needed files for my downloaded wikipedias? I downloaded Commons and it is 33.5 gb, a lot more than the 3-4 gb if I download it separately.

The mouse buttons really ease the navigation, at least for people like me who have them and use them. I know usually it's not a good thing to write things for a specific platform, but if you have the time, please do it :)

About the tabs: I was thinking more about the menus. As you said, I can't use middle click there. Can you add an option to open pages from the menu in a new tab?
Or better.. if there is a tab with wiki page, system pages will open in a new tab. If there is an open tab with system page, clicking on a system menu will open it in the same system tab. Basically, separate system and wiki tabs.
Maybe add a small plus, like in firefox, to the right of the tab, that opens an empty one?

**Comment by gnosygnu** [comment]
> Is this file the translation? It has a few more lines than the one in sourceforge. Can use it instead of the other one? Can I replace that file to test the translation?

Yup, forgot that I put the latest one there. You should use that one. To use it in XOWA, do the following:
* Copy column H (the one called gfs) to the file called J:\xowa\bin\any\xowa\cfg\lang\core\bg.gfs
* Go to home/wiki/Help:Options/Language
* Change the language dropdown to Bulgarian
If there are values that don't change, let me know which ones, and I'll look into it.

> About the wikipedia download, I understand that I have to download Commons. Is it possible to download only the needed files for my downloaded wikipedias?

Actually, you don't need commons unless you want to view the same infopage as commons.wikimedia.org. For example, XOWA can show a page similar to this: https://commons.wikimedia.org/wiki/File:Earth.png . Unless you want info on this page (like the Summary and Licensing section) you don't need commons. XOWA used to need commons to show a larger image, but I changed XOWA several months ago to work without commons.

If you do decide to use commons, there's no way to break it up. You need the whole thing.

> The mouse buttons really ease the navigation, at least for people like me who have them and use them. I know usually it's not a good thing to write things for a specific platform, but if you have the time, please do it :)

Ok. I'll take another look at the Java API to integrate mouse button support.

> About the tabs: I was thinking more about the menus. As you said, I can't use middle click there. Can you add an option to open pages from the menu in a new tab?
> Or better.. if there is a tab with wiki page, system pages will open in a new tab. If there is an open tab with system page, clicking on a system menu will open it in the same system tab. Basically, separate system and wiki tabs.

I put it on my todo list, but it make take some time to get to. I'm finishing up Android, and would like to do one other database-related piece, before I go to GUI

> Maybe add a small plus, like in firefox, to the right of the tab, that opens an empty one?

Ideally, this would be best, but I'm using a Tab control (SWT) that doesn't allow it.

Feel free to comment on anything else. Thanks!

**Comment by AdmiralAnimE** [comment]
Thank you :) I'm hoping I can translate it soon.
I want to ask another two things:
1. Is there any chance of Xowa to run on e-reader with Linux? Almost all of them use Linux in some sort, but specifically Pocketbook Inkpad. It's not quite the same as desktop Linux or Android e-reader.
2. What is the meaning of Xowa? The name, what does it mean, is it an abbreviation?

**Comment by gnosygnu** [comment]
> Thank you :) I'm hoping I can translate it soon.

No, thank you for offering to translate! :) Please let me know if you run into any issues.

> 1. Is there any chance of Xowa to run on e-reader with Linux? Almost all of them use Linux in some sort, but specifically Pocketbook Inkpad. It's not quite the same as desktop Linux or Android e-reader.

I tried to do some quick research on app development, but can't turn up anything.  http://wiki.mobileread.com/wiki/PocketBook_InkPad

The XOWA Android app is based on the Wikipedia Mobile app and the latter looks like it can run on Amazon Kindle / Fire devices. If that's true, then it should also be runnable on an eReader device like PocketBook, though it probably needs more testing.

I'm planning to test the XOWA Android app on Amazon Kindle / Fire a little after the Google Play Store release. If that goes well, you can try to use that for the PocketBook app and see how far you get.

> 2. What is the meaning of Xowa? The name, what does it mean, is it an abbreviation?

XOWA stands for the XOWA Offline Wiki Application. :)

**Comment by AdmiralAnimE** [comment]
Ok, thanks, I will try to test it when you release it. If you have the time, you can look at some applications for Pocketbook, because I too don't know if they have official documentation. There are three programs in active development:
https://github.com/koreader/koreader
https://github.com/blchinezu/pocketbook-coolreader
http://www3.telus.net/rkomar/pbimageviewer/
What I know is that the reader needs .app file to start the program, and that .app file can contain all files of the program (like in the case of pbimageviewer) or just launch the program, which has it's files in a different folder (which may be better for you).

Do you mind if I translate the name of the program or type the pronunciation in my language?

**Comment by gnosygnu** [comment]
> If you have the time, you can look at some applications for Pocketbook, because I too don't know if they have official documentation.

Thanks for the links. I'll take a look at them later this weekend and let you know.

> Do you mind if I translate the name of the program or type the pronunciation in my language?

I was hoping that XOWA would just be XOWA in Bulgarian. :) What translation / pronunciation did you have in mind?

**Comment by AdmiralAnimE** [comment]
I didn't want to leave it XOWA, because we use different alphabets. I can translate it by pronunciation that is easier to us - КСОВА (KSOVA), or I can translate the meaning - ХАПУ (something like X Autonomous Program/Application for Wikipedias).

**Comment by gnosygnu** [comment]
Hmm... How about other X-initialisms / acronyms like XML, XUL or XSLT ? Do these become K or translated?

Ideally, I'd like XOWA to be constant across all languages (like XML), but you're the expert here, so use whatever you think is best.

Thanks!

**Comment by AdmiralAnimE** [comment]
This is an argument between translators that may never end. Usually, it should be translated. In the case of XML, it is РМЕ(RME). But many don't do it, especially in IT. I view latin as equal to any other alphabet, so from my point of view it should be translated - by pronunciation for names, by meaning for acronyms. I can do something different here - ХОВА, so it retains a lot of the original. Thanks for understanding me!

**Comment by gnosygnu** [comment]
Cool. I'll trust your sentiments, and XOBA looks fine. Thanks!

**Comment by gnosygnu** [comment]
I changed the title to reflect the outstanding items on this issue. Let me know if I missed anything.

**Comment by gnosygnu** [comment]
I'm marking this item closed for now. It is a future enhancement, so I'll reopen later, but for now, I'd like to wade through my list of open items. Thanks.
