### ISSUE TITLE
unescaped ampersand

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#371]
As an experiment I turned on the warning/errors of jtidy
(commenting out two lines (48,49) in Xoh_tidy_wkr_jtidy.java)

I realise that this will show some 'false' positives; however I wanted to see if there were other issues

This has led to this issue of unescaped ampersands

The page en.wikipedia.org/wiki/Balangiga_bells has thrown up a large number of errors of the form

    line 248 column 1,128 - Warning: Warning: unescaped & or unknown entity "&rft_val_fmt"
    line 248 column 1,179 - Warning: Warning: unescaped & or unknown entity "&rft.genre"
    line 248 column 1,197 - Warning: Warning: unescaped & or unknown entity "&rft.atitle"
This has to do with citations and COinS

For a citation most of the work takes place in Module:Citation/CS1
This in turn calls a function COinS defined in Module:Citation/CS1/COinS which returns a string with the return statement of

    return table.concat(OCinSoutput, "&");
That is, an ampersand delimited string

Back in Module:Citation/CS1 at line 3352

    table.insert (render, substitute (cfg.presentation['ocins'], {OCinSoutput}));

Where `cfg.presentation['ocins']` is `<span title="$1" class="Z3988"></span>`

Somehow the string in OCinSoutput should get its ampersands escaped
(is it a part of how substitute works?)

**Comment by desb42** [comment]
Or is mediawikis tidy (remex) supplying the \&amp;

**Comment by desb42** [comment]
another example

    [//aaa.bbb.com/ddd?f1=a&f2=b example]
which in xowa (without tidy) gives

    <a href="https://aaa.bbb.com/ddd?f1=a&f2=b" rel="nofollow" class="external text">example</a>
and should be (and is with tidy)

    <a href="https://aaa.bbb.com/ddd?f1=a&amp;f2=b" rel="nofollow" class="external text">example</a>
The question I have is where should this work be done?
[How does mediawiki do it]

**Comment by gnosygnu** [comment]
Rough week on my side, so can only comment quickly

> Somehow the string in OCinSoutput should get its ampersands escaped
> (is it a part of how substitute works?)

```substitute``` is defined in https://en.wikipedia.org/wiki/Module:Citation/CS1/Utilities

It's possible that newRawMessage doesn't work correctly. But I doubt it should be doing ampersand substitution logic

> Or is mediawikis tidy (remex) supplying the &amp;
> The question I have is where should this work be done?
> [How does mediawiki do it]

At first blush, I think remex is the issue. Tidy (or JTidy in XOWA) does a lot of fixing up. I would guess that it doesn't fix the ```f1=a&f2=b``` -> ```f1=amp;&f2=b```. But remex now does?

**Comment by desb42** [comment]
On my local copy of mediawiki, I have turned off the tidying mechanism (basically I have told the system to use an external tidy that does not exist)
I have then tried both examples above and they end up with \&amp; being appropriately generated
That is, Tidy (Remex) is not doing any tidying

For the external link, my suggestion is to change 400_xowa\src\gplx\xowa\htmls\core\wkrs\lnkes\Xoh_lnke_html.java Lines 54 - 68
From

            if (lnke.Lnke_relative()) {        // relative; EX: //a.org
                bfr.Add(ctx.Wiki().Utl__url_parser().Url_parser().Relative_url_protocol_bry()).Add_mid(src, href_bgn, href_end);
                return true;
            }
            else {                            // xowa or regular; EX: http://a.org
                if (proto_is_xowa) {
                    bfr.Add(Xop_lnke_wkr.Bry_xowa_protocol);
                    gfs_encoder.Encode(bfr, src, href_bgn, href_end);
                    return false;
                }
                else {                        // regular; add href
                    bfr.Add_mid(src, href_bgn, href_end);
                    return true;
                }
            }
To

            if (lnke.Lnke_relative()) {        // relative; EX: //a.org
                bfr.Add(ctx.Wiki().Utl__url_parser().Url_parser().Relative_url_protocol_bry());
            }
            else if (proto_is_xowa) {
                bfr.Add(Xop_lnke_wkr.Bry_xowa_protocol);
                gfs_encoder.Encode(bfr, src, href_bgn, href_end);
                return false;
            }
            Xoh_html_wtr_escaper.Escape(ctx.App().Parser_amp_mgr(), bfr, src, href_bgn, href_end, true, false);    // NOTE: escape the link???
            return true;

**Comment by gnosygnu** [comment]
Cool. Thanks for the research and the recommendation.

It looks like MediaWiki encodes all attributes. I was able to confirm this also locally on my MediaWiki (v1.29) by changing the code below.

Fixed in the patch above.

Thanks.

```
// from /includes/Html.php (v1.29)

			if ( in_array( $key, self::$boolAttribs ) ) {
				$ret .= " $key=\"\"";
			} else {
				// Apparently we need to entity-encode \n, \r, \t, although the
				// spec doesn't mention that.  Since we're doing strtr() anyway,
				// we may as well not call htmlspecialchars().
				// @todo FIXME: Verify that we actually need to
				// escape \n\r\t here, and explain why, exactly.
				// We could call Sanitizer::encodeAttribute() for this, but we
				// don't because we're stubborn and like our marginal savings on
				// byte size from not having to encode unnecessary quotes.
				// The only difference between this transform and the one by
				// Sanitizer::encodeAttribute() is ' is not encoded.
				$map = [
					'&' => '&amp;',
					'"' => '&quot;',
					'>' => '&gt;',
					// '<' allegedly allowed per spec
					// but breaks some tools if not escaped.
					"<" => '&lt;',
					"\n" => '&#10;',
					"\r" => '&#13;',
					"\t" => '&#9;'
				];
				$ret .= " $key=$quote" . strtr( $value, $map ) . $quote;
			}
```
