### ISSUE TITLE
div with a blank id

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#373]
Looking at en.wikipedia.org/wiki/Balangiga_bells jtidy reported a div with an id that is blank
eg \<div id="" ...>
On investigation this occures within the generation of the wikitext `{{Bells}}`
This itself is a {{Navbox ...}} which in turn ends up in Module:Navbox

Within this module from line 135

        :tag('div')
            -- id for aria-labelledby attribute
            :attr('id', mw.uri.anchorEncode(args.title))
            :addClass(args.titleclass)
            :css('font-size', '114%')
            :css('margin', '0 4em')
            :wikitext(processItem(args.title))

The id is set by calling `mw.uri.anchorEncode` with args.title (in this case of) `[[Bell]]s`

The xowa version of this function returns '' whereas mediawiki returns 'Bells'

I do not know how often the anchorEncode function is used in this way, so this could be minor (most probably) or possible major

**Comment by gnosygnu** [comment]
I suspect this may be closer to major than minor since anchorEncode sounds like a utility function.

I'll look at it over the weekend and post more results later. Thanks.

**Comment by gnosygnu** [comment]
Thanks again for the clear example. Basically, XOWA wasn't handling trailing characters in anchor_encode: ```[[a]]b```

Fixed with the commit above.
