### ISSUE TITLE
Script error: =Module:WikidataIB:1080 attempt to index ? (a nil value)

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#374]
I have just looked at commons.wikimedia.org/wiki/Category:Michelangelo_Buonarroti
and this has thrown two invoke errors resulting in the above error being displayed

I have chased this down to the wikitext that will reproduce the error

    {{#invoke:WikidataIB | getValue | rank=best | P20 | name=birthplace | linkprefix=":" | qlinkprefix=":" | qid=Q5592 | spf={{{suppressfields|}}} | fwd=ALL | osd=no | noicon=yes | qual=ALL}}

WikidataIB p.getValue calls propertyvalueandquals which is called recursively

The error occurs  on the line 1080

    local datatype = objproperty[1].datatype or objproperty[1].mainsnak.datatype
Somehow objectproperty[1] does not exist

First time round the mw.table_dump of objectproperty is

    { [1] = { ["type"] = statement,["qualifiers"] = { ["P17"] = { [1] = { ["snaktype"] = value,["property"] = P17,["datavalue"] = { ["value"] = { ["id"] = Q170174,["numeric-id"] = 170174,["entity-type"] = item,} ,["type"] = wikibase-entityid,} ,["datatype"] = wikibase-item,} ,} ,} ,["id"] = P20,["mainsnak"] = { ["snaktype"] = value,["property"] = P20,["datavalue"] = { ["value"] = { ["id"] = Q220,["numeric-id"] = 220,["entity-type"] = item,} ,["type"] = wikibase-entityid,} ,["datatype"] = wikibase-item,} ,["rank"] = normal,} ,}  
The second time

    { ["P17"] = { [1] = { ["snaktype"] = value,["property"] = P17,["datavalue"] = { ["value"] = { ["id"] = Q170174,["numeric-id"] = 170174,["entity-type"] = item,} ,["type"] = wikibase-entityid,} ,["datatype"] = wikibase-item,} ,} ,}

objectproperty[1] of this give nil which leads to the error
Not sure why

**Comment by desb42** [comment]
I have been working on this issue recently and now that I understand how to use mediawiki module sandbox, I have discovered that the data returned for getEntityStatements differs between xowa and mediawiki

Mediawiki has  three more bits of information "id", "hash" and "qualifiers_order"
It is the last one that solves this problem
In myxowa commit 1fa47e5, I have added "qualifiers_order"
This seems to fix this issue

**Comment by gnosygnu** [comment]
> I have been working on this issue recently and now that I understand how to use mediawiki module sandbox,

Cool. That's pretty useful for me when debugging as well. :+1: 

> In myxowa commit 1fa47e5, I have added "qualifiers_order"

Okay. Adding that to the queue for tomorrow.: https://github.com/desb42/myxowa/commit/1fa47e51d6d54066c5a8bbab9c300423966b34b2

**Comment by gnosygnu** [comment]
Fixed with the commit above. Again, thanks for the super-helpful commit! It was spot on! :+1:
