### ISSUE TITLE
Warning: <span> Anchor "xowa_math_txt_0" already defined

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#375]
I randomly picked page en.wikiversity.org/wiki/Electric_Circuit_Analysis/Passive_Sign_Convention to review the warnings that tidy threw up and for this page I got quite a few of the above warnings

On investigation this is occurring because the counter (uid in Xomath_html_wtr.java) being used to supposedly generate unique ids is always zero (for the mathjax case - I have not tried it with the latex mechanism)

There ought to be another counting mechanism - perhaps when the math is parsed

This does not affect the final rendered page

**Comment by gnosygnu** [comment]
> being used to supposedly generate unique ids is always zero (for the mathjax case - I have not tried it with the latex mechanism)
> There ought to be another counting mechanism - perhaps when the math is parsed

Oops. This used to work for latex. Never realized it stopped working for mathjax.

Added a simple counter to the Xoa_page object. This will need to be refactored in future, but holding off on dramatic refactorings until a little after the next enwiki build.

Thanks!
