### ISSUE TITLE
extra image files in the 'res' directory of github

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#380]
I have just noticed (although it may have been there for some time) some image file directories that seem (to me) to be out of place
res/user/anonymous/wiki/home/html/bits.wikimedia.org 
If I try to access https://bits.wikimedia.org I get `bits.wikimedia.org’s server IP address could not be found.`

where do they fit in

**Comment by gnosygnu** [comment]
Yeah, good point. These were old files that weren't needed. More details below.

Thanks!

---

* The ```home/html``` folder is the same as the ```en.wikipedia.org/html``` folder (except for the logo.png)
* I generate this folder by just taking the latest ```en.wikipedia.org/html``` and copying it over to ```home/html```
* The last time I did this was a few years ago -- when bits.wikimedia.org was still active
* I just repeated the process just now and checked in all the files
