### ISSUE TITLE
Expression error: Missing operand for =.

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#397]
Having just done the html_dump phase of enwiki, I came across this page
en.wikipedia.org/wiki/Multiply-with-carry_pseudorandom_number_generator

Looking at this page in xowa generates a few of the above errors

I have tracked this down to the sample wikitext

    {{scinote|{{#expr:2^63*(2^64-10408)}}|4}}
the internal expression

    {{#expr:2^63*(2^64-10408)}}
evaluates to

    170141183460473813607767308000000000000
it seems to be the length of this that is an issue.
That is, if I trim the number down to 17 digits, it works

    {{scinote|17014118346047381|4}}
gives
1.701×10<sup>16</sup>

by implication an error associated with big numbers

**Comment by gnosygnu** [comment]
Resolved with the commit above. More detail below. Thanks!

---

It turned out the issue was with this snippet:

```
{{#expr:ln1.7014118346048E+38}}
```

XOWA was returning  ```53145839733938160520665405783802270889.2822265625``` whereas MediaWiki was returning ```88.029691931113```

In the above case, ```ln``` was being applied before ```E+38``` which is obviously incorrect
