### ISSUE TITLE
XOWA v4.6.0.1903 Build - German 2019-03 Wikipedia

### ISSUE THREAD

**Issue by Ope30** [gnosygnu/xowa#404]
Hey.

I just found out, that you uploaded German 2019-03 Wikipedia, I did not know until today. I thought you would notify me, but hey, whatever, doesn't matter. Thanks a bunch that you decided to upload the March build!

I've heard of the new XOWA build and immediately downloaded it. Downloading the wiki took less than an hour. Everything good to go. The patch notes look interesting. One of the biggest releases yet. (?)

Is this just me, or has there been an huge improvement in terms of speed? Articles like de.wikipedia.org/wiki/Rom took you sometimes 5-8 seconds to load up. Now it's less than a second. o_O

Unfortunately, I'm having issues. Just a few.

I have so many wikis dating back to 2016-2017. My EN-Wikipedia is from 2018-08, and the way I understand it, any wiki before 2019-03 does not work in the latest release.

Log:
https://pastebin.com/ihjyG7Ev

![Screenshot_37](https://user-images.githubusercontent.com/19750226/54929771-642c2400-4f16-11e9-8235-2a846d5b7d6b.png)

You remember the good ol' "Go back one page and I'll make all your images disappear" bug? Lol.

![Honeycam 2019-03-25 13-32-16](https://user-images.githubusercontent.com/19750226/54920094-9df32f80-4f02-11e9-8fa6-eeda6ea2f4e3.gif)

At first I thought Commons Wiki was causing it. That is not the case. Even just reloading the page causes this. :(

![Honeycam 2019-03-25 13-35-46](https://user-images.githubusercontent.com/19750226/54920209-f1fe1400-4f02-11e9-95b0-8e61fe76e02a.gif)

In the first .gif, can you see "Wappen von Parysow"? The reason it's not being displayed is because it's a .gif file? I mean the file is already there, so it has nothing to do with it being not included in the image dump, probably.

If you're curious, here's the log:
https://pastebin.com/JCQxYydd

I think the answer is this right here?
20190325_123911.705 file.get: file=Red_pog.svg width=8 page=Parysów
20190325_123911.809 file.unknown: err=[err 0] <gplx> counts do not match: hash=6889 list=6890

The Main Page of DE Wikipedia looks like this:

![Screenshot_34](https://user-images.githubusercontent.com/19750226/54920622-f24adf00-4f03-11e9-901e-4ed101fab021.png)

In "Kunst und Kultur":
![Screenshot_35](https://user-images.githubusercontent.com/19750226/54920760-55d50c80-4f04-11e9-9a2d-3f78638d6d4d.png)

As you can see, there are red links for no reason. They're not missing or anything (fortunately).

When you start XOWA and your last session was de.wikipedia.org/wiki/Wikipedia:Quiz/Geschichte, it'll become this:

![Screenshot_36](https://user-images.githubusercontent.com/19750226/54920946-d72c9f00-4f04-11e9-8662-2ebea56a2da7.png)

Log:

https://pastebin.com/NwDJULmk

Have a look at de.wikipedia.org/wiki/Wikipedia:Quiz/Geschichte above "Neuzeit", no clue why the image isn't displayed. It's definitely there.

![Honeycam 2019-03-25 13-52-53](https://user-images.githubusercontent.com/19750226/54921215-836e8580-4f05-11e9-9b46-63e6105e6599.gif)

Example here too:

de.wikipedia.org/wiki/Maria_Uhden

![Honeycam 2019-03-25 20-38-59](https://user-images.githubusercontent.com/19750226/54949195-d0228280-4f3e-11e9-8e8a-d886ad5cf7c6.gif)

The image "„Rastende Zigeuner“ (1918), Holzschnitt, 26 cm × 20 cm" is not displayed, although it's there.

I've came across this in another articles as well, such as de.wikipedia.org/wiki/Lorenzo Langstroth. Weird.

Last thing regarding the XOWA HTTP Server, I'm getting the following:
[err 0] 2 [trace]: gplx.xowa.apps.servers.http.Http_url_parser.Parse(Unknown Source) gplx.xowa.apps.servers.http.Http_server_wkr.Write_wiki(Unknown Source) gplx.xowa.apps.servers.http.Http_server_wkr.Process_get(Unknown Source) gplx.xowa.apps.servers.http.Http_server_wkr.Run(Unknown Source) gplx.xowa.apps.servers.http.Http_server_wkr.Invk(Unknown Source) gplx.Gfo_invk_.Invk_by_msg(Unknown Source) gplx.core.threads.Thread_adp.run(Unknown Source) java.base/java.lang.Thread.run(Unknown Source)

![Honeycam 2019-03-25 20-43-02](https://user-images.githubusercontent.com/19750226/54949222-d9abea80-4f3e-11e9-8a6a-d4b3f5b0ba8e.gif)

I'm on Windows 10, 64 bit. Always starting the HTTP Server with java -jar xowa_windows_64.jar --app_mode http_server --http_server_port 8080

I truly hope the logs are somehow useful for you!

**Comment by gnosygnu** [comment]
> I just found out, that you uploaded German 2019-03 Wikipedia, I did not know until today. I thought you would notify me, but hey, whatever, doesn't matter. 

Oops. Sorry about that. Forgot that there was another open ticket.

> The patch notes look interesting. One of the biggest releases yet. (?)

Yup, a big release due to the time gap (8 months) as well as the number of issues (60+)

> Is this just me, or has there been an huge improvement in terms of speed? Articles like de.wikipedia.org/wiki/Rom took you sometimes 5-8 seconds to load up. Now it's less than a second. o_O

Hmm. There really should be no difference in speed. The pre-generated HTML database (.html.) should load up in 1 second or less. The Wikitext version (.text.) can take 5 to 8 seconds.

> I have so many wikis dating back to 2016-2017. My EN-Wikipedia is from 2018-08, and the way I understand it, any wiki before 2019-03 does not work in the latest release.

Nope. It should be backward compatible. If you find a pre 2019-03 wiki that doesn't work with 4.6, let me know and I'll fix it.

The main issue is that a pre 4.6 version won't work with a 2019-03 wiki (specifically, the .html. databases)

> You remember the good ol' "Go back one page and I'll make all your images disappear" bug? Lol.

I'll take a look at that. It may be an issue with the new .html. databases

> In the first .gif, can you see "Wappen von Parysow"? The reason it's not being displayed is because it's a .gif file? I mean the file is already there, so it has nothing to do with it being not included in the image dump, probably.

Possibly an issue related to the .html. databases, though I'm a bit surprised. Will look into it later.

> I think the answer is this right here?
> 20190325_123911.705 file.get: file=Red_pog.svg width=8 page=Parysów
> 20190325_123911.809 file.unknown: err=[err 0] counts do not match: hash=6889 list=6890

Yeah, that's a problem. That's from de.wikipedia.org/wiki/Main_Page?

> As you can see, there are red links for no reason. They're not missing or anything (fortunately).

Definitely an issue with the 2019-03 wiki and the new .html. databases. The redlink behavior had to be re-coded.

> When you start XOWA and your last session was de.wikipedia.org/wiki/Wikipedia:Quiz/Geschichte, it'll become this:

Odd. Will look at this.

> The image "„Rastende Zigeuner“ (1918), Holzschnitt, 26 cm × 20 cm" is not displayed, although it's there.

> I've came across this in another articles as well, such as de.wikipedia.org/wiki/Lorenzo Langstroth. Weird.

K. Will look at those.

> Last thing regarding the XOWA HTTP Server, I'm getting the following:
[err 0] 2 [trace]: gplx.xowa.apps.servers.http.Http_url_parser.Parse(Unknown Source) gplx.xowa.apps.servers.http.Http_server_wkr.Write_wiki(Unknown Source) gplx.xowa.apps.servers.http.Http_server_wkr.Process_get(Unknown Source) gplx.xowa.apps.servers.http.Http_server_wkr.Run(Unknown Source) gplx.xowa.apps.servers.http.Http_server_wkr.Invk(Unknown Source) gplx.Gfo_invk_.Invk_by_msg(Unknown Source) gplx.core.threads.Thread_adp.run(Unknown Source) java.base/java.lang.Thread.run(Unknown Source)

Will need to look at the log for that also.

---

Will try to look at the above during the week, but may go to weekend. Will definitely post back here. Thanks.

**Comment by Ope30** [comment]
> The main issue is that a pre 4.6 version won't work with a 2019-03 wiki (specifically, the .html. databases)

Ah.


> Nope. It should be backward compatible. If you find a pre 2019-03 wiki that doesn't work with 4.6, let me know and I'll fix it.


The only Main Page that is working in 4.6 is  2017-06 French Wikipedia, for whatever reason. Reloading the page doesn't affect images, but articles are not working




![Honeycam 2019-03-26 10-05-00](https://user-images.githubusercontent.com/19750226/54984507-45c63700-4faf-11e9-969d-dc46f5bc8bb7.gif)


I'm always having this error at the very top, the same as in the log


![Screenshot_38](https://user-images.githubusercontent.com/19750226/54984569-67bfb980-4faf-11e9-953b-db0a0f4e1c74.png)



> Yeah, that's a problem. That's from de.wikipedia.org/wiki/Main_Page?

The log is from de.wikipedia.org/wiki/Parysów

Could also be this?
20190326_091209.338 file.get: file=POL_gmina_Parysów_COA.gif width=-1 page=Parysów
20190326_091209.338 file.unknown: err=[err 0] <gplx> val is not in switch/if: val=64



> Will need to look at the log for that also.


This is the CMD log:



`failed to process request;
request=type: GET       url: /fsys/bin/any/xowa/file/app.window/app_icon.png    protocol: HTTP/1.1  host: localhost:8080        user_agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:64.0) Gecko/20100101 Firefox/64.0  accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8     accept_encoding: gzip, deflate  dnt: false  x_requested_with: <<NULL>>  cookie: <<NULL>>        referer: <<NULL>>       content_length: 0       content_type: <<NULL>>  content_type_boundary: <<NULL>> connection: keep-alive  pragma: <<NULL>>        cache_control: <<NULL>>
err_msg=[err 0] <java.net.SocketException> Software caused connection abort: socket write error
[err 1] <net> Write_str failed
[trace]:
  java.base/java.net.SocketOutputStream.socketWrite0(Native Method)
  java.base/java.net.SocketOutputStream.socketWrite(Unknown Source)
  java.base/java.net.SocketOutputStream.write(Unknown Source)
  java.base/java.io.DataOutputStream.writeBytes(Unknown Source)
  gplx.core.net.Http_client_wtr__stream.Write_str(Unknown Source)
  gplx.xowa.apps.servers.http.Http_server_wkr.Serve_file(Unknown Source)
  gplx.xowa.apps.servers.http.Http_server_wkr.Process_get(Unknown Source)
  gplx.xowa.apps.servers.http.Http_server_wkr.Run(Unknown Source)
  gplx.xowa.apps.servers.http.Http_server_wkr.Invk(Unknown Source)
  gplx.Gfo_invk_.Invk_by_msg(Unknown Source)
  gplx.core.threads.Thread_adp.run(Unknown Source)
  java.base/java.lang.Thread.run(Unknown Source)`


> Will try to look at the above during the week, but may go to weekend. Will definitely post back here. Thanks.

Alrighty propighty. Take your time

**Comment by gnosygnu** [comment]
Oops. Thanks. I see the problem now. I'll try to push out a fix later tonight or tomorrow.

**Comment by gnosygnu** [comment]
I pushed a fix tonight to fix the old html databases. I'll fix the other items above this weekend (image constantly refreshing; redlinks)

Thanks again for the catch.

**Comment by Ope30** [comment]
"Portal:Wikipedia nach Themen" is broken. Possibly related to "Wikipedia:Quiz/Geschichte"?


![Screenshot_39](https://user-images.githubusercontent.com/19750226/55254986-a6789c80-5259-11e9-8111-23dd1dfee4ee.png)


I would've mentioned this earlier in my post if I knew about it. Just found out

**Comment by gnosygnu** [comment]
Sorry, this issue has been in todo, but I was a bit lazy in prioritizing

I created separate issues for each unresolved bug here. Let me know if I'm missing anything and I'll create a new issue for it.

Thanks.

**Comment by Ope30** [comment]
> 
> 
> Sorry, this issue has been in todo, but I was a bit lazy in prioritizing
> 
> I created separate issues for each unresolved bug here. Let me know if I'm missing anything and I'll create a new issue for it.
> 
> Thanks.


No problemo.

JFYI: I had to delete DE 2019-03 in order to download EN 2019-05 (unpacking also requires a lot of disk space). I could download it again, but I have the next build (September or October, depends) in my sights!

**Comment by gnosygnu** [comment]
Cool. Thanks for the info.

Closing out this issue for now. Let me know if anything else.
