### ISSUE TITLE
Wikisource not found

### ISSUE THREAD

**Issue by and00r** [gnosygnu/xowa#41]
Downloaded Xowa_enwikisource_2016-01-12_text.7z

Extracted to fresh install of current version of xowa

Path is correct "c:\xowa\wiki\en.wikisource.org\"
files are where they should be

Xowa says wiki is not found

**Comment by gnosygnu** [comment]
Hmmm... You should see files like this:

* C:\xowa\wiki\en.wikisource.org\en.wikisource.org-core.xowa
* C:\xowa\wiki\en.wikisource.org\en.wikisource.org-text-ns.000.xowa
* C:\xowa\wiki\en.wikisource.org\en.wikisource.org-xtn.search.core.xowa

Again, you can try looking at home/wiki/Special:XowaSystemData?type=log_session . 

You can also do home/wiki/Special:XowaDiag?type=fs.check&wiki=en.wikisource.org 

Hope this helps.

**Comment by and00r** [comment]
yes, as i said earlier, the files are where they should be. 
this is definitely a bug within xowa. try it yourself with v3.2.1.1 for windows 64bit

clean install from Xowa_enwikisource_2016-01-12_text.7z

**Comment by and00r** [comment]
it does the same for wiktionary, also on a clean install with just the text portion.

and i also tried wikibooks
...wikibooks loads properly

**Comment by gnosygnu** [comment]
Thanks! I see the issue. I forgot to upload a file.

I updated the links at https://archive.org/details/Xowa_enwiki_latest . There's now a link for "core" . You can also download it directly here: https://archive.org/download/Xowa_enwiki_latest/Xowa_enwikisource_2016-01-12_core.7z

**Comment by and00r** [comment]
yes i thought this after looking at the files 

thanks :)

**Comment by and00r** [comment]
i guess i should close the thread...
