### ISSUE TITLE
Script error: =Module:links:233 vm error: java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#419]
I have just rebuilt xowa using xowa_get_and_make.sh
The first page I looked at was en.wiktionary.org/wiki/Wiktionary:Main_Page (as I am looking at another issue in enwiktionary)

This page had on it the error as above in the `Wiktionaries in other languages` section
The wikitext triggering this - from the main page is:

    {{m|fr|dictionnaire}}
This in turn uses Template:mention - extracting the wikitext further

    {{#invoke:links/templates|l_term_t|face=term|demo=term}}
This calls Module:Links/Templates which in turn calls Module:Links and then the error

Looking at Module:links at line 233 is the lua statement

    if text:find("[[", nil, true) then
I placed a dbg statement just before this:

    dbg('links', text.find("[["))
And now it fails on this line
It looks to me like a regex issue - but my Lua skills  are minimal

**Comment by gnosygnu** [comment]
Ooops. The problem was the new luaj for #413 . It's fixable by going back to the previous version and commenting out most of the code in https://github.com/gnosygnu/xowa/blob/master/400_xowa/src/gplx/xowa/xtns/scribunto/libs/patterns/Scrib_pattern_matcher__luaj.java

I'll put a fix for this tonight. Thanks.

**Comment by gnosygnu** [comment]
I rolled back the broken LuaJ jar. I'll put in a fix sometime this weekend. Thanks.

**Comment by gnosygnu** [comment]
This was fixed by #413 a while ago, but I forgot to close it out. Closing now.
