### ISSUE TITLE
Personal Wiki Customization

### ISSUE THREAD

**Issue by len-ny** [gnosygnu/xowa#429]
I am using Xowa to create my personal wiki. My newbie questions: 

1. How to change the left panel (side bar) to add the navigation links?
2. How to upload file (png for instance) to my personal wiki & insert it as picture gallery or embedded file?

**Comment by gnosygnu** [comment]
Hey, thanks for the interest in XOWA. Nice to hear from someone using the personal wiki!

Regarding your questions:
> How to change the left panel (side bar) to add the navigation links?

I believe you should just be able to add a page called MediaWiki:Sidebar. See https://www.mediawiki.org/wiki/Manual:Interface/Sidebar

If that doesn't work, let me know, and I'll take a look at it. In the meantime, you can always manually set it using the instructions in #45 

> How to upload file (png for instance) to my personal wiki & insert it as picture gallery or embedded file?

You should be able to do this in a three-step process. See home/wiki/App/Personal_wikis/Default_Main_Page#Images 

```
Images are supported, but the process is slightly complicated due to the set-up of third-party software.

Here is a broad overview:
* Set up imagemagick and inkscape on your machine. For more instructions, see http://xowa.org/home/wiki/App/Wiki_types/Wikia.com#Part_3c:_Setup_Imagemagick_and_Inkscape
* Place your images in your wiki directory. Assuming your wiki is set up in <code>C:\your_wiki</code>, then you need to copy an image to <code>C:\your_wiki\file\orig</code>. As an example, do the following:
** Download the image from <code><nowiki>https://upload.wikimedia.org/wikipedia/commons/9/97/The_Earth_seen_from_Apollo_17.jpg</nowiki></code>
** Move the image to <code>C:\your_wiki\file\orig\The_Earth_seen_from_Apollo_17.jpg</nowiki></code>
** Edit the page, and add the following text: <code><nowiki>[[File:The_Earth_seen_from_Apollo_17.jpg]]</nowiki></code>
* Preview the page. You should see the image.

For more info, see https://en.wikipedia.org/wiki/Wikipedia:Picture_tutorial
```

Hope this helps. Thanks!

**Comment by len-ny** [comment]
The MediaWiki:Sidebar doesn't work. It already have the default settings as below but sidebar is not appear :
* navigation
** mainpage|mainpage-description
** recentchanges-url|recentchanges
** randompage-url|randompage
** helppage|help
* SEARCH
* TOOLBOX
* LANGUAGES

I tried to edit it but the changes are not saved when 'Save page' was clicked.

**Comment by gnosygnu** [comment]
Thanks for checking. I took a look now and it doesn't work. Code reference below

I'm not sure how to fix it without breaking wikia wikis. For now, can you try setting it manually as per #45?

Thanks

---

https://github.com/gnosygnu/xowa/blob/341d2e13a43bb91e40b0c0204a750a5f56780a26/400_xowa/src/gplx/xowa/addons/htmls/sidebars/Xoh_sidebar_mgr.java#L45

**Comment by len-ny** [comment]
Yes it can be done with  #45 instructions.
