### ISSUE TITLE
Xowa stops working after extracting images

### ISSUE THREAD

**Issue by GitterHubber** [gnosygnu/xowa#43]
Xowa Ver 3.2.1.1
OS Windows 7, 32bit

I downloaded the dump file from wikipedia servers 

> enwiki-20160204-pages-articles.xml.bz2

I successfully went through the import process through the Xowa interface and it was all working fine.
I could see pages and browse Wikipedia offline.

Later I decided it would be nice to have images. 
So I started to download the image files from 

> https://archive.org/details/Xowa_enwiki_latest

I download the first 3 files 

> Xowa_enwiki_2015-06-02_file_v2b_core.7z
> Xowa_enwiki_2015-06-02_file_v2b_ns-000_part-1.7z
> Xowa_enwiki_2015-06-02_file_v2b_ns-000_part-2.7z

I didn't want to wait for the other sets to download so extracted these 3  files in the root of XOWA dir. While extracting "Xowa_enwiki_2015-06-02_file_v2b_core.7z" it asked me if I would like to overwrite an existing file I said yes. The existing core file was smaller in size than this one.

After doing this I just get this message in XOWA while trying to search for any subject.
Anyway I could correct this?
![xowa_err](https://cloud.githubusercontent.com/assets/2816034/13451843/d41de05c-e068-11e5-8c76-47f1dc5a16c7.png)

**Comment by GitterHubber** [comment]
Sorry my bad! I was browsing the wrong url.
In XOWA i have to go to [en.wikipedia.org/wiki/](url) and then everything works.
Many Thanks and sorry for the goof up!

**Comment by gnosygnu** [comment]
No worries! Kudos to you for figuring it out. Let me know if there's anything else. Thanks!
