### ISSUE TITLE
Update/Release a Wikidata build

### ISSUE THREAD

**Issue by lugusto** [gnosygnu/xowa#430]
Many wikis are embebeding data directly from Wikidata. Tons of articles displays images on infoboxes directly from the corresponding Wikidata item. Please update/release a Wikidata build and consider adding it as an adittional step before releasing any wiki updates.

**Comment by gnosygnu** [comment]
Thanks for the feedback! I'm still trying to get back on track in terms of regular wiki updates. Right now, I'm working pretty hard on getting an English Wikipedia update. Whenever I realize that, I'll release the corresponding Wikidata with it.

In the meantime, you can always build your own wikidata using the link at home/wiki/Dashboard/Import/Online . The downside is that it needs about 300 GB of disk space to build (and several hours). But the upside is that you can update it whenever.

Hope that helps. Thanks!

**Comment by gnosygnu** [comment]
It's been a while, but I uploaded 2019-04 wikidata here: https://archive.org/details/Xowa_adhoc_requests
