### ISSUE TITLE
paragraph not being respected

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#437]
I think some inline comments are causing the paragraphs not to be respected
Taking the page en.wikisource.org/wiki/Three_Villages/2_Shirley
In the wikitext is the phrase `During our six weeks`
taking a few lines either side

    children of our own.&rdquo;
    
    
    During our six weeks' stay near them we saw
The wikitext indicates a paragraph break but the html generated is 

    <p>children of our own.”
    During our six weeks' stay near them we saw
    </p>

If, however the comment is removed

    children of our own.&rdquo;
    
    During our six weeks' stay near them we saw
The html generated is

    <p>children of our own.”
    </p><p>During our six weeks' stay near them we saw
    </p>
Something about comments?

**Comment by desb42** [comment]
I think I have found the culprit
By adding

    i = -1;  // found one, break out of for loop
at line 58 of Xop_comm_lxr.java

This prevents the comment handler gobbling up previous newlines

**Comment by gnosygnu** [comment]
Thanks for the tip. This fix looks ok as it doesn't break any existing tests. Let me look at it after this weekend.

Adding a new tag to give it better visibility for me:
https://github.com/gnosygnu/xowa/blob/master/400_xowa/src/gplx/xowa/parsers/miscs/Xop_comm_lxr.java#L58

**Comment by gnosygnu** [comment]
Added line as recommended. Thanks for the pointer!
