### ISSUE TITLE
Xowa wiki update process

### ISSUE THREAD

**Issue by GitterHubber** [gnosygnu/xowa#44]
First of all many thanks for the outstanding work on Xowa, it is simply par excellence.

I guess the process to regularly update offline wikipedia in XOWA is to download the text dump from [wikipedia servers](https://en.wikipedia.org/wiki/Wikipedia:Database_download) which is 15-20GB in size and then also download the image updates that you put up monthly on [archive.org](https://archive.org/details/Xowa_enwiki_latest)
So that would make it around 25GB download per month, incase its needed to update the offline wikipedia monthly.
Please correct me if I'm wrong.

1. Is there any way to get around the 15-20GB update of the text dump, I mean some sort of incremental update?

2. What is the process of generating the image update files, would it be as simple as downloading the text dump from wikipedia servers. I have checked wikipedia mirror sites but all those links were outdated? I have even searched around the XOWA documentation not sure if i missed something.

Thanks again.

**Comment by gnosygnu** [comment]
> First of all many thanks for the outstanding work on Xowa, it is simply par excellence.

Thanks for the kind words. Always glad to hear when someone appreciates XOWA. :)

> So that would make it around 25GB download per month, incase its needed to update the offline wikipedia monthly.
> Please correct me if I'm wrong.

Yup. You got it perfectly right

> Is there any way to get around the 15-20GB update of the text dump, I mean some sort of incremental update?

Not now, but this will change. I'm focusing on Android now, but will start implementing monthly incremental updates within the next month or two. Hopefully by April

> What is the process of generating the image update files, would it be as simple as downloading the text dump from wikipedia servers. 

The process is sort of complicated as it requires command-line scripts and a fast machine. It takes about 4 days of parsing all of English Wikipedia to generate a month's updates. You can check home/wiki/Help:Import/Command-line/Dumps in XOWA and let me know if you have any questions.

Hope this helps.

**Comment by GitterHubber** [comment]
> The process is sort of complicated as it requires command-line scripts and a fast machine. It takes about 4 days of parsing all of English Wikipedia to generate a month's updates. You can check home/wiki/Help:Import/Command-line/Dumps in XOWA and let me know if you have any questions.

Thanks for the info.
Will certainly have a look at it and try to figure it out.
Many Thanks!

**Comment by GitterHubber** [comment]
Hello again,

Getting a bit further into the update process.
I've downloaded the following files.
```
images.core
images.main articles.part-1
images.main articles.part-2
images.main articles.part-3
images.main articles.part-4
images.main articles.part-5
images.main articles.part-6
images.main articles.part-7
images.main articles.part-8
images.other articles
```
These seem to be in .xowa and v2b version also the wiki date of these files is 2015-12-06.

There several more links to the image update files some are even older than the above set.
Some are different format .sqlite, xowa and some .xowa (v1).

1. Do I have to download only the .xowa (V2B) versions?
2. Since the wiki date for the above set (core and articles) was 2015-12-06, do I only have to download updates later than this date?

Thanks in advance.

**Comment by gnosygnu** [comment]
> There several more links to the image update files some are even older than the above set.
> Some are different format .sqlite, xowa and some .xowa (v1

Yeah, you can ignore these. I only left them there because they take a long time to upload.

> Do I have to download only the .xowa (V2B) versions?

Yup. You only need v2b. v1 is only for backward compatibility with older users

> Since the wiki date for the above set (core and articles) was 2015-12-06, do I only have to download updates later than this date?

Thanks! Actually this was a mistake in my dates on archive.org. The images are actually from 2015-06. The 2015-12-06 date applies to the wiki only. I fixed this now

You'll need all the images from 2015-06 -> 2016-02. Keep in mind these should be unzipped in order. For example, there are files in 2015-08 that will overwrite those in 2015-06.

Let me know if there's anything else.

**Comment by GitterHubber** [comment]
Thank again for the clarification and corrections.
After the huge chunk set of images form images.core ... to images.other articles, these seem to be from 2nd June 2015

Now I'm list all the v2b versions --
I find the image updates for the following  dates on archive.org

1st Sep 2015
6th Oct 2015
6th Dec 2015
13th Jan 2016

so there doesn't seem to be any update for July and August.

Thanks again!!

**Comment by gnosygnu** [comment]
Yeah, July and November were skipped. Those updates were rolled into August and December.

August is actually for v2b. I updated the labels now to make them clearer. 

For a full list of images, see https://github.com/gnosygnu/xowa/issues/36#issuecomment-172428070 . 

Sorry for the confusion. Let me know if there is anything else.

**Comment by gnosygnu** [comment]
I think I answered all the questions above. Let me know if there's anything I missed, and I'll reply accordingly. Thanks!
