### ISSUE TITLE
Xtn.Translation: #translation not supported

### ISSUE THREAD

**Issue by gnosygnu** [gnosygnu/xowa#445]
While looking at #442, I noticed the following error when going to commons.wikimedia.org/wiki/Hyacinthus

```
Script error: @C:/xowa/bin/any/xowa/xtns/Scribunto/engines/Luaj/MWServer.lua:59 vm error: gplx.Err: callParserFunction: function was not found: function=#translation
```

It looks like commonswiki relies on a parser function called ```#translation```. I did a quick search, and could only find the following documentation: https://www.mediawiki.org/wiki/Help:Extension:Translate/Page_translation_administration

**Comment by desb42** [comment]
I took a look at what was calling this and find it in commons.wikimedia.org/wiki/Module:Cat_see_also

lines 25-30 are the relevant lines

    -- use page language instead of user language on pages translated using the Translate extension
    if frame:callParserFunction('#translation', '') ~= '' then
        args.lang = frame:preprocess('{{PAGELANGUAGE}}')
    else
        args.lang = frame:callParserFunction('int', 'lang')
    end
I think that for xowa purposes this function just needs to return the empty string

**Comment by gnosygnu** [comment]
Okay. Nice find. Let me take a look at that tomorrow / later this week

**Comment by gnosygnu** [comment]
Nice. Thanks for pointing that out. Resolved with the commit above.
