### ISSUE TITLE
Mwh_atr_parser.java does not handle utf8 properly

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#457]
In the course of investigating how to make proofread pages work better. I decided to implement Pp_pagelist_nde.java to handle <pagelist .. />
I decided that as the attributes of an element are parsed before invoking the xnde parse I would use that array of attributes.

This seemed to work until I came across this example wikitext (from en.wikisource.org/wiki/Index:Cather--One_of_ours.djvu):

    <div type="ffraa"></div>
    <pagelist
    1=Cover
    2to4=–
    5=Half-title
    6=Adv.
    7=Title
    8=Copyright
    9=Dedication
    10=–
    11=Contents
    12=–
    13="Book I"
    14=–
    15=1
    474to480=–
     />
I could not understand why the second attribute (` 2to4=–`) was indicated as invalid

It turns out the the character ` –` is emdash (3byte utf8 char)

It took me a while to determine that Mwh_atr_parser.java is effectively invalidating any utf8 sequence
Please see myxowa commit 57fc4c1 for a possible solution

**Comment by gnosygnu** [comment]
Thanks for the commit and nice catch. I think I assumed that anything that wasn't in quotes was ASCII. So, I assumed it would be ```2to4='–'``` and not just a bare ```2to4=–```. Oh well.

Let me take a look at it this weekend and try to get it done. Thanks again.

**Comment by gnosygnu** [comment]
[Link to desb42 commit for reference: https://github.com/desb42/myxowa/commit/57fc4c1fe39ba5c19a95ca9107bec4e55f10478d]

I made the change above. I deviated a bit from the suggested commit in that I wanted to not change as many lines of code (although the ```ALPHANUM``` is clearer).

Let me know if there's anything else. Thanks!
