### ISSUE TITLE
Error trying to open en.wikipedia.com

### ISSUE THREAD

**Issue by nsaustin** [gnosygnu/xowa#459]
So, I'm using the docker container and got it all up and working great. I went and did the download of the English full Wikipedia (en.wikipedia.com) - which all downloaded, verified and unzipped without a problem. (I see the wikipedia articles, images and wikitext all showing up at the bottom of the list under "imported", which tells me it was successful). However, when I click on the "en.wikipedia.com" link on the left-hand side, I'm given this error:

"[err 0] 2	[trace]:	gplx.xowa.apps.servers.http.Http_url_parser.Parse(Unknown Source)	gplx.xowa.apps.servers.http.Http_server_wkr.Write_wiki(Unknown Source)	gplx.xowa.apps.servers.http.Http_server_wkr.Process_get(Unknown Source)	gplx.xowa.apps.servers.http.Http_server_wkr.Run(Unknown Source) gplx.xowa.apps.servers.http.Http_server_wkr.Invk(Unknown Source)	gplx.Gfo_invk_.Invk_by_msg(Unknown Source)	gplx.core.threads.Thread_adp.run(Unknown Source)	java.lang.Thread.run(Thread.java:748)"

Any ideas? Thanks! FYI, My XOWA version is: v4.6.1.1903 (2019-03-27 03:39:22)

**Comment by desb42** [comment]
Elsewhere (#411 ) @gnosygnu  has expressed no knowledge of docker
I have some knowledge.
In order to try to help, would it be possible for you to show the `Dockerfile` and the `docker run` (or whatever mechanism used to build and fire up the container)
This might help in trying to reproduce
OS environment would be useful as well

**Comment by gnosygnu** [comment]
Thanks @desb42 for the assist. And yes, I don't know anything about Docker (sadly)

@nsaustin : Thanks for the report! This is a bug with the HTTP server. Clicking on the ```en.wikipedia.org``` link in the left hand side causes the error. For some reason, the trailing slash breaks it. Navigate instead directly to ```http://localhost:8080/en.wikipedia.org```

**Comment by gnosygnu** [comment]
I fixed it with the commit above. @nsaustin: Let me know if you'd like a new build, and I could push something out.

Also, I like to credit users for reporting issues finding bugs. The next Change log will have a line like ```HTTP Server: Fix links not working in left nav bar. {detected by anonymous}:``` Let me know if you'd like to be referenced by nickname or would rather remain anonymous.

Thanks!

**Comment by nsaustin** [comment]
Sorry for the delay. Whatever works. Referenced by name would work. Thanks! @gnosygnu
