### ISSUE TITLE
Wiktionary not loading

### ISSUE THREAD

**Issue by GitterHubber** [gnosygnu/xowa#46]
Hello again!
I downloaded the 2 links given on archive.org for Wiktionary 

https://archive.org/download/Xowa_enwiki_latest/Xowa_enwiktionary_2016-01-12_text.7z
https://archive.org/download/Xowa_enwiki_latest/Xowa_enwiktionary_2016-01-12_file.7z

and extracted them in the root folder of xowa.
It succesfully make a folder en.wiktionary.org and extracted all the relevant files into the folder.

There after I could see 2 links in the sidebar when I open XOWA, one for wikipedia and the other for wiktionary but though I can use wikipedia I cannot browse wiktionary.

When I click on the wiktionary link it says 

> could not find en.wiktionary.org

I even tried manually entering the url into the search bar of XOWA but to no avail it gives the same error.
Am I doing anything wrong here?
Is it possible that these files are not in the newer v2b format? (v2b is not mentioned in the archive.org links)

Thanks in advance!

**Comment by gnosygnu** [comment]
Sorry. I forgot to include one other link for "core". I added it now. Try: https://archive.org/download/Xowa_enwiki_latest/Xowa_enwiktionary_2016-01-12_core.7z

Thanks!

**Comment by GitterHubber** [comment]
Thank you very much!
That fixed it!!

> Navigate between offline wikis. Click on "Look up this word in Wiktionary" and instantly view the page in Wiktionary. 

I haven't been able to locate or enable this feature? Is there a setting to enable this?
Thanks in advance!

**Comment by gnosygnu** [comment]
Nope. No setting. It will be automatic. For example:

* Go to en.wikipedia.org/wiki/Encyclopedia
* Scroll down and look for "Look up encyclopedia..."
* Click on the word. This will automatically open up the related entry in your offline Wiktionary.

Hope this helps.

**Comment by gnosygnu** [comment]
As detailed above, the Wiktionary issue has been resolved. The "look up word" function should work as described.  If there are any other issues, feel free to reopen and I'll take a look. Thanks.
