### ISSUE TITLE
div with a strange id

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#460]
this is very similar to #373 
It is to do with the same call to `mw.uri.anchorEncode`

I have found another example (this time not blank but still not correct)
en.wikipedia.org/wiki/Template:Party_of_European_Socialists

The wikitext is (trimmed):

    {{Navbox
     | name = Party of European Socialists
     | title = [[Party of European Socialists|{{color|white|Party of European Socialists (PES)}}]]
    ...
In this case, `mw.uri.anchorEncode` is called with the expanded args.title 

    [[Party of European Socialists|<span style="color:white">Party of European Socialists (PES)</span>]]
xowa is currently producing

    .3Cspan_style.3D.22color:white.22.3EParty_of_European_Socialists_.28PES.29.3C.2Fspan.3E
it should be

    Party_of_European_Socialists_(PES)

**Comment by gnosygnu** [comment]
Thanks for the breakdown. This was due to some lax encoding for image captions (```[[File:A.png|caption with <span> html </span>]]```) 

I fixed it in the commit above. Also, I regularized html id encoding a little with #462.
