### ISSUE TITLE
<includeonly> may not be working

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#461]
Looking at en.wikipedia.org/wiki/Template:Party_of_European_Socialists
A snippet of the wikitext is:

    {{Navbox
    ...
     | state = {{{state<includeonly>|collapsed</includeonly>}}}
     | image = 
     | above = European Parliament group: [[Progressive Alliance of Socialists and Democrats]]
    ...
Note the `<includeonly>`
Looking at the html generated for this page (only the bit about state)

    <table class="nowraplinks collapsible {{{state}}} navbox-inner" style="border-spacing:0;background:transparent;color:inherit">
Note the `{{{state}}}`
This is occurring (I think) because either \<includeonly> is not behaving or the parser does not handle the variable alternative correctly

I would hope the latter

That is {{{state|collapsed}}} is probably correctly parsed whereas {{{state\<includeonly>|collapsed\</includeonly>}}} is not

**Comment by gnosygnu** [comment]
Hey, thanks for the detail. IncludeOnly, OnlyInclude and NoInclude always confuses me (I have to refer to the tests).

In this case though, I think the behavior matches Wikipedia.

XOWA produces what you had above

```
<table class="nowraplinks collapsible {{{state}}} navbox-inner" 
```

Wikipedia produces the same except the curly brackets are encoded (view-source:https://en.wikipedia.org/wiki/Template:Party_of_European_Socialists)

```
table class="nowraplinks collapsible &#123;&#123;&#123;state&#125;&#125;&#125; navbox-inner"
```

Let me know if I'm missing something. Thanks!

**Comment by desb42** [comment]
I did not think to check wikipedia (duh!)

Therefore essentially same behaviour - no issue

**Comment by gnosygnu** [comment]
Ah, okay! Thanks for the confirm!

**Comment by gnosygnu** [comment]
Closing out the issue. Feel free to reopen. Thanks!
