### ISSUE TITLE
Template:Template:Edit_templates does not exists

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#473]
the page en.wikipedia.org/wiki/Template:Edit_templates
shows a link to Template:Template:Edit_templates - and should be to itself

The wikitext ends up calling Module:Navbar and I think line 60 is the culprit

    local title = mw.title.new(mw.text.trim(titleText), 'Template')
In this case `titleText` is `Template:Edit templates` and after the assignment `title.fullText` is `Template:Template:Edit_templates`
An extra 'Template:'

**Comment by gnosygnu** [comment]
Thanks for the write-up. Let me fix this one sometime tonight / tomorrow.

**Comment by gnosygnu** [comment]
Sorry for delay, but time (and energy) has been hard to come by.

Fixed with commit above. Let me know if anything else. Thanks!
