### ISSUE TITLE
self link change

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#478]
during my rummaging I have noticed that in a page where there is a link to itself (ie a self link) that 'link' is the caption wrapped with \<b> ... \</b> (bold)
eg en.wikipedia.org/wiki/Template:To_do

However, it seems mediawiki now uses a different wrapper
\<a class="mw-selflink selflink"> ... \</a>

A small change to Xoh_lnki_wtr.java

**Comment by gnosygnu** [comment]
Nice find. I'll push that through in the next few days or so.

**Comment by gnosygnu** [comment]
More than a few days, but handled by the commit above. Thanks again for the heads up.
