### ISSUE TITLE
renderSnak causes an exception on empty snaks

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#481]
I was reviewing the dewiki rebuild logs and thought I would look at the following relatively common #invoke exception

    invoke failed: Es_war_einmal_in_Amerika {{#invoke:Wikidata|claim|P179|qualifier=P156|parameter=numeric-id}} 
    [err 0] <gplx> @d:/des/xowa_x/bin/any/xowa/xtns/Scribunto/engines/Luaj/MWServer.lua:59 vm error: java.lang.NullPointerException
      stack traceback:
      
      d:/des/xowa_x/bin/any/xowa/xtns/Scribunto/engines/Luaj/MWServer.lua:53: in function '__index'
      
      Module:Wikidata:622: in function <Module:Wikidata:621>
      
      mw.lua:531: in function <mw.lua:530>
      
      [Java]: in function '__index'
      
      d:/des/xowa_x/bin/any/xowa/xtns/Scribunto/engines/Luaj/MWServer.lua:75: in function '__index'
      
      d:/des/xowa_x/bin/any/xowa/xtns/Scribunto/engines/Luaj/MWServer.lua:53: in function '__index'
      
      mw.lua:199: in function '__index'
      
      Module:Wikidata:775: in function <Module:Wikidata:774>
      
      mw.lua:531: in function <mw.lua:530>
      
      [Java]: in function '__index'
      
      d:/des/xowa_x/bin/any/xowa/xtns/Scribunto/engines/Luaj/MWServer.lua:75: in function <d:/des/xowa_x/bin/any/xowa/xtns/Scribunto/engines/Luaj/MWServer.lua:74>
      
      [Java]: in ?: ttl=Es_war_einmal_in_Amerika excerpt={{#invoke:Wikidata|claim|P179|qualifier=P156|parameter=numeric-id}}
      [trace]:
        gplx.xowa.xtns.scribunto.Scrib_core.Handle_error(Scrib_core.java:226)
        gplx.xowa.xtns.scribunto.engines.luaj.Luaj_engine.Dispatch_as_kv_ary(Luaj_engine.java:84)
        gplx.xowa.xtns.scribunto.engines.luaj.Luaj_engine.CallFunction(Luaj_engine.java:59)
        gplx.xowa.xtns.scribunto.Scrib_core.Invoke(Scrib_core.java:192)
        gplx.xowa.xtns.scribunto.Scrib_invoke_func.Func_evaluate(Scrib_invoke_func.java:80)
        gplx.xowa.parsers.tmpls.Xot_invk_tkn_.Eval_func(Xot_invk_tkn_.java:30)
        gplx.xowa.parsers.tmpls.Xot_invk_tkn.Tmpl_evaluate(Xot_invk_tkn.java:258)
        gplx.xowa.parsers.tmpls.Arg_itm_tkn_base.Tmpl_evaluate(Arg_itm_tkn_base.java:45)
        gplx.xowa.xtns.scribunto.libs.Scrib_lib_mw.GetExpandedArgument(Scrib_lib_mw.java:119)
        gplx.xowa.xtns.scribunto.libs.Scrib_lib_mw.Procs_exec(Scrib_lib_mw.java:53)
        gplx.xowa.xtns.scribunto.procs.Scrib_proc.Proc_exec(Scrib_proc.java:29)
        gplx.xowa.xtns.scribunto.engines.luaj.Luaj_engine.Server_recv_call(Luaj_engine.java:97)
        gplx.xowa.xtns.scribunto.engines.luaj.Luaj_server_func_recv.call(Luaj_server_func_recv.java:27)
        org.luaj.vm2.lib.OneArgFunction.invoke(Unknown Source)
        org.luaj.vm2.LuaValue.onInvoke(Unknown Source)
        org.luaj.vm2.TailcallVarargs.eval(Unknown Source)
        org.luaj.vm2.TailcallVarargs.arg1(Unknown Source)
        org.luaj.vm2.LuaClosure.call(Unknown Source)
        org.luaj.vm2.LuaClosure.execute(Unknown Source)
        org.luaj.vm2.LuaClosure.onInvoke(Unknown Source)
        org.luaj.vm2.TailcallVarargs.eval(Unknown Source)
        org.luaj.vm2.TailcallVarargs.arg1(Unknown Source)
        org.luaj.vm2.LuaClosure.call(Unknown Source)
        org.luaj.vm2.LuaClosure.execute(Unknown Source)
        org.luaj.vm2.LuaClosure.call(Unknown Source)
        org.luaj.vm2.LuaValue.gettable(Unknown Source)
        org.luaj.vm2.LuaTable.get(Unknown Source)
        org.luaj.vm2.LuaClosure.execute(Unknown Source)
        org.luaj.vm2.LuaClosure.onInvoke(Unknown Source)
        org.luaj.vm2.LuaClosure.invoke(Unknown Source)
        org.luaj.vm2.LuaClosure.execute(Unknown Source)
        org.luaj.vm2.LuaClosure.onInvoke(Unknown Source)
        org.luaj.vm2.TailcallVarargs.eval(Unknown Source)
        org.luaj.vm2.LuaClosure.invoke(Unknown Source)
        org.luaj.vm2.lib.BaseLib$xpcall.invoke(Unknown Source)
        org.luaj.vm2.LuaClosure.execute(Unknown Source)
        org.luaj.vm2.LuaClosure.onInvoke(Unknown Source)
        org.luaj.vm2.TailcallVarargs.eval(Unknown Source)
        org.luaj.vm2.TailcallVarargs.arg1(Unknown Source)
        org.luaj.vm2.LuaClosure.call(Unknown Source)
        org.luaj.vm2.LuaValue.method(Unknown Source)
        gplx.xowa.xtns.scribunto.engines.luaj.Luaj_server.Dispatch(Luaj_server.java:45)
        gplx.xowa.xtns.scribunto.engines.luaj.Luaj_engine.Dispatch_as_kv_ary(Luaj_engine.java:72)
        gplx.xowa.xtns.scribunto.engines.luaj.Luaj_engine.CallFunction(Luaj_engine.java:59)
        gplx.xowa.xtns.scribunto.Scrib_core.Invoke(Scrib_core.java:192)
        gplx.xowa.xtns.scribunto.Scrib_invoke_func.Func_evaluate(Scrib_invoke_func.java:80)
        gplx.xowa.parsers.tmpls.Xot_invk_tkn_.Eval_func(Xot_invk_tkn_.java:30)
        gplx.xowa.parsers.tmpls.Xot_invk_tkn.Tmpl_evaluate(Xot_invk_tkn.java:258)
        gplx.xowa.parsers.tmpls.Xot_defn_tmpl_.Make_itm(Xot_defn_tmpl_.java:52)
        gplx.xowa.parsers.tmpls.Xot_defn_tmpl_.CopyNew(Xot_defn_tmpl_.java:42)
        gplx.xowa.parsers.tmpls.Xot_invk_tkn.Tmpl_evaluate(Xot_invk_tkn.java:272)
        gplx.xowa.parsers.tmpls.Arg_itm_tkn_base.Tmpl_evaluate(Arg_itm_tkn_base.java:45)
        gplx.xowa.xtns.pfuncs.Pf_func_.Eval_arg_or(Pf_func_.java:46)
        gplx.xowa.xtns.pfuncs.Pf_func_.Eval_arg_or(Pf_func_.java:40)
        gplx.xowa.xtns.pfuncs.Pf_func_.Eval_arg_or_empty(Pf_func_.java:35)
        gplx.xowa.xtns.pfuncs.ifs.Pfunc_if.Func_evaluate(Pfunc_if.java:31)
        gplx.xowa.parsers.tmpls.Xot_invk_tkn_.Eval_func(Xot_invk_tkn_.java:30)
        gplx.xowa.parsers.tmpls.Xot_invk_tkn.Tmpl_evaluate(Xot_invk_tkn.java:258)
        gplx.xowa.parsers.tmpls.Xot_defn_tmpl_.Make_itm(Xot_defn_tmpl_.java:52)
        gplx.xowa.parsers.tmpls.Xot_defn_tmpl_.CopyNew(Xot_defn_tmpl_.java:42)
        gplx.xowa.parsers.tmpls.Xot_invk_tkn.Tmpl_evaluate(Xot_invk_tkn.java:272)
        gplx.xowa.parsers.tmpls.Arg_itm_tkn_base.Tmpl_evaluate(Arg_itm_tkn_base.java:45)
        gplx.xowa.xtns.pfuncs.Pf_func_.Eval_arg_or(Pf_func_.java:46)
        gplx.xowa.xtns.pfuncs.Pf_func_.Eval_arg_or(Pf_func_.java:40)
        gplx.xowa.xtns.pfuncs.Pf_func_.Eval_arg_or_empty(Pf_func_.java:35)
        gplx.xowa.xtns.pfuncs.ifs.Pfunc_if.Func_evaluate(Pfunc_if.java:31)
        gplx.xowa.parsers.tmpls.Xot_invk_tkn_.Eval_func(Xot_invk_tkn_.java:30)
        gplx.xowa.parsers.tmpls.Xot_invk_tkn.Tmpl_evaluate(Xot_invk_tkn.java:258)
        gplx.xowa.parsers.tmpls.Arg_itm_tkn_base.Tmpl_evaluate(Arg_itm_tkn_base.java:45)
        gplx.xowa.xtns.pfuncs.Pf_func_.Eval_arg_or(Pf_func_.java:46)
        gplx.xowa.xtns.pfuncs.Pf_func_.Eval_arg_or(Pf_func_.java:40)
        gplx.xowa.xtns.pfuncs.Pf_func_.Eval_arg_or_empty(Pf_func_.java:35)
        gplx.xowa.xtns.pfuncs.ifs.Pfunc_if.Func_evaluate(Pfunc_if.java:33)
        gplx.xowa.parsers.tmpls.Xot_invk_tkn_.Eval_func(Xot_invk_tkn_.java:30)
        gplx.xowa.parsers.tmpls.Xot_invk_tkn.Tmpl_evaluate(Xot_invk_tkn.java:258)
        gplx.xowa.parsers.tmpls.Xot_defn_tmpl.Tmpl_evaluate(Xot_defn_tmpl.java:87)
        gplx.xowa.parsers.tmpls.Xot_invk_tkn.Tmpl_evaluate(Xot_invk_tkn.java:288)
        gplx.xowa.parsers.tmpls.Xot_defn_tmpl.Tmpl_evaluate(Xot_defn_tmpl.java:87)
        gplx.xowa.parsers.tmpls.Xot_invk_tkn.Tmpl_evaluate(Xot_invk_tkn.java:288)
        gplx.xowa.parsers.tmpls.Xot_tmpl_wtr.Write_tkn(Xot_tmpl_wtr.java:104)
        gplx.xowa.parsers.tmpls.Xot_tmpl_wtr.Write_tkn(Xot_tmpl_wtr.java:35)
        gplx.xowa.parsers.tmpls.Xot_tmpl_wtr.Write_all(Xot_tmpl_wtr.java:23)
        gplx.xowa.parsers.Xop_parser.Expand_tmpl(Xop_parser.java:50)
        gplx.xowa.parsers.Xop_parser.Expand_tmpl(Xop_parser.java:44)
        gplx.xowa.parsers.Xop_parser.Parse_text_to_wdom(Xop_parser.java:102)
        gplx.xowa.parsers.Xow_parser_mgr.Parse(Xow_parser_mgr.java:102)
        gplx.xowa.wikis.pages.Xowe_page_mgr.Load_page(Xowe_page_mgr.java:93)
        gplx.xowa.apps.servers.http.Http_server_mgr.Parse_page_to_html(Http_server_mgr.java:134)
        gplx.xowa.apps.servers.http.Http_server_wkr.Write_wiki(Http_server_wkr.java:115)
        gplx.xowa.apps.servers.http.Http_server_wkr.Process_get(Http_server_wkr.java:86)
        gplx.xowa.apps.servers.http.Http_server_wkr.Run(Http_server_wkr.java:64)
        gplx.xowa.apps.servers.http.Http_server_wkr.Invk(Http_server_wkr.java:348)
        gplx.Gfo_invk_.Invk_by_msg(Gfo_invk_.java:34)
        gplx.core.threads.Thread_adp.run(Thread_adp.java:33)
        java.lang.Thread.run(Thread.java:748)
I have tracked this down to the following wikitext

    {{#invoke:Wikidata|claim|P179|qualifier=P156|parameter=numeric-id}}

This has to do with movie series and next/prev links
In the case of Es_war_einmal_in_Amerika there is a previous link Todesmelodie but no next link

The wikidata for Es_war_einmal_in_Amerika (Q206388) contains

    "P179":
    [ 
      { "mainsnak":
        { "snaktype":"value"
        , "property":"P179"
        , "hash":"f5d4256da2623041dd80aeb9b84d1656a126692e"
        , "datavalue":
          { "value":
            { "entity-type":"item"
            , "numeric-id":468018
            , "id":"Q468018"
            }
          , "type":"wikibase-entityid"
          }
        }
      , "type":"statement"
      , "qualifiers":
        { "P155":
          [ 
            { "snaktype":"value"
            , "property":"P155"
            , "hash":"4371e32048d219b5c11b24632c70a435cc421d73"
            , "datavalue":
              { "value":
                { "entity-type":"item"
                , "numeric-id":510657
                , "id":"Q510657"
                }
              , "type":"wikibase-entityid"
              }
            }
          ]
        , "P1545":
          [ 
            { "snaktype":"value"
            , "property":"P1545"
            , "hash":"0e979f28bf306fefdcd352b4eb8dee5da2153a6d"
            , "datavalue":
              { "value":"3"
              , "type":"string"
              }
            }
          ]
        , "P156":
          [ 
            { "snaktype":"novalue"
            , "property":"P156"
            , "hash":"e01eaadff052ac16e704398f5ebddbd9542b15fa"
            }
          ]
        }
      , "qualifiers-order":
        [ "P155"
        , "P1545"
        , "P156"
        ]
      , "id":"Q206388$5aec9d53-4417-e760-1276-5c5283e4c0b3"
      , "rank":"normal"
      }
    ]
P179 is 'part of series', and within P155 'follows' and P156 'followed by'
In the above P155 has a `datavalue`, P156 does not

Eventually in Module:Wikidata a call is made to renderSnak
This is handled by Wdata_prop_val_visitor_.java 'Render_snak'
This routine does not cope well with no datavalue

A suggested change is to add the following to Line 64

    // the snak can exists with no datavalue
    if (datavalue_ary == null) return;

**Comment by gnosygnu** [comment]
Nice breakdown. Actually this issues looks like it has a wide impact and is easy to fix. Will make this the first priority next.

**Comment by gnosygnu** [comment]
Fixed with the commit above. Again, nice breakdown. Thanks for all the pointers!
