### ISSUE TITLE
Parsing \u codes

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#486]
I was looking at another problem to do with unicode when I came across this (minor) issue

When parsing a document to json in Json_parser.java, the routine Make_string is looking for a `\u` combo
If found, it is assumed there are 4 hex characters
Line 107 reads

    pos += 4; break;	// \uFFFF	4 hex-dec
This should be 5, to take the `u` into account

**Comment by gnosygnu** [comment]
Oops. Nice catch. Resolved with the commit above. Thanks!
