### ISSUE TITLE
utf surrogates

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#487]
Up until yesterday I was ignorant of this term - however, in looking at the wikidata entry Q2 (earth), I noticed a lot of `?` in the display
![q2a](https://user-images.githubusercontent.com/861631/58758679-73cb7880-8516-11e9-983f-c71eb8bddd9c.jpg)

This display does not reflect the current xowa layout of wikidata - I am working to make it reflect the current mediawiki version

On investigation of the `?`, this turned out to be UTF surrogates
That is the combo `\ud83d\uddfa` (as an example) needs to be combined to make the 'real' utf-16 codepoint

please see myxowa commit 31270c8
![q2b](https://user-images.githubusercontent.com/861631/58758760-04ef1f00-8518-11e9-907a-3de542de91e2.jpg)

**Comment by gnosygnu** [comment]
Cool! Thanks for screenshots and for commit! Fixed in above!
