### ISSUE TITLE
Xowa file version not updated to 3.2.1.1

### ISSUE THREAD

**Issue by robinkly** [gnosygnu/xowa#49]
Even though internally the version of the xowa app shows the version as 3.2.1.1, when right click on the app > properties > details still shows that it is 3.1.1.1. Please update... Thank you

**Comment by gnosygnu** [comment]
Thanks for filing the issue! This is indeed a bug in the build script and launch4j. I've been increasing these version numbers manually and forgot to do so for v3.2.1.1.

I'll set the correct version number for the next build. Whenever I fix the issue in the build script, I'll then mark this issue closed.

**Comment by gnosygnu** [comment]
Tonight's release has the correct version number: 3.3.4.1. Also, I fixed the build script to automatically stamp the version number. This shouldn't be a problem in the future.

I'm closing this ticket for now. Feel free to reopen if there are any related issues. Thanks!
