### ISSUE TITLE
Corrupt file: Xowa_enwiki_2016-03-05_wiki_text_ns-100.7z

### ISSUE THREAD

**Issue by XowaWilliam** [gnosygnu/xowa#50]
Hi
I downloaded this file and found it was corrupt, and could not unzip, or open archive to view contents.
I downloaded it a second time, and it was still corrupt.
William

Download address: 
https://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2016-03-05_wiki_text_ns-100.7z

**Comment by and00r** [comment]
same, 
just downloaded. 

also corrupt

**Comment by gnosygnu** [comment]
Thanks for the report and confirm. I also verify that it's corrupted. I'll upload a new version tomorrow and comment here when done. Thanks.

**Comment by gnosygnu** [comment]
I uploaded a version tonight. The link is https://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2016-03-05_wiki_text_ns-100.7z

I also downloaded it and verified it wasn't corrupt. Thanks again for the heads up.

**Comment by gnosygnu** [comment]
I'm marking this ticket closed as the corrupt file has now been replaced. Thanks for the help William and and00r.
