### ISSUE TITLE
lua formatDate not returning correct value

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#500]
I was researching Module:Wikidata when I noticed in its documentation the section 'Testing dates BC/BCE'
As suggested taking en.wikipedia.org/wiki/Horace and using the wikitext

    {{#invoke:Wikidata|getDateValue|P569|FETCH_WIKIDATA|y|BCE}}
Xowa gives `2065 BCE` whereas mediawiki is `65 BCE`
Xowa is adding the current century

The actual timestamp is `-0065-12-08T00:00:00Z`, it is converted to  `+0065-12-08T00:00:00Z` within lua
I think the trimming in function FormatDate in Scrib_lib_language.java

    int year_bgn = Bry_find_.Find_fwd_while(date_bry, 1, date_bry_len, Byte_ascii.Num_0);
    date_bry = Bry_.Mid(date_bry, year_bgn);  // lop off beginning "+000000..."
should be replaced by

    if (date_bry_len > 20)
      date_bry = Bry_.Mid(date_bry, date_bry_len - 20);  // lop off beginning "+000000..."
    else
      date_bry = Bry_.Mid(date_bry, 1);  // lop off just "+"
This gives the correct result

**Comment by gnosygnu** [comment]
Thanks for the simple write-up. This looks easy enough for me to handle tomorrow as well.

**Comment by gnosygnu** [comment]
Fixed with commit above. Approach is slightly different, but has the same end-result (only use the 4 characters before "-" as year instead of trying to trim all the zeroes)

Thanks!
