### ISSUE TITLE
invoke failed: ... {{#invoke:Navbar|navbar}}

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#503]
During the build of enwiki 2019-06-01 I get a lot of the above errors.
It goes on

    [err 0] <gplx> =Module:Navbar:64 Invalid title :
example pages
2003_Tippeligaen
2000_Tippeligaen
2000_AFC_Asian_Cup

This issue also occurs in the latest xowa build
The error being reported is that `:` is an invalid title

This is due to the fact that Module:Navbar contains the lines

    local titleText = args[titleArg] or (':' .. mw.getCurrentFrame():getParent():getTitle())
    local title = mw.title.new(mw.text.trim(titleText), 'Template')
    if not title then
        error('Invalid title ' .. titleText)
    end

`mw.getCurrentFrame():getParent():getTitle()` is returning blank - hence the colon
This routine is actually called from Module:Sports_table
I do not think, in this instance, it should be called as the trigger is guarded by the code:

    if (Args['template_name'] or (mw.title.getCurrentTitle().text ~= frame:getParent():getTitle())) then
again `frame:getParent():getTitle()` is returning blank

It seems to boil down to the fact that `*:getParent():getTitle()` is returning blank - I think it should be the name of the containing page
It it were this issue would not exist

**Comment by gnosygnu** [comment]
Great detail. I think this should be a relatively straightforward fix. Let me look at it for this weekend also. Thanks!

**Comment by gnosygnu** [comment]
Thanks again for super-helpful breakdown. It turned out issue was related to &lt;onlyinclude> around the table

Fixed with the commit above. Also, made frameTitle a mandatory constructor argument, so it shouldn't recur again. Thanks!

---
```
==League table==
<onlyinclude>{{#invoke:sports table|main|style=WDL
|res_col_header=QR
...
```
