### ISSUE TITLE
Scribunto: Infinite loop for {{WP7a|got|Gothic}} and ucs-2 chars (autosorttable issue?)

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#506]
Relating to #502
Continuing through my list of unprocessed pages, I have got to the 3164th entry and found another looper
en.wikipedia.org/wiki/List_of_Wikipedias 
From the debugger, it seems to be something to do with `AutosortTable`

Within List_of_Wikipedias there are 2 AutosortTable its the second where the issue is.

The cut down wikitext that provoces the problem is:

    {{#invoke: AutosortTable| create | class = wikitable sortable | style= text-align:right; | separator = -- | order = 2 | numeric = 2 | descending = 2, 5, 6, 7, 8, 9, 10, 11, 12 | hidden = 2
    | header = --Language--Language (local)--Wiki--Articles--Total--Edits--Admins--Users--Active users--Images--Depth
    | {{WP7a|got|Gothic}}
    }}

It seems to be something to do with the language `got`

**Comment by gnosygnu** [comment]
This looks like a bug in Scrib_lib_ustring.Find. The below code fixes the issue. 

Will have a more rigorous fix in the morning

```
			// find pos by literal match
			Ustring find_ucs = Ustring_.New_codepoints(find_str);
			int pos = text_ucs.Index_of(find_ucs, bgn_as_codes);

			// if nothing found, return empty
			if (pos == String_.Find_none)
				return rslt.Init_ary_empty();
			// else, convert char_idx to code_idx
//			else
//				pos = text_ucs.Map_char_to_data(pos);
```

**Comment by gnosygnu** [comment]
* 1st commit fixed issue with test (test was hard to nail down).
* 2nd commit changed dbg to print to console as well. This helped when tracking down where exactly the loop was occurring (since debugging itself is pretty hard)

At any rate, thanks again for all the detail above. Starting off at ```{{WP7a|got|Gothic}}``` was incredibly helpful
