### ISSUE TITLE
build of xowa from source - built exe failed to start

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#512]
I have just rebuilt xowa from source using  xowa_get_and_make.sh
Up to commit 3b5a1f8ffc72dcc6d35bbd12524782e5ceb44ebf
Now on starting the exe I get the following error

    OS: windows
    Java: 1.8.0_181 (64 bit)
    Java path: 1.8.0_181
    XOWA: 4.6.1.1903
    XOWA path: G:\xowa_dev\xowa_dev.jar
    
    Error: java.lang.NoClassDefFoundError: gplx/xowa/parsers/xndes/Xop_xnde_tag_
    Stack: gplx.xowa.parsers.htmls.Mwh_atr_parser.<clinit>(Unknown Source)
    gplx.xowa.parsers.Xoa_parser_mgr.<init>(Unknown Source)
    gplx.xowa.Xoae_app.<init>(Unknown Source)
    gplx.xowa.apps.boots.Xoa_boot_mgr.Run_app(Unknown Source)
    gplx.xowa.apps.boots.Xoa_boot_mgr.Run(Unknown Source)
    gplx.xowa.Xoa_app_.Run(Unknown Source)
    gplx.xowa.Xowa_main.main(Unknown Source)

I'm still working on merging the changes into my version to check

**Comment by desb42** [comment]
I forgot to check the build logs
the final step said BUILD SUCCESS but the first step failed

    [javac] g:\xowa_dev\src\400_xowa\src\gplx\xowa\mediawiki\XomwEnv.java:48: error: cannot find symbol
    [javac]     public static XomwEnv NewTest() {return NewTestByApp(Xoa_app_fxt.Make__app__edit());}
    [javac]                                                          ^
    [javac]   symbol:   variable Xoa_app_fxt
    [javac]   location: class XomwEnv
    [javac] g:\xowa_dev\src\400_xowa\src\gplx\xowa\mediawiki\includes\parsers\XomwParserTest.java:65: error: cannot find symbol
    [javac]             Xoae_app app = Xoa_app_fxt.Make__app__edit();
    [javac]                            ^
    [javac]   symbol:   variable Xoa_app_fxt
    [javac]   location: class XomwParserFxt
    [javac] g:\xowa_dev\src\400_xowa\src\gplx\xowa\mediawiki\includes\parsers\XomwParserTest.java:66: error: cannot find symbol
    [javac]             Xowe_wiki wiki = Xoa_app_fxt.Make__wiki__edit(app);
    [javac]                              ^
    [javac]   symbol:   variable Xoa_app_fxt
    [javac]   location: class XomwParserFxt
    [javac] g:\xowa_dev\src\400_xowa\src\gplx\xowa\mediawiki\includes\title\XomwMediaWikiTitleCodecTest.java:52: error: cannot find symbol
    [javac]             Xoae_app app = Xoa_app_fxt.Make__app__edit();
    [javac]                            ^
    [javac]   symbol:   variable Xoa_app_fxt
    [javac]   location: class XomwMediaWikiTitleCodecFxt
    [javac] g:\xowa_dev\src\400_xowa\src\gplx\xowa\mediawiki\languages\XomwLanguageTest.java:119: error: cannot find symbol
    [javac]             Xoae_app app = Xoa_app_fxt.Make__app__edit();
    [javac]                            ^
    [javac]   symbol:   variable Xoa_app_fxt
    [javac]   location: class XomwLanguageFxt
    [javac] Note: Some input files use unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.
    [javac] 5 errors

    BUILD FAILED

It looks like the file 400_xowa/src/gplx/xowa/Xoa_app_txt.java no longer exists

**Comment by desb42** [comment]
it looks like the line

    find ./src -type f -name '*_fxt.java' -delete
in xowa_get_and_make.sh is causing the problem

Adding back the file Xoa_app_txt.java makes it all work

**Comment by gnosygnu** [comment]
Oops. This is related to the huge MediaWiki transpilation commit in #508

I'll fix the classes in the ```/xowa/mediawiki/``` namespace to follow the same conventions as the rest of XOWA. Namely ```_fxt``` and ```_tst``` suffixes (instead of ```Fxt``` and ```Test```)

Thanks for the detail!

**Comment by gnosygnu** [comment]
Okay, I made a number of commits to remove any ```error```. There's a lot of output from the script, but things look good. My ultimate test was to run ```java -jar xowa_dev.jar``` which launched XOWA.

Let me know if there is anything else. In the meantime, thanks!

**Comment by desb42** [comment]
I might have jumped the gun, but . ..

The shell script build failed
some error output

    [javac] g:\xowa_dev\src\110_gfml\tst\gplx\gfml\yfxts_GfmlParse_fxt.java:18: error: cannot find symbol
    [javac]     public GfmlNde_mok nde_() {return GfmlNde_mok.new_();}
    [javac]            ^
    [javac]   symbol:   class GfmlNde_mok
    [javac]   location: class GfmlParse_fxt
    [javac] g:\xowa_dev\src\110_gfml\tst\gplx\gfml\yfxts_GfmlParse_fxt.java:19: error: cannot find symbol
    [javac]     public GfmlTkn_mok tkn_grp_ary_(String... ary) {return GfmlTkn_mok.new_().Subs_(GfmlTkn_mok.Xto_bry(ary));}
    [javac]            ^
    [javac]   symbol:   class GfmlTkn_mok
    [javac]   location: class GfmlParse_fxt

**Comment by gnosygnu** [comment]
I tried to run it now, but didn't get the error. Let me look at it a little more later. I should be able to figure something out from the error output. Thanks.

**Comment by gnosygnu** [comment]
I looked a little closer at the error output and it shouldn't be trying to compile the ```yfxts_GfmlParse_fxt.java``` class.

I'm guessing that your version has this line commented out?

> it looks like the line

> find ./src -type f -name '*_fxt.java' -delete

> in xowa_get_and_make.sh is causing the problem

Specifically, ```xowa_get_and_make.sh``` should have these lines:

```
# remove test files
find ./src -type f -name '*_tst.java' -delete
find ./src -type f -name '*_fxt.java' -delete
find ./src -type f -name '*_mok.java' -delete
```

Let me know if it does have these lines but is still throwing the error above.

Thanks!

**Comment by desb42** [comment]
You are correct, I did have that line commented out and had fixed it yesterday
Everything works fine now
