### ISSUE TITLE
cannot rebuild enwiki or enwikisource

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#514]
I have just tried to rebuild the html part of enwiki (from mass_parse)
I get the following error

    cmd bgn: wiki.mass_parse.init
    cmd end: wiki.mass_parse.init 35s 32f
    cmd bgn: wiki.mass_parse.exec
    error while executing script: err=[err 0] <gplx> counts do not match; same key is either added twice, or delete failed: proc=Add_base key=xowa.app.page_cache.'en.wikipedia.org'.1702660825 hash=4 list=5
    [err 1] <bldr> unknown error: key=wiki.mass_parse.exec
    [err 2] <bldr> unknown error
    [trace]:
      gplx.Ordered_hash_base.AssertCounts(Ordered_hash_base.java:65)
      gplx.Ordered_hash_base.Add_base(Ordered_hash_base.java:24)
      gplx.core.lists.Hash_adp_base.Add(Hash_adp_base.java:21)
      gplx.core.caches.Lru_cache_root.Add(Lru_cache_root.java:21)
      gplx.core.caches.Lru_cache.<init>(Lru_cache.java:25)
      gplx.xowa.wikis.caches.Xow_page_cache.<init>(Xow_page_cache.java:27)
      gplx.xowa.addons.bldrs.mass_parses.parses.utls.Xomp_tmpl_cache_bldr.New(Xomp_tmpl_cache_bldr.java:21)
      gplx.xowa.addons.bldrs.mass_parses.parses.mgrs.Xomp_parse_mgr.Run(Xomp_parse_mgr.java:36)
      gplx.xowa.addons.bldrs.mass_parses.parses.Xomp_parse_cmd.Cmd_run(Xomp_parse_cmd.java:24)
      gplx.xowa.bldrs.Xob_bldr.Run(Xob_bldr.java:104)
      gplx.xowa.bldrs.Xob_bldr.Invk(Xob_bldr.java:139)
      gplx.langs.gfs.GfsCore_.Exec(GfsCore_.java:22)
      gplx.langs.gfs.GfsCore_.Exec(GfsCore_.java:50)
      gplx.langs.gfs.GfsCore_.Exec(GfsCore_.java:50)
      gplx.langs.gfs.GfsCore.ExecOne_to(GfsCore.java:35)
      gplx.xowa.apps.gfs.Xoa_gfs_mgr.Run_str_for(Xoa_gfs_mgr.java:54)
      gplx.xowa.apps.gfs.Xoa_gfs_mgr.Run_str_for(Xoa_gfs_mgr.java:47)
      gplx.xowa.apps.gfs.Xoa_gfs_mgr.Run_url_for(Xoa_gfs_mgr.java:44)
      gplx.xowa.apps.gfs.Xoa_gfs_mgr.Run_url(Xoa_gfs_mgr.java:34)
      gplx.xowa.apps.boots.Xoa_boot_mgr.Run_app(Xoa_boot_mgr.java:118)
      gplx.xowa.apps.boots.Xoa_boot_mgr.Run(Xoa_boot_mgr.java:28)
      gplx.xowa.Xoa_app_.Run(Xoa_app_.java:24)
      gplx.xowa.Xowa_main.main(Xowa_main.java:19)

This is with my sources
So I have tried a build of enwikisource from the latest xowa source - same error

    cmd bgn: wiki.mass_parse.init
    cmd end: wiki.mass_parse.init 7s 146f
    cmd bgn: wiki.mass_parse.exec
    error while executing script: err=[err 0] <gplx> counts do not match; same key is either added twice, or delete failed: proc=Add_base key=xowa.app.page_cache.'en.wikisource.org'.1758056825 hash=4 list=5
    [err 1] <bldr> unknown error: key=wiki.mass_parse.exec
    [err 2] <bldr> unknown error
    [trace]:
      gplx.Ordered_hash_base.AssertCounts(Unknown Source)
      gplx.Ordered_hash_base.Add_base(Unknown Source)
      gplx.core.lists.Hash_adp_base.Add(Unknown Source)
      gplx.core.caches.Lru_cache_root.Add(Unknown Source)
      gplx.core.caches.Lru_cache.<init>(Unknown Source)
      gplx.xowa.wikis.caches.Xow_page_cache.<init>(Unknown Source)
      gplx.xowa.addons.bldrs.mass_parses.parses.utls.Xomp_tmpl_cache_bldr.New(Unknown Source)
      gplx.xowa.addons.bldrs.mass_parses.parses.mgrs.Xomp_parse_mgr.Run(Unknown Source)
      gplx.xowa.addons.bldrs.mass_parses.parses.Xomp_parse_cmd.Cmd_run(Unknown Source)
      gplx.xowa.bldrs.Xob_bldr.Run(Unknown Source)
      gplx.xowa.bldrs.Xob_bldr.Invk(Unknown Source)
      gplx.langs.gfs.GfsCore_.Exec(Unknown Source)
      gplx.langs.gfs.GfsCore_.Exec(Unknown Source)
      gplx.langs.gfs.GfsCore_.Exec(Unknown Source)
      gplx.langs.gfs.GfsCore.ExecOne_to(Unknown Source)
      gplx.xowa.apps.gfs.Xoa_gfs_mgr.Run_str_for(Unknown Source)
      gplx.xowa.apps.gfs.Xoa_gfs_mgr.Run_str_for(Unknown Source)
      gplx.xowa.apps.gfs.Xoa_gfs_mgr.Run_url_for(Unknown Source)
      gplx.xowa.apps.gfs.Xoa_gfs_mgr.Run_url(Unknown Source)
      gplx.xowa.apps.boots.Xoa_boot_mgr.Run_app(Unknown Source)
      gplx.xowa.apps.boots.Xoa_boot_mgr.Run(Unknown Source)
      gplx.xowa.Xoa_app_.Run(Unknown Source)
      gplx.xowa.Xowa_main.main(Unknown Source)

There has been some change to LRU caching but that may not be relevant

**Comment by gnosygnu** [comment]
Oops. Your intuition was correct and it was related to the recent change for LRU caching. Should've caught it earlier :grimacing:

Anyway, fixed with the commit above. As always, thanks!
