### ISSUE TITLE
Project management: Kanban board and issue prioritization

### ISSUE THREAD

**Issue by gnosygnu** [gnosygnu/xowa#523]
Hey @desb42 . First, let me say thanks for all the issues you've reported and fixed. XOWA is definitely much improved due to all your efforts

I know I'm pretty far behind on the backlog. Moreover, I want to try to do a MediaWiki port of the parser which will probably take me several weeks to complete.

I'm still going to label your issues and prioritize what I can (I skipped your issues tonight, because I'm trying to do a release now). However, there are so many, and honestly, you probably have a much better idea of priority than I do. In addition, there are probably commits that you integrated in your fork, which probably makes pulls from my branch sort of painful.

As an idea, I'm thinking that you can add issues to the "To do" column in https://github.com/gnosygnu/xowa/projects/2 . I'll still prioritize based on effort involved, and slip in other issues which are important to me, but at least it allows me to tackle the issues you find important.

You can add whatever issues based on whatever criteria you want. As candidates, I'd think the following fall into scope:
* Issues that are blockers (wikis fails to build; infinite loops)
* Issues that affect many pages (any of the Scribunto errors)
* Issues that you've implemented and are just waiting for me to integrate
* Anything else

Again, this is just an idea, so feel free to reject or take in whatever direction you will.

Thanks!

**Comment by gnosygnu** [comment]
Marking this issue closed for now. Offer always stands to add missed items to the project boards. One day, I'll catch up!

**Comment by desb42** [comment]
Sorry for the slow response on this one.

I am hesitant about actually adding to the "To do" list

Issues that are blocker are swept up pretty quickly

However as noted, some of the areas of change are more difficult for me to integrate

The top most of this is Categories/Categorytrees (various changes)
My version still uses the attach table mechanism
Although my version of Categorytrees display the info correctly - trying to expand does not.
My thinking is to make the json call via a new Special page (Special:Api) but I have not figured out the way to add a new Special page into the codebase
(as an aside Special:Api could be used to implement https://tools.wmflabs.org/reasonator/)

I believe that work is ongoing with a different parser that should remove the \<nowiki> issues (and others)

I also realise that there are other pressures on you (issues from others, other things you want to introduce)

I do not have the pressure of making it work for all the variations (just the ones I need)
That is, some of the changes I suggest are simple to me but there is a bigger picture that I may have missed

That said, I hope my small contribution has made xowa more appealing to others

**Comment by gnosygnu** [comment]
Thanks for the reply!

Yeah, in short, feel free to make use (or not make use) of this feature.

I think my greatest pressure is the lack of time. I used to have much more, but between my new job and personal obligations, I can only spare several hours a week. That's barely enough to keep up with some of your issues, much less do some of the larger scale work.

I think your suggestions are generally spot on. I just make odd decisions for implementation which are regrettable in hindsight (for example, ditching the regex for byte-array manipulation in #524). Also, I like to add unit tests for most of my changes, and usually that turns up issues / concern. 

> That said, I hope my small contribution has made xowa more appealing to others

Lol. I hope this comes across correctly, but your contribution has been amazing! XOWA has definitely been much better this past year because of you.

Thanks again and feel free to reconsider. I'll close this issue in a few days, but you should always have the ability to move issues around on the Kanban board.
