### ISSUE TITLE
Wbase: Handle 'unknown value' (=Module:Location map:414 No value was provided for longitude)

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#529]
This issue manifests in a number of pages
eg
Ely_Mound
Little_Mountain_Pictograph_Site
Wild_Goose_Pass_Tree
Hatch_Archeological_Site
to name a few

an example within the browser
![wild_goose_pass_tree](https://user-images.githubusercontent.com/861631/62272624-61e15580-b433-11e9-96fe-e3bc8531da2b.jpg)

Investigating this issue I have found this wikitext within Template:Infobox_NRHP

    {{#switch:{{#property:P625}}|unknown value|=|#default=1}}}}
Looking at www.wikidata.org/wiki/Q17065978, which is the wikidata for 'Wild_Goose_Pass_Tree'
Within that page is
![unknown](https://user-images.githubusercontent.com/861631/62273764-39a72600-b436-11e9-9868-78b216c41d74.jpg)
This corresponds to the json

    , "P625":
      [ 
        { "mainsnak":
          { "snaktype":"somevalue"
          , "property":"P625"
          , "hash":"17c5b80dfcf04569e32cfb687efc7f154a1618e5"
          }
        , "type":"statement"
        , "qualifiers":
          { "P828":
            [ 
              { "snaktype":"value"
              , "property":"P828"
              , "hash":"f694523cb68863b03b918d6a7de549ae4a6ca3c9"
              , "datavalue":
                { "value":
                  { "entity-type":"item"
                  , "numeric-id":47460806
                  , "id":"Q47460806"
                  }
                , "type":"wikibase-entityid"
                }
              }
            ]
          }
        , "qualifiers-order":
          [ "P828"
          ]
Note the snaktype of `somevalue` 
This in turn get 'translated' to 'unknown value' (or should)

The wikitext quoted above is looking specifically for `unknown value` or blank

My branch snaktype does the minimum to fix this

There are a lot more modification on the wikibase side of things (which I have done in my version)

**Comment by gnosygnu** [comment]
Nice detail as well as the commit at https://github.com/desb42/xowa/commit/2e1a9e3e10fe6474a95363e8deb5d12bcbc5ac00.

This looks pretty straightforward. I'll fix this after the HTTP Server fixes (which should be in the weekend or so)

Thanks!

**Comment by gnosygnu** [comment]
Sorry for delay, but took a while to track down actual behavior (and was queued up elsewhere)

Basically, added a new message for ```wikibase-snakview-variations-somevalue-label``` and use that insead.

Commit details below. Thanks!

---

* Add ```wikibase-snakview-variations-somevalue-label``` / ```wikibase-snakview-variations-novalue-label```
* Deprecate ```xowa_wikidata_novalue``` and ```xowa_wikidata_somevalue``` in favor of above
* Add comment / unit-tests
