### ISSUE TITLE
cfg:itm not found; key=xowa.gui.toolbar.show_search

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#532]
This error, along with

    cfg:itm not found; key=xowa.gui.toolbar.show_allpages
seem to have started to appear since the latest change to xo.cfg.sqlite3

The new keys (I believe) are

    xowa.gui.browser.toolbar.show_search
and

    xowa.gui.browser.toolbar.show_allpages

If this is intentional, should Xog_win_itm_cfg.java be changed as well?

**Comment by gnosygnu** [comment]
Oops. You're right. It should be ```xowa.gui.toolbar``` not ```xowa.gui.browser.toolbar```. I'm not sure how, but the ```browser``` crept in there.

I'll fix this in the next batch of updates (probably this weekend)

Thanks!

**Comment by gnosygnu** [comment]
Fixed with the commit above. Verified that Show Search and Show All Pages work now

Thanks!
