### ISSUE TITLE
Setup-pi: Fatal swt-pi-gtk-3833 in java.library.path (Xowa doesn't run on the latest raspberry pi image (Raspbian OS))

### ISSUE THREAD

**Issue by User234324** [gnosygnu/xowa#535]
After opening the xowa_arm.jar file via the terminal by entering `./xowa_arm.jar`,  a windows opens up with the following error message:

`Sorry! XOWA failed to run! Please check the TROUBLESHOOTING section in the readme.txt for known issues. You can also open an issue or send an email with the data below. Thanks! 
OS: linux Java: 11.0.3 (32 bit) Java path: 11.0.3 XOWA: 4.6.3.1908 XOWA path: /home/pi/Downloads/xowa_arm.jar 
Error: java.lang.UnsatisfiedLinkError: Could not load SWT library. Reasons: no swt-pi-gtk-3833 in java.library.path: [/usr/java/packages/lib, /usr/lib/arm-linux-gnueabihf/jni, /lib/arm-linux-gnueabihf, /usr/lib/arm-linux-gnueabihf, /usr/lib/jni, /lib, /usr/lib] no swt-pi-gtk in java.library.path: [/usr/java/packages/lib, /usr/lib/arm-linux-gnueabihf/jni, /lib/arm-linux-gnueabihf, /usr/lib/arm-linux-gnueabihf, /usr/lib/jni, /lib, /usr/lib] Can't load library: /usr/lib/jni/libswt-pi-gtk-3833.so Can't load library: /usr/lib/jni/libswt-pi-gtk.so Can't load library: /home/pi/.swt/lib/linux/arm/libswt-pi-gtk-3833.so Can't load library: /home/pi/.swt/lib/Iinux/arm/libswt-pi-gtk.so 
Stack: org.eclipse.swt.internal.Library.loadLibrary(Library.java:335) org.eclipse.swt.internal.Library.loadLibrary(Library.java:240) org.eclipse.swt.internal.gtk.OS.<clinit>(0S.java:22) org.eclipse.swt.internal.Converter.wcsToMbcs(Converter.java:63) org.eclipse.swt.internal.Converter.wcsToMbcs(Converter.java:54) org.eclipse.swt.widgets.Display.<clinit>(Display.java:133) gplx.gfui.kits.core.Swt_kit.Kit_init(Unknown Source) 
`

As it seems the latest xowa version has problems with openJDK, but the original oracleJDK version isn't any longer supported. I really tried to fix this issue on my own, but the application is still not working. May someone of you can help me to fix the issue.

**Comment by gnosygnu** [comment]
Hi! Thanks for the report.

```Error: java.lang.UnsatisfiedLinkError: Could not load SWT library. Reasons: no swt-pi-gtk-3833 in java.library.path```

It sounds like it can't find SWT. I did a random search, and came across this post: https://www.raspberrypi.org/forums/viewtopic.php?t=160217 . Specifically: ```sudo ln -s /usr/lib/jni/libswt-gtk-3836.so /usr/lib/jni/libswt-gtk.so```

Have you tried something like that? If it doesn't work, can you let me know more details on Raspberry Pi (I'm a bit fuzzy on details)

**Comment by User234324** [comment]
Thanks for your answer! I already tried to create a symbolic link on my own as described in your mentioned forum post, but it didn't work.

**As requested, here is some information on my raspberry pi:
Overview**
```
Model: Raspberry Pi 3 B+
SoC: Broadcom BCM2837B0 quad-core A53 (ARMv8) 64-bit @ 1.4GHz
GPU: Broadcom Videocore-IV
RAM: 1GB LPDDR2 SDRAM
Networking: Gigabit Ethernet (via USB channel), 2.4GHz and 5GHz 802.11b/g/n/ac Wi-Fi
Bluetooth: Bluetooth 4.2, Bluetooth Low Energy (BLE)
Storage: Micro-SD
GPIO: 40-pin GPIO header, populated
Ports: HDMI, 3.5mm analogue audio-video jack, 4x USB 2.0, Ethernet, Camera Serial Interface (CSI), Display Serial Interface (DSI)
Dimensions: 82mm x 56mm x 19.5mm, 50g
```

**Used OS:
pi@raspberrypi:~ $ cat /etc/os-release**
```
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```

More specific hardware information:
**pi@raspberrypi:~ $ cat /proc/cpuinfo**
```
processor	: 0
model name	: ARMv7 Processor rev 4 (v7l)
BogoMIPS	: 38.40
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

processor	: 1
model name	: ARMv7 Processor rev 4 (v7l)
BogoMIPS	: 38.40
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

processor	: 2
model name	: ARMv7 Processor rev 4 (v7l)
BogoMIPS	: 38.40
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

processor	: 3
model name	: ARMv7 Processor rev 4 (v7l)
BogoMIPS	: 38.40
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

Hardware	: BCM2835
Revision	: a020d3
```

**Comment by gnosygnu** [comment]
Thanks for the detail. I tried today with XOWA v4.6.3.1908 and an old Raspberry Pi B, but it still works. Stats below.

Can you try the steps here? https://www.eclipse.org/forums/index.php/t/455989/

Basically:
* Run ```$ locate libswt-gtk```
* Paste the listing here
* Then do this ```$ export LD_LIBRARY_PATH=/usr/lib/jni``` where ```/usr/lib/jni``` is one of the directories listed in ```locate```

I'd rather not install Java 11 or "Raspbian GNU/Linux 10 (buster)" on this device, but if that's the next step....

---

### Java

```
pi@raspberrypi ~ $ java -version
java version "1.8.0"
Java(TM) SE Runtime Environment (build 1.8.0-b132)
Java HotSpot(TM) Client VM (build 25.0-b70, mixed mode)
```

### OS
```
pi@raspberrypi ~ $ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 7 (wheezy)"
NAME="Raspbian GNU/Linux"
VERSION_ID="7"
VERSION="7 (wheezy)"
ID=raspbian
ID_LIKE=debian
ANSI_COLOR="1;31"
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```

### CPU
```
pi@raspberrypi ~ $ cat /proc/cpuinfo
processor	: 0
model name	: ARMv7 Processor rev 5 (v7l)
BogoMIPS	: 38.40
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xc07
CPU revision	: 5

processor	: 1
model name	: ARMv7 Processor rev 5 (v7l)
BogoMIPS	: 38.40
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xc07
CPU revision	: 5

processor	: 2
model name	: ARMv7 Processor rev 5 (v7l)
BogoMIPS	: 38.40
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xc07
CPU revision	: 5

processor	: 3
model name	: ARMv7 Processor rev 5 (v7l)
BogoMIPS	: 38.40
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xc07
CPU revision	: 5

Hardware	: BCM2709
Revision	: a21041
Serial		: 000000005f0a30c6
```

**Comment by User234324** [comment]
**Thanks for your reply, but the problem still remains after following these steps.** 

It seems as the (older) Raspbian version wheezy still uses the oracle java version, whereas the newer Raspbian version buster only used OpenJDK. These problems only emerge on systems using OpenJDK, but  oracle doesn't any longer provide an oracle java version for the arm architecture of the raspberry pi. A few years ago it was even possible to download these version on the oracle website or via the apt-command within the raspberry pi, but nowadays the Raspbian developers have fully replaced it with OpenJDK. I'm using my raspberry pi also for other projects and home office related stuff, wherefore I would prefer a solution which includes the latest Raspbian OS instead of downgrading my current system. Thanks anyways for your help :)

**Comment by gnosygnu** [comment]
Okay. Cool. I'm really not a Raspberry Pi person, so the extra info helps

At this point, I think I need to get a Raspberry Pi 3 B+ . I'm planning on ordering this one here: https://www.adafruit.com/product/3775?src=raspberrypi . Let me know if I should get a different model.

Thanks!

**Comment by User234324** [comment]
There is already a newer raspberry pi model (Raspberry Pi 4 B), which has a better performance than the former one with many hardware improvements. I would recommend you to buy the newer model, because it can run the same OS as the former model with a better performance for the same amount of money (although the retail price can be slightly different depending on the reseller; it also depends on the amount of RAM you want: 1GB/2GB/4GB). 

It also has many hardware improvements, such as a USB 3.0 support: https://www.cnx-software.com/2019/06/24/raspberry-pi-4-vs-pi-3-what-are-the-differences/

The only thing you should note is, that the raspberry pi 4 B model uses a **micro** HDMI connection (not to be confused with **mini** HDMI), so you may need an adapter.

**Comment by gnosygnu** [comment]
Nice. Thanks for the recs.

I ordered a Raspberry Pi 4 B last night. Should be arriving within a few days. I'm away this weekend, so may not post again for another week. Will let you know.

Thanks!

**Comment by gnosygnu** [comment]
Hi! So, I finally got my Raspberry Pi 4 B and set it up (slight delay due to missing an hdmi piece).

I got it to work using the script below. Could you try this on your side and see how it works for you? If it works, then I'll pack the swt-gtk-3.8.jar into future XOWA distributions.

Other details below. Thanks!

----

#### Script to get it working with fresh install on Raspberry Pi 4 B (NOOBS)

```
# install swt gtk-3 libs and, most importantly, swt-gtk-3.8.jar
sudo apt-get install libswt-gtk-3-jni libswt-gtk-3-java libswt-webkit-gtk-3-jni libwebkitgtk-1.0-0

# overwrite xowa's swt jar with the swt-gtk-3.8.jar
cp /usr/share/java/swt-gtk-3.8.jar /home/pi/xowa/bin/arm/swt/swt.jar

# install swt cairo jni (else XOWA will fail citing these libs)
sudo apt-get install libswt-cairo-gtk-3-jni

# launch xowa
java -jar xowa_arm.jar

```

#### Links
* Getting swt-gtk-3.8.jar: https://www.raspberrypi.org/forums/viewtopic.php?t=126774
* Installing SWT cairo:  https://www.raspberrypi.org/forums/viewtopic.php?t=75658

#### Technical details
My understanding (probably incomplete, but documenting for later reference)
* XOWA uses an old version of SWT for ARM (3.8 I believe, compared to 4.6.3 for everything else)
* This SWT relies on 3833 libraries, which exists in ```/usr/lib/jni``` on my Raspberry PI b
* However, on Raspberry PI 4 b (and presumably 3 b), ```/usr/lib/jni``` has incompatible libraries for 3836.

Stuff I tried which failed:
* ```ln``` 3833 to 3836: various SWT error messages about failure to create webview
* Downloading later versions of SWT: SWT error messages about running IA on ARM
* Various combinations of ```export SWT_GTK=1``` and ```export SWT_GTK=0``` with the above

Why the above should work:
* The swt-gtk-3.8.jar now is the same version as the libs in ```/usr/lib/jni```

**Comment by User234324** [comment]
**The commands mentioned above fixed the Problem. Thanks for your help :) 👍**

**Comment by gnosygnu** [comment]
Cool! Thanks for the confirm. I'll update the xowa_arm package on my side for the next release so it comes with the gtk-3.8 jar.

Also, I like to give credit to users for finding bugs. Right now, there's a line in the Change Log like this: ```Setup.Pi: Fix 'Fatal swt-pi-gtk-3833' error when loading XOWA GUI on Raspberry Pi 3 +. {detected by anonymous}``` Let me know if you would like to be referred to as User234324 or some other nick or would rather remain anonymous.

Thanks again!

**Comment by User234324** [comment]
Thanks 👍 , but I would prefer to remain anonymous.

**Comment by gnosygnu** [comment]
> Thanks +1 , but I would prefer to remain anonymous.

Yup, sounds good. :)

> I'll update the xowa_arm package on my side for the next release so it comes with the gtk-3.8 jar.

I looked at this tonight, and wasn't able to build an XOWA ARM package.
* The new swt.jar fails on the Raspbery PI B device
* The new swt.jar still doesn't work on the Raspberry PI 4 B device without installing the appropriate gtk libraries.

Instead,  I updated the generic README.TXT file to have the text below.

---

```
=== Raspberry PI: rror: java.lang.UnsatisfiedLinkError: Could not load SWT library. Reasons: no swt-pi-gtk-3833 in java.library.path ===
This error occurs because the swt.jar at /xowa/bin/arm/swt/swt.jar is included from a Raspberry PI B installation and it has libraries for 3833.

This swt.jar (3.8.1) will not run on Raspberry PI 3 or Raspberry PI 4 devices. In addition, these devices will need to install the requisite swt libraries.

To fix the issue, run the following script

<pre>
# install swt gtk-3 libs and, most importantly, swt-gtk-3.8.jar
sudo apt-get install libswt-gtk-3-jni libswt-gtk-3-java libswt-webkit-gtk-3-jni libwebkitgtk-1.0-0

# overwrite xowa's swt jar with the swt-gtk-3.8.jar
cp /usr/share/java/swt-gtk-3.8.jar /home/pi/xowa/bin/arm/swt/swt.jar

# install swt cairo jni (else XOWA will fail citing these libs)
sudo apt-get install libswt-cairo-gtk-3-jni

# launch xowa
java -jar xowa_arm.jar
</pre>

For more information, see https://github.com/gnosygnu/xowa/issues/535
```
