### ISSUE TITLE
Differences between html from html database and from generated by wikitext

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#536]
Taking the page en.wikipedia.org/wiki/Towson_University_buildings_and_structures
Taking a copy of the html produced from en.wikipedia.org-html-ns.000.xowa say towson_html.htm
and generated from en.wikipedia.org-text-ns.000.xowa as towson_wiki.htm

I ran these two files through a file comparison program and got some surprising differences

The ones I want to concentrate on are to do with the gallery imagery

around line 353 is the section
for towson_html.htm

    <ul data-xogly="-1|-1|-1" class="gallery mw-gallery-traditional">
      <li class="gallerybox" style="width:155px;">
        <div style="width:155px;">
          <div class="thumb" style="width:150px;">
            <div style="margin:15px auto;">
              <a href="/en.wikipedia.org/wiki/File:TURedMan%27sHall.jpg" class="image" xowa_title="TURedMan%27sHall.jpg"><img id="xoimg_0" src="/fsys/file/en.wikipedia.org/thumb/6/4/f/5/TURedMan%27sHall.jpg/89px.jpg" width="89" height="120" alt=""></a>
            </div>
          </div><div class="gallerytext"><center><b><a id="xolnki_8" href="/en.wikipedia.org/wiki/Improved_Order_of_Red_Men" title="Improved Order of Red Men">&quot;Red Men's Hall&quot;</a>, North Paca Street</b><br>1866</center>
    
          </div>
        </div>
      </li>
and for towson_wiki.htm

    <ul id="xowa_gallery_ul_0" class="gallery mw-gallery-traditional">
      <li id="xowa_gallery_li_0" class="gallerybox" style="width:155px;">
        <div style="width:155px;">
          <div class="thumb" style="width:150px;">
            <div style="margin:15px auto;">
              <a href="/en.wikipedia.org/wiki/File:TURedMan%27sHall.jpg" class="image" xowa_title="TURedMan%27sHall.jpg"><img id="xoimg_0" alt="" src="/fsys/file/en.wikipedia.org/thumb/6/4/f/5/TURedMan%27sHall.jpg/89px.jpg" width="89" height="120" /></a>
            </div>
          </div><div class="gallerytext"><center><b><a href="/en.wikipedia.org/wiki/Improved_Order_of_Red_Men" id="xolnki_8" title="Improved Order of Red Men">"Red Men's Hall"</a>, North Paca Street</b><br />1866</center>
    
          </div>
        </div>
      </li>

the \<ul> differs `data-xogly="-1|-1|-1"` and `id="xowa_gallery_ul_0"`
the \<li differs in that wiki has `id="xowa_gallery_li_0"` 
the File: reference has `alt=""` at different points
the centered \<a has `id="xolnki_` at different points

I guess that this is being produced by different code
(possibly a hang over from hzip?)

Does it need to be different code?

**Comment by desb42** [comment]
Some of this I can see is of my own making
[I seem to remember that I switched the order of href and id due to the Convert_page then requiring '<a href="/wiki' for identifying internal links]

Is it intended that the prebuilt html match the generated html (as much as possible)?

**Comment by gnosygnu** [comment]
> the &lt;ul> differs data-xogly="-1|-1|-1" and id="xowa_gallery_ul_0"
> the &lt;li differs in that wiki has id="xowa_gallery_li_0"
> the File: reference has alt="" at different points
> the centered <a has id="xolnki_ at different points

> Some of this I can see is of my own making
> [I seem to remember that I switched the order of href and id due to the Convert_page then requiring '<a href="/wiki' for identifying internal links]

> Is it intended that the prebuilt html match the generated html (as much as possible)?

Yeah, the ```wikitext``` and the ```html``` versions are intentionally different. The html databases couldn't hard-code the ```src``` (unfortunately, somehow they are hard-coded in #524), so I devised the ```data-*``` attributes to handle &lt;img> tags. I can't remember why I extended that to gallery, but I think it's to handle size attributes.

As for ```id```, I omit that because I didn't want to serialize the id numbers at runtime (I believe there are issues with pagebanner or something else that might change the id numbers)

Only the ```data-```   and ```id``` attributes should be different. The alt should be the same, but there could be a bug where ```alt=""``` and no alt is saved.

Anyway, hope this helps. Let me know if there is something that affects the page.

Thanks!

**Comment by gnosygnu** [comment]
I think the question is answered. Let me know if you need other info on this subject. Thanks!
