### ISSUE TITLE
Search highlight curio

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#538]
Starting xowa-http accessing an enwiki page and searching for `kyl` gives
![imediat2](https://user-images.githubusercontent.com/861631/62819338-aebbdf00-bb4b-11e9-85a4-798533b596aa.jpg)
followed by adding an `e` for `kyle`
![imediat3](https://user-images.githubusercontent.com/861631/62819357-15d99380-bb4c-11e9-9e56-36478ee9343f.jpg)
removing that `e` - back to `kyl`
![imediat4](https://user-images.githubusercontent.com/861631/62819400-ac0db980-bb4c-11e9-9ebb-0edae591dfa8.jpg)
Note the red highlighting
The letters `kyle` are highlit, however it should be `kyl`

I suspect this is something to do with how the search results are cached

**Comment by gnosygnu** [comment]
Thanks for the screenshots. Yeah, this is a caching issue. I can fix it on my side with code like the below.

Let me review in the morning and commit a more final version. Thanks

---

```
		// run it
		addon.Clear_rslts_cache();
		addon.Search(qry, cbk);
```

**Comment by gnosygnu** [comment]
Fixed with commit above. Some details below. Thanks!

---

* Changed my mind and decided not to clear cache before search-suggest
* Instead, moved highlighting logic to code just before JS is generated
* Had to change an interface definition to pass the Search_ctx down
