### ISSUE TITLE
Search: Fail gracefully when searching wikidata / commons (question on searching in commons and wikidata)

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#539]
Everyone 'knows' that searching in these to wikis does not work.
[Mainly because the indexing is not run on them]
Internally trying a search will result in a NullPointerException as the index database cannot be found

Should xowa be more forgiving and at least indicate that no search results are available?

**Comment by gnosygnu** [comment]
Yeah, let me handle the NullPointerException so it fails gracefully

**Comment by gnosygnu** [comment]
* Fixed the NPE when doing search-suggest
* Show ```Search databases are missing``` when on Special:XowaSearch

Hope that's what you had in mind. Thanks!
