### ISSUE TITLE
Parser: Remove br/, mark and potentially other tags in TOC parse (dewiki unknow tag in toc)

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#542]
The page de.wikipedia.org/wiki/Portal:Dark_Wave (dewiki 2019-06-01) has the wikitext

    === ''Jugend-<br/ >kulturelle Szene'' ===
This leads to the above error

    unknown tag in toc: page=de.wikipedia.org/wiki/Portal:Dark_Wave tag=br/

The issues seems to be the space in `<br/ >`
This does not give an error if that space is removed eg

    === ''Jugend-<br/>kulturelle Szene'' ===
or even

    === ''Jugend-<br      />kulturelle Szene'' ===

I suspect the tag parser does not expect to see whitespace between `/` and `>`

**Comment by desb42** [comment]
In addition to the above toc failure, the page de.wikipedia.org/wiki/Wikipedia:Wikimedia_CH/WIKIdienstag/VE4Phabricator

give the toc error as

    unknown tag in toc: page=de.wikipedia.org/wiki/Wikipedia:Wikimedia_CH/WIKIdienstag/VE4Phabricator tag=mark

Looking at the HTML spec it seems \<mark> is a valid tag

**Comment by gnosygnu** [comment]
Hmmm, that should be a straightforward change to handle ```&lt;br/>``` and ```&lt;mark>```. 

Out of curiosity, are you using VNU or JTidy? I'm assuming it's VNU b/c I thought ```&lt;br/>``` doesn't get outputted by JTiday

**Comment by desb42** [comment]
You guessed it - I am using VNU

I do not think that the tag parser can handle space between `/` and `>` generally

**Comment by gnosygnu** [comment]
Yeah, I wrote this parser specifically for the JTidy parser output. Hopefully, I can generalize it.

Thanks for the confirm.

**Comment by gnosygnu** [comment]
Old issue. Fixed with the commit above, with details below.

As always, thanks for the thorough report!

---

* Added option to Xoh_tag_rdr to skip ws after slash and enabled option for TOC generator
* Added mark as valid TOC tag
