### ISSUE TITLE
Reference: ref follow causes dupe (reference duplicating)

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#555]
In building enwikisource, I came across the same issue as #526, which required me to abort the build

Investigating this I identified a number of duplicates
An example of which is
en.wikisource.org/wiki/Page:Writings_of_Saint_Patrick,_Apostle_of_Ireland.djvu/154

Within the source to this page two copies of \<templatestyles src="Greek/fonts.css" /> appear
(This I believe is what is triggering #526)

further observation shows that for this page viewed in xowa-gui
![refdup](https://user-images.githubusercontent.com/861631/63208269-f00f3a00-c0c9-11e9-8987-0140d4fe6849.jpg)

each numbered section has the text written twice
Wikipedia does not
![reddup2](https://user-images.githubusercontent.com/861631/63208333-9f4c1100-c0ca-11e9-8bfe-7d858ec66776.jpg)
I am still trying to understand the convolutions of this wikitext

**Comment by gnosygnu** [comment]
As always, great write-up. Narrowed it down to the following wikitext. Will try to fix this weekend. 

```<ref name="note01"/><ref follow="note01">abc</ref><references></references>```

**Comment by gnosygnu** [comment]
Fixed with commit above. Details below.

Thanks!

---

#### Commit details
* Ignore &lt;ref follow=abc> when writing main item (surprised this didn't come up before)
* Add some extra logic to avoid adding space character in between follow items
* Add unit tests
* Add some comments
