### ISSUE TITLE
Category: Fix category count total b/c of DynamicPageList (looking at categories in enwiktionary)

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#556]
In xowa-gui I tried the page en.wiktionary.org/wiki/Category:English_lemmas
This has .. pages and it tries to display all of them
A smaller example is en.wiktionary.org/wiki/Category:English_conjunctions
![cats1](https://user-images.githubusercontent.com/861631/63446509-3e0da000-c432-11e9-874e-9ac79c55b112.jpg)

Note that it says

    The following 268 pages are in this category, out of 268 total.
it ought to be

    The following 200 pages are in this category, out of 268 total.
I also tried en.wikipedia.org/wiki/Category:20th-century_American_lawyers - this seems to behave correctly
![cats2](https://user-images.githubusercontent.com/861631/63447108-58944900-c433-11e9-89de-63ddf4490a5f.png)

The difference is in the blue outlined box(es)
These are dynamicPageList blocks 
These results are cached and when it comes to the main sections the cached results are returned instead

A small change to \400_xowa\src\gplx\xowa\addons\wikis\ctgs\htmls\catpages\Xoctg_catpage_mgr.java
is required
where the lines

    public Xoctg_catpage_ctg Get_or_load_or_null(byte[] page_ttl, Xoctg_catpage_url catpage_url, Xoa_ttl cat_ttl, int limit) {
        // load categories from cat dbs; exit if not found
        Xoctg_catpage_ctg ctg = (Xoctg_catpage_ctg)cache.Get_by(cat_ttl.Full_db());
change to

    public Xoctg_catpage_ctg Get_or_load_or_null(byte[] page_ttl, Xoctg_catpage_url catpage_url, Xoa_ttl cat_ttl, int limit) {
        // load categories from cat dbs; exit if not found
        Xoctg_catpage_ctg ctg = null;
        if (limit == Int_.Max_value) // only check if  Max_val (DynamicPageList);
            ctg = (Xoctg_catpage_ctg)cache.Get_by(cat_ttl.Full_db());

That is, only check the cache, if it is a dynamicpagelist request

**Comment by desb42** [comment]
It also begs a different question, should the dynamicpagelist be limited to say, 5000 as 563,383 entries in "English lemmas" takes a long time to process

**Comment by gnosygnu** [comment]
Thanks for the breakdown. The code change looks pretty simple, so I should be able to get that done in the next few days (Unfortunately, work is going to be busy for me for the next few weeks)

Regarding dynamicpagelist limit, it looks like it's unlimited by default: https://www.mediawiki.org/wiki/Extension:DynamicPageList_(Wikimedia)/en

However, I do agree that something needs to be done as  en.wiktionary.org/wiki/Category:English_lemmas never loaded for me.

**Comment by gnosygnu** [comment]
I looked at this a little tonight and I think I can optimize it to load 500+k entries in about 10 seconds instead of 5+ minutes (if not longer). I don't think it will be an easy fix, so unsure about when it will be completed.

**Comment by gnosygnu** [comment]
Resolved with the commit above. Specifically:
* Fixed the ```The following 268 pages are in this category, out of 268 total.``` message so that it reads ```The following 268 pages``` instead
* Improved performance of Dpl for 500,000 members so that it loads in less than a minute. This required a rewrite of the page finder which was unnecessarily verbose

Due to the rewrite of Dpl page-finder, I bumped the risk to major. I checked with the following pages:

* en.wiktionary.org/wiki/Category:English_conjunctions
* en.wiktionary.org/wiki/Category:English_lemmas
* en.wikipedia.org/wiki/Category:20th-century_American_lawyers

Will have a better idea when I get to rebuilding some wikis. Let me know if anything goes awry. Thanks.

**Comment by desb42** [comment]
> Improved performance of Dpl for 500,000 members so that it loads in less than a minute. 

Unfortunately this does not happen for me
However, if I request the page and wait about 5 minutes (possibly more) for the 'page' to complete
Subsequent request work fast due to the caching of the dynamic pages

I have also noticed that if I restart xowa-http the page loads fast - I assume Window 10 and the disks themselves are doing some form of caching
