### ISSUE TITLE
JDBC not found/ not running

### ISSUE THREAD

**Issue by chris-hawley** [gnosygnu/xowa#56]
version: 3.5.1.1; build date: 2016-05-02 00:48

arguments:
  **** NONE ****
  use --help to show help

SplashScreen.getSplashScreen() returned null
app init failed: [err 0] <java.lang.ClassNotFoundException> org.sqlite.JDBC
[err 1] <db> could not load sqlite jdbc driver
[err 2] <db> db.engine:exec failed: url=data source=D:\knowledgebases\wikipedia\user\xowa.user.anonymous.sqlite3;version=3; sql=PRAGMA page_size = 4096;
[trace]:
  java.net.URLClassLoader.findClass(Unknown Source)
  java.lang.ClassLoader.loadClass(Unknown Source)
  sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
  java.lang.ClassLoader.loadClass(Unknown Source)
  java.lang.Class.forName0(Native Method)
  java.lang.Class.forName(Unknown Source)
  gplx.dbs.engines.sqlite.Sqlite_engine.Conn_make(Unknown Source)
  gplx.dbs.engines.Db_engine_sql_base.Conn_assert(Unknown Source)
  gplx.dbs.engines.Db_engine_sql_base.New_stmt_exec(Unknown Source)
  gplx.dbs.engines.Db_engine_sql_base.Exec_as_int(Unknown Source)
  gplx.dbs.engines.Db_engine_sql_base.Exec_as_obj(Unknown Source)
  gplx.dbs.Db_conn.Exec_qry(Unknown Source)
  gplx.dbs.Db_conn_bldr_wkr__sqlite.New(Unknown Source)
  gplx.dbs.Db_conn_bldr.New(Unknown Source)
  gplx.dbs.Db_conn_bldr.Get_or_new(Unknown Source)
  gplx.xowa.users.data.Xou_db_mgr.Init_by_app(Unknown Source)
  gplx.xowa.users.Xoue_user.Init_by_app(Unknown Source)
  gplx.xowa.Xoae_app.Init_by_app(Unknown Source)
  gplx.xowa.apps.boots.Xoa_boot_mgr.Run_app(Unknown Source)
  gplx.xowa.apps.boots.Xoa_boot_mgr.Run(Unknown Source)
  gplx.xowa.Xoa_app_.Run(Unknown Source)
  gplx.xowa.Xowa_main.main(Unknown Source)

**Comment by gnosygnu** [comment]
Hi! Thanks for the error dump!

I tried to reproduce this now, but wasn't able to. Here were my steps:
* Downloaded https://github.com/gnosygnu/xowa/releases/download/v3.5.1.1/xowa_app_windows_64_v3.5.1.1.zip
* Unzipped to C:\xowa
* Ran the following in a command-line: java -jar xowa_windows_64.jar
* Repeated the above with https://github.com/gnosygnu/xowa/releases/download/v3.5.1.1/xowa_app_windows_v3.5.1.1.zip

When you get a chance, can you confirm the following?:
* Are you using the command-line? Or are you double-clicking the exe?
* What JRE version and bitness do you have? You can run "java -version". I get the following:
```
java version "1.7.0_79"
Java(TM) SE Runtime Environment (build 1.7.0_79-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.79-b02, mixed mode)
```
* Did you download the 64-bit package or the 32-bit package?
* Do you have a file at D:\knowledgebases\wikipedia\bin\any\java\jdbc\sqlite\sqlite-jdbc-3.8.11.2.jar
* Can you try again by unzipping the App Package to a separate directory? For example, unzip to D:\knowledgebases\wikipediaTest\

Hopefully, one of the above will yield clues. Thanks!

**Comment by chris-hawley** [comment]
I downloaded both the latest 64-bit and 32-bit versions and placed them in the same folder. I tried running the .exe files for both versions and running through command line with the same command as you did. I also went as far as downgrading my java to version 7 (i was using Java 8). I also tested both the jdk and jre versions. 

I then decided to try the upgrade version. And...it gave me a gui error message this time around as opposed to being limited to console errors. I then tried rerunning the jar files with the driver added to class path manually. Same error. 

I'll check on the file location but I don't remember seeing those directories.

**Comment by gnosygnu** [comment]
Thanks for the quick feedback. That's strange. Neither should Java 7 nor Java 8 should matter. I tried with Java 8 JDK right now.

I don't know why the update package changed anything. It should have kept things the same.

Try unzipping xowa_app_windows_64_v3.5.1.1.zip into a new directory. A brand new app package should always work. I suspect that something got corrupted in either D:\knowledgebases\wikipedia\bin\any\java\jdbc\sqlite\sqlite-jdbc-3.8.11.2.jar (the aforementioned JDBC jar) or D:\knowledgebases\wikipedia\user\xowa.user.anonymous.sqlite3 (the main settings database).

If a new directory doesn't work, I'll do some more investigation. Out of curiosity, which version of Windows are you on? For comparison, I'm on Windows 7 64-bit SP1.

**Comment by chris-hawley** [comment]
i have found the problem. i didn't know where the driver was supposed to be so i didn't know how to check the paths. turns out, if the path you provided is correct, the only thing in the java directory is luej. 

those directories are not included in the download on github. "user" is the only folder there.

**Comment by chris-hawley** [comment]
ok...peazip was the problem. since, i guessed that you are probably smart enough to put a release with dependencies included, i checked the zip file again and this time opened it with windows zip manager and voila...its all there.

**Comment by gnosygnu** [comment]
Cool. Thanks for the follow-up.

Just an FYI: I checked peazip now, and it is a bit weird. If I view the contents of xowa_app_windows_64_v3.5.1.1.zip, then the bin folder is missing. However, if I test it or extract it, then it shows up. See the image for context

I build the packages with the 7-zip command-line tool. The syntax is pretty basic: "7za a -t7z <package_name> <list_of_files>". I know the .zip file works on 7-Zip, as well as the default zip managers for Windows 7, Mac OS X, openSUSE, RaspberryPi, Mint, etc...

I'm going to chalk this up to a peazip issue. If there are more reports, I'll find a different way to pack the archive, but it's worked pretty well so far, so I'm a bit reluctant to change it.

![peazip](https://cloud.githubusercontent.com/assets/4994104/15089089/00474242-13ca-11e6-8b32-8c7957c87257.png)
