### ISSUE TITLE
Parser: Trim whitespace from end of title (bad argument: table expected, got nil)

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#567]
looking at page it.wikipedia.org/wiki/Italo_Toni I get
![italo](https://user-images.githubusercontent.com/861631/64352882-aba1fa80-cff4-11e9-97e7-78b00253e673.jpg)

Cutting down the wikitext to

    {{Bio
    |Nome = Italo
    |Cognome = Toni
    |Sesso = M
    |LuogoNascita = Sassoferrato
    |GiornoMeseNascita = 31 gennaio
    |AnnoNascita = 1930
    |LuogoMorte = 
    |GiornoMeseMorte = 
    |AnnoMorte = {{sp}}
    |NoteMorte = [[persona scomparsa|scomparso]] a [[Beirut]] il 2 settembre [[1980]]
    |Epoca = 1900
    |Attività = giornalista
    |Nazionalità = italiano
    }}
The issue can still be provoked

Placing `dbg('titleExists', name)` in Module:Bio I get
![italo2](https://user-images.githubusercontent.com/861631/64353841-51099e00-cff6-11e9-897b-c439425f5574.jpg)
Note two trailing `&#32;` and one on its own
If I place

    if name == '&#32;' then
      return nil
    end
immediately after the dbg statement, the error does not occur

This is (obviously) not the right place to do this
Some discussion of trailing whitespace (and `&#32;`) has occurred, but I cannot seem to find it

**Comment by desb42** [comment]
A better place for the change is in Xoa_ttl.java
around line 250 add (something like)

    // quick trailing whitespace removal (or &#32;'
    while (end > 0) {
        if (src[end-1] == ' ')
            end--;
        else if (end > 4 && src[end-5] == '&' && src[end-4] == '#' && src[end-3] == '3' && src[end-2] == '2' && src[end-1] == ';')
            end -= 5;
        else
            break;
    }

**Comment by gnosygnu** [comment]
> A better place for the change is in Xoa_ttl.java
> around line 250 add (something like)

Cool. Thanks for the investigation. I followed your suggestion and trimmed at the end. Also updated the unit tests.

> Some discussion of trailing whitespace (and &#32;) has occurred, but I cannot seem to find it

Hmm, don't remember trailing whitespace. Maybe #516 which has to do with url-encoding in the title?

Anyway, let me know if anything else. Thanks again!
