### ISSUE TITLE
Html_dump: Include namespace+title in redlink ttl, not just title (redlinks on html generated pages)

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#568]
I know that this has come up - and others have commented; but I cannot find the reference at the moment

I was looking at why there are so many more red links in the html pregenerated version versus the wikitext generated version

I think I have tracked it down to 400_xowa\src\gplx\xowa\htmls\core\wkrs\Xoh_hdoc_wkr__make.java
Line 59

    byte[] ttl_bry = data.Href_itm().Ttl_page_db();
if I change this to

    byte[] ttl_bry = data.Href_itm().Ttl_full_txt();
It seems to work much better

**Comment by gnosygnu** [comment]
Nice! This was definitely an issue because it was ignoring namespaces. This should also help #546 (if not resolve entirely)

Fixed with commit above. Thanks!
