### ISSUE TITLE
Url-encode urls in portal div (trailing percent sign in page name)

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#572]
this is a very subtle issue

the page en.wikipedia.org/wiki/.07% ends in a percent sign
in a url `%` is an escape character (introducing two further hex digits for conversion eg `%23`)

strictly the url for this page should be `en.wikipedia.org/wiki/.07%25`
as hex 25 is the percent character

It so happens that both mediawiki and I use the proxy server nginx
This server is forgiving for  `en.wikipedia.org/wiki/.07%`
but not for `en.wikipedia.org/wiki/.07%?action=edit`
![bad400](https://user-images.githubusercontent.com/861631/64486643-6a456100-d227-11e9-88ba-c971d06b0a7b.jpg)

xowa-gui is forgiving - so not noticeable

I still think this should be fixed

**Comment by gnosygnu** [comment]
Hey, thanks for the details as well as the screenshot. I wasn't able to reproduce. See my screenshot below.

I don't understand this part: ```It so happens that both mediawiki and I use the proxy server nginx```

I'm actually using apache for my localhost mediawiki. For XOWA, I'm not using any proxy server. Honestly, I don't have any experience with this, so will have to look this up later.

In the meantime, is this issue happening when just running ```--app_mode=http_server``` from the command-line (without any proxy server)? 
* If it is something else is at stake.
* If it is not, then this is a nginx / proxy server issue and I'll have to investigate it

![07%](https://user-images.githubusercontent.com/4994104/64607748-240f0f80-d397-11e9-94cd-ef01490097b9.png)

**Comment by desb42** [comment]
Strictly any `%` in a page title should actually be escapped to `%25` (unless it is already being used as an escape)

in the string `.07%?action=edit` the sequence `%?a` is invalid (I think that is why nginx barfs - I suspect apache is more forgiving)
the correct string should be '.07%25?action=edit`

If you take a look at the source to this page from mediawiki all the links that have this page title use `.07%25`

> It so happens that both mediawiki and I use the proxy server nginx

As I tried to show in the screenshot, the error is being generated when I request

    https://en.wikipedia.org/wiki/.07%?action=edit
That error comes directly from mediawiki servers (which run nginx)

**Comment by desb42** [comment]
Performing this select on enwiki 2019-08-01

    select page_title from page
    where page_title REGEXP '%'
    and page_is_redirect=0
yields 254 rows
This is a sample of the first 10

    100%_Live
    The_10%ers
    Alcohol_120%
    99%
    Articles_for_deletion/99%
    100%_(game_show)
    Lycos'_Top_5%
    The_10%_Solution_for_a_Healthy_Life
    Articles_for_deletion/The_10%_Solution_for_a_Healthy_Life
    100%_Bran

It is not just a trailing `%`

Typing `https://en.wikipedia.org/wiki/100%_Live` into Chrome yields the Bad request error above

it should be `https://en.wikipedia.org/wiki/100%25_Live`

**Comment by gnosygnu** [comment]
So, apologies again for lack of follow-up on another old issue.

I think this issue is limited to certain hrefs which are constructed by hand. Most hrefs go thru [Xoh_href_wtr](https://github.com/gnosygnu/xowa/blob/4c47bb87932b4f29443bb47ec841d9099269511f/400_xowa/src/gplx/xowa/htmls/hrefs/Xoh_href_wtr.java) which will properly `%` encode hrefs.

However, in the example above, the Edit link is constructed manually in [this code](https://github.com/gnosygnu/xowa/blob/06afe7a7b15fc84a74db04a619f4f6efcfabb459/400_xowa/src/gplx/xowa/htmls/portal/Xow_portal_mgr.java#L164)

Will fix that later this week. Let me know if you feel otherwise.

Thanks!

**Comment by gnosygnu** [comment]
Encoded urls in the portal div (which has the Edit and View HTML links above)

Tested with http_server which now shows the following in Chrome bar: `http://localhost:8080/en.wikipedia.org/wiki/.07%25?action=edit`.

Let me know if anything else. Thanks!
