### ISSUE TITLE
Html: Add 'lang=page_lang' to <html> and <div> tag (html tags with lang="en" should be wiki language specific)

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#576]
I have been working with frwiki and noticed in the html generated tags of the form

    <div id="mw-content-text" lang="en" dir="ltr" class="mw-content-ltr">
comparing this with mediawiki

    <div id="mw-content-text" lang="fr" dir="ltr" class="mw-content-ltr">

I have created a branch html_lang that should address this

**Comment by gnosygnu** [comment]
Thanks for the commit!

This looks pretty straightforward. I'll move it to the to-do and get it done sometime this weekend.

Thanks!

https://github.com/desb42/xowa/commit/355cd77ec330163b56ec0ab2a79b2b4d0cff41b7
