### ISSUE TITLE
automatic increase in int array failure

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#579]
I have been playing with the proofread page extension.
This uses the element \<pagelist> which can have (potentially) a large number of attributes

I was getting some unexpected results. On investigation, I think there may be a problem
In 400_xowa\src\gplx\xowa\parsers\htmls\Mwh_atr_mgr.java  the function `Add` adds data to an internal array `data_ary`
This array `data_ary` has an autoextend feature, that automatically doubles its size once it becomes full
The process actually creates a new array and it is intended to copy the old data to the new. In this case the line (44)

    Int_ary_.Copy_to(data_ary, data_max, data_ary);
copies to itself, the line should read

    Int_ary_.Copy_to(data_ary, data_max, new_data_ary);

On checking other sources for

    Int_ary_.Copy_to
I have found that 400_xowa\src\gplx\xowa\parsers\htmls\Mwh_doc_mgr.java also seems to suffer from the same issue
Line 41

    Int_ary_.Copy_to(data_ary, data_max, data_ary);
should be 

    Int_ary_.Copy_to(data_ary, data_max, new_data_ary);

**Comment by gnosygnu** [comment]
Sorry about the lack of updates on my side. I'm about 95% done with #553 but still have about 2 or so hours left on it. It's going to change about 20+ files, so I've been reluctant to work on anything else in the meantime (I should've branched at the start, but it looked like a straightforward change)

Anyway, I'll add this to the todo list as it looks pretty simple (arising from a stupid mistake on my side). Thanks as always for the detailed reports.

**Comment by gnosygnu** [comment]
Thanks for the code pointers. Added the change now. Also part of this commit was mistakenly incorporated into #584. Sorry about that
