### ISSUE TITLE
incorrect redirection

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#581]
following on from #580 
If I try to build a page from the link `en.wiktionary.org/wiki/w:zh`
Note the `w:`

in xowa-gui I get
![redlink2](https://user-images.githubusercontent.com/861631/65408915-66e0d680-ddde-11e9-87eb-48022202af8d.jpg)
Note that this is now `en.wikipedia.org/wiki/ZH`
which matches what mediawiki does

However in xowa-http there is a different behaviour
![redlink3](https://user-images.githubusercontent.com/861631/65409361-6e54af80-dddf-11e9-9b59-4cfe83165a0d.jpg)
Note that address `en.wiktionary.org/wiki/w:zh` is actually interpreted as
`en.wiktionary.org/wiki/zh` no `w:`

**Comment by desb42** [comment]
This issue has been fixed by #600

**Comment by gnosygnu** [comment]
Cool. Sorry for the late follow-up. Thanks for marking it closed!
