### ISSUE TITLE
Xtn.References: Auto-inline dangling references tag (Non closed <references> tag)

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#583]
Looking at `en.wiktionary.org/wiki/tepilli`
![references](https://user-images.githubusercontent.com/861631/65619877-ca266080-dfb8-11e9-82b6-6940830404ef.jpg)
There is a hanging \<references>

mediawiki shows this
![references2](https://user-images.githubusercontent.com/861631/65620280-70726600-dfb9-11e9-9fc1-1ccebaf75031.jpg)
It seems that there is a final check to display references

Strictly the \<refrerences> tag should be changed to \<references/>

**Comment by gnosygnu** [comment]
> Strictly the <refrerences> tag should be changed to <references/>

Committed code, but then saw your suggestion and realized that approach was better.

Fixed with commit above. Thanks!
