### ISSUE TITLE
xowa_get_and_make.sh failed

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#584]
As of 20190727, this script is not successful in building xowa

It seems that a directory is missing (or at least a java class)
`Xoh_hdump_wkr` is missing
and `import gplx.xowa.htmls.hdumps.*;` does not exist

**Comment by gnosygnu** [comment]
Oops. Sorry about that! Should've checked all my files in staging before pushing.

Pushed missing files now. Also confirmed xowa_get_and_make.sh works. 

Thanks!
