### ISSUE TITLE
Scribunto: mw.lua-dataWrapper metatable does not support next  (possible regex issue)

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#586]
looking at `en.wiktionary.org/wiki/Wiktionary:Japanese_transliteration`
comparing xowa-http and mediawiki
![japanese](https://user-images.githubusercontent.com/861631/65819466-d73f8b80-e214-11e9-8f85-17925c581e60.gif)

note that the highlit grey changes from japanese to romanji
The logic to handle this starts in Module:ja-link
This in turn makes use of Module:ja
Which in turn uses Module:ja/data
This contains a data structure data.kr

In Module:ja is the line

    text = gsub(text, '.', data.kr)
to me, this does not seem to be working

if I add this to Module:ja

    dbg('c2', data.kr['シ'])
    text = 'シ'
    text = gsub(text, '.', data.kr)
    dbg('c3', text)
I get

    c2 xi 
    c3 シ 

This does not seem right

**Comment by gnosygnu** [comment]
Again, thanks for all the investigative detail. Pretty impressive that you caught that difference.

The problem itself was pretty interesting.
* Basically, mw.lua has code to wrap all tables imported from other modules (```en.d:Module:ja/data``` above).
* However, when these tables are wrapped, they're wrapped in a metatable which doesn't support the ```next``` method (which XOWA uses to iterate keys in a hash)

I tried to force the metatable to override ```next``` but that has a bigger risk involved (I'd have to change ```LuaTable.next``` to be aware of metatable which has implications). As such, I settled for a simpler approach of adding an ```xo_orig_data``` and using that.

Anyway, tested with en.wiktionary.org/wiki/Wiktionary:Japanese_transliteration and added a diagnostic for it.

And, as always, thanks!
