### ISSUE TITLE
Wbase: Serialize 'references' for Scribunto (Some references not appearing)

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#587]
Looking at `fr.wikipedia.org/wiki/VLC_media_player` and the references section
Mediawiki:
![refs2](https://user-images.githubusercontent.com/861631/65946004-10eadf00-e42d-11e9-89c3-933343840f52.jpg)
and xowa-gui:
![refs1](https://user-images.githubusercontent.com/861631/65946027-1fd19180-e42d-11e9-8e06-4ca79ea18f3a.jpg)
There are at least two more references in the mediawiki version

These two references (I know there are others) have been generated by logic that starts with Template:Infobox Logiciel
This in turn ultiamtely calls Module:Wikidata
Down in the depths of this module is a call to `mw.wikibase.getAllStatements`

I believe this issue is similar to #374. That is, xowa is not generating all the info from wikidata as it should

In this case the properties have extra info in their `references` section that should be passed back for further processing in the lua module

For this case the wikidata entry is Q171477
Within this is (as an example) [inception]

    "P571":
    [ 
      { "mainsnak":
        { "snaktype":"value"
        , "property":"P571"
        , "hash":"9dd4d7f78fbd0d3520030ee93e9b104a48693878"
        , "datavalue":
          { "value":
            { "time":"+1996-00-00T00:00:00Z"
            , "timezone":0
            , "before":0
            , "after":0
            , "precision":9
            , "calendarmodel":"http:\/\/www.wikidata.org\/entity\/Q1985727"
            }
          , "type":"time"
          }
        }
      , "type":"statement"
      , "id":"Q171477$6bdd2e8c-4506-9676-02d4-c39d53937182"
      , "rank":"normal"
      , "references":
        [ 
          { "hash":"6ade582edf0210c68317d588ca45f929f6e473d9"
          , "snaks":
            { "P854":
              [ 
                { "snaktype":"value"
                , "property":"P854"
                , "hash":"6c5d51c810b0ec252d1043b61fa8060c14654223"
                , "datavalue":
                  { "value":"https:\/\/www.videolan.org\/videolan\/"
                  , "type":"string"
                  }
                }
              ]
            }
          , "snaks-order":
            [ "P854"
            ]
          }
        ]
      }
    ]
 
Note in the 'references' section is a value

    https://www.videolan.org/videolan/
This is the first reference in the mediawiki version

**Comment by gnosygnu** [comment]
Thanks for the detailed breakdown. Pretty impressed that you even noticed the difference to begin with

Handled with the commit. Other details below.

Thanks!

---

* Reproduced it with this snippet.
```
{{Wikidata|P571||linktopic=-|linkback=true|addcat=true|showsource=true}}
<references/>
```
* Fixed by serializing 'references' node for Scribunto
* Tested with https://fr.wikipedia.org/wiki/VLC_media_player

**Comment by desb42** [comment]
Nice, but ...
one tiny(!) detail

In the references section
xowa-http shows
![refcount1](https://user-images.githubusercontent.com/861631/66135348-b8187380-e5f1-11e9-8ee3-3080d234e346.jpg)
with 52 references
and mediawiki
![refcount2](https://user-images.githubusercontent.com/861631/66135368-c070ae80-e5f1-11e9-8f3f-d5099c4b14d1.jpg)
with 51 references

It seems that mediawiki has combined two refs whereas xowa not
(the duplicate is the ref regarding `Dernière version` - which comes from wikidata)

I suspect that this is a rare occurrence and possibly note for some future enhancement

**Comment by gnosygnu** [comment]
Sorry, missed this comment.

Yeah, I agree. This looks sort of rare. Created a separate issue for it, and leaving it somewhere in the backlog. See #596 

Let me know if anything else. Thanks!
