### ISSUE TITLE
xowa_exec problems with HTTP server interface

### ISSUE THREAD

**Issue by thombles** [gnosygnu/xowa#59]
Hullo, I'm having some problems using the HTTP server mode from an external browser. I'm not sure if it's a bug or I'm doing something wrong. Any tips will be much appreciated!

Version: 3.5.1.1
Platform: WIN64 and ARM
Wiki: full EN wikipedia text, search, etc. (everything except "file" and "html").
Command line: `java -jar xowa_windows_64.jar --app_mode http_server --http_server_port 8100`

 
If I start typing in the search field I get this error in the javascript console:
![xowa_exec_search](https://cloud.githubusercontent.com/assets/5511175/15989611/c33e0c16-30be-11e6-9c4e-e34784df71f1.png)

If I press enter I get a page like this one:
![search_result](https://cloud.githubusercontent.com/assets/5511175/15989615/e3d1d962-30be-11e6-9f0c-b0c095708a50.png)

Search is working correctly if I simply run the GUI launcher:
![inside_app](https://cloud.githubusercontent.com/assets/5511175/15989619/158bc4c2-30bf-11e6-8c12-b5c45987173f.png)

The second problem happens on the options page. I might, for example, check the "Web access enabled" box. When I hover my mouse over the "Save" button I get this error in my console:
![xowa_exec](https://cloud.githubusercontent.com/assets/5511175/15989631/4cac3310-30bf-11e6-88bc-6be9b8a258aa.png)

When I click on "Save" the browser goes to this URL, which XOWA doesn't particularly like.
`http://localhost:8100/exec/app.user.prefs.save%28%29;`

**Comment by gnosygnu** [comment]
Hi! Thanks for the great bug report! Unfortunately, these are known bugs.

* **Search not working**: The XOWA http-server does not handle messages back to the client (long-polling). I know Search is important, so I'll take another look at it this week. If it's difficult though, it may be a while.
* **Options not working**: This is also a limitation of the HTTP-server. The Option screens should be using POST requests. Instead, they do a GUI-workaround (something like "Get me the current HTML for the page"). This work's fine in the GUI, but fails in HTTP-server. This would take longer to fix, as it involves reworking the Options approach. Let me know if you can't get by with using the GUI, and I'll bump up the priority.

Let me know if there's anything else. Thanks again!

**Comment by thombles** [comment]
Thanks for the fast reply! No problem, it's not so bad.

**Options:** I have used a GUI instance to change the settings then copied the relevant lines from the user cfg file to the other XOWA instance. I don't need to change them often so this is fine for me.

**Search:** This would be cool to have as I am using http server mode to share one instance among multiple users on LAN. If it makes it any easier, I don't think the AJAX autocomplete is so important. It would still be quite usable if you typed your term, pressed enter and landed on the search results page.

Happy to wait. :) Feel free to ping me if you want help testing master. XOWA is really good stuff!

**Comment by gnosygnu** [comment]
Hey! Thanks for the quick feedback. Let me try to do a version that doesn't require incremental AJAX updates. It will be slower to generate all the search results at once, but it should be simpler than trying to send back results one at a time to different users.

I'll post here again by next week with an update.

**Comment by gnosygnu** [comment]
I have a workaround which will be part of this Sunday night's release. Basically I'm going to skip the AJAX part, and just generate all the search results at once. This should be responsive, as the XOWA Search engine has been optimized for fast retrieval (which was needed for Android)

Let me know if you want to try this out before Sunday night. If so, let me know your OS, and I'll upload a provisional build to my Google Drive account.

Thanks.

**Comment by thombles** [comment]
Awesome, thanks. That's okay, I'll wait 'til the Sunday release and give it a go.

**Comment by gnosygnu** [comment]
@thombles Tonight's release fixes the Search issue. I'm going to table the Options for a future fix. Let me know if there's anything else, otherwise I think this ticket can be closed.

Also, I think I stumbled across your entry for XOWA at https://karp.id.au/a/2016/06/13/wikipedia-on-lan/. If so, thank you very much for the well-written post! I was tempted to leave a comment, but wasn't sure if it was inappropriate or a conflict of interest.

Just so you know, this release also includes support for reading directly from the HTML databases. This should handle the issue about intensive resource usage on the Raspberry PI. I tried it on my Raspberry Pi, and pages come back in a handful of seconds (as opposed to minutes). You'll need to download the HTML databases separately, but you can either do that in the GUI app at Download Central. If you need to do it manually, you can refer to the instructions here: http://xowa.org/home/wiki/App/Import/Download_Central

Also, I'll add torrents for wikis in the next release. I discontinued them before, because they were little used, but I'm going to give it another go.

Let me know if there's anything else. Otherwise, thanks again for all the feedback!

**Comment by thombles** [comment]
Hello! Thanks very much, I installed the latest release and wanted to let you know that the search field is now working great.

I'm not sure if I should mention it yet... but I will - all of my wiki articles are now rendering blank. It's likely that I accidentally broke something but I don't have time to investigate this week. When I have more time to check my installation I will report a new issue if I think something is wrong. :)

Yes that is my blog post. You are certainly welcome to comment! I simply hope it was fair and accurate - I haven't been using this software for long. I look forward to trying the HTML databases on my Pi, as it would use much less power than my microserver. I suspect it might also help with my blank pages. Cheers!

**Comment by gnosygnu** [comment]
Hey again! A few points

* The blank wiki articles was yet another defect. I made a release now that should fix the issue. Please try the latest from https://github.com/gnosygnu/xowa/releases/tag/v3.6.3.3
* Your blog post was very well written. You covered the major points with just the right amount of clarity and detail. For what it's worth, I left a comment on your site. Again, let me say I really appreciate the time you took in writing the post. Thanks a bunch!

Let me know if there's anything else. Thanks again!
