### ISSUE TITLE
ParserFunction: Add {{PAGELANGUAGE}} (Script error: =Module:Pg:51 attempt to index ?)

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#595]
This page `commons.wikimedia.org/wiki/Commons:Structured_data` gives the above error (5 times)

On investigation of Module:Pg
The function p.main has the line

    local lang = args.lang or mw.getCurrentFrame():preprocess('{{PAGELANGUAGE}}')
with a dbg immediately following this, lang has a value of

    [[:Template:PAGELANGUAGE]]
I believe this should be

    en

`PAGELANGUAGE` is a magic word that does not seem to have been processed
In fact, no code seems to exist for this

**Comment by gnosygnu** [comment]
More straightforward than I expected. Thanks for the great write-up. Links to Wikimedia task and commit below.

---

* Task: https://phabricator.wikimedia.org/T59603
* Commit: https://gerrit.wikimedia.org/r/#/c/mediawiki/core/+/330982/
