### ISSUE TITLE
References: Duplicate reference generated from Module:Wikidata does not get deduped

### ISSUE THREAD

**Issue by gnosygnu** [gnosygnu/xowa#596]
As per #587, there is a minor difference between XOWA and MediaWiki when handling duplicate references generated by Module:Wikidata

* MediaWiki: Combines duplicate references into an ```a et b```
* XOWA: Lists duplicate references separately (Listed as Reference ```#2``` and ```#39```)

This is probably related to the different code-paths of MediaWiki and XOWA. The XOWA references code is the oldest extension and was written with little review of the MediaWiki CITE code. As this is a minor difference, I'm leaving it in the backlog, and will return to it if it turns out to have more widespread effects

More details below.

---

* Page: fr.wikipedia.org/wiki/VLC_media_player
* Wikitext:
```
{{Wikidata|P571||linktopic=-|linkback=true|addcat=true|showsource=true}}
{{Wikidata|P571||linktopic=-|linkback=true|addcat=true|showsource=true}}
<references/>
```
* MediaWiki: Combines duplicate references into an ```a et b```
* XOWA: Lists duplicate references separately
* Possible cause:
Module:Wikidata has code like this:
```
	for i, j in ipairs(sources) do
		local refArgs = {name = 'ref', content = j}
		if useHashes and hashes[i] ~= '-' then
			refArgs.args = {name = 'wikidata-' .. hashes[i]}
		end
dbg(mw.dump_table(refArgs));
		sources[i] = mw.getCurrentFrame():extensionTag(refArgs)
	end
```

Somehow, the extensionTag is deduping in XOWA but not in MediaWiki. Since the cite-extension code of the two code-bases don't resemble each other, it's possible that MediaWiki has some sort of de-duping logic in the CITE code. However, the following is the same for both apps

```
{{#tag:ref|<span class="ouvrage">[https://www.videolan.org/videolan/ « <cite style="font-style: normal;">https://www.videolan.org/videolan/</cite> »]</span>}}
{{#tag:ref|<span class="ouvrage">[https://www.videolan.org/videolan/ « <cite style="font-style: normal;">https://www.videolan.org/videolan/</cite> »]</span>}}
<references/>
```

The other possibility is that the tag extension gets wrapped up in UNIQs with the same hash. Depending on order-of-operations, MediaWiki may somehow end up combining the references based on the same hash (not sure how this would happen)

**Comment by desb42** [comment]
I think (in this case) the issue is that the wikibase logic to parse the wikidata json object ignores the 'hash' key and hence is unable to pass it on to the Lua module

This hash seems to be used in the french Module:wikidata 

When I change my logic to parse and pass on the hash value, I get the expected result

**Comment by gnosygnu** [comment]
Nice find! I spent an hour trying to figure it out, but your discovery was the main point. Fixed with the commit above. Thanks!
