### ISSUE TITLE
Scribunto: Cache results of title.exists (missing images slow page load)

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#597]
Although I thought that I have built a version where all the image have been downloaded and added to the 'file' databases, the page `en.wiktionary.org/wiki/網` takes time to load

This is due to the fact that on requesting the page, 6 images fail to download

    download_failed: 網-bronze-spring.svg
    download_failed: 網-odd.svg
    download_failed: 網-vulgar.svg
    download_failed: 網-bigseal.svg
    download_failed: 網-clerical.svg
    download_failed: ACC-s05493.svg

These images do not exist - but every time the page is loaded these six images will be requested

This is due to the Module:zh-glyph which is cycling through a pattern of images for this page, some of which may not exist (in this case 6 but I have seen more failures on other pages of Chinese characters)

I think this is an instance where the failures should be noted, so that the page could/should load faster

**Comment by gnosygnu** [comment]
Cool. Thanks for the detail.

The page loads quickly on my end, but I'm guessing that's because I have an SSD? Regardless, as you pointed out, the Scribunto Title.exists call should be using cached data. I added it with the commit above.

Let me know if any issues. Thanks!

**Comment by desb42** [comment]
This problem manifests when generating from wikitext (the hdump version does not seem to be affected)
As I have a slow internet connection, this probably exacerbates it

**Comment by gnosygnu** [comment]
Makes sense. Thanks!
