### ISSUE TITLE
Xowa and Android compatible phones.

### ISSUE THREAD

**Issue by XowaWilliam** [gnosygnu/xowa#6]
Hi on this new site Mr gnosygnu.

Now that I appear to have Xowa well established on my PC, I am now considering installing it on my Samsung phone, but before downloading it, I would first like to know if my phone is compatible. I know I will need to install a 64GB extended memory card.
I remember reading all the compatible phones before on SourceForge, and my model was not listed, hence this request.
Also is the Xowa on Android considered stable enough for general use?

My phone: Samsung Galaxy Core Prime - SM-G360H ( Android version 4.4.4 )
Wikipedia: https://en.wikipedia.org/wiki/Samsung_Galaxy_Core_Prime

I was not sure how GitHub posting works yet, I hope this was placed correctly. You can move it or delete it once I have seen your reply.

William

**Comment by gnosygnu** [comment]
Hey, your Github posting was fine. I just labeled the issue accordingly.

As for your question, it should work. I've been testing on a Samsung Galaxy Note II and the two models are near enough.

If you want to do a test run with a smaller wiki, try Simple Wiki. The instructions are at https://github.com/gnosygnu/xowa/wiki/Android

Thanks.

**Comment by XowaWilliam** [comment]
OK... Simple Wiki first.
Thanks.

**Comment by gnosygnu** [comment]
No problem. I'm going to go ahead and close this issue. Thanks.
