### ISSUE TITLE
HTTP Server: Redirect xwiki urls to different wikis (shortcut difference between gui and http-server)

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#600]
sort of continuing on from #580 

this seems to  be a difference in behaviour between xowa-gui and xowa-http-server

If I try `en.wikipedia.org/wiki/it:Roma` in xowa-gui the page displayed is `it.wikipedia.org/wiki/Roma`
whereas if I try `en.wikipedia.org/wiki/it:Roma` in xowa-http-server the page displayed is`en.wikipedia.org/wiki/Roma` - (the it: is ignored)

**Comment by gnosygnu** [comment]
Nice find. HTTP-server didn't support xwiki-style urls (```it:Roma```)

I added support for it in the commit above. Let me know if anything else. Thanks!

**Comment by desb42** [comment]
Almost ...

I use a proxy server (nginx) and it is picky about http headers

A block of http headers needs to be separated from any following body by two line breaks

As it stands only one is being generated in the redirect logic
That is,
Within `Write_redirect` of Http_server_wkr.java the last line of the Add block is

    , Byte_ascii.Nl_bry
This needs to be doubled, (so that there are 2 Newlines)

    , Byte_ascii.Nl_bry
    , Byte_ascii.Nl_bry

**Comment by gnosygnu** [comment]
Ah, didn't know. Updated just now. Thanks!
