### ISSUE TITLE
NullPointerException with non existent pages

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#608]
on a 'reset' xowa-gui (after a clean build), I try for the page `en.wikipedia.org/wiki/DOESNOTEXIST` which currently does not exist in enwiki
This gives a blank page (no surprise)

If I try to reload this page, I get a NullPointerException in the session log

this is an incredible contrived error, so not of any level of urgency

**Comment by gnosygnu** [comment]
Hey. That should be an easy bug to fix -- if I can reproduce it. :(

I wasn't able to though. I tried on my dev-build (with enwiki) as well as a get-and-make build (with home). See my steps below and let me know what's different? Thanks!

---

* Run ```/cygdrive/c/xowa_dev/xowa_get_and_make.sh```
* Run ```java -jar xowa_dev.jar```
* Click on url bar and enter ```home/wiki/DOES_NOT_EXIST```
* Click on url bar and enter ```home/wiki/DOES_NOT_EXIST``` again
* Do Main Menu -> View -> Reload Page
* Go to ```home/wiki/Special:XowaSystemData?type=log_session```

```
20191102_130138.665 page.load: url=home/wiki/DOES_NOT_EXIST
20191102_130138.666 page_load: loaded wikitext; page=DOES_NOT_EXIST wikitext_len=0
20191102_130139.929 page.load: url=home/wiki/DOES_NOT_EXIST
20191102_130139.930 page_load: loaded wikitext; page=DOES_NOT_EXIST wikitext_len=0
20191102_130145.041 page.load: url=home/wiki/DOES_NOT_EXIST
20191102_130145.042 page_load: loaded wikitext; page=DOES_NOT_EXIST wikitext_len=0
```

**Comment by desb42** [comment]
First of all, there is a difference between
`home/wiki/DOES_NOT_EXIST`
and
`en.wikipedia.org/wiki/DOESNOTEXIST`

the `home` version actually displays something, the enwiki version is just a blank page
(I am not sure this should be the correct behaviour - but that's another story)


I think it is to do with a close between sessions
Start xowa
close all tabs
create a new tab
enter `en.wikipedia.org/wiki/DOESNOTEXIST` - should get a blank page
close xowa

restart xowa
should just have a blank page
reload this page
open a new tab and look at the session log - this should have the error

**Comment by gnosygnu** [comment]
Thanks for follow-up. Missed the 'reset' above.

> First of all, there is a difference between
> home/wiki/DOES_NOT_EXIST
> and
> en.wikipedia.org/wiki/DOESNOTEXIST

> the home version actually displays something, the enwiki version is just a blank page
> (I am not sure this should be the correct behaviour - but that's another story)

Yeah, this is a hacky way of differentiating between 2 states
* Read-only wiki (enwiki) -> displays blank page so that "Edit" can't be reached
* Read-writeable wiki (home) -> displays page with MediaWiki portal so "Edit" can be reached

This was the original design, but has been undone recently (particularly with ?action=edit)

> I think it is to do with a close between sessions

Cool. I was able to reproduce it.

The problem is sort of an edge-case. I should refactor the GUI to handle it better, but I'm sort of waiting for SWT Chromium support before doing any GUI changes

For now, I just added a simple check. Excerpt below, as well as longer comment.

Thanks!

```
		public void Page__reload() {
			Xog_tab_itm tab = tab_mgr.Active_tab();
			if (tab.History_mgr().Count() == 0) return; // MISSING_PAGES will generate NPE if (a) is a startup tab and (b) View -> Reload Page is called; FOOTNOTE:MISSING_PAGES_NPE ISSUE#:608; DATE:2019-11-03
```

```
/*
== MISSING_PAGES_NPE ==
The NPE occurs because a MISSING_PAGE never adds to the history stack
* Exit point is `usr_dlg.Prog_one("", "", "could not find page in wiki: ~{0}", String_.new_u8(url.Raw()));`
* Several lines later, the add occurs: `history_mgr.Add(page);`

This NPE primiarily occurs for a MISSING_PAGE when loaded at start-up
* It doesn't occur in other situations, because a MISSING_PAGE will always be preceded by a "real" page
** Note that a "real" page includes Special:XowaDefaultTab (or Ctrl+T)
* It does occur for start-up b/c there is no "Special:XowaDefaultTab"; just the MISSING_PAGE

This could be fixed properly by...
* Saving and reloading the entire history stack per tab (right now only the last item is saved)
* Refactoring the GUI to avoid the NPE
** This is tricky b/c moving `history_mgr.Add(page)` above the exit point causes other side-effects
*** MISSING_PAGE will be loaded at start-up as an empty page (no ARTICLE_TEXT, but MediaWiki portal / side bar) instead of a blank page
**** This is probably desirable, but will need to change behavior to fail when someone tries to edit a read-only wiki (right now, this is the only guard)
*** Some possibly unknown behavior by registering missing pages into history
*/
```
