### ISSUE TITLE
Scribunto: Synchronize latest of ustring.lua (missing function toNFKC in ustring.lua)

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#609]
I was looking at `fr.wikisource.org/wiki/Auteur:Victor_Hugo` and noticed that some colons ':' were in the wrong place
This lead me to look at `Template:Document` 
The document page for this displayed the error

    Erreur de script: =Module:String:737 attempt to call nil
Investigating `Module:String`
Line 737 reads:

    s = mw.ustring.lower( mw.ustring.toNFKC( s ) )
Looking at xowa ustring.lua, there is no function `toNFKC`

Mediawik ustring.lua has this function

Comparing the xowa and mediawiki ustring.lua modules shows a number of differences that a simple replace probably would not work

**Comment by gnosygnu** [comment]
Nice write-up. Thanks for all the detail.

> Looking at xowa ustring.lua, there is no function toNFKC
> Mediawik ustring.lua has this function
> Comparing the xowa and mediawiki ustring.lua modules shows a number of differences that a simple replace probably would not work

Yup. I basically synchronized the latest of ustring.lua (the only difference is a custom piece of XOWA code for performance)

> I was looking at fr.wikisource.org/wiki/Auteur:Victor_Hugo and noticed that some colons ':' were in the wrong place

Yeah, I don't know why this is occurring. I know it can be "fixed" with the following steps:
* Go to fr.wikisource.org/wiki/Module:Document
* Change the following lines:
  * old: ```html = html .. date_link(args.date) .. ' :&nbsp;'```
  * new: ```html = html .. date_link(args.date) .. '&nbsp;:&nbsp;'```

For some reason, MediaWiki is converting the first space into a &amp;nbsp;

It's a bit annoying, so I created #611 to track it.

Let me know if anything else. Thanks!
