### ISSUE TITLE
HTTP_Server: Show Special:XowaError if wiki is not installed (xowa-http give NullPointerException if a not existant wiki is requested)

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#613]
This url `en.wiktionary.org/wiki/w:zh:%E7%B6%B2` appears in `en.wiktionary.org/wiki/%E7%B6%B2`

Note the `w:zh:...`
This causes now causes xowa-http (thanks to #600) to do two redirections
`en.wiktionary.org/wiki/w:zh:%E7%B6%B2` -> `en.wikipedia.org/wiki/zh:%E7%B6%B2`
`en.wikipedia.org/wiki/zh:%E7%B6%B2` -> `zh.wikipedia.org/wiki/zh:%E7%B6%B2`

I have a limited number of wikis and `zhwiki` is not one of them
On redirecting to zhwiki I get a NPE as xowa is assuming that the wiki exists and the page just times out

**Comment by gnosygnu** [comment]
Ah, missed that. That NPE occurs today with unknown wikis (For example, navigate to localhost:8080/missing_wiki/wiki/Page1)

Fixed it with the above commit. Now navigates to an error page with "wiki not installed". Thanks!
