### ISSUE TITLE
download and import images offline

### ISSUE THREAD

**Issue by ve3lst** [gnosygnu/xowa#62]
Hi,

I don't think this is the right place to post this but I wasn't able to find any other way to ask these questions.

I've done downloading and importing en.wikipedia.org to XOWA and it works perfect, now that I want to download en.wikipedia.org images and import it to XOWA I'm completely lost.

First I fund this: http://xowa.org/home/wiki/Dashboard/Image_databases.html 
but the problem I wasn't able to understand what i'm supposed to download, there's 4 downloads in different dates, then there was another link on xowa.org http://ftpmirror.your.org/pub/wikimedia/imagedumps/tarballs/fulls/
the size here is more than 1.75 TB not to mention it's from 2012.

Which one I'm supposed to download?
When the download finish all I've to do is extract the files in C:\xowa\files and I'm done?

Thanks

**Comment by gnosygnu** [comment]
Hi! No problem with your post! This was the right place to start

I simplified this in the latest releases. Try this:
* Download v3.6.4.1 at https://github.com/gnosygnu/xowa/releases
* Go to home/wiki/Special:XowaDownloadCentral 
* Add a task called "English Wikipedia - Images (2016-06) [98.70 GB]" to the queue
* Run it. It'll start downloading the images.

Alternatively, if you use a download manager, just use the URLs from home/wiki/Special:XowaDownloadCentralInfo?task_id=4 . I excerpt them below.

Hope this helps. Glad to hear that English Wikipedia works great. Let me know if there's anything else!

```
http://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2016-06_file_core.zip
http://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2016-06_file_ns.000_db.001.zip
http://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2016-06_file_ns.000_db.002.zip
http://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2016-06_file_ns.000_db.003.zip
http://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2016-06_file_ns.000_db.004.zip
http://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2016-06_file_ns.000_db.005.zip
http://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2016-06_file_ns.000_db.006.zip
http://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2016-06_file_ns.000_db.007.zip
http://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2016-06_file_ns.000_db.008.zip
http://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2016-06_file_ns.000_db.009.zip
http://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2016-06_file_ns.000_db.010.zip
http://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2016-06_file_ns.000_db.011.zip
http://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2016-06_file_ns.000_db.012.zip
http://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2016-06_file_ns.000_db.013.zip
http://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2016-06_file_ns.000_db.014.zip
http://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2016-06_file_ns.000_db.015.zip
http://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2016-06_file_ns.000_db.016.zip
http://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2016-06_file_ns.000_db.017.zip
http://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2016-06_file_ns.000_db.018.zip
http://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2016-06_file_ns.000_db.019.zip
http://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2016-06_file_ns.000_db.020.zip
http://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2016-06_file_ns.000_db.021.zip
http://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2016-06_file_ns.000_db.022.zip
http://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2016-06_file_ns.000_db.023.zip
http://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2016-06_file_ns.000_db.024.zip
http://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2016-06_file_ns.000_db.025.zip
http://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2016-06_file_ns.000_db.026.zip
http://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2016-06_file_ns.000_db.027.zip
http://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2016-06_file_ns.000_db.028.zip
http://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2016-06_file_ns.000_db.029.zip
http://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2016-06_file_ns.000_db.030.zip
http://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2016-06_file_ns.000_db.031.zip
http://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2016-06_file_ns.000_db.032.zip
http://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2016-06_file_ns.000_db.033.zip
http://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2016-06_file_ns.000_db.034.zip
http://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2016-06_file_ns.000_db.035.zip
http://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2016-06_file_ns.000_db.036.zip
http://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2016-06_file_ns.000_db.037.zip
http://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2016-06_file_ns.000_db.038.zip
http://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2016-06_file_ns.000_db.039.zip
http://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2016-06_file_ns.000_db.040.zip
http://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2016-06_file_ns.000_db.041.zip
http://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2016-06_file_ns.000_db.042.zip
http://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2016-06_file_ns.000_db.043.zip
http://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2016-06_file_ns.000_db.044.zip
http://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2016-06_file_ns.000_db.045.zip
http://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2016-06_file_ns.000_db.046.zip
http://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2016-06_file_ns.000_db.047.zip
http://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2016-06_file_ns.004_db.001.zip
http://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2016-06_file_ns.014_db.001.zip
http://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2016-06_file_ns.014_db.002.zip
http://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2016-06_file_ns.100_db.001.zip
http://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2016-06_file_ns.000_db.048.zip
http://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2016-06_file_ns.000_db.049.zip
http://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2016-06_file_ns.000_db.050.zip
http://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2016-06_file_ns.000_db.051.zip
http://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2016-06_file_ns.000_db.052.zip
http://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2016-06_file_ns.000_db.053.zip
http://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2016-06_file_ns.000_db.054.zip
http://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2016-06_file_ns.000_db.055.zip
http://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2016-06_file_ns.000_db.056.zip
http://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2016-06_file_ns.000_db.057.zip
http://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2016-06_file_ns.000_db.058.zip
http://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2016-06_file_ns.000_db.059.zip
http://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2016-06_file_ns.004_db.002.zip
http://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2016-06_file_ns.000_db.060.zip
```

**Comment by ve3lst** [comment]
Hi,

Thank you for your fast and useful response.

I guess I'll download it using download manger using the links you provided, but I've one more question.

When all the downloads finish what I've to do, just extract them into C:\xowa\file ?

Thanks

**Comment by gnosygnu** [comment]
Nope. The unzipped files go to C:\xowa\wiki\en.wikipedia.org. For example, you'll have a file called C:\xowa\wiki\en.wikipedia.org\en.wikipedia.org-file-core.xowa

Note that XOWA's Download Central automatically unzips the file and moves it for you. The main reason you don't want to use XOWA's Download Central is that most Download Managers will be faster. Most will do tricks like open multiple connections to the server and download in segments: XOWA only opens one connection.

Out of curiosity, where are you seeing C:\xowa\file? XOWA used to save to this location about a year ago, but I've moved everything under C:\xowa\wiki.

Hope this helps. Thanks!

**Comment by ve3lst** [comment]
That's strange I'd downloaded XOWA from the web site just a few days ago, anyhow the folder appears in both 32bit and 64bit when I open any Wikipedia pages (AR or EN) when I'm connected to the internet, the screenshots of the 32bit and only EN Wikipedia imported.

BTW, XOWA 32bit stopped responding and closed when importing enwiki (2 times on a 64bit and one time on a 32bit computer), but there was no problem importing arwiki!
What I did here, I imported enwiki using XOWA 64bit and then moved the wiki folder to XOWA 32bit.

![screenshot 128](https://cloud.githubusercontent.com/assets/18611574/16363233/f44dccec-3bcc-11e6-83fe-b84b39ab5b9c.png)
![screenshot 127](https://cloud.githubusercontent.com/assets/18611574/16363235/fb0f7b84-3bcc-11e6-8e29-dcc0b14867d5.png)
![screenshot 129](https://cloud.githubusercontent.com/assets/18611574/16363236/ff7cf73c-3bcc-11e6-9f2f-1768626e4eb7.png)

**Comment by gnosygnu** [comment]
Thanks for the screenshots! My comments are below

> That's strange I'd downloaded XOWA from the web site just a few days ago,

Not sure what was strange, but if you're asking about the version difference, I updated a new app last night. XOWA releases weekly -- usually on Sunday evening

> anyhow the folder appears in both 32bit and 64bit when I open any Wikipedia pages (AR or EN) 

Ah! That makes sense. XOWA still uses C:\xowa\file as a temporary location to place files. You'll find single images here, so that the HTML can refer directly to them.

However, all .xowa databases (such as the ones you're interested in) go to C:\xowa\wiki\ . I've changed all the docs to indicate as much, but keep worrying I missed a place.

> BTW, XOWA 32bit stopped responding and closed when importing enwiki (2 times on a 64bit and one time on a 32bit computer), but there was no problem importing arwiki!

That's strange. I assume you're using Import Online from home/wiki/Dashboard/Import/Online ? This process hasn't changed in years (I'm planning to rewrite parts of it in the near future).

Do you remember where it was when it stopped? Was it downloading the dump file, or was it generating the wiki? You'd see this information in the status bar at the bottom.

Also, arwiki probably imported fine because it was much smaller.

> What I did here, I imported enwiki using XOWA 64bit and then moved the wiki folder to XOWA 32bit.

Yup, this is perfectly acceptable. XOWA is modular, so you can copy and paste files from one folder to another. You can also move them from one computer to another, as well as from one OS to another (Windows -> Linux -> Mac OS X -> Raspberry PI -> Android)

**Comment by ve3lst** [comment]
That's awesome I'll download the new version now.

No

> That's strange. I assume you're using Import Online from home/wiki/Dashboard/Import/Online ?

No, I'm using the offline import method for both wikis.

> Do you remember where it was when it stopped? 


In update search link or something like this, step 1/2 if I remember correctly.


> You can also move them from one computer to another, as well as from one OS to another (Windows -> Linux -> Mac OS X -> Raspberry PI -> Android)

Thanks, I was wondering if the android files would be different from windows. That's save a lot of time.

**Comment by gnosygnu** [comment]
>> Do you remember where it was when it stopped?

> In update search link or something like this, step 1/2 if I remember correctly.

Ah! That makes sense. There's a known issue with import on 32-bit machines. See: https://github.com/gnosygnu/xowa/issues/55 . I was hoping that many machines weren't affected, but I guess that was naive.

The bug is hard to fix, as it fails deep in sqlite or sqlite-jdbc. I'll take another look at it this week. If I can't fix it, I'll put up a warning message to warn about 32-bit import.

> Thanks, I was wondering if the android files would be different from windows. That's save a lot of time.

Yeah, the Android wikis are different than the PC ones. The PC ones are too slow to run on Android.

If you get a chance, you should download the Android wikis. You can download them through Download Central. Right now, there are only Android versions for the English Wikis. German wiki will be slated for next week, and Arabic will probably be in 2 to 3 weeks. If you have an Android and would like an Arabic version earlier, let me know, and I can bump up the priority of Arabic.

Let me know if there's anything else. Otherwise, I'll close this ticket out later. Thanks!

**Comment by gnosygnu** [comment]
I'm going to mark this issue closed for now as I believe the original question was answered. 

There is still an ongoing issue with search, import and 32-bit machines. I'm going to track all progress for that under #55.

Let me know if there's anything else and I'll reopen. Thanks.
