### ISSUE TITLE
Configuration: Disable Option Page

### ISSUE THREAD

**Issue by laboef1900** [gnosygnu/xowa#621]
I'm wondering if it possible to disable the xowa "option" page for the users?

**Comment by gnosygnu** [comment]
Nope. At the moment, it's not possible. I'm assuming you want to do this for HTTP_SERVER where multiple users are accessing a site?

If so, I can add a command-line flag to the http-server boot-up. Something like ```--disable_specials XowaCfg```.

Let me know if that sounds good to you, and I'll start work on it. Thanks!

**Comment by laboef1900** [comment]
Yes it would be for the HTTP_SERVER for multiple users.
Something like --disable_specials XowaCfg would be greate.

**Comment by gnosygnu** [comment]
Cool. Thanks for the follow-up

I checked the code and actually there is safelist support for specials. For example:

```
java -jar xowa_linux_64.jar --root_dir /xowa/ --show_license n --show_args n --app_mode http_server --http_server.special_pages_safelist "Random|XowaSearch|AllPages"
```

This would allow Random, Search and AllPages, but disable anything else (for example, XowaCfg)

Hopefully that works for you. Let me know if there are any issues

Thanks!

**Comment by laboef1900** [comment]
Hello,
Thank you, that helped me. But I didn't found this option in the documetation.
I also have searched a possiblity to remove the edito button on a page. I also solve this with an filtern on a proxy.

Best Regards

**Comment by gnosygnu** [comment]
Cool! Thanks for the confirmation.

I'll add a doc page for this before I close it out. I'll also look at an option to disable the edit button, or add a new issue for it.

Thanks!

**Comment by laboef1900** [comment]
Thank you that would be grade!

**Comment by gnosygnu** [comment]
Hey! Sorry for the late reply, but have been busy.

I uploaded the documentation for instructions on disabling the Options page. In addition, there is a slightly simpler way of disabling the Edit page. See http://xowa.org/home/wiki/App/Xtn/Browser/HTTP_Server#Advanced

Finally, I like to give credit to users for suggestion / fixing bugs. The next XOWA update will have a line in the change log like ```Add instructions for disabling Special pages and edit mode {detected by anonymous}```. Let me know if you would like to be referred by another nickname (laboef1900?) or would rather remain anonymous.

Thanks!

**Comment by laboef1900** [comment]
Hello!

Thank you for the help!
You can use my nickname.

**Comment by gnosygnu** [comment]
Cool. ```laboef1900``` it is. Thanks!
