### ISSUE TITLE
Issue opening for the first time

### ISSUE THREAD

**Issue by GayPunkNerd** [gnosygnu/xowa#628]
When opening xowa for the first time, I get the following:

[err 0] <java.lang.NullPointerException> null
[trace]:
  org.eclipse.swt.widgets.Control.internal_new_GC(Unknown Source)
  org.eclipse.swt.graphics.GC.<init>(Unknown Source)
  org.eclipse.swt.graphics.GC.<init>(Unknown Source)
  org.eclipse.swt.custom.CTabFolder.updateTabHeight(Unknown Source)
  org.eclipse.swt.custom.CTabFolder.runUpdate(Unknown Source)
  org.eclipse.swt.custom.CTabItem.getBounds(Unknown Source)
  org.eclipse.swt.custom.CTabFolder.onPaint(Unknown Source)
  org.eclipse.swt.custom.CTabFolder$1.handleEvent(Unknown Source)
  org.eclipse.swt.widgets.EventTable.sendEvent(Unknown Source)
  org.eclipse.swt.widgets.Display.sendEvent(Unknown Source)
  org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
  org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
  org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
  org.eclipse.swt.widgets.Control.drawWidget(Unknown Source)
  org.eclipse.swt.widgets.Widget.drawRect(Unknown Source)
  org.eclipse.swt.widgets.Display.windowPro

and I'm assuming there's more to the message.

**Comment by gnosygnu** [comment]
Hi! Thanks for the interest in XOWA!

When you get a chance, could you provide more details about your environment? Specifically:
* Version of XOWA
  * It should be part of whatever XOWA zip file you downloaded.
  * For example, ```xowa_app_linux_64_v4.6.5.1911.zip```
* Operating System
  * If Linux, distro and version would also be useful
  * For example, ```Linux: openSUSE 14.1``` or "Windows 10" or "OS X High Sierra"
* How you're opening XOWA
  * Are you sh'ing the ```xowa_linux_64.sh link```? (as opposed to double-clicking it which will fail)
  * Are you double-clicking the ```xowa_64.exe```? (as opposed to the jar file which will fail)

Thanks!

**Comment by gnosygnu** [comment]
Marking resolved for now. Feel free to reopen. Thanks!
