### ISSUE TITLE
Download always stops / hangs / crashes

### ISSUE THREAD

**Issue by jangirke** [gnosygnu/xowa#63]
Hi
I have this problem since I started using XowA which was pretty recently.

Windows 10 v1511b10586.318
JAVA v8u92b1.8.0_92-b14
XowA 32 & 64  v3.6.3.3 & v3.6.4.2

I start the download and some time along the way it just stops and never recovers.
It always happens with the English Wikipedia articles and it never gets to the images.

Any solutions?

**Comment by gnosygnu** [comment]
Hi! Thanks for the details!

I have a few questions.
* Are you using Import / Online (home/wiki/Dashboard/Import/Online)? Or Download Central (home/wiki/Special:XowaDownloadCentral)?
* Approximately how many MB / GB have you downloaded when it fails? 1 GB? 5 GB? Are you sure you have enough disk space?
* Do you get past the download part? (I think not, but I just want to make sure)

I've not seen any errors in the download stage. The code is pretty straightforward.

I'd recommend using the HTML dumps if you can. You can download them at home/wiki/Special:XowaDownloadCentral

If you want to use the Wikitext dumps, you can try the offline import:
* Download the latest dump from https://dumps.wikimedia.org/enwiki/20160601/enwiki-20160601-pages-articles.xml.bz2
* Go to Tools -> Import Offline (home/wiki/Dashboard/Import/Offline)
* Change language from "Simple English" to "English"
* Change "Where to get the dump" from "download" to "read from file"
* Press "Import Now"

If you're failing **after** you download, then let me know where exactly. You can also try sending me the log from home/wiki/Special:XowaSystemData?type=log_session

Hope this helps.

**Comment by jangirke** [comment]
home/wiki/Special:XowaDownloadCentral

**Comment by gnosygnu** [comment]
Ah, okay. Thanks for clarifying

A few other questions:
* Which file are you stopped at? Can you copy and paste the text here? 
For example, here's the text for the very first step
```
English Wikipedia - Articles (2016-06) [34.81 GB]
Xowa_enwiki_2016-06_core.zip ·(1/22)
download: 0% · 0 s · 0 B / 829.57 mb
```
* Have you tried restarting XOWA and pressing the Run button again? Does it not do anything or does it go a little further and then stop again?
* If it still fails, can you copy and paste the log from this screen: home/wiki/Special:XowaLog . This has log info specific to DownloadCentral.

**Comment by gnosygnu** [comment]
BTW: I'm redownloading English Wikipedia Articles now, and I'm now at 4 of 22. It should be done by morning. I'll post again when it's complete.

For reference, I'm on Windows 7 64-bit with Java 7. Windows 10 and Java 8 should work fine as well.

**Comment by gnosygnu** [comment]
I confirm the download finished this morning.

When you get a chance, please provide the information from the points above. I repeat them again here.

* Which file are you stopped at? Can you copy and paste the text here? 
For example, here's the text for the very first step
```
English Wikipedia - Articles (2016-06) [34.81 GB]
Xowa_enwiki_2016-06_core.zip ·(1/22)
download: 0% · 0 s · 0 B / 829.57 mb
```
* Have you tried restarting XOWA and pressing the Run button again? Does it not do anything or does it go a little further and then stop again?
* If it still fails, can you copy and paste the log from this screen: home/wiki/Special:XowaLog . This has log info specific to DownloadCentral.

Thanks!

**Comment by gnosygnu** [comment]
I'm marking this ticket unreproducible and closed for now. Let me know if you can get me any of the info from above, and I'll reopen and investigate. Thanks.
