### ISSUE TITLE
Gallery: Enabled packed-hover (packed hover)

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#631]
in #325 the following comment was made

> Ugh. There is support for packed-hover, but something must have broke.

I thought I would investigate (almost a year later)

It seems that the class `Gallery_mgr_packed_hover` in `400_xowa\src\gplx\xowa\xtns\gallery\Gallery_mgr_packed_base.java` is empty

I believe that this should have one override

    class Gallery_mgr_packed_hover extends Gallery_mgr_packed_overlay {
      @Override public byte Tid() {
        return Gallery_mgr_base_.Tid__packed__hover;}
    }
To return the correct Tid

**Comment by gnosygnu** [comment]
Forgot about this. Nice bump and thanks for the suggested commit.

Feel free to bump any old items as well. I've been splitting my time between triaging new tickets and working on the templateParser rewrite, so it will be a while before I get to old ones.

Anyway, made change as recommended above. Tested with ```en.wikipedia.org/wiki/Help:Pictures``` and the Cat gallery.

Thanks!
