### ISSUE TITLE
Hxtn: Add null-check for other extensions (extending hxtn)

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#634]
I have noticed that hxtn tables can be used to store arbitrary bits of text for an hdump html page - for use in reconstructing a page from html without referring to the wikitext of that page

Currently, this only stores info about the Templatedata that may be associated with a page

I have looked at the logic and come up with five additional bits of information to add (so far)

1) the various, top-right icons that may appear (eg good read) - internally, this is the code generated for indicators 
2) for wikivoyage - storage of the #isin relation (along with the additional 'parent' table #612 )
3) for wikivoyage - storage of the pagebanner and table of contents
4) for wikisource - storage of the Index: page
5) for wikisource - storage of the page quality (the coloured bar - top left)

The wikivoyage data requires changes to xowa.gfs (and java) to bring it more in line with mediawiki

The wikisource data requires other change to the java code including adding a new table (I call maxpage) and ascertaining the page quality of Page: pages
Also quite a bit of javascript code is necessary to show the additional navigation tabs (for example Prev page, Next Page)

This is a potentially breaking change for xowa versions not aware of these extensions

It would be helpful if the code in 400_xowa\src\gplx\xowa\htmls\hxtns\pages\Hxtn_page_mgr.java
within function Load_by_page the line

    Hxtn_page_wkr wkr = (Hxtn_page_wkr)wkrs.Get_by_or_fail(itm.Wkr_id());
could be replaced by

    Hxtn_page_wkr wkr = (Hxtn_page_wkr)wkrs.Get_by_or_null(itm.Wkr_id());
    if (wkr == null) continue;
(possibly with a warning)
So that it does not fail

**Comment by gnosygnu** [comment]
Hey, going through some of the todo tickets today and came across this one. I added the null-handling (with warning) as requested above (see commit link as well as code excerpt below). Let me know if anything else. 

Thanks!

```
Hxtn_page_wkr wkr = (Hxtn_page_wkr)wkrs.Get_by_or_null(itm.Wkr_id());
if (wkr == null) { // ignore unknown wkrs so other devs can add new xtns; ISSUE#:634 DATE:2020-03-08
    Gfo_usr_dlg_.Instance.Warn_many("", "", "hxtn.unknown wkr: page_id=~{0} wkr_id=~{1}", itm.Page_id(), itm.Wkr_id());
    continue;
}
```
