### ISSUE TITLE
HTML: Update HTML Santizer whitelist (Revamped whitelist)

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#636]
300 up!

I was looking at the differences  between the html of xowa and mediawiki on this page `fr.wikisource.org/wiki/Rose_et_Blanche/2/1`
and noticed that in one of the first \<span>'s in mediawiki was

    <span itemscope="" itemtype="http&#58;//schema.org/Article" itemid="https&#58;//fr.wikisource.org/wiki/Rose_et_Blanche/2/1">
After quite a bit of rummaging I found that there is a whitelist of what attributes are allowed (as part of a sanitization process)

The java responsible is in 400_xowa\src\gplx\xowa\parsers\xndes\Xop_xatr_whitelist_mgr.java
I have taken the appropriate section from https://github.com/wikimedia/mediawiki/includes/parser/Sanitizer.php and placed it into Xop_xatr_whitelist_mgr
I have tried to keep the same alignment

Please see
[Xop_xatr_whitelist_mgr.zip](https://github.com/gnosygnu/xowa/files/3944324/Xop_xatr_whitelist_mgr.zip)

This means that 7 more tags needed to be created in 400_xowa\src\gplx\xowa\parsers\xndes\Xop_xnde_tag_.java

    , Tag__audio = New(Tid__audio, "audio")
    , Tag__video = New(Tid__video, "video")
    , Tag__track = New(Tid__track, "track")
    , Tag__rtc = New(Tid__rtc, "rtc")
    , Tag__figure = New(Tid__figure, "figure")
    , Tag__figure_inline = New(Tid__figure_inline, "figure-inline")
    , Tag__figcaption = New(Tid__figcaption, "figcaption")
Strictly, there should be some code added to 400_xowa\src\gplx\xowa\htmls\core\htmls\Xoh_html_wtr.java as well

**Comment by gnosygnu** [comment]
> 300 up!

Nice going! Sadly, open issues are at 290, so I'm not really keeping up :(

I started working on PLURALs (#633), but that is turning out to be pretty complicated. May re-divert and work on the latest ones.

**Comment by gnosygnu** [comment]
It's been a while, but pushed the commit above. Thanks for the contrib!

Also, regarding this:
> 400_xowa\src\gplx\xowa\htmls\core\htmls\Xoh_html_wtr.java as well

Yup, made the change to not-escape them

Anyway, thanks again!
