### ISSUE TITLE
Capitalize pages category list

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#637]
Looking at `fr.wikisource.org/wiki/Catégorie:Religions_et_croyances`
![uplowcat](https://user-images.githubusercontent.com/861631/70533021-1876e480-1b50-11ea-9acc-b3c0dada0f93.jpg)
Note the mix of lower and upper case letters

By capitalising the first character of sortkey_normalized they would all be grouped by capital letters

Please see
[Xoctg_catpage_itm.zip](https://github.com/gnosygnu/xowa/files/3945042/Xoctg_catpage_itm.zip)

**Comment by gnosygnu** [comment]
Nice breakdown, and clean commit!

I fixed with the commit above. Had to change a bunch of files to pass in wiki.

Let me know if anything else. Thanks!
