### ISSUE TITLE
Mixed up authors

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#638]
If I start up xowa-gui, with no tabs, and ensure that the wikitext is being used
![author1](https://user-images.githubusercontent.com/861631/70848144-0acda180-1e65-11ea-9bd0-ffbcd552e9c0.jpg)

Create a new page and request `en.wikisource.org/wiki/Author:Victor_Hugo`
![author2](https://user-images.githubusercontent.com/861631/70848149-14570980-1e65-11ea-8d06-63374f393aea.jpg)

then create a further new page and request `en.wikisource.org/wiki/Author:Charles_Dickens`
![author3](https://user-images.githubusercontent.com/861631/70848155-1caf4480-1e65-11ea-8955-f5eb123fa2b0.jpg)

Note, that the image is the same (that of Victor Hugo)
also the dates of birth and death are of Victor Hugo

In my examination of this, I have found that
Author:Victor_Hugo contains the wikitext:

    {{author
     | firstname    = Victor
     | lastname     = Hugo
     | last_initial = Hu
     | description  = French writer
     }}

Template:Author contains the wikitext:

    {{#invoke:Author|dates |dates={{{dates|}}} |birthyear={{{birthyear|}}} |deathyear={{{deathyear|}}} |wikidata_id={{{wikidata|}}} }}

Which is effectively

    {{#invoke:Author|dates }}

Module:Author contains within the function dates(), the line

    local item = mw.wikibase.getEntity()

This in turn makes use of code in mw.wikibase.lua
And this is where I think there is an issue (possibly a mediawiki bug!)

within mw.wikibase.lua
getEntity calls getIdOfConnectedItemIfNil
getIdOfConnectedItemIfNil calls getEntityIdForCurrentPage
The code is

    function wikibase.getEntityIdForCurrentPage()
      php.incrementStatsKey( 'wikibase.client.scribunto.wikibase.getEntityIdForCurrentPage.call' )
  
      if pageEntityId == false then
        pageEntityId = php.getEntityId( tostring( mw.title.getCurrentTitle().prefixedText ) )
      end
  
      return pageEntityId
    end

and finally pageEntityId is a local variable that is set to false on initiation (but never reset)
This seems to be the issue

If I comment out the if statement, the desired behaviour occurs (at a little bit more computational expense) eg

    function wikibase.getEntityIdForCurrentPage()
      php.incrementStatsKey( 'wikibase.client.scribunto.wikibase.getEntityIdForCurrentPage.call' )
  
      --if pageEntityId == false then
        pageEntityId = php.getEntityId( tostring( mw.title.getCurrentTitle().prefixedText ) )
      --end
  
      return pageEntityId
    end

**Comment by gnosygnu** [comment]
Great investigation as always. Added this to the to-do list. Nearing finish with plurals issue, so hoping to get that done before moving onwards.

**Comment by gnosygnu** [comment]
Finally got around to this. Resolved with commit above.

Again, great break-down of the issue. I'm sure that was a complicated one to track down

Thanks!
