### ISSUE TITLE
ceil function in gallery

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#640]
continuing on from #325 and #631, reviewing the PHP it seems that mediawiki uses a ceiling function for (packed) gallery

the function Adjust_image_parameters in 400_xowa\src\gplx\xowa\xtns\gallery\Gallery_mgr_packed_base.java
needs ceil()

please see
[Gallery_mgr_packed_base.zip](https://github.com/gnosygnu/xowa/files/3972421/Gallery_mgr_packed_base.zip)

**Comment by gnosygnu** [comment]
Added with the commit above.

Thanks!
