### ISSUE TITLE
new span for redirects

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#642]
Starting with `en.wikivoyage.org/wiki/Finding_accommodation`, I noticed a discrepancy between xowa and mediawiki
Examining the source, the first thing I noticed was that mediawiki has added an extra \<span>

    <span class="mw-redirectedfrom">(Redirected from <a href="/w/index.php?title=Finding_accommodation&amp;redirect=no" class="mw-redirect" title="Finding accommodation">Finding accommodation</a>)</span>

The class mw-redirecedfrom has been added

Also note that the anchor has also gained another class 'mw-redirect' -  I am still tracking that one down.

A second thing to note (Should this be a separate issue?)
If I try the page `en.wikipedia.org/wiki/AssistiveTechnology` and look at the source to this page in xowa and mediawiki, other than the extra \<span> another discrepancy is that in mediawiki is the line:

    <span class="mw-redirectedfrom">&#160;&#160;(Redirected from <a href="/w/index.php?title=AssistiveTechnology&amp;redirect=no" class="mw-redirect" title="AssistiveTechnology">AssistiveTechnology</a>)</span>
Note the two `&#160;`s

If I look at `https://en.wikipedia.org/w/index.php?title=MediaWiki:Redirectedfrom&action=edit`
the wikitext is:

    &nbsp;&nbsp;(Redirected from $1)
If I look at `en.wikipedia.org/wiki/MediaWiki:Redirectedfrom?action=edit`
the wikitext is:

      (Redirected from ~{0})
(there are two leading spaces)

However, xowa does not even attempt to use this
the file 400_xowa\src\gplx\xowa\parsers\utils\Xop_redirect_mgr.java seems to be using the wrong msg_mgr call

attached is my attempt at a fix for both these problems
[Xop_redirect_mgr.zip](https://github.com/gnosygnu/xowa/files/3997976/Xop_redirect_mgr.zip)

**Comment by desb42** [comment]
by the way class `mw-redirect` is tacked onto those links that would redirect

**Comment by gnosygnu** [comment]
As always, great breakdown!

Addressed the items in the commit above. More notes below.

Let me know if anything else. Thanks!

---

* Added ```mw-redirectedfrom``` span as per https://github.com/wikimedia/mediawiki/blob/master/includes/page/Article.php#L1115-L1117
* Manually added ```mw-redirect``` span to simulate https://github.com/wikimedia/mediawiki/blob/82311f8c2c79bc469cae14e17546fd79d3541b76/includes/linker/LinkRenderer.php#L479
* Changed href to use href_encoding (as you did in myxowa: https://github.com/desb42/myxowa/blob/f8df920ef2c066c2a7d14cc0f3edc2b545edf402/400_xowa/src/gplx/xowa/Xoa_ttl.java#L134-L138)
* Didn't do anything for ```&nbsp;```. XOWA is actually using it, but it doesn't convert the 160 byte to ```&nbsp;``` . If you save the HTML as a text file and examine its bytes you should see the UTF-8 version of 160 byte, not the 32 byte
