### ISSUE TITLE
xolnki numbering is inconsistent

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#643]
during the generation of a page (either by wikitext or from hdump), links to 'internal' pages have an extra unique id assigned - this is for later redlink processing. The id prefix is `xolnki_`

In enwikivoyage, with my additions to add a breadcrumb and to add class `mw-redirect`, I have found that the generation from an hdump does not create unique ids

I believe that the routine `Add_direct` in 400_xowa\src\gplx\xowa\wikis\pages\lnkis\Xopg_lnki_list.java
needs a slight change (to keep 'lnki_idx' in step)
This seems to make things consistent

Please see
[Xopg_lnki_list.zip](https://github.com/gnosygnu/xowa/files/4002595/Xopg_lnki_list.zip)

**Comment by gnosygnu** [comment]
Added with the commit above. Thanks!
