### ISSUE TITLE
mixed up log file

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#646]
In #612 I mentioned that I have added extra logging to capture information about the #isin relationship of wikivoyage wikis

This results in many more lines being written to the log files (in this case both session.log and err.log (and to the console)
I have noticed that some of the lines are crashing (mixing up) together

A recent example is 

    20200101_161343.94320200101_161343.994 #isin: ttl=Yampupata parent=La Paz (department, Bolivia)
Note there seems to be a mixup of timestamps

Tracking this done, it seems that in 100_core\src\gplx\Gfo_usr_dlg__log_base.java function `Bld_msg` does not like multithreading - so I added a `synchronized` block

I also added a `synchronized` block around function `Log_msg` - not sure if this is entirely necessary

With these fixes, I no longer seem to get the issue (although I have only rebuilt enwikivoyage once since then)

Please see
[Gfo_usr_dlg__log_base.zip](https://github.com/gnosygnu/xowa/files/4015138/Gfo_usr_dlg__log_base.zip)

**Comment by gnosygnu** [comment]
Nice find! I kept the synchronized block with ```Log_msg``` since it uses queued_list which may have out-of-order inserts across multiple threads. However, I didn't keep the one for ```Bld_msg``` since it uses a ```StringBuffer``` which should be thread safe.

Let me know if you have any objections.

Thanks!

**Comment by desb42** [comment]
I applied the changes and removed the synchronous block around Stringbuffer. Having just rebuilt 2020-03-01 enwikivoyage, I notice that there is still crashing
eg

    20200310_211035.535 #isin: ttl=Ciamis parent=East Parahyangan
    
    20200310_211035.819 #isin: ttl=Ayaz-Kala parent=Northern Uzbekistan
    20200310_211035.81920200310_211035.914 #isin: ttl=Campinas parent=Campinas Region
Having reapplied the synchronous block, I do not seem to be getting any crashing

**Comment by desb42** [comment]
I applied the changes and removed the synchronous block around Stringbuffer. Having just rebuilt 2020-03-01 enwikivoyage, I notice that there is still crashing
eg

    20200310_211035.535 #isin: ttl=Ciamis parent=East Parahyangan

    20200310_211035.819 #isin: ttl=Ayaz-Kala parent=Northern Uzbekistan
    20200310_211035.81920200310_211035.914 #isin: ttl=Campinas parent=Campinas Region

Having reapplied the synchronous block, I do not seem to be getting any crashing

**Comment by gnosygnu** [comment]
>  However, I didn't keep the one for Bld_msg since it uses a StringBuffer which should be thread safe.

Oops. Brain lapse on my side. Forgot basic threading 101 there. 

> Having reapplied the synchronous block, I do not seem to be getting any crashing

Sorry about the trouble, and appreciate you sticking with it. Reapplied the synchronous block around `sb` with the commit above. Thanks!
