### ISSUE TITLE
missing page content in itwikisource

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#650]
Looking at `it.wikisource.org/wiki/Il_mistero_del_poeta/I` in xowa-gui
![missing](https://user-images.githubusercontent.com/861631/71998753-1c258600-3238-11ea-8837-774777f636f8.jpg)
Note that the text starts with `d’acque ...`

The equivalent mediawiki 
![missing2](https://user-images.githubusercontent.com/861631/71999266-fa78ce80-3238-11ea-8c04-456025ccf744.jpg)
Note that the text `d’acque ...` starts half way done the page

After some investigation this comes down to the wikitext of this page

    <pages index="Il Mistero del Poeta (Fogazzaro).djvu" from=15 to=18 fromsection="" tosection="" />
Note both the `fromsection` and `tosection`
Both indicate essentially that there is no fromsection or tosection; however, in \400_xowa\src\gplx\xowa\xtns\proofreadPage\Pp_pages_nde.java the coding is such that these sections have a value (albeit empty), specifically not `null`

I have changed Pp_pages_nde.java to check for the presence of a section that has a non zero length, else reset to null

Please see
[Pp_pages_nde.zip](https://github.com/gnosygnu/xowa/files/4036448/Pp_pages_nde.zip)

**Comment by gnosygnu** [comment]
Great write-up! I was able to reproduce the issue easily on my side.

My approach was slightly different, but the end-effect is the same. Let me know if there is anything else.

Thanks!
