### ISSUE TITLE
comments being ignored in Xoa_css_img_downloader.java

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#652]
I have just been looking at \xowa_dev\user\anonymous\wiki\en.wikisource.org\html\xowa_wiki.css and noticed that there seems to be some unmatched comments (that is '/\*' ... '\*/') partly because there seems to be comments inside comments

This lead me to look at the basis of this file - which I believe is `en.wikisource.org/wiki/Mediawiki:Common.css`

Looking at the first few lines of this:

    /* CSS placed here will be applied to all skins */
    
    /* end baseline See  [[MediaWiki:Gadget-Site.css]]  for remaining CSS loaded */
    /* @import url('/w/index.php?title=MediaWiki:Dynimg.css&action=raw&ctype=text/css') screen; */
    @import url('//en.wikisource.org/w/index.php?title=MediaWiki:Dynimg.css&action=raw&ctype=text/css') screen;
    
    /*	Stylesheets being tested	*/
    /* @import url('/w/index.php?title=MediaWiki:Coltest.css&action=raw&ctype=text/css') screen; */
    /*@import url('//en.wikisource.org/w/index.php?title=MediaWiki:Dynimg.css&action=raw&ctype=text/css') screen;*/
Note that there are four `@import url`s - three are inside comment blocks

Unfortunately xowa is ignoring these comment blocks and doing four imports

My suggested changes are in
[Xoa_css_img_downloader.zip](https://github.com/gnosygnu/xowa/files/4044317/Xoa_css_img_downloader.zip)

**Comment by gnosygnu** [comment]
Nice find! I would never have noticed that, as I think it would just be some extra files sitting in the directory.

I took a different approach as I wanted to clean up the existing logic a little. Covered the basic scenarios in the new Comment test.

Thanks!
