### ISSUE TITLE
Xtn.Pages: Do not escape <pages> upon invalid attributes (spurious text in <pages>)

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#656]
Looking at the wikitext of `fr.wikisource.org/wiki/Mémoires_posthumes_de_Braz_Cubas`
is the line

    <pages index="Machado de Assis - Mémoires posthumes de Bras Cubas.djvu" from=501 to 505, header=sommaire/>
Note the text ` to 505,` within that line
If that text did not exist OR if the text were something like ` zto 505,`, the page would render

The issue here seems to be that `to` is a valid keyword; however, it has an 'invalid' value

My suggestion is to check for a valid value

Please see
[Pp_pages_nde.zip](https://github.com/gnosygnu/xowa/files/4070529/Pp_pages_nde.zip)

**Comment by gnosygnu** [comment]
Again, many thanks for the clear write-up as well as the provided solution. 

Fixed with the 2nd commit above (not the first)

Again, thanks!
