### ISSUE TITLE
<pages> 'from' and 'to' blank should be null

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#657]
following on from #650, I have found a similar problem in `fr.wikisource.org/wiki/Les_Croix_de_bois` with the 'from' and 'to' attributes

The wikitext is:

    <pages index="Dorgelès - Les Croix de bois.djvu" from="" to="" header=1 />
Note the blank 'from' and 'to'

Making the same change as for 'fromsection' in Pp_pages_nde.java cures this

**Comment by gnosygnu** [comment]
Thanks for the report! The commit takes a different approach than #650 b/c ```from``` / ```to``` have some interactions with ```include```. If there are more edge cases, then I think I'll need to emulate the MW version which is more involved: https://github.com/wikimedia/mediawiki-extensions-ProofreadPage/blob/master/includes/Parser/PagequalityTagParser.php

Hopefully the above works for now. Thanks!
