### ISSUE TITLE
create xml dumps via mediawiki api

### ISSUE THREAD

**Issue by Mattze96** [gnosygnu/xowa#66]
Hey,

i was looking for an xml-dump of the archlinux-user wiki. Since the last one was from 2014, i decided to make use of the mediawiki-api and create my own one.

The dump is around 50MB and includes only basic articles, importing to xowa works. 

I plan to extend it further and i might need some help with the xml-fields needed for templating etc.

https://github.com/Mattze96/mwad

What do you think of it? Please open an issue in my repo if it doesn't work.

The last time i was active in the xowa development, was when i created the basic http-server and i'm impressed how far this project went.

Matthias

**Comment by gnosygnu** [comment]
Hey, good to hear from you! I've said it before, but I'll say it again, as it can't be said enough. Thanks again for creating the http-server! It got a lot of use from many satisfied users: from full-blown server data-scrapers to raspberry pi hackers to simple localhosters (like me).

I ran mwad and it works great. In case you're curious, my throughput was about 50 pages per second, and the whole process completed in about 3 minutes. I also gave it a test run against a recently-requested wikia wiki: http://wikiofbrothers.wikia.com/api.php . Worked perfectly well.

I created an issue now to request parameterization of the url. See: https://github.com/Mattze96/mwad/issues/1 . I don't know what's needed for xml-fields and templating, so let me know, and I'll help out.

Thanks!

**Comment by Mattze96** [comment]
Thank you for the compliments!

i fixed your issue and one of mine. The memory consumption is about 20MB RAM, so big wikis shouldn't be a problem, but maybe some breaks between the requests are needed to prevent ddos their servers :)
**wikiofbrothers takes now about 2 seconds on my Core2Duo laptop. ** Did you have the same formatting issues like in the picture below?


![bildschirmfoto_2016-07-07_21-42-27](https://cloud.githubusercontent.com/assets/3738126/16667240/c0e6a4e2-448b-11e6-8bd6-5c2b50b50146.png)

**Comment by gnosygnu** [comment]
> i fixed your issue and one of mine.

Cool. Looks good. I tested with the following: python mediawiki_api_dump.py -v -n bandofheroes.wikia.com http://bandofheroes.wikia.com . Takes about 1 or 2 seconds on my desktop.

> Did you have the same formatting issues like in the picture below?

Yeah, that's correct. XOWA supports most of Wikimedia's extensions, but Wikia has a bunch of custom extensions. I've been adding them on a per-request basis, but a good deal of Wikia pages will look like that.

**Comment by Mattze96** [comment]
> Yeah, that's correct. XOWA supports most of Wikimedia's extensions, but Wikia has a bunch of custom extensions. I've been adding them on a per-request basis, but a good deal of Wikia pages will look like that.

I've found out, that my script only downloaded the root namespace ("0"). With all the others the template issues seem to be gone. The other tags seem to be extension specific, like you said.

So all in all it looks like my script is generating an equivalent pages-articles xml dump like you can download from dumps.wikipedia.org

![bildschirmfoto_2016-07-08_17-05-16](https://cloud.githubusercontent.com/assets/3738126/16691782/5137ce3e-452e-11e6-979b-67d9108c9241.png)

**Comment by gnosygnu** [comment]
Oops! Sorry about that. I looked at it quickly, but I should have caught that.

Yes, the initial version was missing templates. This looks better now. The missing tags are clearly extensions now (createbox, mainpage-*, rss, bloglist, title, etc..)

**Comment by Mattze96** [comment]
No problem :)

I've added bz2 compression, which saves ~75% and some progress-indicators for the non-verbose mode.

**Comment by gnosygnu** [comment]
Cool. Nice work.

If you're okay with it, I can include the script in XOWA's package for this upcoming release. I'd put it under /xowa/bin/any/python/mwad and also include a help page in XOWA's home wiki. It'd be a useful starting point for other Wikia users / non-Wikimedia wiki users

Let me know if you have any other thoughts. Thanks.

**Comment by Mattze96** [comment]
Yes, that's absolutely fine. I'm looking for a way to create one-file bundled executeables for every platform, so it would be easier to run it or include it to xowa. Also tought of creating a source for dumps like your archive.org to unload their servers: [Dump Archive](https://github.com/Mattze96/mwad_dumps)  I don't know if there are any licensing issues with that... I'll delete it then.

**Comment by Mattze96** [comment]
I hope you don't mind, that i post the progress here so frequently...
After removing the python requests package the program should work on every linux distro which has python3 installed. Python on windows is not very common so maybe http://www.py2exe.org/ might be worth looking at.

Do you plan to include the script directly in xowa? If so, i can provide better formatted output for the statusbar at the bottom. But first some heavy testing as a seperate script is required!

```
[matthias@vaio-vgnsz61vn mwad]$ ./mediawiki_api_dump.py --compress https://wiki.archlinux.de/
Getting a list of all pages...
[########################################] 1269/1269 (100%)
Downloading pages...
[########################################] 1272/1272 (100%)
```

**Comment by gnosygnu** [comment]
> I'm looking for a way to create one-file bundled executeables for every platform, so it would be easier to run it or include it to xowa. 

One-file executeables would probably be best, but I think the challenge is getting python on windows. Unfortunately, I don't have any experience with Python, so I don't have any ideas / suggestions. Your py2exe.org looks promising.

> Also thought of creating a source for dumps like your archive.org to unload their servers: Dump Archive I don't know if there are any licensing issues with that... I'll delete it then.

I think licensing should be fine. The archlinux wiki is under the GFDL, so you shouldn't have any problems. Ditto with CC wikis, and that includes Wikia: http://www.wikia.com/Licensing . 

The only licensing issues I see are:
* Wikia images: These tend to be murky and depend on the fair use provision of copyright. However, I don't think you're interested in that.
* Wikis without CC or GFDL. I don't know of any offhand, but these would be offlimits with MWAD.

All other wikis should be fine. 

That said, I do think you may run into an issue with web-crawling policy. I'm pretty sure you'd get banned running this on en.wikipedia.org -- even with using the official API. I don't know how other sites would work

Also, I'd probably upload to archive.org over github.org. Github.org is more dev-centric, and I'm not sure how they would handle user-content resources

**Comment by gnosygnu** [comment]
> I hope you don't mind, that i post the progress here so frequently...

No problem. Post away. :)

> Python on windows is not very common so maybe http://www.py2exe.org/ might be worth looking at.

Yeah, as mentioned above, it looks good, but I don't have any experience with it (or Python)

> Do you plan to include the script directly in xowa? 

I was planning to include the script in the XOWA /xowa/bin directory. It would be up to the user to actually have Python on their system and run the script. If you get an executable, and it's reasonably small (< 5 MB), then I can include it in the xowa_app*.zip package directly. If it's larger, then maybe offer it as a download link (XOWA is pretty big at 60+ MB).

> If so, i can provide better formatted output for the statusbar at the bottom. But first some heavy testing as a seperate script is required!

If you want to do in-app integration, that would be great. I imagine XOWA would launch a Process, open a Stream to it, and print out messages from MWAD. This can wait a few weeks for direct integration, but we can include whatever you want, whenever you're ready.

Hope this helps. Thanks!

**Comment by Mattze96** [comment]
Yeah, sounds great!

Here is a first release: https://github.com/Mattze96/mwad/releases

I had serious troubles getting the bundler to work on windows. 
If i output the resulting xml-file uncompressed to stdout and the status updates to stderr, might be even better for the XOWA Process.
I thought also of rewriting it in java, but the xml and json parsing looks horrible...

**Comment by gnosygnu** [comment]
> Here is a first release: https://github.com/Mattze96/mwad/releases

Cool! Nice going! I tried it now, and it works great!

> but didn't hit the border with 4.49 MB. :)

Wow! Quite a surprise.

> If i output the resulting xml-file uncompressed to stdout and the status updates to stderr, might be even better for the XOWA Process and saves a lot of hard-disk memory.

Sounds good as an option. ;)

Keep in mind though I need to change the XOWA dump-parser to be more stream-friendly. Right now it parses the XML in chunks, but it's a pretty controlled envrionment.

I've been meaning to rewrite parts of the dump-parser to extract revision-id, so this should be good motivation to start soon.

Let me integrate mwad with XOWA's status bar for next week's release. If you get the output to stdout / stderr working by then, I'll take a crack at rewriting the importer.

> I thought also of rewriting it in java, but the xml and json parsing looks horrible...

I'm fine for using the Python version now. Translating to Java can always come later.

For what it's worth, I already do some API integration in XOWA: 
* Get original file sizes for images
* Get wiki metadata (list of namespaces, extensions, interwiki links, etc)

So I can probably integrate this into XOWA directly if the need ever arises.

Let me know if there's anything else. Otherwise great work again!

**Comment by Mattze96** [comment]
I've included the Xowa-mode in the latest commit. It is activated via the ```--xowa``` argument.
For debugging:

    ./mediawiki_api_dump.py --xowa http://wiki.archlinux.de/ --log mwad.log 2> /dev/null

Only outputs stdout and redirects stderr to /dev/null

    ./mediawiki_api_dump.py --xowa http://wiki.archlinux.de/ --log mwad.log 1> /dev/null

Only outputs stderr and redirects stdout to /dev/null

While in xowa mode, the console output is deactivated and the log-file-options has to be used. Customizing the status messages can be easily done, but later i plan to rewrite the progress-bar and -logger.

I will be offline for the next week, Good luck!

**Comment by gnosygnu** [comment]
I added mwad to tonight's release. I also provided a write-up at http://xowa.org/home/wiki/App/Import/mwad

I'll close out this issue in a week's time. Let me know if there's anything else you want to cover.

Thanks again for the great work!

**Comment by gnosygnu** [comment]
I know the status bar integration is still outstanding, but I'm going to go ahead and close out this issue. If I don't get it done in the next few releases, feel free to open up another issue to "encourage" me. :)
