### ISSUE TITLE
mw.wikibase.sitelink takes two parameters

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#665]
I was looking at `commons.wikimedia.org/wiki/Category:Paddy_Ashdown` and noticed down the left hand side are some links to other wikimedia sites. In this case showing links to 5 other sites.
The links (in xowa-gui) are of the form (for enwiki) `/site/en.wikipedia.org/wiki/Category:Paddy_Ashdown`
Note the namespace (Category:)

The equivalent mediawiki page shows only two links and the link is of the form `https://en.wikipedia.org/wiki/Paddy_Ashdown`
Note no namespace

On investigation, inside `Template:Wikidata Infobox` is a call to `Template:Wikidata Infobox/core` which has within it the line 

    {{#invoke:WikidataIB | getSiteLink | qid={{#invoke:WikidataIB |getQid |qid={{{qid|}}} }} | wiki={{#invoke:WikidataIB|siteID}}wiki}}
which for this page translates to

    {{#invoke:WikidataIB | getSiteLink | qid=Q333066 | wiki=enwiki}}
`Module:WikidataIB` function `getSiteLink` ulimately end up at the lines

	if wiki == "" then
		sitelink = mw.wikibase.sitelink(qid)
	else
		sitelink = mw.wikibase.sitelink(qid, wiki)
	end
Note that `mw.wikibase.sitelink` can have one or two parameters
this call ends up in xowa file 400_xowa\src\gplx\xowa\xtns\scribunto\libs\Scrib_lib_wikibase.java function `GetSiteLinkPageName`
I have made some changes to this function to allow for two parameters - which seems to make it work correctly

please see
[Scrib_lib_wikibase.zip](https://github.com/gnosygnu/xowa/files/4172232/Scrib_lib_wikibase.zip)

**Comment by gnosygnu** [comment]
As always, great investigation of issue and breakdown of fix! Wish I could say more, but want to say at least that you've done an amazing analysis and resolution (as usual!)

At any rate, thanks for the commit. Added it above with a test. Let me know if anything else. Thanks!
