### ISSUE TITLE
rendersnak(s) misbehaving

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#666]
Having built jawiki (2020-01-01) the log files show a number of errors of the form

    unknown enum key for wikibase; ..... enum=core.mainsnak key=1
Digging down to try and track this error it comes down to the fact that more info is coming from wikidata
A property is checked to see if it has references
each reference is then checked to see if it contains the text 'Wikipedia'
The Template:Infobox makes calls to Module:WikidataIB of the form

    local ref = mw.wikibase.renderSnaks(vr.snaks)
then xowa throws the error

Taking `ja.wikipedia.org/wiki/Sed_(コンピュータ)` as an example and its wikidata page Q305876
The property P3966 - programming paradigm

    , "P3966":
      [ 
        { "mainsnak":
          { "snaktype":"value"
          , "property":"P3966"
          , "hash":"d8416da594c033411bb39e3ff3ce7747622954c6"
          , "datavalue":
            { "value":
              { "entity-type":"item"
              , "numeric-id":187432
              , "id":"Q187432"
              }
            , "type":"wikibase-entityid"
            }
          }
        , "type":"statement"
        , "id":"Q305876$8010A53E-4A9A-4183-9595-53F111776BF0"
        , "rank":"normal"
        , "references":
          [ 
            { "hash":"fa278ebfc458360e5aed63d5058cca83c46134f1"
            , "snaks":
              { "P143":
                [ 
                  { "snaktype":"value"
                  , "property":"P143"
                  , "hash":"e4f6d9441d0600513c4533c672b5ab472dc73694"
                  , "datavalue":
                    { "value":
                      { "entity-type":"item"
                      , "numeric-id":328
                      , "id":"Q328"
                      }
                    , "type":"wikibase-entityid"
                    }
                  }
                ]
              }
            , "snaks-order":
              [ "P143"
              ]
            }
          ]
        }
      , 
        { "mainsnak":
          { "snaktype":"value"
          , "property":"P3966"
          , "hash":"03c5710789f3bde2396e15ba6e34b7a292c84bf1"
          , "datavalue":
            { "value":
              { "entity-type":"item"
              , "numeric-id":287472
              , "id":"Q287472"
              }
            , "type":"wikibase-entityid"
            }
          }
        , "type":"statement"
        , "id":"Q305876$E693DF4A-482F-4F1C-8992-6DA7501CD94C"
        , "rank":"normal"
        }
      ]
This property has two mainsnaks, the first one having on reference
This reference has a snak
This snak can be viewed as a dictionary {} contained within a one element array []
It is this one element array that is confusing xowa

The fix I have used is to assume that this is always a one element array and drill down one level

Please see
[Wdata_prop_val_visitor_.zip](https://github.com/gnosygnu/xowa/files/4174128/Wdata_prop_val_visitor_.zip)

**Comment by desb42** [comment]
Turns out it seems to apply specifically to rendersnaks (plural) not rendersnak

So my logic is in the wrong place

see below for another attempt
[Wdata_prop_val_visitor_.zip](https://github.com/gnosygnu/xowa/files/4174279/Wdata_prop_val_visitor_.zip)


An example where the

**Comment by gnosygnu** [comment]
Thanks for the detailed breakdown! It was of tremendous help, especially to track down the cause.

Regarding your commit, it works for ja.w, but I think it will fail in other wikis.

Basically, RenderSnaks needs to handle two forms:
* ```Key=P123,Val=Snak[]``` (as you have above)
* ```Snaks[]``` (as was the orginal version)

In terms of code:
* The main MediaWiki code snippet [is here](https://github.com/wikimedia/mediawiki-vendor/blob/4361929262cc87a08345c69a71258f59319be2c7/wikibase/data-model-serialization/src/Deserializers/SnakListDeserializer.php#L53-L68) 
* The XOWA counterpart is now this: https://github.com/gnosygnu/xowa/blob/f73164d55e70817bced6ab4bfea0dcc413008ddc/400_xowa/src/gplx/xowa/xtns/scribunto/libs/Scrib_lib_wikibase.java#L459

More details below the break. Let me know if you disagree. Thanks!

---

The MediaWiki code-path eventually leads to the line above:
* https://ja.wikipedia.org/wiki/Sed_(コンピュータ) is the problematic page
* Eventually it calls this function in https://ja.wikipedia.org/wiki/Module:WikidataIB
```
local sourced = function(claim)
	if claim.references then
		for kr, vr in pairs(claim.references) do
			local ref = mw.wikibase.renderSnaks(vr.snaks)
			if not ref:find("Wikipedia") then
				return true
			end
		end
	end
end
```
* This passes claims.references.snaks to lua's renderSnaks: https://github.com/wikimedia/mediawiki-extensions-Wikibase/blob/a07a6d0cc7f4c5d12a60042546cf302c3d55c836/client/includes/DataAccess/Scribunto/mw.wikibase.lua#L358
* Which then passes it to PHP's renderSnaks:
https://github.com/wikimedia/mediawiki-extensions-Wikibase/blob/351f8c4e49348556fb12ac83aeeb48133184ac10/client/includes/DataAccess/Scribunto/Scribunto_LuaWikibaseLibrary.php#L711
* Which eventually calls deserialize for the struct:
https://github.com/wikimedia/mediawiki-extensions-Wikibase/blob/68b16d27282821055680ada0255dcaeaca530e0b/client/includes/DataAccess/Scribunto/SnakSerializationRenderer.php#L74
* Which will eventually get deserialized by this specialized SnakList deserializer. Note the if case:
https://github.com/wikimedia/mediawiki-vendor/blob/4361929262cc87a08345c69a71258f59319be2c7/wikibase/data-model-serialization/src/Deserializers/SnakListDeserializer.php#L53

This function handles two forms of snakLists specified above

**Comment by desb42** [comment]
I thought it was going to be tricksy
In my searching of mediawiki code I did not see that deserialize
This is definitely a better fix

**Comment by gnosygnu** [comment]
Cool. Thanks!
