### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#668]
This is a very rare issue I stumbled across
Looking at `commons.wikimedia.org/wiki/File:England_in_the_UK_and_Europe.svg`
![outofbounds2](https://user-images.githubusercontent.com/861631/74587490-e5871c00-4fea-11ea-975d-7b3417aa81ab.jpg)
and hovering over `FakeSVG` - the popup logic is triggered
However reviewing the session log shows

    20200215_115137.598 failed to get popup: href=/wiki/Template:FakeSVG err=[err 0] <java.lang.ArrayIndexOutOfBoundsException> 0
    [trace]:
      gplx.xowa.parsers.Xop_parser.Parse_to_src_end(Unknown Source)
      gplx.xowa.htmls.modules.popups.Xow_popup_parser.Parse(Unknown Source)
      gplx.xowa.htmls.modules.popups.Xow_popup_mgr.Get_popup_html(Unknown Source)
      gplx.xowa.htmls.modules.popups.Xow_popup_mgr.Show_init(Unknown Source)
      gplx.xowa.htmls.js.Xoh_js_cbk.Popups_get_html(Unknown Source)
      gplx.xowa.htmls.js.Xoh_js_cbk.Invk(Unknown Source)
      gplx.Gfo_invk_.Invk_by_msg(Unknown Source)
      gplx.gfui.controls.standards.Gfui_html.Js_args_exec(Unknown Source)
      gplx.gfui.kits.swts.Swt_html_func.function(Unknown Source)
      org.eclipse.swt.browser.External.invokeFunction(Unknown Source)
      org.eclipse.swt.browser.External.callJava(Unknown Source)
      org.eclipse.swt.browser.External$4.method3(Unknown Source)
      org.eclipse.swt.internal.mozilla.XPCOMObject.callback3(Unknown Source)
      org.eclipse.swt.internal.win32.OS.DispatchMessageW(Native Method)
      org.eclipse.swt.internal.win32.OS.DispatchMessage(Unknown Source)
      org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
      gplx.gfui.kits.core.Swt_kit.Kit_run(Unknown Source)
      gplx.xowa.guis.Xoa_gui_mgr.Run(Unknown Source)
      gplx.xowa.apps.boots.Xoa_boot_mgr.Run_app(Unknown Source)
      gplx.xowa.apps.boots.Xoa_boot_mgr.Run(Unknown Source)
      gplx.xowa.Xoa_app_.Run(Unknown Source)
      gplx.xowa.Xowa_main.main(Unknown Source)

This can be 'fixed' by checking for a zero length `src` in Xop_parser.Parse_to_src_end
please see
[Xop_parser.zip](https://github.com/gnosygnu/xowa/files/4208430/Xop_parser.zip)

**Comment by gnosygnu** [comment]
Thanks for the detailed breakdown! Fixed with the commit above. Thanks!
