### ISSUE TITLE
Request for Offline Haitian  and/or French Wikipedia for Android App

### ISSUE THREAD

**Issue by NickRance** [gnosygnu/xowa#67]
Hi! I'm working with a non-profit that teaches literacy in Haiti using Android tablets. We're interested in installing Xowa with the French and Haitian wikipedias.  Would it be possible to have these languages prepped for offline use in the coming week?

Best Wishes,
Nick

**Comment by gnosygnu** [comment]
Hi! Glad to hear of your interest!

I'm working on Haitian now, and should have something ready by tonight or tomorrow for you to download and try. French is also running, but it will take longer as there are more GB to generate and upload to archive.org.

I'll post again here when I have Haitian ready. Let me know if you have any other comments or questions.

Thanks!

**Comment by gnosygnu** [comment]
Hey, I uploaded Haitian just now. Here are the steps to try it:

* Open XOWA Android
* Go to Download Central. If you haven't used it before, here is a step-by-step:
    * Press the Menu button in the upper-left hand corner
    * Press the XOWA item
    * Click on the "Down Arrow" icon at the top of the table
* In Download Central, click the "Down Arrow" next to the "Available" table. This will bring down the latest list of wikis.
* You'll see two new items at the bottom called "Kreyòl ayisyen Wikipedia". One is for article text (html) and the other is for images. Add them both to the queue by pressing the plus icon
* Run the Queue. When they're done, go back to the XOWA screen and select the wiki.

If you want to download them manually, you can grab them at https://archive.org/download/Xowa_htwiki_latest. You'll have to import them using the "folder" icon on the main XOWA page

Let me know if you have any questions. I spot-checked about 30 articles and they match the online version. Keep in mind some of the articles are not well-formatted. Here are some of the better pages I reviewed:
* https://ht.wikipedia.org/wiki/Simón_Bolívar
* https://ht.wikipedia.org/wiki/Leopoldo_López
* https://ht.wikipedia.org/wiki/Postila_Bètran
* https://ht.wikipedia.org/wiki/Fòs_Ayeryen_Swis
* https://ht.wikipedia.org/wiki/Aprann_pale_kreyòl_ayisyen
* https://ht.wikipedia.org/wiki/MINUSTAH
* https://ht.wikipedia.org/wiki/Ayiti
* https://ht.wikipedia.org/wiki/Karayib

I'm running French Wikipedia now. I figure it will take 1 day to generate, and 2 days to upload. So it should be ready sometime Monday, though it could slip to Tuesday / Wednesday if I run into issues. Let me know if you have a hard time constraint and I'll try to work something out (upload to google drive or elsewhere)

Again, thanks for the interest!

**Comment by NickRance** [comment]
Great, Thanks for the fast response! Our time constraint isn't hard so feel free to upload French wikipedia at your leisure.

**Comment by gnosygnu** [comment]
Just a quick update. French Wikipedia is uploading now, and should be ready by tomorrow morning. I'll post links and more info when everything's in place.

**Comment by gnosygnu** [comment]
I ran into an issue with the French Wikipedia upload. Basically, archive.org hiccupped, and I lost the entire upload. See https://archive.org/post/1060161/blank-page-when-editing-files-for-https-archiveorg-details-xowa_frwiki_latest

I'm reuploading again now. Unfortunately it takes a full 24 hours, so we're looking at Tuesday night. I'm going to try posting in smaller batches, so hopefully if archive.org fails again, I'll only lose some work, not all of it.

**Comment by gnosygnu** [comment]
French Wikipedia Articles is uploaded. You can try it out by doing either of the following:

* Opening Download Central and picking "Français Wikipedia - Articles (2016-07) [10.52 GB]"
* Downloading all the "Xowa_frwiki_2016-07_*" dbs (except for Xowa_frwiki_2016-07_file_*) from https://archive.org/download/Xowa_frwiki_latest

French Wikipedia Images are uploading now. This takes longer and probably won't be done until later 23:00 EST. I'll post again when done.

**Comment by gnosygnu** [comment]
French Wikipedia Images is uploaded. You can try it out by doing either of the following:

* Opening Download Central and picking "Français Wikipedia - Images (2016-07) [35.66 GB]"
* Downloading all the "Xowa_frwiki_2016-07_file_" dbs from https://archive.org/download/Xowa_frwiki_latest

Sorry about all the back and forth. Let me know if you have any questions.

Thanks again for the interest!

**Comment by gnosygnu** [comment]
Tonight's PC release officially supports the 2016-07 French Wikis, including French Wiktionary, Wikisource, Wikivoyage, etc.

The Android release already supports them. You have to click the "Download" button in "Download Central" to get the latest list of French Wikis.

I'm going to close out the ticket in the meantime. If you have any questions or issues, please feel free to reopen this issue.

Thanks!
