### ISSUE TITLE
hidden categories should also show the singular form

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#674]
Looking at `de.wikipedia.org/wiki/Kategorie:Datei:Commonsduplikat`
![plural](https://user-images.githubusercontent.com/861631/75606078-28fc8280-5ae1-11ea-8c4c-94266e68edee.jpg)
There is only one hidden category
But, xowa shows `Versteckte Kategorien` which is the plural
It should be `Versteckte Kategorie`

This stems from the file 400_xowa\src\gplx\xowa\addons\wikis\ctgs\htmls\pageboxs\doubles\Xoctg_double_grp.java
where there is the line:

    byte[] lbl_hidden = wiki.Msg_mgr().Val_by_id_args(Xol_msg_itm_.Id_ctg_tbl_hidden, count);
Id_ctg_tbl_hidden in 400_xowa\src\gplx\xowa\langs\msgs\Xol_msg_itm_.java refers to a link `hidden-category-category`, if this name is changed to `hidden-categories`
Then this will 'correct' the issue

`https://de.wikipedia.org/w/index.php?title=MediaWiki:Hidden-categories&action=edit` gives

    {{PLURAL:$1|Versteckte Kategorie|Versteckte Kategorien}}

**Comment by gnosygnu** [comment]
Great breakdown of issue. Made the change as you suggested. Thanks!
