### ISSUE TITLE
filename for class Pxd_itm_tz_abbr

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#676]
I have just noticed that on syncing with the latest xowa commits, I ran a compare (as I do) with my version to merge the changes.
One tiny difference (there are some big differences but that is not the point here)

The filename for the class Pxd_itm_tz_abbr is `Pxd_itm_tz_abbr .java` whereas in my version it is `Pxd_itm_tz_abbr.java` (xowa has an extra space character)
Up until now I did not know that java allowed a trailing space in the class name (as filename)

**Comment by gnosygnu** [comment]
Oops. Nice catch. Fixed above. Thanks!
