### ISSUE TITLE
ParserFunctions: Round numbers to default precision of 14 (decimal precision (numbers with more than 12 decimal places))

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#683]
In reviewing the errors generated by a full build of dewiki (2020-03-01) I came across this error

    20200316_142808.516 imap has invalid line: page=de.wikipedia.org/wiki/Nationalpark_Mu_Ko_Ang_Thong line=(2-2*((10)=1)-((00)>250)-((00)>25)))/3600 mod 180“</strong>° <strong class="error">Fehler im Ausdruck: Unerkanntes Wort „abs(3600*<span class="error">Breitengrad: DMS-Formatfehler</span> round

This does not seem related to the issue title; however ...

The wikitext makes a call to Template:Infobox_Nationalpark
one of the parameters to this is `latitude` with the value `9/31/15.064329981401556/N`
this internally calls `Template:Positionskarte` which in turn calls `Template:CoordinateLAT` which calls `Template:IstZahl` this is the problematic process

the actual wikitext is

    {{IstZahl|0{{#titleparts:{{{1|}}}|1|3}}|R+}}
The needed result is `1` (which is not happening)

Expanding this by hand the logic failing is

    {{#ifexpr:abs(015.064329981401556) = (015.064329981401556) | 1 }}
this number has 15 decimal places
Within xowa `abs(015.064329981401556)` results in `15.064329981402` which will not match the original value

changing the original latitude value to under 12 dp `9/31/15.06432998140/N` allows the page to display properly

I have not checked but I thought `java.math.BigDecimal` could cope with this

**Comment by gnosygnu** [comment]
Wow, amazing breakdown above! Pretty hard to get from the initial error all the way down to a decimal precision issue. Just to say it again (and it could never be said enough), I really appreciate the effort in getting from initial bug to actual cause. Great work!

Anyway, resolved with the commit above. Let me know if anything else.

Thanks!
