### ISSUE TITLE
Not an issue, just a question.

### ISSUE THREAD

**Issue by Ope30** [gnosygnu/xowa#69]
Sorry for making this topic, but since I may get more space in the next coming days, could you tell me where to get the up-to-date Wikipedias? I'm going to download the German and the English ones as soon as I have more space.

I'm aware, that this actually has nothing to do regarding the point of this topic, but I've went through several articles, and unfortunately some of them were missing atleast one image in the German one. I don't know why, but may be because I'm still using the 04.2016 ones?
You could check out Frédéric Chopin in the German one.

**Comment by gnosygnu** [comment]
> Sorry for making this topic,

No worries! Issues are fine for asking questions.

> but since I may get more space in the next coming days, could you tell me where to get the up-to-date Wikipedias? I'm going to download the German and the English ones as soon as I have more space.

The best way is to use XOWA 3.7.1.2 and go to Download Central. You can....
* Download automatically using Download Central. This will download the files from archive.org and place them in the appropriate path in /xowa/wiki/
* Download manually using Download Central Info. Each download has an "info" button which lists the underlying files. For example, see below for the files for English Wikipedia Articles at home/wiki/Special:XowaDownloadCentralInfo?task_id=3

If you haven't used Download Central before, you can access it with either the following:
* Go to Main Menu -> Tools -> Download Central
* Go to home/wiki/Special:XowaDownloadCentral)

Note that Download Central also works on Android.

> unfortunately some of them were missing atleast one image in the German one. I don't know why, but may be because I'm still using the 04.2016 ones?
You could check out Frédéric Chopin in the German one.

I checked now using the 2016-06 version, and the files are all good for de.wikipedia.org/wiki/Frédéric_Chopin. I post one screenshot below, but the rest of the page looks fine. Note that I checked both the text and html databases.

It's possible that it might be related to your 2016-04 version. I find that 1% of all images change any given month. Still, 1 per page is pretty high. Out of curiosity, which image is missing on the Chopin page? 

Also, if you have a chance, reload the Chopin page and go to home/wiki/Special:XowaSystemData?type=log_session . I get output like the below:

Let me know if there's anything else. Thanks!

```
http://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2016-06_core.zip
http://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2016-06_xtn.search.core.zip
http://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2016-06_html_ns.000.zip
http://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2016-06_html_ns.000_db.002.zip
http://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2016-06_html_ns.000_db.003.zip
http://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2016-06_html_ns.000_db.004.zip
http://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2016-06_html_ns.000_db.005.zip
http://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2016-06_html_ns.000_db.006.zip
http://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2016-06_html_ns.000_db.007.zip
http://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2016-06_html_ns.000_db.008.zip
http://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2016-06_html_ns.000_db.009.zip
http://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2016-06_html_ns.000_db.010.zip
http://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2016-06_html_ns.000_db.011.zip
http://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2016-06_html_ns.000_db.012.zip
http://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2016-06_html_ns.000_db.013.zip
http://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2016-06_html_ns.000_db.014.zip
http://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2016-06_html_ns.000_db.015.zip
http://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2016-06_html_ns.004.zip
http://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2016-06_html_ns.004_db.002.zip
http://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2016-06_html_ns.004_db.003.zip
http://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2016-06_html_ns.014.zip
http://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2016-06_html_ns.100.zip
```
![frederic_chopin_1](https://cloud.githubusercontent.com/assets/4994104/16715756/27a550f2-46b7-11e6-9e5f-30c213e056aa.png)

```
20160710_194430.347 page.load: url=de.wikipedia.org/wiki/Chopin
20160710_194430.397 page.async: url=de.wikipedia.org/wiki/Fr%C3%A9d%C3%A9ric_Chopin
20160710_194430.529 file.get: file=Disambig-dark.svg width=25 page=Frédéric_Chopin
20160710_194430.533 file.get: file=Frederic_Chopin_photo.jpeg width=-1 page=Frédéric_Chopin
20160710_194430.541 file.get: file=Chopins_Unterschrift.jpg width=-1 page=Frédéric_Chopin
20160710_194430.544 file.get: file=Chopin_1846_daguerreotypefix.JPG width=-1 page=Frédéric_Chopin
20160710_194430.547 file.get: file=Frederic_Chopin_-_Büste_-_KPM_(1).jpg width=-1 page=Frédéric_Chopin
20160710_194430.560 file.get: file=Poland_Zelazowa_Wola.jpg width=-1 page=Frédéric_Chopin
20160710_194430.563 file.get: file=Fridericus_Franciscus_Choppen.jpg width=-1 page=Frédéric_Chopin
20160710_194430.566 file.get: file=Chopin_herz.jpg width=-1 page=Frédéric_Chopin
20160710_194430.569 file.get: file=Kwiatkowski-chopin.jpg width=-1 page=Frédéric_Chopin
20160710_194430.573 file.get: file=Maria_Wodzińska.jpeg width=-1 page=Frédéric_Chopin
20160710_194430.585 file.get: file=Die_junge_George_Sand.jpg width=-1 page=Frédéric_Chopin
20160710_194430.590 file.get: file=Chopin_und_George_Sand_Skulpturen.jpg width=-1 page=Frédéric_Chopin
20160710_194430.599 file.get: file=Ostatnie_chwile_Fryderyka_Chopina.jpg width=-1 page=Frédéric_Chopin
20160710_194430.603 file.get: file=Frederic_Chopin_1849.jpg width=-1 page=Frédéric_Chopin
20160710_194430.615 file.get: file=Chopin_Berceuse.png width=-1 page=Frédéric_Chopin
20160710_194430.622 file.get: file=Moscheles-Chopin-Vergleich.png width=-1 page=Frédéric_Chopin
20160710_194430.634 file.get: file=Loudspeaker.svg width=12 page=Frédéric_Chopin
20160710_194430.637 file.get: file=Chopin_Grave_Grab_Pere_Lachaise.JPG width=-1 page=Frédéric_Chopin
20160710_194430.640 file.get: file=Chopin_zelazowa_wola.JPG width=-1 page=Frédéric_Chopin
20160710_194430.649 file.get: file=Commons-logo.svg width=-1 page=Frédéric_Chopin
20160710_194430.652 file.get: file=Wikiquote-logo.svg width=-1 page=Frédéric_Chopin
20160710_194430.654 file.get: file=Qsicon_lesenswert.svg width=24 page=Frédéric_Chopin
20160710_194430.657 redlink.redlink_bgn: page=Frédéric Chopin total_links=330
20160710_194430.731 redlink.redlink_end: redlinks_run=3
```

**Comment by Ope30** [comment]
Okay, cool! I'll do it through the Download Centre.
Regarding Chopin, the picture on the right was missing, the "Fotoportrait Chopins von Louis-Auguste Bisson" one. Fortunately I've found a solution for those, that are not connected to the web using Xowa. All you have to do is enable Web-Access, reload the article and you'll download the missing picture(s).

**Comment by gnosygnu** [comment]
> Regarding Chopin, the picture on the right was missing, the "Fotoportrait Chopins von Louis-Auguste Bisson" one. 

Thanks for the example. I checked all the changes for the article from late March till today: https://de.wikipedia.org/w/index.php?title=Fr%C3%A9d%C3%A9ric_Chopin&type=revision&diff=153262173&oldid=152916519 . None involved that File.

If you get a chance, can you try turning off Web-Access and looking at another missing-image page. Then...
* Check the log: home/wiki/Special:XowaSystemData?type=log_session 
* Reload the page. I've seen odd cases wherein the in-app browser doesn't pick up the first image on the page unless you reload it (XOWA returns the image before the in-app browser is ready)

> Fortunately I've found a solution for those, that are not connected to the web using Xowa. All you have to do is enable Web-Access, reload the article and you'll download the missing picture(s).

Yup, that works too. :)

**Comment by Ope30** [comment]
Sure, I've been doing it all the time. If I find any further articles with missing articles, I'll inform you as soon as I can.

**Comment by gnosygnu** [comment]
Cool. Let me know when you find a page with a missing image. Again, a log excerpt would be very helpful (home/wiki/Special:XowaSystemData?type=log_session ).

Otherwise, I'll close this issue in a week's time. Thanks.

**Comment by gnosygnu** [comment]
I'm going to go ahead and close this ticket. Let me know if you find an example of that missing image, and I'll reopen it again to troubleshoot. Thanks.
