### ISSUE TITLE
Root or Admin rights needed

### ISSUE THREAD

**Issue by WeaverStever** [gnosygnu/xowa#70]
While researching the copy/paste problem, I read a thread somewhere about a user having a problem with having to run the program as administrator/su. I had the same problem.

Here is what I found.
[err 0] /home/username/xowa/user/anonymous/app/tmp/log/current/**session.txt** (Permission denied)
[err 1] <io> file not found: url=/home/username/xowa/user/anonymous/app/tmp/log/current/**session.txt**

The session.txt file is owned by root, I used chown to take ownership of all of the files and directories recursively.

On Ubuntu...
sudo chown -R username:username /home/username/xowa

**Comment by gnosygnu** [comment]
Thanks for the note!

I vaguely remember this issue. I thought it had to do with that user's particular setup. I've personally not seen the issue, and I've installed XOWA on openSUSE, Mint, Ubuntu, Debian, RedHat and Raspberry Pi.

The session.txt file is created within XOWA and there isn't any different permissioning for it (i.e.: it's created just like any other file in XOWA). However, session.txt is created very early in the app boot process, so if there are any general permission issues, it would be the point of failure.

One guess is that maybe the entire "/xowa/" hive was owned by root because it was unzipped with root? Then when XOWA is run as username, it fails because it can't create "session.txt" in the root-owned hive.

Not sure what to do about this as I can't elevate filesystem permissions inside XOWA. Any input welcome.

**Comment by WeaverStever** [comment]
No, I did not have to elevate privileges to unpack, and the xowa directory is in my profile area, per the installation recommendation.  I did have issues while installing / using xowa.

1. Downloading and integrating en.wikipedia.org was more than a 24 hour process and my system locked up during the first attempt.  I increased my swap file to 5gb, which has improved my overall performance.
2. At this point, Xowa was working, but the Terminal window that launched it was throwing some (SWT?) errors that I did not document.
3. Due to the copy/paste problem (and the fact that my version of Chrome won't launch Iced Tea), I suspected that it was an issue with Java. I dropped the Ubuntu installer version of Java, re-installed Java and the new Eclipse from the prompt.  This was when the permission issue began exhibiting in the Terminal window.
4.  I checked the upper level directories, they are owned as expected, by my user profile. It isn't until I drilled deeply into the tree where I found the the log/current directory was owned by root.  I fumbled around with chown on the sub-directories (not understanding the chown parameters) until I went to the /xowa root and did the entire tree recursively -- just to be sure I got everything. 
5. I changed to Chrome after an Ubuntu update hosed up Firefox and I was already having problems with Flash content. I haven't switched back because all my passwords will need to be changed again.

Thanks  for offering up this great little project!

**Comment by gnosygnu** [comment]
Again, just replying inline.

> No, I did not have to elevate privileges to unpack

Ah, just a guess. Oh well.

> Downloading and integrating en.wikipedia.org was more than a 24 hour process and my system locked up during the first attempt. 

Just to make sure, you're downloading from "Import online", right? Not "Download Central"? I'm using the latter to make things "quicker" as imports have gotten longer with the recent search changes

> I increased my swap file to 5gb, which has improved my overall performance.

This is probably also a factor of the search changes. Swap file size is pretty transparent on Windows, and on Linux, I have it manually set to be a high number

> At this point, Xowa was working, but the Terminal window that launched it was throwing some (SWT?) errors that I did not document.

SWT sometimes shows unimportant messages. I'd only be concerned if the app crashes. Of course, if you see the message again, let me know, and I'll investigate

> Due to the copy/paste problem [extended list of events] ....

Yeah, honestly, I'm hoping that this is related to your setup. I'll try to bring down a vanilla Ubuntu install and do an install. If I run into anything like what you're describing, I'll investigate. If not, I'm not sure what to do. I've not run across these issues on my Linux boxes, but most of my XOWA installs are either (a) on a temporary live image or (b) if on a permanent machine, installed early (so it doesn't run afoul of anything else)

Thanks again for all the input.

**Comment by gnosygnu** [comment]
BTW: I forgot to update this issue. I did try a Live Disc for 64-bit Ubuntu 16.04 a few weeks ago, but I didn't run across the permissions issue. In case you're interested, I list the steps below.

Let me know if it recurs, or if there's anything to investigate.

Thanks.

-----

**Setting up Ubuntu boot disk**
* Downloaded 16.04 64-bit desktop from here: http://releases.ubuntu.com/16.04/ubuntu-16.04.1-desktop-amd64.iso
* Generated a bootable USB using Rufus USB installer: http://www.ubuntu.com/download/desktop/create-a-usb-stick-on-windows
* Booted up Ubuntu on my 64-bit box

**Installing XOWA**
* Launched terminal and ran following:
    * sudo apt-get update
    * sudo apt-get install default-jre
This brought down opendjk 1.8.
* Downloaded XOWA 3.7.3.1
* Unzipped to /home/ubuntu/xowa
* Launched XOWA with "sh xowa_linux_64.sh"

**Comment by WeaverStever** [comment]
Thanks for that.

I'm on Ubuntu 14.04 64 bit desktop,  I believe that my problem had something to do with my platform and a dependency that would not install properly.

I'll go ahead and close this, I suspect Ubuntu 16 will handle the Java dependencies better. I just don't want to disrupt my work platform right now.

Forgotten that I had open two threads, I close this.

**Comment by gnosygnu** [comment]
No worries! Let me know if it crops up again, and I'll definitely take another look. Thanks!
