### ISSUE TITLE
File: Add '.stl' and '.webp' as image extensions (unknown extensions)

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#710]
Page `en.wikipedia.org/wiki/House_with_two_rooms` is supposed to show two 'images'
I believe the reason is due to the file extension to these 'images'
The first one links to `wikipedia.org/wiki/File:Bing%27s_house.stl`

Note the extension is `.stl`

I believe that `400_xowa\src\gplx\xowa\files\Xof_ext_.java` is involved (and possibly others)
In rummaging I have found one further extension `.webp` that I think should also be added
(there may be more)

my version of Xof_ext_.java is attached
[Xof_ext_.zip](https://github.com/gnosygnu/xowa/files/4479851/Xof_ext_.zip)

**Comment by gnosygnu** [comment]
Thanks for the attached file! Made the change there, as well as a few other supporting files (see commit above)

Let me know if anything else. Thanks!
