### ISSUE TITLE
TemplateStyles: Support wrapper argument

### ISSUE THREAD

**Issue by gnosygnu** [gnosygnu/xowa#712]
As @desb42 pointed out in #704, TemplateStyles supports a wrapper argument

https://github.com/wikimedia/mediawiki-extensions-TemplateStyles/blob/master/includes/TemplateStylesHooks.php#L277

This results in the following mismatch in behaviors between XOWA and MW
* Load https://en.wikipedia.org/wiki/Buenos_Aires in HTTP_Server
* Examine source -> `.tmulti` is missing from TemplateStyles CSS at head (XOWA)

This ocurrs because TemplateStyles adds `.tmulti` by the following process:
* https://en.wikipedia.org/wiki/Buenos_Aires calls https://en.wikipedia.org/wiki/Module:Multiple_image
* On line 293, there is a code-block which calls TemplateStyles
```
	return frame:extensionTag {name = 'templatestyles', args = {src = 'Multiple image/styles.css', wrapper = ".tmulti"}}
		.. renderMultipleImages( frame )
		.. (autoscaledimages and '[[Category:Pages using multiple image with auto scaled images]]' or '')
		.. (nonautoscaledimages and '[[Category:Pages using multiple image with manual scaled images]]' or '')
```
* This results in https://en.wikipedia.org/wiki/Template:Multiple_image/styles.css being added to the CSS head, but without the `.tmulti` wrapper.

**Comment by gnosygnu** [comment]
Added with the commit above. Thanks @desb42 for reporting it!

**Comment by desb42** [comment]
Sorry, but not quite.
In the case of `en.wikipedia.org/wiki/Buenos_Aires` the `.tmulti` class needs to be added to each selector (like `.mw-parser-output`)
The wapper needs to be passed to the minify routine (where mw-parser-output is applied)

**Comment by gnosygnu** [comment]
Ah, didn't realize. Thanks for the catch!

Will fix today / tomorrow

**Comment by gnosygnu** [comment]
Fixed with the commit above. Moved XOWA-related CSS changes to new transformer class

Thanks again for the follow-up! Would've missed it otherwise!
