### ISSUE TITLE
page <title>

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#715]
looking at the main page of enwikivoyage `en.wikivoyage.org/wiki/Main_Page`
In mediawiki the \<title> is `Wikivoyage – The free worldwide travel guide that you can edit`
whereas for xowa it is `Main Page - XOWA`

Similarly for any other page (as an example `Thimphu – Travel guide at Wikivoyage`)
mediawiki \<title> is `Thimphu – Travel guide at Wikivoyage`
and xowa is `Thimphu – XOWA`

This only becomes noticeable in xowa-http

Researching, I have found two MediaWiki 'messages' that control this effect
`MediaWiki:Pagetitle` -> `$1 – Travel guide at {{SITENAME}}`
`MediaWiki:Pagetitle-view-mainpage` -> `{{SITENAME}} – The free worldwide travel guide that you can edit`

by modifying `400_xowa\src\gplx\xowa\htmls\Xoh_page_wtr_wkr.java`
and adding these few lines just before the `fmtr.Bld_bfr_many`

    Xow_msg_mgr msg_mgr = wiki.Msg_mgr();
    byte[] page_mask_msg = Bry_.new_a7("pagetitle");
    if (Bry_.Eq(Xoa_ttl.Replace_unders(page.Ttl().Raw()), wiki.Props().Main_page()))
        page_mask_msg = Bry_.new_a7("pagetitle-view-mainpage");
    page_name = msg_mgr.Val_by_key_args(page_mask_msg, page_name);

should make it work across all wikis

**Comment by gnosygnu** [comment]
Great detail as always!

* Made a few more changes than needed, but primarily because I wanted to clean the code a little and put it under tests.
* Also, made a 2nd fix commit b/c I didn't realize that the 1st commit was being wrong applied to GUI tabs also (it makes the SWT/GUI tab names very long)

Let me know if anything else. Thanks!

**Comment by desb42** [comment]
Looks good.

Unfortunately, I cannot apply this fix in quite the same way
I have made a number of changes to the 'page' generation over time (Xoh_page_wtr_wkr.java)
Some of which are:
1) Add logic to display heading for wikidata (which is quite convoluted)
2) always display `Firstheader` - the css on page should cope with hiding it if necessary
3) commons has a Data: namespace - when .tab show a table
4) added a printfooter for a javascript hook in wikisource (and possibly other wikis)

I realise that all these bits of code could be extracted into classes of their own. This is more of a playground for ideas that somehow need to be integrated into the main build

**Comment by gnosygnu** [comment]
> Some of which are:
> 1. Add logic to display heading for wikidata (which is quite convoluted)
> 2. always display Firstheader - the css on page should cope with hiding it if necessary
> 3. commons has a Data: namespace - when .tab show a table
> 4. added a printfooter for a javascript hook in wikisource (and possibly other wikis)

Yeah, sorry, I'm sure I've been long overdue in responding to those issues. Feel free to bump any of them in priority (or just picking them from the list above) and I'll prioritize higher.

Otherwise, thanks!
