### ISSUE TITLE
xowa_get_and_make.sh

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#718]
This build process does not seem to work anymore
I suspect the new *Test.java classes introduced with the intelliJ build system

**Comment by gnosygnu** [comment]
Oops. Forgot that the file needed new updates due to Test changes.

Also, needed to bump JDK to 8. Still need to handle general JDK #709 issues as well as Maven's #706 , but closing this for now. Let me know if any issues.

Thanks!

**Comment by desb42** [comment]
works for me

**Comment by gnosygnu** [comment]
Cool! Thanks for the confirm!
