### ISSUE TITLE
HTML_dumps: Categories div should be at bottom of page

### ISSUE THREAD

**Issue by gnosygnu** [gnosygnu/xowa#722]
As reported in #694

>> The second reason (I know it's not really a big deal) is that when using HTML, the categories in a category change positions so that they are at the top instead of at the bottom (in the original, they are at the bottom).

> Ugh. Okay, that's a bug also (checked now with en.wikipedia.org/wiki/Category:Earth). I think that requires just a little extra code, but I remember there was some sort of problem with that. Will create an issue later.

**Comment by desb42** [comment]
I came across this issue a while ago (when enhancing categories)

I basically commented out the whole of the if statement starting `if (load_ctg)` in `400_xowa\src\gplx\xowa\htmls\core\Xow_hdump_mgr__load.java`
and removed the `ctgs_len` check in `400_xowa\src\gplx\xowa\htmls\Xoh_page_wtr_wkr.java`

**Comment by gnosygnu** [comment]
Ah, interesting! Let me give that a try and update tomorrow-ish. Thanks!

**Comment by gnosygnu** [comment]
> I basically commented out the whole of the if statement starting if (load_ctg) in 400_xowa\src\gplx\xowa\htmls\core\Xow_hdump_mgr__load.java

Cool. That definitely works. Have to remember why I put that there

> and removed the ctgs_len check in 400_xowa\src\gplx\xowa\htmls\Xoh_page_wtr_wkr.java

Just so you know, this didn't make a difference on my side. This class gets called during the parse-wikitext stage, so it won't be in the show-html-from-static-db stage 

I was able to make the change with a few fixes to Xow_hdump_mgr__load. Will post a commit tomorrow-ish.

Thanks!

**Comment by gnosygnu** [comment]
Fixed with the commit above. For now, no tests as the code is unfortunately monolithic. However, did verify with https://en.wikipedia.org/wiki/Category:Earth and https://en.wikipedia.org/wiki/Earth in both Wikitext and Hdump modes

Thanks again @Ope30 and @desb42!
