### ISSUE TITLE
right to left language tab display

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#723]
Looking at `he.wikipedia.org/wiki/עמוד ראשי` - the main page of the Hebrew wiki
The tabs are displayed as
![rtl1](https://user-images.githubusercontent.com/861631/81796689-b444bc00-9505-11ea-8ac0-6c3f62b67dab.jpg)

Apart from the fact that they are in English (see #278), they are in the wrong order
They should be
![rtl2](https://user-images.githubusercontent.com/861631/81797396-a3487a80-9506-11ea-98c8-a9d33dfcbdbc.jpg)

At some point in the past this effect seems to have been achieved by reversing the list of tabs when generating the page

Now this effect is achieved with CSS

So the reversing logic in `400_xowa\src\gplx\xowa\htmls\portal\Xow_portal_mgr.java` [Reverse_li] is no longer required

**Comment by gnosygnu** [comment]
Thanks for the breakdown! Will also fix in next day or so!

```
private byte[] Reverse_li(byte[] bry) {
		return lang_is_rtl ? Xoh_rtl_utl.Reverse_li(bry) : bry;
	}
```

**Comment by gnosygnu** [comment]
Resolved with the commit above. Thanks again for the fix!
