### ISSUE TITLE
Release: Change default download server from dumps.wikimedia.your.org to dumps.wikimedia.org

### ISSUE THREAD

**Issue by gnosygnu** [gnosygnu/xowa#727]
I was doing a build for simple.wikipedia and noticed that the default server of your.org is down.

For now, I'm going to default back to the official download site of wikimedia.org

Option link for reference: home/wiki/Special:XowaCfg?grp=xowa.bldr.general

**Comment by desb42** [comment]
it seems that your.org is back (not sure when it came back, but it has been down a while
