### ISSUE TITLE
title is invalid: any.wiki*.org

### ISSUE THREAD

**Issue by markusmaresch** [gnosygnu/xowa#73]
Upgraded to 3.7.4.1
Never used upgrade central before  - always downloaded updates via archive.org and 7z ..
Have a list of several en.* and de.* Wikis in left side tab
Upon clicking on any of them, I get: title is invalid: name.of.wiki.org .. in the bottom line - and it does not work.
Download Central does not fix it for simple.wikipedia.org ..

I have about 250GB's of wiki's ... don't want to reload all of them ..
Thanks for the help !

<img width="1092" alt="xowa_title_is_invalid" src="https://cloud.githubusercontent.com/assets/13298571/17279645/ca09341c-5779-11e6-9081-036e1a7c1ecf.png">

**Comment by markusmaresch** [comment]
However, going to: home/wiki/Special:XowaPageHistory and clicking on individual entries works just fine.

**Comment by gnosygnu** [comment]
Hi! Thanks for opening the issue!

This is a pretty embarrassing bug. I broke it during a recent release. It'll be fixed in tonight's release (within the next 4 or 5 hours)

I'll post here again when it's out.

Thanks!

**Comment by gnosygnu** [comment]
One other thing. You can still navigate around by using the URL bar. For example, enter in "de.wikipedia.org" directly into the URL bar and press enter. Also, if you're curious, "de.w" also works, as well as as "de.w:Erde"

Unfortunately, this is how I always get around. That's why I didn't notice the bug.

**Comment by gnosygnu** [comment]
Tonight's [release](https://github.com/gnosygnu/xowa/releases/tag/v3.8.1.1) resolves this fix. Let me know if there's anything else. Otherwise, I'll close this issue out within a few days.

Thanks again for the report.

**Comment by markusmaresch** [comment]
confirmed fixed.
Thanks for the quick fix !!

**Comment by gnosygnu** [comment]
No problem! Thanks for the quick confirmation! :)
