### ISSUE TITLE
HTML: nullPointerException in Xoh_html_wtr

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#730]
Have just built enwikibooks (2020-05-01) and have two pages reporting a nullPointerException

`en.wikibooks.org/wiki/Japanese/Introduction`
`en.wikibooks.org/wiki/XML_-_Managing_Data_Exchange/DocBook`
The line of failure is 375
for the first page it seems the tag `<rtc>` is involved
and the second `<figure>`

In the source to Xoh_html_wrt.java just above the error line is the comment

    // added new tags below; ISSUE#:636 DATE:2020-03-08

If I change these two tags to call

    Write_xnde(bfr, ctx, hctx, xnde, tag, tag_id, src);
instead - it seems to work

**Comment by gnosygnu** [comment]
Thanks for the report! It turns out that this was broken as part of #636

Fixed now, and added a nominal test. Thanks again!
