### ISSUE TITLE
Static html dump

### ISSUE THREAD

**Issue by sammyizimmy** [gnosygnu/xowa#739]
I need to create a static html dump of a wiki that is already in xowa.
Basically like the DumpHTML extension for mediawiki, producing html files that one can "browse" on a device that has only a web browser.

Is there functionality built in xowa that can do it? Or do I need to use other tricks like "xowa in server mode + wget crawler"? 

Please provide a working example.
Reward: 0.003btc(25usd) to the address of your choice. (If no address is provided it will be sent to gnosygnu)

Thanks.

**Comment by gnosygnu** [comment]
Hey, thanks for the interest in XOWA! Sorry for the late reply, but my email has been weird recently.

> Is there functionality built in xowa that can do it?

If you're looking to just use static `.html` files, then there is no built-in functionality to do it

Keep in mind that static `.html` files have a few complications:
* **Disk space usage**: Each file takes up extra space. If your hard drive's sector size is 64kb, then even a 1kb file will take up 64 kb
* **Special pages**: Wikipedia has Special pages which will take effort to reproduce in a static environment. For example, Search / Random.
* **Portal / Chrome**: (minor) Wikipedia has a chrome (the left navbar; top tabs) which is sometimes dynamic per page
* **Images**: (minor) If you're using a browser for offline reading, then you would have to store the images in some relative root. This adds a lot of "complication" to the initial set-up, and some "brittleness" to the whole solution

If you do want to try to generate static `.html` files with XOWA, it would involve the following high-level steps:
* Use the command-line to generate an offline HTML dump in SQLite databases. See: http://xowa.org/home/wiki/Dev/Command-line/Dumps
* Write some code to do `SELECT`s against the SQLite databases and generate your static HTML files. You'd probably want to look at the following
  * `core` database: Has `page` table with id / title of page
  * `html` databases: Has `html` tables which stores the generated HTML by page_id
    * The HTML is mostly the same as the actual Wikipedia HTML, except for the bugs in XOWA's parser.
    * Keep in mind you probably want to change the compression method during the command-line step. See `// compression method for html: 1=none; 2=zip; 3=gz; 4=bz2`
* (Complicated) If you want images, write more code to handle generation of relative-path urls to the image.
  * Note that for system portability, XOWA uses its own custom format to store image information

If you have questions on the above, feel free to comment, and I'll try to point out where to look.

In my opinion though, if you can use XOWA files (and the XOWA jar), then that would probably be best. XOWA can run on systems as low as a Raspberry Pi, and just needs a working installation of Java 8 and SQLite.

Hope this helps!

**Comment by sammyizimmy** [comment]
Thanks for the detailed reply.
So, I tried creating a HTML dump as described in [Command-line/Dumps](http://xowa.org/home/wiki/Dev/Command-line/Dumps).
Below is the GFS I tried to dump an existing 25,000 page wiki named _gameoorg-20200328-wikidump_ .
```
app.bldr.pause_at_end_('n');
app.scripts.run_file_by_type('xowa_cfg_app');
app.cfg.set_temp('app', 'xowa.app.web.enabled', 'y');
app.cfg.set_temp('app', 'xowa.bldr.db.layout_size.text', '0');
app.cfg.set_temp('app', 'xowa.bldr.db.layout_size.html', '0');
app.cfg.set_temp('app', 'xowa.bldr.db.layout_size.file', '0');
app.bldr.cmds {
  // v2 html generator; allows for multi-threaded / multi-machine builds
  add     ('gameoorg-20200328-wikidump' , 'wiki.mass_parse.init') {cfg {ns_ids = '0|4|14|8';}}
  add     ('gameoorg-20200328-wikidump' , 'wiki.mass_parse.exec') {
    cfg {
      manual_now = '2020-02-01 01:02:03';      
      num_wkrs = 4;
      indexer_enabled = 'n';      
      load_all_templates = 'y';    
      load_all_imglinks = 'n'; 
      cleanup_interval = 50;
    }
  }
  add     ('gameoorg-20200328-wikidump' , 'wiki.mass_parse.make');
}
app.bldr.run;
```
Xowa output when running the above GFS.
```
version: 4.6.5.1911; build date: 2019-11-25 23:19:43

arguments:
  [0] = '--cmd_file'
  [1] = './html.gfs'

SplashScreen.getSplashScreen() returned null
cmd bgn: wiki.mass_parse.init
cmd end: wiki.mass_parse.init 261f
cmd bgn: wiki.mass_parse.exec
initing wkrs
```
Xowa hung at **initing wkrs** and did not continue. 

I was starting to feel a bit like maybe there is no quick way of doing the task I wanted. But your comment about querying the SQLite database got my brain running in a different direction.

Does the core.xowa file contains all the page titles? Yes it does! So I dumped the titles from namespace 0(articles) and 6(File pages) to _articles.txt_ and _files.txt_.
Next I prepended each line in the resulting files with the Xowa server path.
Then merge both _articles.txt_ and _files.txt_ to _urls.txt_.
Next, fire up Xowa in server mode ```java -Xmx1256m -jar xowa_linux_64.jar --app_mode http_server```
Then ```wget -p -k -nc -i urls.txt``` downloads each page with dependencies for offline viewing from the Xowa server.
Boom! Works great! I now have a static HTML dump of all the articles and file pages.

Here is a quick shell script I whipped up to automate things a bit.
```
#!/bin/bash 
WIKIFILESPATH="/home/classic/programs/xowa_v4.6.5/wiki/gameoorg-20200328-wikidump/"
WIKINAME="gameoorg-20200328-wikidump"
HOST="127.0.0.1:8080"

#dump all pages to files
sqlite3 -readonly $WIKIFILESPATH/"$WIKINAME-core.xowa" "SELECT page_title from page WHERE page_namespace=0" > ./articles.txt
sqlite3 -readonly $WIKIFILESPATH/"$WIKINAME-core.xowa" "SELECT page_title from page WHERE page_namespace=6" > ./files.txt

#prepend xowa server address to files
sed -i -e "s/^/http:\/\/$HOST\/$WIKINAME\/wiki\//" ./articles.txt
sed -i -e "s/^/http:\/\/$HOST\/$WIKINAME\/wiki\/File:/" ./files.txt

#Manual add Main Page
echo "http://$HOST/$WIKINAME/Main_Page" >> ./articles.txt

#Merge files
cat ./articles.txt ./files.txt  > ./urls.txt

#Download files for offline viewing
wget -p -k -i ./urls.txt

#Clean up
rm ./articles.txt ./files.txt ./urls.txt

echo "Done, point browser to file://$(pwd)/$HOST/$WIKINAME/Main_Page"
```

Thanks a bunch for your work, all I need yet is your bitcoin address!

**Comment by gnosygnu** [comment]
Hey, sorry for the late supply, but my phone is still weird with email notifications.

Regarding the failed GFS script. Thanks first for the script and the output. Not sure why the script hung. Is the `gameoorg` xml dump anywhere for download? I can take a look at it on my end.

Otherwise, the script looked fine.

> Here is a quick shell script I whipped up to automate things a bit.

Cool, glad to hear it works! Nice ingenuity in whipping together an alternate solution :+1:

> Thanks a bunch for your work, all I need yet is your bitcoin address!

Embarrassingly, I don't have a bitcoin address. I'll pick one up later this week, and drop it here.

Thanks!

**Comment by sammyizimmy** [comment]
The xml dump was generated by [wikiteam](https://github.com/WikiTeam/wikiteam) from [gameo.org](https://gameo.org/index.php?title=Welcome_to_GAMEO)
Tip sent via paypal.

Thanks.

**Comment by AiliAili** [comment]
@sammyizimmy 
Hi sammyizimmy, 
I am doing the same thing as you: getting the static html for all articles.
I am wondering can we open the HTML file in a browser not relying on XowA interface?
Thank you

**Comment by gnosygnu** [comment]
Sorry, forgot about the bitcoin account. Thanks for the paypal tip though! Good luck!

@AiliAili 
Hey, I wrote a detailed reply further above: https://github.com/gnosygnu/xowa/issues/739#issuecomment-639468117 . In short, you can use the command-line to generate `.xowa` with static HTML and then run SQL against the `.xowa` files to extract the HTML. Hope it helps!

**Comment by AiliAili** [comment]
@gnosygnu thank you. I will try as you suggested.

**Comment by AiliAili** [comment]
@gnosygnu Thank you for pointing out the direction to Dev/Command-line/Thumbs. From this website, http://xowa.org/home/wiki/Dev/Command-line/Thumbs, it says we first build commons database and wikidata database, followed by the actual English Wikipedia if I am building English Wikipedia. Based on my progress now, I see that the provided script first download the latest commons and wikidata. What if I want to build English Wikipedia from a historical dump, such as a dump from 20190120. 

I saw the line: manual_now = '2020-02-01 01:02:03'. Does it mean it will retrieve the 20200201 dump?
Thank you : )

**Comment by gnosygnu** [comment]
> What if I want to build English Wikipedia from a historical dump, such as a dump from 20190120.

It's possible, but you'll need to have all the dump files from that date. Note that includes 'pages-articles', 'categorylinks', 'page_props', 'image', 'pagelinks', and 'imagelinks'.

The official dump source (https://dumps.wikimedia.org/enwiki/) only goes back to `20200401` so you would have to find a source that has all those files

> I saw the line: manual_now = '2020-02-01 01:02:03'. Does it mean it will retrieve the 20200201 dump?

Nope. The actual download command is `add     ('en.wikipedia.org' , 'util.download')         {dump_type = 'pages-articles';}` By default it will download the "latest" version at https://dumps.wikimedia.org/enwiki/. If you want a specific date, you can do `add     ('en.wikipedia.org' , 'util.download')         {dump_type = 'pages-articles'; dump_type = '20200401'}` but you have to make sure the date actually exists at `dumps.wikimedia.org`

For `manual_now = '2020-02-01 01:02:03`, this just tells XOWA to pretend that the current date and time is `2020-02-01 01:02:03` when it generates the HTML. Some pages refer current day (such as "On this day"), and I wanted the entire HTML dump to have the same date / time

**Comment by AiliAili** [comment]
Thank you soooo much for your timely reply. I will follow your instructions. I have another minor question:
How can I get the HTML from the generated SQLite database if the above process succeed, given the page id or page title?
Thank you again.

**Comment by gnosygnu** [comment]
> How can I get the HTML from the generated SQLite database if the above process succeed, given the page id or page title?

So first, I'd recommend you start with simplewiki as it's much quicker to generate (less than 5 hours).

To get the HTML, you'd have to write a SQL query that pulls `page_id` from the `page` table in the `core.xowa` database. Note that `page_title` is in that same `page` table. Then, with that `page_id`, you'd pull the HTML from the `html` table in any of the `html` databases

Hope that helps. Thanks!

**Comment by AiliAili** [comment]
Following instructions from http://xowa.org/home/wiki/Dev/Command-line/Thumbs, I encountered issues in building simple Wikipedia.
When the version is 1,  the following occurs:
cmd bgn: file.fsdb_make
error while executing script: err=[err 0] <gplx> could not find atr file: dir=/media/user/Elements/xowa_app_linux_64_v4.6.5.1911/file/simple.wikipedia.org-prv/ mnt=fsdb.main
[err 1] <bldr> unknown error: key=file.fsdb_make
[err 2] <bldr> unknown error
[trace]:
  gplx.fsdb.Fsdb_db_mgr__v1.Get_atr_db_url(Unknown Source)
  gplx.fsdb.Fsdb_db_mgr__v1.<init>(Unknown Source)
  gplx.xowa.addons.bldrs.files.cmds.Xobldr__fsdb_db__create_data.new_src_bin_db_mgr(Unknown Source)
  gplx.xowa.addons.bldrs.files.cmds.Xobldr__fsdb_db__create_data.Cmd_bgn(Unknown Source)
  gplx.xowa.bldrs.Xob_bldr.Run(Unknown Source)
  gplx.xowa.bldrs.Xob_bldr.Invk(Unknown Source)
  gplx.langs.gfs.GfsCore_.Exec(Unknown Source)
  gplx.langs.gfs.GfsCore_.Exec(Unknown Source)
  gplx.langs.gfs.GfsCore_.Exec(Unknown Source)
  gplx.langs.gfs.GfsCore.ExecOne_to(Unknown Source)
  gplx.xowa.apps.gfs.Xoa_gfs_mgr.Run_str_for(Unknown Source)
  gplx.xowa.apps.gfs.Xoa_gfs_mgr.Run_str_for(Unknown Source)
  gplx.xowa.apps.gfs.Xoa_gfs_mgr.Run_url_for(Unknown Source)
  gplx.xowa.apps.gfs.Xoa_gfs_mgr.Run_url(Unknown Source)
  gplx.xowa.apps.boots.Xoa_boot_mgr.Run_app(Unknown Source)

When I changed to version 2, the following occurs:
error while executing script: err=[err 0] <gplx> fsdb.make:source fsdb not found: version=v2 url=/media/user/Elements/xowa_app_linux_64_v4.6.5.1911/wiki/simple.wikipedia.org/prv/
[err 1] <bldr> unknown error: key=file.fsdb_make
[err 2] <bldr> unknown error
[trace]:
  gplx.xowa.addons.bldrs.files.cmds.Xobldr__fsdb_db__create_data.new_src_bin_db_mgr(Unknown Source)
  gplx.xowa.addons.bldrs.files.cmds.Xobldr__fsdb_db__create_data.Cmd_bgn(Unknown Source)
  gplx.xowa.bldrs.Xob_bldr.Run(Unknown Source)
  gplx.xowa.bldrs.Xob_bldr.Invk(Unknown Source)
  gplx.langs.gfs.GfsCore_.Exec(Unknown Source)
  gplx.langs.gfs.GfsCore_.Exec(Unknown Source)
  gplx.langs.gfs.GfsCore_.Exec(Unknown Source)
  gplx.langs.gfs.GfsCore.ExecOne_to(Unknown Source)
  gplx.xowa.apps.gfs.Xoa_gfs_mgr.Run_str_for(Unknown Source)
  gplx.xowa.apps.gfs.Xoa_gfs_mgr.Run_str_for(Unknown Source)
  gplx.xowa.apps.gfs.Xoa_gfs_mgr.Run_url_for(Unknown Source)
  gplx.xowa.apps.gfs.Xoa_gfs_mgr.Run_url(Unknown Source)
  gplx.xowa.apps.boots.Xoa_boot_mgr.Run_app(Unknown Source)
  gplx.xowa.apps.boots.Xoa_boot_mgr.Run(Unknown Source)
  gplx.xowa.Xoa_app_.Run(Unknown Source)

I don't know how to fix this issue.
Do you have any ideas? (I strictly followed the command lines) 

Thank you.

**Comment by gnosygnu** [comment]
> Following instructions from http://xowa.org/home/wiki/Dev/Command-line/Thumbs, I encountered issues in building simple Wikipedia.
> When the version is 1, the following occurs:

Sorry, I think that's bad documentation on my side. Can you try commenting it out? Specifically:

```
    // specify whether original wiki databases are v1 (.sqlite3) or v2 (.xowa)
   // src_bin_mgr__fsdb_version = 'v1';
```

**Comment by gnosygnu** [comment]
Updated doc to comment out line and mark it deprecated. Let me know if you're still having issues. Thanks.

http://xowa.org/home/wiki/Dev/Command-line/Thumbs
