### ISSUE TITLE
trying to run xowa from a mounted hdd 

### ISSUE THREAD

**Issue by anon11111** [gnosygnu/xowa#74]
root is encrypted, this could be a permissions issue 

OS: linux
Java: 1.7.0_101 (64 bit)
Java path: /usr/lib/jvm/java-7-openjdk-amd64/jre
XOWA: 3.7.3.1
XOWA path: /media/tb1/xowa/xowa_linux_64.jar

Error: XPCOM error 0x80004005
Stack: org.eclipse.swt.browser.Mozilla.error(Unknown Source)
org.eclipse.swt.browser.Mozilla.initXULRunner(Unknown Source)
org.eclipse.swt.browser.Mozilla.create(Unknown Source)
org.eclipse.swt.browser.Browser.<init>(Unknown Source)
gplx.gfui.kits.swts.Swt_html.<init>(Unknown Source)
gplx.gfui.kits.core.Swt_kit.New_html(Unknown Source)
gplx.xowa.guis.views.Xog_tab_itm.Make_html_box(Unknown Source)
gplx.xowa.guis.views.Xog_tab_mgr.Tabs_new(Unknown Source)
gplx.xowa.guis.views.Xog_tab_mgr.Tabs_new_init(Unknown Source)
gplx.xowa.guis.views.Xog_launcher_tabs.Launch_tab(Unknown Source)
gplx.xowa.guis.views.Xog_launcher_tabs.Restore_tab_failover(Unknown Source)
gplx.xowa.guis.views.Xog_launcher_tabs.Launch(Unknown Source)
gplx.xowa.guis.views.Xog_tab_itm_read_mgr.Launch(Unknown Source)
gplx.xowa.guis.Xoa_gui_mgr.Run(Unknown Source)
gplx.xowa.apps.boots.Xoa_boot_mgr.Run_app(Unknown Source)
gplx.xowa.apps.boots.Xoa_boot_mgr.Run(Unknown Source)
gplx.xowa.Xoa_app_.Run(Unknown Source)
gplx.xowa.Xowa_main.main(Unknown Source)

**Comment by anon11111** [comment]
Alternatively, is there a way to launch xowa on root (since it seems to need everything that's on root) and store additional wiki pages on an external drive?

**Comment by WeaverStever** [comment]
I had a permissions problem a few weeks ago.  As a user, I could not write to session.txt 

file not found: url=/home/username/xowa/user/anonymous/app/tmp/log/current/session.txt

The session.txt file and some directories above were owned by root. I tried walking up the tree, but did not document (I was having other issues), I finally took ownership of the entire structure.  

On Ubuntu...
sudo chown -R username:username /home/username/xowa

**Comment by gnosygnu** [comment]
@anon11111: Usually, Error: XPCOM error 0x80004005 means that XULRunner doesn't work. For example, I've seen this happen when running on systems without GTK2. I've also seen it happening on systems wherein the existing Firefox libs conflict with the XULRunner ones.

If it doesn't work after granting root permissions, then make sure you're using the .sh file. From the command-line, you can do <code>export SWT_GTK3=0 && java -Xmx256m -jar /XOWA_DIR/xowa_linux_64.jar</code> where XOWA_DIR is wherever you placed it.

If it does work after granting root permissions as per WeaverStever (@WeaverStever : Thanks!) then let me know. I'll update the readme.txt to list it as a troubleshooting option.

For what it's worth, I tried denying the entire /xowa/bin/ and /xowa/user/ hive to users. When I run it, I get the error:

```
app launch failed: [err 0] <java.awt.HeadlessException> 
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
[trace]:
````

Hope this helps.

**Comment by gnosygnu** [comment]
I'm going to mark this issue as answered for now. @anon11111 : let me know if there's anything else. Otherwise, I'll close this issue out in a few days. Thanks.

**Comment by anon11111** [comment]
Hey I ended up just moving the program to the os hdd and storing the wikis on the external cause I found import offline instructions to do that, I think the issue was just the program uses firefox and other linux programs in order to boot and being alone on an external it couldnt find those programs

**Comment by gnosygnu** [comment]
Sorry @anon11111. Forgot to reply to your comment. But it sounds like you managed to get it going.

I'm marking this issue closed for now. Feel free to reopen if if there's anything else related. Thanks.
