### ISSUE TITLE
a couple of css minify issues

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#741]
I have just come across a couple of minify issues as a result of building itwiki

taking page `it.wikipedia.org/wiki/help:Tutorial/Discussione`

The first issue is StringIndexOutOfBoundsException.
This is due to a blank comment in the template (ie `/**/`)
and the second is that the mechanism to add `.mw-parser-output` to all selectors is not quite right

In the example page the original text is

    .avviso .mbox-text-div>div,.avviso .mbox-text-full-div>div{font-size:90%} ...
Note the comma
The current implementation does this

    .mw-parser-output .avviso .mbox-text-div>div,.avviso .mbox-text-full-div>div{font-size:90%} ...
it should do

    .mw-parser-output .avviso .mbox-text-div>div,.mw-parser-output .avviso .mbox-text-full-div>div{font-size:90%} ...

attached are my suggestions (a bit of a hack in XoCssTransformer.java)
[css.zip](https://github.com/gnosygnu/xowa/files/4740527/css.zip)

**Comment by desb42** [comment]
With further investigation more work was needed
page `en.wikipedia.org/wiki/Portal:Islam` demonstrates a number of other Templatestyle issues

attached is a revised class
[XoCssTransformer.zip](https://github.com/gnosygnu/xowa/files/4742004/XoCssTransformer.zip)

**Comment by gnosygnu** [comment]
Thanks for the full detail!

Made a commit to handle the `StringIndexOutOfBoundsException`. Changed the approach a little to use a `JsString_.charAt`-like method so that the code matches `cssmin.js` more closely

Am looking at other item

**Comment by gnosygnu** [comment]
Thanks for the commit! Changed PrependSelector a bit to reduce some argument-duplication, as well as to add more comments. Added a bunch of tests, so hopefully the intent is clear.

Let me know if anything else. Thanks again!
