### ISSUE TITLE
Html: Add 'mw-footer' class to 'footer' div [#745] (new class in footer)

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#745]
I have created a new (built from scratch) xowa environment.
I noticed a strange effect on the footer part of the page
`en.wikivoyage.org/wiki/Shikoku`
![foot1](https://user-images.githubusercontent.com/861631/84684182-37f02f00-af30-11ea-923f-1a2a5802ad7a.jpg)

On examining the equivalent mw page there is a subtle difference in the footer

    <div id="footer" class="mw-footer" role="contentinfo" >
 The `class` is new

Adding this class to the footer code in xo.cfg.sqlite3 seems to fix the problem

**Comment by gnosygnu** [comment]
Nice breakdown! Added above with simple fix. Thanks!
