### ISSUE TITLE
Missing pagebanner

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#748]
I came across this page
`en.wikivoyage.org/wiki/Wikivoyage:Past_events/World_Cup_2010`
and noticed that there is no page banner, whereas mw shows one

In Pgbnr_func.java is a check `Chk_pgbnr_allowed` that, when commented out, fixes the problem

Something to do with the fact that this particular page is in a different namespace 'Wikivoyage:'
It seems there are about 30 pages like this

**Comment by gnosygnu** [comment]
Thanks for the report! Will take a look at that after #737 . I'm also done with a hierarchical config system which I want to use to limit the sleep / timeout mechanism. Basically, "only run scribunto in threaded mode for this Module and Function"

**Comment by gnosygnu** [comment]
Ended up just adding the namespace to the PageBanner namespace list.

Thanks as always for the clear report!
