### ISSUE TITLE
Publish current en.wiki and de.wiki? Request, no issue.

### ISSUE THREAD

**Issue by Ope30** [gnosygnu/xowa#75]
Hello there, it has been a long time. I just wanted to ask you, IF you could publish the latest en.wiki and the de.wiki for XOWA right now, I would do it through the Download Central with all the links, just to be safe. I'm aware that would take a long time, uploading it, extracting it etc., but you know, I just want to be up-to-date this time. That would be very nice.

By the way, I haven't gotten the time to look for more bugs, hence no threads recently. I will do it this time though.

**Comment by gnosygnu** [comment]
Hi! Good to hear from you again.

Actually, this week is a bad time for me. I'm working on some significant changes to handle some outstanding issues (videos, galleries, imageMaps). I won't have 2016-08 English Wikipedia ready until next week (08-21), and a German Wikipedia refresh may be a few days after that.

If you need it sooner, here are some recommendations:
* Are you running the desktop version? If so, you can always download the latest XML dumps through home/wiki/Dashboard/Import/Online .
* Do you need them for Android?
    * If so, English Wikipedia is up until 2016-07
        * As I said above, I'll have 2016-08 ready in about a week. This will be about 30 GB of HTML articles, and probably 4 GB of images
        * In the meantime, you can download all the images. That will be about 90 GB. They won't change between now and 2016-08
    * German Wikipedia is available as of 2016-06. It sounds like you want a refresh, so I'll try to do 2016-08 after English Wikipedia
        * Again, like English Wikipedia, you can download the images beforehand.

Hope this is enough information. Let me know if you have any questions.

Thanks!

**Comment by Ope30** [comment]
Thanks for the recommendations. I'll start as soon as you're done with the 08 wikis.

Take your time though. No rush.

**Comment by gnosygnu** [comment]
Cool. I'll post again here when I have them uploaded. Probably on 08-21. Thanks!

**Comment by gnosygnu** [comment]
I posted the files tonight. Please download the latest release at https://github.com/gnosygnu/xowa/releases/tag/v3.8.5.1 .

After you install XOWA, go to home/wiki/Special:XowaDownloadCentral . You'll see entries for 2016-08 English and German Wikipedia.

Let me know if you run into any issues. I'm going to mark this issue resolved for now, and will close it later this week.

Thanks.

**Comment by Ope30** [comment]
I definitely will! Thank you for the hard work, Gnosy. :)

**Comment by gnosygnu** [comment]
I'm going to mark this ticket closed. Both 2016-08 and 2016-09 wikis have been published. Feel free to open another issue if there's something else. Thanks!
