### ISSUE TITLE
Lua compilation errors

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#759]
I was trying to work out why `en.wiktionary/wiki/ἄλφα` was causing an invoke fail, so I place a `dbg` into the module

Unfortunately, I made a typo in the statement

When I refreshed the page, I got:

    Script error: org.luaj.vm2.LuaNil cannot be cast to org.luaj.vm2.LuaTable

The first few lines of the error within the log file are

    20200713_132034.533 invoke failed: ἄλφα {{#invoke:R:Strong's|strongs}}
     [err 0] <java.lang.ClassCastException> org.luaj.vm2.LuaNil cannot be cast to org.luaj.vm2.LuaTable
      [trace]:
        gplx.xowa.xtns.scribunto.engines.luaj.Luaj_value_.Get_val_as_lua_table(Unknown Source)
        gplx.xowa.xtns.scribunto.engines.luaj.Luaj_engine.LoadString(Unknown Source)
        gplx.xowa.xtns.scribunto.Scrib_lua_mod.LoadString(Unknown Source)
        gplx.xowa.xtns.scribunto.Scrib_core.Mods_get_or_new(Unknown Source)
        gplx.xowa.xtns.scribunto.Scrib_core.Invoke(Unknown Source)
        
this was not immediately obvious that this was due to my typo

On further examination, it is the code in Luaj_engine.LoadString that is triggering the issue

This function essentially assumes a positive result - it does not check the `op` code
If it had this would have indicated an error

Adding the following lines

    // need to check for error
    String op = Luaj_value_.Get_val_as_str(rsp, "op");
    if (String_.Eq(op, "error"))
      String err = Luaj_value_.Get_val_as_str(rsp, "value");
      throw Scrib_xtn_mgr.err_(err);
    }
Gives a more appropriate error

**Comment by gnosygnu** [comment]
Thanks for the breakdown! Change looks straightforward enough. Let me work on it tomorrow / Wednesday!

**Comment by gnosygnu** [comment]
Pushed with the commit above. Thanks again!
