### ISSUE TITLE
torrent downloads

### ISSUE THREAD

**Issue by ndxf** [gnosygnu/xowa#76]
hi
I can't find torrent links for downloading over slow or unreliable connections. if there a way to setup XOWA with downloading files over torrents?

**Comment by ndxf** [comment]
nevermind I found the torrents on wikimedia website.

https://meta.wikimedia.org/wiki/Data_dump_torrents

**Comment by gnosygnu** [comment]
Hi! Just a few notes:
* There are two xml dump sites: [Wikimedia](https://dumps.wikimedia..org/backup-index.html) and [your.org](https://dumps.wikimedia.your.org/backup-index.html).
    * Both are generally reliable. Let me know if you're having a problem with dropped connections for either, and I'll raise a ticket for them. For example, last week, there was some weird download issues at the Wikimedia site: https://lists.wikimedia.org/pipermail/xmldatadumps-l/2016-August/001326.html
* I also upload HTML dumps to archive.org. In particular, the offline images are only at archive.org. For example, all the <code>\*2016-06_file_\*.xowa</code> databases at https://archive.org/download/Xowa_enwiki_latest 
    * archive.org is sometimes spotty, but I believe they use Amazon AWS. I've not had any known reports
* I will create torrents to seed from my machine by the end of this month.
    * I know these will be slow at start, but I'm hoping it will get better as more people to use them.

Let me know if there's anything else. Thanks!
