### ISSUE TITLE
HTTP Server: Fix broken links in left nav (Dead link)

### ISSUE THREAD

**Issue by NijazM** [gnosygnu/xowa#768]
When I use xowa via server via Firefox, there is menu on left of any article called Help.
It leads to dead url: http://localhost:8082/home/wiki/Contents
While I found working url in main page of xowa: http://localhost:8082/home/wiki/Help/Contents
There are probably few other dead links.
Actually this is appearing even without server, for example in xowa app: home/wiki/Contents
Link that can be activated by enabling in home/wiki/Special:XowaCfg?grp=xowa.html.page "Show home menu in sidebar (desktop)"

**Comment by desb42** [comment]
I came across this issue a while ago - but forgot to mention it

This requires a minor mod to `bin\any\xowa\cfg\app\xowa.gfs` (depends on where the root is)

        <li><a href="/site/home/wiki/About" class='xowa-hover-off'>~{<>app.user.msgs.get('xowa-portal-about');<>}</a></li>
        <li><a href="/site/home/wiki/Contents" class='xowa-hover-off'>~{<>app.user.msgs.get('help');<>}</a></li>

change to

        <li><a href="/site/home/wiki/Help/About" class='xowa-hover-off'>~{<>app.user.msgs.get('xowa-portal-about');<>}</a></li>
        <li><a href="/site/home/wiki/Help/Contents" class='xowa-hover-off'>~{<>app.user.msgs.get('help');<>}</a></li>

Not the addition of `/Help`

**Comment by gnosygnu** [comment]
Thanks @desb42 ! I forgot to update this when I reworked the home wiki a few years ago

@NijazM : Thanks for the report! I attached a version of the updated file below. You can fix it by doing the following:
* Copying the file to C:\xowa\bin\any\xowa\cfg\app (or wherever you setup XOWA)
* Renaming the file from `xowa.gfs.log` to `xowa.gfs`

Let me know if there's anything else. Thanks!

[xowa.gfs.log](https://github.com/gnosygnu/xowa/files/4965836/xowa.gfs.log)
