### ISSUE TITLE
[err 1] <db> could not load sqlite jdbc driver

### ISSUE THREAD

**Issue by BobYoplait** [gnosygnu/xowa#77]
Hello,

I am on   Ubuntu 13.10
I did download   xowa_app_linux_64_v3.8.2.1.zip
I did "unzip xowa_app_linux_64_v3.8.2.1.zip"

When I do:
java -Xmx256m  -jar ./xowa_linux_64.jar

I get:
app init failed: [err 0] <java.lang.ClassNotFoundException> org.sqlite.JDBC
[err 1] <db> could not load sqlite jdbc driver
[err 2] <db> db.engine:exec failed: url=data source=/home/lee/tools/xowa/user/xowa.user.anonymous.sqlite3;version=3; sql=PRAGMA page_size = 4096;

I have this in "user":
 tree user/
user/
└── anonymous
    └── app
        ├── data
        │   └── cfg
        │       ├── user_system_cfg.gfs
        │       └── xowa_user_cfg.gfs
        └── tmp
            └── log
                └── current
                    ├── err.txt
                    └── session.txt

7 directories, 4 files

I love xowa, did anyone hit this issue before ?
Thank you.

**Comment by gnosygnu** [comment]
Hi! Thanks for all the details (as well as your enthusiasm with XOWA)!

I've not seen this error before. It means that it couldn't open up the SQLite library, which should not happen.

Let's try the following:
* Does the SQLite library exist?
    * It should be at /home/lee/tools/xowa/bin/any/java/jdbc/sqlite/sqlite-jdbc-3.8.11.2.jar
    * The file there should be 5.3 MB (5,575,351 bytes)
    * It has an MD5 of c56e036631557d93c9a28acd3a49e32b
* What version of Java do you have?
    * It should run with any JDK above 1.5. I just want to confirm that you have a recent JDK and that it's OpenJDK (Oracle should work, but I don't know about GNU Classpath)
    * Run "java -version". I get the following:
```
openjdk version "1.8.0_101"
OpenJDK Runtime Environment (IcedTea 3.1.0) (suse-15.1-x86_64)
OpenJDK 64-Bit Server VM (build 25.101-b13, mixed mode)
```
* Can you try out a live disk of Ubuntu 16.04? 
    * I tried a live disk back in late July. I downloaded it from here: http://releases.ubuntu.com/16.04/ubuntu-16.04.1-desktop-amd64.iso
    * I ran into no problems. I just want to make sure it's the same case for yours. I doubt it's a 13.10 problem, but I'd feel better if we can make sure that a "live disk" 16.04 still works on your box
    * I've tried other versions of Ubuntu as well (14.04 I believe). I've also tried Mint as well. No problems with them.
* Anything else "interesting" about your machine?
    * I've gotten random one-offs due to strange configurations on machines. They're pretty hard for me to troubleshoot, especially since I can't debug it. This is pretty open, but any info would be useful

Depending on your answers to the above, we'll try to go on to the next step.

Thanks!

**Comment by BobYoplait** [comment]
Thank you for your answer.
Actually first test doesn't pass:
"Does the SQLite library exist?"
It does not and as a matter of fact "bin" doesn't exist either.
I must have had a problem during the unzip. Don't really know what happened.

Anyways, I ran it again and all the files are here. So no problem actually.

For your info I am using Oracle jdk, and everything works on Ubuntu 13:
java version "1.7.0_75"
Java(TM) SE Runtime Environment (build 1.7.0_75-b13)
Java HotSpot(TM) 64-Bit Server VM (build 24.75-b04, mixed mode)

Thanks anyway, you can close the issue.

**Comment by gnosygnu** [comment]
> Anyways, I ran it again and all the files are here. So no problem actually.

Cool. Thanks for confirming! I'll close out the issue for now.
