### ISSUE TITLE
Wikidata: Implement Lexeme (Script error: gplx.Err: key not found: key=sense)

### ISSUE THREAD

**Issue by gnosygnu** [gnosygnu/xowa#771]
I found this issue during the 2020-06 enwiki dump. A bunch of pages have an error message like this `Script error: @D:/xowa/bin/any/xowa/xtns/Scribunto/engines/Luaj/MWServer.lua:59 vm error: gplx.Err: key not found: key=sense`

It looks like the Wikipedias are finally using the Lexeme data. For example: https://www.wikidata.org/wiki/Lexeme:L2

**Comment by desb42** [comment]
I have done a bit of work in that area
Addedsense and form
implemented a crude display of Lexeme and EntitySchema
made the title the english version of the description (if any)

If you have time, take a look at my version

**Comment by gnosygnu** [comment]
Thanks for the reference! It looks like most of the changes are in these commits:

* [Ttl differences](https://github.com/desb42/myxowa/commit/66a5970e9d911349bf0dfe620f7ca3a778c4e8e6)
* [add datatype display names](https://github.com/desb42/myxowa/commit/7563d0aec5c6df0c436e73d8c5203d5bf5645b76)
* [wikistrip to allow for trailing whitespace in tag closure](https://github.com/desb42/myxowa/commit/00d8e9315ca3717d53bb5f207f79f5445388c945)

... with a lot seeded from this one:
* [bring into line with local](https://github.com/desb42/myxowa/commit/b25301d361acbee7bd9bfcb22718f256e3bc1035)

I've been working on changes on my side as well. Will compare to yours to make sure I don't have anything left out.

**Comment by gnosygnu** [comment]
Fixed with commits above. Added new issue #781 and #782 to track other work from those commits.

Thanks for the commits!

**Comment by desb42** [comment]
I merged the changes to 7b6b3ed09a00cca0efef71434e1baad5823f0ead with my code 9 days ago

I started running a dump of wikidata (2020-08-01) yesterday (2020-08-08)
Unfortunately, I started getting the above error (form, sense and lexeme)

It turns out that I did not notice a subtle change to the file Wbase_claim_type_.java

The file at the moment has the lines

    , Itm__lexeme               = New(Tid__lexeme                , "lexeme")            // EX:wd:Lexeme:L2
    , Itm__form                 = New(Tid__form                  , "form")              // EX:wd:Lexeme:L2 P5830
    , Itm__sense                = New(Tid__sense                 , "sense")             // EX:wd:Lexeme:L2 P6072
whereas prior to that change the lines in myxowa were

    , Itm__lexeme               = New(Tid__lexeme                , "wikibase-lexeme")   // EX:wd:Property:P5188
    , Itm__sense                = New(Tid__sense                 , "wikibase-sense")    // EX:wd:Property:P5972
    , Itm__form                 = New(Tid__form                  , "wikibase-form")     // EX:wd:Property:P5193
 
the `wikibase-` prefix is important

**Comment by gnosygnu** [comment]
> the wikibase- prefix is important

Oops. Didn't realize the difference.

Fixed in the commit above. Thanks for reopening the issue!
