### ISSUE TITLE
new div contentSub2

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#783]
I have just noticed that a new (to me) \<div> has appeared in mw pages

It immediately follows the "contentSub" \<div>

I have been ignoring this, only to discover that in itwikisource pages, this \<div> is significant
for example `it.wikisource.org/wiki/Autore:William_Robert_Grove`
The spacing between the title and the following panel is different between xowa and mw

Adding `<div id="contentSub2"></div>` to xowa.gfs fixes this

**Comment by gnosygnu** [comment]
I'm always impressed by your attention to detail. This is something I never would have noticed unless I were looking for it.

Thanks as always for the excellent overview! Fixed in the commit above
