### ISSUE TITLE
Parser: Add namespace to Template title (template frame ttl should include namespace)

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#784]
This page `en.wikipedia.org/wiki/Wikipedia:Wikipedia_Signpost/2015-07-15/Op-ed` generates an error
`Script error: =Module:Signpost poll:177 Please specify a question`

This calls the template `Wikipedia:Wikipedia Signpost/Templates/Voter`
which eventually calls `en.wikipedia.org/wiki/Module:Arguments`
Within this module a check is made on the name of the parent template

Unfortunately, the name as supplied is `Wikipedia Signpost/Templates/Voter` - missing the namespace `Wikipedia:`

I tracked this down to 400_xowa\src\gplx\xowa\parsers\tmpls\Xot_defn_tmpl_.java function `CopyNew`

Within this function a specific check is made for the `Template:` namespace but no other

I changed this to append a namespace (except Main) regardless

please see
[Xot_defn_tmpl_.zip](https://github.com/gnosygnu/xowa/files/5026895/Xot_defn_tmpl_.zip)

**Comment by gnosygnu** [comment]
Nice work on two fronts!

First, tracking down the bug: I think that error has been around for years, but never realized it was coming from that code.

Second, that DB_case_cvt_ class is quite comprehensive. That must have taken quite a lot of work to generate!

I'll make the change in the next few days. Regarding the `DB_case_cvt` classes, I'll add them with a line like `Copyright (C) 2020 https://github.com/desb42` My apologies for missing this in the past, and do let me know any other files which are changed. Honestly, in the end, I feel that Copyright is an obsolete formality (as per #711), but definitely do want to give credit where credit is overwhelmingly due.

Let me know if anything else. Thanks!

**Comment by desb42** [comment]
oops - I had forgotten that there were other mods in that file

With regard to DB_case_cvt_, I have a python script that reads the file Xol_case_mgr_.java and produces that massive switch statement

So if any changes were to be made to that java file I can regen the table

**Comment by gnosygnu** [comment]
> So if any changes were to be made to that java file I can regen the table

Thanks for explanation :+1:. Took a quick look at it, and it looks fine. Will re-evaluate if any issues

Fixed with the commit above. Thanks again for tracking this down, as well as the case_cvt classes!

**Comment by desb42** [comment]
I have also modified a number of other java files to replace case_cvt
They are

    400_xowa\src\gplx\xowa\addons\wikis\ctgs\htmls\catpages\doms\Xoctg_catpage_itm.java
    400_xowa\src\gplx\xowa\xtns\scribunto\libs\Scrib_lib_language.java
    400_xowa\src\gplx\xowa\xtns\geoCrumbs\Geoc_isin_func.java
