### ISSUE TITLE
attribute "role" is not just for presentation

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#785]
I was looking at
`en.wikipedia.org/wiki/Salvador_Dalí`
and comparing mw and xowa versions

I noticed that for mw a number of \<div>s had the attribute 'role' whereas not in xowa

I have chased this down to the attribute whitelist manager 400_xowa\src\gplx\xowa\parsers\xndes\Xop_xatr_whitelist_mgr.java Line 50
where a check to see if the role is 'presentation'

I have just commented out this line and now there are lots more 'role's

**Comment by gnosygnu** [comment]
Nice find. Always impressed with how you pick up even the smallest of differences, including HTML tag differences

I checked my earlier notes, and couldn't find a corresponding pointer in MW code, nor could I reproduce any issue today. Removed check with minor comment

Thanks!
