### ISSUE TITLE
Image: Mark tif orig files as not images [tif]

### ISSUE THREAD

**Issue by NijazM** [gnosygnu/xowa#788]
Tif files are are not downloaded when clicking on image, but is downloaded only small thumbnail when I am on pages such as `Varicocele`
Not downloaded: `en.wikipedia.org/wiki/File:Trans_varicocele.tif`
Tested in app and in server + chrome.

Or maybe...it is downloaded, I can see it in my `xowa\file\commons.wikimedia.org\orig\d\3\c\6\Trans_varicocele.tif` folder, but it is not shown on `en.wikipedia.org/wiki/File:Trans_varicocele.tif` page, neither in app nor in server + web browser.

Actually it is shown but only as link to open it with my image viewer in case of xowa app, or download file (save as) in case of chrome + server.

In normal (real) wikipedia that file is shown as thumbnail (preview). Can it be made to show that way?

**Comment by gnosygnu** [comment]
Hey, sorry about the delay, but my email has been weird again.

Great report, as well as all the details! I was able to reproduce on my side, and fixed with the commit above

Let me know if you want a build for this, and I'll push out an unofficial one.

Thanks!

**Comment by NijazM** [comment]
Nice. No, I will rather wait until next release as tif images are still rare, and have slow bandwidth.
