### ISSUE TITLE
Resume cabability

### ISSUE THREAD

**Issue by aweasadbek** [gnosygnu/xowa#791]
I was building full English Wikipedia, after 10 hours the build did not finished. Unfortunately, my sister shut down my computer. And then I had to start everything building from the beginning. Also I cannot keep my computer on for several days. Already build dumps have a very large size which would take me a month to download.
So can you add resume capability for building.  So that I can continue building from where left after computer shut down.

**Comment by gnosygnu** [comment]
Hey. Sorry for the late reply. Working on cleaning up email over the next few days

Resume capability does exist, though it was missing some documentation. I added another step here: http://xowa.org/home/wiki/Dev/Command-line/Thumbs#Resuming

Let me know if you have any issues. Also, thanks @NijazM for the helpful tip!
