### ISSUE TITLE
syntaxhighlight 'inline' option not behaving

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#794]
Investigating #793 I was looking at `Template:yesno`
within the documentation of that template a table is shown
xowa:
![inline1](https://user-images.githubusercontent.com/861631/91386620-51b0cb00-e82b-11ea-8e3e-37d4b6d0708d.jpg)
the equivalent in mw is
![inline2](https://user-images.githubusercontent.com/861631/91386637-5e352380-e82b-11ea-8c84-aebfe4f7b5e0.jpg)
The section encircled in red is generated by the wikitext `({{code|1=1=}})`

`Template:code` invokes `syntaxhighlight` and in this case uses the `inline` keyword

The syntaxhighlight code in xowa (knows about the `inline` keyword and seems to treat it identically to `enclose`

This is not quite correct

`inline` != `enclose` but `inline` can be treated as the same as `enclose=none`

please see a suggested fix in
[Synh_xtn_nde.zip](https://github.com/gnosygnu/xowa/files/5134227/Synh_xtn_nde.zip)

**Comment by gnosygnu** [comment]
Nice. Wonderful write-up as always!

Made change as you prescribed. Thanks!
