### ISSUE TITLE
#switch picking the wrong item

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#795]
Looking at `en.wikipedia.org/wiki/Template:Infobox_language/ref`
There are many examples of a template not existing
xowa-gui
![switch1](https://user-images.githubusercontent.com/861631/92098821-a32ffb80-edd1-11ea-9106-d33ab1dd80d9.jpg)
whereas mw 
![switch2](https://user-images.githubusercontent.com/861631/92098870-b4790800-edd1-11ea-9a3b-4cf8c2c9ea53.jpg)

looking at the underlying wikitext - an example that provokes the problem is

    {{Infobox language/ref|e23}}
`Template:Infobox_language/ref` is a big #switch 

the first few lines of which are (cut down to show the structure)

    {{#switch: {{{1}}}
    | =
    | e24 = {{#ifexist:Template:Ethnologue24| ... | e23 = {{#tag:ref|{{#if:{{{iso3|}}}|{{Ethnologue23| ... | e22 = {{#tag:ref|{{#if:{{{iso3|}}}|{{Ethnologue22| ... <!--
    ...

As it happens `Template:Ethnologue24` does not exists
but all the other numerically less do
that is `Template:Ethnologue23` and 'lower' exist

The issue seems to be the comparison routine `Pf_func_.Eq`
when called with the arguments `e24` and `e23`
This function returns true (it should be false)

**Comment by gnosygnu** [comment]
Thanks for the great breakdown! Especially since that was a pretty hard path to debug!

The issue is with the `Gfo_number_parser`. It thinks that `e24` is a number. Will fix with the next commit

**Comment by gnosygnu** [comment]
Fixed with the commit above. Thanks again for all the help!

**Comment by desb42** [comment]
As a matter of protocol, should I close this issue (as I opened it) - once I believe it to be fixed (as it is in this case)
Or do I wait for you to close it

**Comment by gnosygnu** [comment]
Really up to you! Feel free to close / re-open any issue you want!

In terms of current workflow, usually, I move items to `Done` when I feel like they're finished. After a week or so I close them out.

In terms of protocol, I'd say it can be closed first by either submitter or project owner. Let me know if that works for you!

**Comment by desb42** [comment]
This issues is resolved
