### ISSUE TITLE
HTML: Links broken in simple wikipedia

### ISSUE THREAD

**Issue by gnosygnu** [gnosygnu/xowa#799]
I was about to make a release today, but came across this bug. Basically, all links in Simple Wikipedia fail b/c "about:/site/" is prefixed to everything.

This is probably related to #797

Repro steps below.

---

* Download a new Simple Wikipedia from the XOWA Main page
* Click on the `Gothic architecture`
* XOWA navigates to `home/wiki/about:/site/simple.wikipedia.org/wiki/Gothic_architecture`

**Comment by gnosygnu** [comment]
Actually, this looks like it's related to the SWT upgrade from #687 . HTTP_Server works fine

**Comment by desb42** [comment]
This occurs on all wikis, and any local links

A workaround for editing is to add ?action=edit to the address bar

**Comment by gnosygnu** [comment]
Cool, thanks for the tip!

I think I have a fix. Basically strip away the `about:` Need to test it on Linux, Mac OS X. Will have a commit probably in the next day or two.

```
	private void Pub_evt(LocationEvent arg, String evt) {		
		String location = arg.location;
		if (String_.Eq(location, "about:blank")) return;	// location changing event fires once when page is loaded; ignore
		if (	html_box.Browser_tid() == Swt_html.Browser_tid_webkit	// webkit prefixes "about:blank" to anchors; causes TOC to fail when clicking on links; EX:about:blank#TOC1; DATE:2015-06-09
			&&	String_.Has_at_bgn(location, "about:blank")) {
			location = String_.Mid(location, 11);	// 11 = "about:blank".length 
		}
		if (	html_box.Html_doc_html_load_tid() == Gxw_html_load_tid_.Tid_url	// navigating to file://page.html will fire location event; ignore if url mode
			&& 	String_.Has_at_bgn(location, "file:")
			&& 	String_.Has_at_end(location, ".html")
			)
			return;
		if (html_box.Browser_tid() == Swt_html.Browser_tid_mozilla && String_.Has_at_bgn(location, "about:")) {
			location = String_.Mid(location, 6);	
		}
		try {
			Gfo_evt_mgr_.Pub_obj(host, evt, "v", location);
			arg.doit = false; // cancel navigation event, else there will be an error when trying to go to invalid location
		}
		catch (Exception e) {html_box.Kit().Ask_ok("xowa.gui.html_box", evt, Err_.Message_gplx_full(e));}	// NOTE: must catch error or will cause app to lock; currently called inside displaySync 		
	}

```

**Comment by desb42** [comment]
Have just rebuilt the latest xowa (xowa_get_and_make) and it seems the links (read/edit) seem to work 
but not Table of Content links

**Comment by gnosygnu** [comment]
Ugh. Thanks for the catch. Published release before I saw this.

Will have a fix by sometime tomorrow and publish new release. Thanks!

**Comment by gnosygnu** [comment]
Fixed with the commit above. Thanks again for checking!
