### ISSUE TITLE
Discussion at sourceforge are offline or gone?

### ISSUE THREAD

**Issue by AnselmD** [gnosygnu/xowa#8]
Sourceforge is online again. The discussions are offline, hopefully they will come back again.

fyi: 
Should we get away from sf.net? · Issue #407 · tatsuhiro-t/aria2
https://github.com/tatsuhiro-t/aria2/issues/407

**Comment by AnselmD** [comment]
When discussions and ticket system are only again, i will think about to to rescue some of my results, which are stored there.

**Comment by gnosygnu** [comment]
Yeah, I think they're still having problems. The twitter feed is not that descriptive. https://twitter.com/sfnet_ops

> Should we get away from sf.net? · Issue #407 · tatsuhiro-t/aria2

Thanks for the link. I still have to migrate the pages at xowa.sourceforge.net, but I plan to be off in the next few weeks. I'll still check the discussion page, but at this point I'm not planning much else.

> When discussions and ticket system are only again, i will think about to to rescue some of my results, which are stored there. 

Yeah, those results were pretty valuable. Let me know if anything is needed from my side.

Thanks.

**Comment by AnselmD** [comment]
FYI:
SourceForge Infrastructure and Service Restoration | SourceForge Community Blog
http://sourceforge.net/blog/sourceforge-infrastructure-and-service-restoration/

**Comment by gnosygnu** [comment]
Cool. Thanks for the link. It looks like the XOWA discussion pages finally came back online.

**Comment by gnosygnu** [comment]
Sourceforge is basically fully online as of sometime last week. I'm going to mark this issue closed for now. Let me know if you want me to keep it open. Thanks.
