### ISSUE TITLE
Module:Excerpt changes

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#802]
As of 2020-09-01 dump when I tried to produce the hdump of enwiki, I received numerous errors to do with Module:Excerpt

Script error: @k:/xowa_dev/bin/any/xowa/xtns/Scribunto/engines/Luaj/MWServer.lua:59 vm error: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String

In my investigation, I came across this `https://en.wikipedia.org/wiki/Module_talk:Excerpt#New_version`

The actual problem stems from code in `Module:Transcluder`

In `local function matchFlag` is a line

    or mw.ustring.match(value, flag) then
The problem is that under a particular circumstance,`flag` gets the numeric value of '0' (specifically not a string)

It seems that mw returns `nil` and xowa barfs

**Comment by gnosygnu** [comment]
Great breakdown as always! Fixed with the commit above

Out of curiosity which page / version of Wikipedia did you see the error? I tried with 2020-08 and pages like Coal, Algeria, and Aquaculture (from https://en.wikipedia.org/wiki/Special:WhatLinksHere/Module:Excerpt)

**Comment by desb42** [comment]
This seems to be a 'feature' introduced around 28th August 2020, so a later dump is needed. I used 2020-09-01

**Comment by gnosygnu** [comment]
Ah, duh. I should've checked the comment date. Thanks!
