### ISSUE TITLE
templatestyle css transformation not quite right

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#815]
Looking at `it.wikipedia.org/wiki/Kaulon` in xowa-gui
![css1](https://user-images.githubusercontent.com/861631/96263860-6c95f500-0fbb-11eb-84ff-ba54a2740791.jpg)
Note: the coordinates are in the wrong position - they should be above the info box

This turns out to be a subtle bug in how the css of a templatestyle has the class `.mw-output` added

I have altered 400_xowa\src\gplx\xowa\xtns\template_styles\XoCssTransformer.java to only add the extra class if the element is a class or an id (not a built in tag)

Please see
[XoCssTransformer.zip](https://github.com/gnosygnu/xowa/files/5391894/XoCssTransformer.zip)

**Comment by gnosygnu** [comment]
Thanks as always for the well written issue, and sorry for slow progress on my side. Will incorporate your fix tomorrow

**Comment by desb42** [comment]
Not so simple
Just come across another subtlety
`en.wikisource.org/wiki/Strange_Case_of_Dr_Jekyll_and_Mr_Hyde`
This uses `en.wikisource.org/wiki/Template:FreedImg/styles.css` which has `div` selectors
These do need to have the prefix

So change the code to specifically ignore `body`
[XoCssTransformer.zip](https://github.com/gnosygnu/xowa/files/5432600/XoCssTransformer.zip)

**Comment by desb42** [comment]
oops and another fix
[XoCssTransformer.zip](https://github.com/gnosygnu/xowa/files/5434776/XoCssTransformer.zip)

**Comment by gnosygnu** [comment]
Sorry, that was a long tomorrow for me.... Work has been pretty bad recently and all my free time has sadly been going to work time.

I made the fix above as per your commit. Thanks as always for keeping up with it. Just so you know, I wasn't able to reproduce the issue with a 2020-10 itwiki, but at this point, I more than trust your commit is correct. Thanks again.
