### ISSUE TITLE
spaces in i18n

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#817]
rummaging around on itwiki I came across this wikitext

    {{int:history short}}
Which is effectively the contents of `Mediawiki:history short` 
In this case the text is `Cronologia`

First of all this particular value has not been setup in it.gfs
I added the line

    history_short|Cronologia

Then tried again, and it still did not work
The (small) issue comes down to `400_xowa\src\gplx\xowa\xtns\pfuncs\langs\Pfunc_int.java`

The `msg_key` needs a space to underscore convert
I used

    msg_key = Xoa_ttl.Replace_spaces(msg_key);

**Comment by gnosygnu** [comment]
Nice breakdown. Fixed as prescribed in the commit above. Thanks!
