### ISSUE TITLE
Expression error: Unrecognized word "abse"

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#819]
Looking at `en.wikipedia.org/wiki/Iron_fertilization#Financial_opportunities`
![expr1](https://user-images.githubusercontent.com/861631/99877903-5c47ea00-2bf9-11eb-8ace-2239739728ed.jpg)
Note the expression error

This is coming from the wikitext:

    {{chem|CO|2|e}}
which in turn calls Template:Chem/atom

This relies on errors occurring - and at the moment that is not happening

The following wikitext demonstrates the issue

    {{#expr:e}}

    {{#expr:e0}}

    {{#expr:pi}}

    {{#expr:pi0}}
In xowa
![expr2](https://user-images.githubusercontent.com/861631/99878049-8ea61700-2bfa-11eb-8313-a5ea7268b12e.jpg)
mediawiki:
![expr3](https://user-images.githubusercontent.com/861631/99878057-982f7f00-2bfa-11eb-9df3-9fcf05101dae.jpg)
That is `{{#expr:e0}}` and `{{#expr:pi0}}` should error

I have made changes to  `400_xowa\src\gplx\xowa\xtns\pfuncs\exprs\Pfunc_expr_shunter.java` to fix this

please see
[Pfunc_expr_shunter.zip](https://github.com/gnosygnu/xowa/files/5577676/Pfunc_expr_shunter.zip)

**Comment by gnosygnu** [comment]
Nice write-up as always. Fixed in the commit above. Thanks!
