### ISSUE TITLE
Generate HTML dumps / images for 2016-09 French Wikipedia

### ISSUE THREAD

**Issue by gnosygnu** [gnosygnu/xowa#82]
I'm just creating a separate issue for this task. I expect to have it done 2016-09-18. I'd like to get as much done for https://github.com/gnosygnu/xowa/issues/81 as possible, but if I run into roadblocks, I'll just generate the 2016-09 with the known issues (primarily, no categories and sometimes missing images for recently-uploaded items)

I'll post another update within a week's time

**Comment by yonisolo** [comment]
Thank you for all, no problem for me with those issues for the moment

**Comment by Ope30** [comment]
Sounds pretty good! Take all the time you need!

**Comment by gnosygnu** [comment]
I uploaded the French wikis over the weekend. You can download them by either....
* Using Download Central.
    * Go to home/wiki/Special:XowaDownloadCentral
    * Click the Download arrow on the far right side of the Available table. This will bring down the data for French Wikipedia
    * Look for French Wikipedia 2016-09 and click
* Through a browser
    * https://archive.org/download/Xowa_frwiki_latest
    * Download the files that have 2016-09 in the file name.

Let me know if you run into any issues. Thanks!

**Comment by yonisolo** [comment]
You are great!! thx

**Comment by gnosygnu** [comment]
> Just a question, these html dumps works with the raspi xowa edition? These replace the text format?

Yup. The HTML dumps will work on raspberry pi. You can still use the text format, but the HTML dump will be much faster.

Hope that helps. Thanks!

**Comment by yonisolo** [comment]
Yep it helps a lot!! so much work done, good job!!

**Comment by gnosygnu** [comment]
Cool. Thanks!

**Comment by gnosygnu** [comment]
I'm marking this issue closed for now. Let me know if there's anything else. Thanks!

**Comment by yonisolo** [comment]
I tested it today with the 3.9.4.1 version on raspberry. it works like a charm. I can just add that the "wiki/fr.wikipedia.org" directories are missing in the zip files, it can be a trouble for Xowa beginners. thx!

**Comment by gnosygnu** [comment]
> I tested it today with the 3.9.4.1 version on raspberry. it works like a charm.

Cool. Thanks! I'm going to post this to the other raspberry pi thread as well: https://github.com/gnosygnu/xowa/issues/85 . Btw, are you using a raspi2 or a raspi3 for the GUI? Also, what JVM do you have?

> I can just add that the "wiki/fr.wikipedia.org" directories are missing in the zip files, it can be a trouble for Xowa beginners. thx!

Yup, I changed this recently for Download Central. I now unzip directly into the current directory instead of trying to guess the relative one (wiki/fr.wikipedia.org). I've had to answer questions before about the relative location and I thought this would be simpler.

I'll add more explicit instructions in the home wiki later this week.

Thanks!
