### ISSUE TITLE
Opening a link in a new tab directs me to incorrect address

### ISSUE THREAD

**Issue by HywelDda** [gnosygnu/xowa#823]
Hello! I'm really new to xowa, so I'm not sure how to solve this error - hoping to get some help here :)

Whenever I open a link in a new tab, whether it's mouse wheel click or right click -> open in new tab, it opens the wrong address. If I want to go to the "fossils page, it sends me to "en.wikipedia.org/wiki/About:/wiki/Fossil" when it should be going to "en.wikipedia.org/wiki/Fossil" and I'm greeted by a blank page. It adds "About:/wiki/" to the address, and sure enough, if I delete that I arrive where I want to be.

Thank you!

**Comment by gnosygnu** [comment]
Hey, thanks for the interest in XOWA! Sorry for the late reply, but I've been incredibly busy with work.

I fixed the issue and made a temporary release just now. See: https://github.com/gnosygnu/xowa/releases/tag/v4.6.14.2012

Also, I like to credit users for discovering bugs. There will be a line in the next XOWA changelog that says `Gui: Strip `about:/wiki/` from links [#823] {discovered by anonymous}` Let me know if you would rather remain anonymous or be cited by nickname (HywelDda?)

Thanks again for the report!

**Comment by catmaps** [comment]
Hello,
I tried the new temporary release. Now it works fine when you "Open Link in New Tab"
However, when I copy and paste the hyperlink outside of Xowa it still does "About:/wiki/"

**Comment by gnosygnu** [comment]
Thanks for the report! Fixed with the commit above. Will try to generate a new release after resolving #829

**Comment by HywelDda** [comment]
Hello! I just had time to see this, I've had my mind in a short film I'm
working on ^^. I don't know if you'll still see this, but you can
absolutely credit me by nickname (I think it's awesome that you do).

Regards,
Anton

Ps. I'm setting up XOWA as a gift for my father, I think he'll dig it and I
wanted to thank you!

**Comment by gnosygnu** [comment]
Nice! `HywelDda` it is! Let me know if there's anything else. Thanks!
