### ISSUE TITLE
Zerotrim a bit vicious

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#827]
Bry_.Zerotrim("0") returns "" (empty)

it should return "0"

a way is to replace the line

    if (dp && spos > 0)
with

    // or if only a zero
    if ((dp && spos > 0) || (spos == 1 && len == 1))

**Comment by gnosygnu** [comment]
Hey, sorry again for the inactivity on my side, but schedule has been rough.

Regarding the issue above, this is actually in myxowa, not in xowa. Here's the code-link for myxowa: https://github.com/desb42/myxowa/blob/9a8733451f2aa98eb85ac7e59398027f21edb3c6/100_core/src/gplx/Bry_.java#L1260

This looks like it's related to Maplink / Mapframe stuff which I haven't incorporated yet into the xowa code-base. Will keep it in mind when I catch up to it.

Thanks!

**Comment by desb42** [comment]
Oops, I was convinced there was a zerotrim in xowa - but did not check
