### ISSUE TITLE
On Android, Page Not Found error when using .xowa files

### ISSUE THREAD

**Issue by mikemasi** [gnosygnu/xowa#83]
Hello,
When trying to use .xowa files downloaded from archive.org, I receive a "Page Not Found" error, even on pages navigated to by the "Random" option.
I downloaded the .xowa files from archive.org, from the full en.wikipedia.org set.  I am placing the files in /storage/extSdCard/Android/data/org.xowa/ and then clicking Xowa from the menu, and using the blue folder icon to navigate to the same, then picking en.wikipedia.org-core.xowa (or any of the other files from archive.org).  Then clicking the en.wikipedia.org link says "Main Page"  "Page not found"
Any help would be greatly appreciated.
Thank you,
Mike

**Comment by mikemasi** [comment]
Android App v 2.1.159-r-2016-09-11
Log output:
     0|20160918_031622.153|INFO|app.create.bgn|
     0|20160918_031622.386|INFO|app.create.end|
     0|20160918_031622.538|INFO|pageActivity.onCreate.bgn|
     0|20160918_031622.869|INFO|app.boot:boot env|
     0|20160918_031622.906|INFO|app.boot:device info|version_code=159|android_os=21|device_type=samsung:SAMSUNG-SGH-I337|
     0|20160918_031622.909|INFO|app.boot:device misc|Network.isWifi=false|getExternalStorageDirectory=/storage/emulated/0|EXTERNAL_STORAGE=/storage/emulated/legacy|SECONDARY_STORAGE=/storage/extSdCard|getExternalFilesDirs=/storage/emulated/0/Android/data/org.xowa/files:/storage/extSdCard/Android/data/org.xowa/files:|getExternalCacheDirs=/storage/emulated/0/Android/data/org.xowa/cache:/storage/extSdCard/Android/data/org.xowa/cache:|
     0|20160918_031622.909|INFO|app.boot:boot app|
     0|20160918_031622.931|INFO|conn_open|url=/data/data/org.xowa/files/usr-anonymous.sqlite3|
     0|20160918_031622.963|INFO|fsys_mgr:root_dir|root=/storage/extSdCard/Android/data/org.xowa/files/xowa|
     0|20160918_031622.963|INFO|app.boot:init app.bgn|
     0|20160918_031623.285|INFO|app.boot:init app.end|
     0|20160918_031623.347|INFO|xo.io:media scan|urls=/storage/extSdCard/Android/data/org.xowa/files/xowa/user/anonymous/app/tmp/xolog/20160918_111623.log|
     0|20160918_031623.355|INFO|sync files|
     0|20160918_031630.121|INFO|xo.io:media scan|urls=/storage/extSdCard/Android/data/org.xowa/files/xowa/bin/any/xowa/wiki/home/home.xowa.version:/storage/extSdCard/Android/data/org.xowa/files/xowa/bin/any/xowa/wiki/home/home.xowa|
     0|20160918_031631.948|INFO|xo.io:media scan|urls=/storage/extSdCard/Android/data/org.xowa/files/xowa/bin/any/xowa/addon/bldr/central/bldr_central.data_db.xowa.version:/storage/extSdCard/Android/data/org.xowa/files/xowa/bin/any/xowa/addon/bldr/central/bldr_central.data_db.xowa|
     0|20160918_031631.959|INFO|init user.anonymous.db.bgn|
     0|20160918_031632.065|INFO|init load user wikis|
     0|20160918_031632.124|INFO|init home db|
     0|20160918_031632.125|INFO|conn_open|url=/storage/extSdCard/Android/data/org.xowa/files/xowa/bin/any/xowa/wiki/home/home.xowa|
     0|20160918_031632.250|INFO|conn_open|url=/storage/extSdCard/Android/data/org.xowa/files/xowa/bin/any/xowa/wiki/home/home.xowa|
     0|20160918_031632.296|INFO|init home db.end|
     0|20160918_031632.296|INFO|app.boot:boot env|
     0|20160918_031632.296|INFO|app.boot:device info|version_code=159|android_os=21|device_type=samsung:SAMSUNG-SGH-I337|
     0|20160918_031632.299|INFO|app.boot:device misc|Network.isWifi=false|getExternalStorageDirectory=/storage/emulated/0|EXTERNAL_STORAGE=/storage/emulated/legacy|SECONDARY_STORAGE=/storage/extSdCard|getExternalFilesDirs=/storage/emulated/0/Android/data/org.xowa/files:/storage/extSdCard/Android/data/org.xowa/files:|getExternalCacheDirs=/storage/emulated/0/Android/data/org.xowa/cache:/storage/extSdCard/Android/data/org.xowa/cache:|
     0|20160918_031632.299|INFO|app.boot:boot app|
     0|20160918_031632.300|INFO|fsys_mgr:root_dir|root=/storage/extSdCard/Android/data/org.xowa/files/xowa|
     0|20160918_031632.300|INFO|app.boot:init app.bgn|
     0|20160918_031632.314|INFO|app.boot:init app.end|
     0|20160918_031632.316|INFO|xo.io:media scan|urls=/storage/extSdCard/Android/data/org.xowa/files/xowa/user/anonymous/app/tmp/xolog/20160918_111632.log|
     0|20160918_031632.317|INFO|sync files|
     0|20160918_031632.659|INFO|xo.io:media scan|urls=/storage/extSdCard/Android/data/org.xowa/files/xowa/bin/any/xowa/wiki/home/home.xowa.version:/storage/extSdCard/Android/data/org.xowa/files/xowa/bin/any/xowa/wiki/home/home.xowa|
     0|20160918_031632.703|INFO|xo.io:media scan|urls=/storage/extSdCard/Android/data/org.xowa/files/xowa/bin/any/xowa/addon/bldr/central/bldr_central.data_db.xowa.version:/storage/extSdCard/Android/data/org.xowa/files/xowa/bin/any/xowa/addon/bldr/central/bldr_central.data_db.xowa|
     0|20160918_031632.706|INFO|init user.anonymous.db.bgn|
     0|20160918_031632.722|INFO|init load user wikis|
     0|20160918_031632.732|INFO|init home db|
     0|20160918_031632.802|INFO|conn_open|url=/storage/extSdCard/Android/data/org.xowa/files/xowa/bin/any/xowa/wiki/home/home.xowa|
     0|20160918_031632.873|INFO|init home db.end|
     0|20160918_031632.910|INFO|pageActivity.onCreate.end|
     0|20160918_031634.754|INFO|Get_page_or_load.bgn|title=Prince Felix Yusupov|
     0|20160918_031634.773|INFO|conn_open|url=/storage/extSdCard/Android/data/org.xowa/en.wikipedia.org-core.xowa|
     0|20160918_031635.025|INFO|conn_open|url=/storage/extSdCard/Android/data/org.xowa/en.wikipedia.org-text-ns.000.xowa|
     0|20160918_031635.274|INFO|conn_open|url=/storage/extSdCard/Android/data/org.xowa/en.wikipedia.org-text-ns.000-db.002.xowa|
     0|20160918_031635.517|INFO|conn_open|url=/storage/extSdCard/Android/data/org.xowa/en.wikipedia.org-text-ns.000-db.003.xowa|
     0|20160918_031635.772|INFO|conn_open|url=/storage/extSdCard/Android/data/org.xowa/en.wikipedia.org-text-ns.000-db.004.xowa|
     0|20160918_031636.049|INFO|conn_open|url=/storage/extSdCard/Android/data/org.xowa/en.wikipedia.org-text-ns.000-db.005.xowa|
     0|20160918_031636.318|INFO|conn_open|url=/storage/extSdCard/Android/data/org.xowa/en.wikipedia.org-text-ns.000-db.006.xowa|
     0|20160918_031636.582|INFO|conn_open|url=/storage/extSdCard/Android/data/org.xowa/en.wikipedia.org-text-ns.000-db.007.xowa|
     0|20160918_031636.833|INFO|conn_open|url=/storage/extSdCard/Android/data/org.xowa/en.wikipedia.org-text-ns.000-db.008.xowa|
     0|20160918_031637.081|INFO|conn_open|url=/storage/extSdCard/Android/data/org.xowa/en.wikipedia.org-text-ns.000-db.009.xowa|
     0|20160918_031637.206|INFO|conn_open|url=/storage/extSdCard/Android/data/org.xowa/en.wikipedia.org-xtn.search.core.xowa|
     0|20160918_031637.231|INFO|conn_open|url=/storage/extSdCard/Android/data/org.xowa/en.wikipedia.org-file-core.xowa|
     0|20160918_031637.247|INFO|conn_open|url=/storage/extSdCard/Android/data/org.xowa/en.wikipedia.org-file-user.xowa|
     0|20160918_031637.312|INFO|Get_page_or_load.load|
     0|20160918_031637.320|INFO|Get_page_or_load.end|
     0|20160918_031637.334|INFO|Get_page_or_load.bgn|title=Prince Felix Yusupov|
     0|20160918_031712.725|INFO|Get_page_or_load.bgn|title=Main Page|
     0|20160918_031712.742|INFO|Get_page_or_load.load|
     0|20160918_031712.753|INFO|Get_page_or_load.end|
     0|20160918_031712.765|INFO|Get_page_or_load.bgn|title=Main Page|
     0|20160918_031713.015|INFO|Get_page_or_load.bgn|title=Special:XowaWikis|
     0|20160918_031713.025|INFO|Get_page_or_load.load|
     0|20160918_031713.039|INFO|Get_page_or_load.end|
     0|20160918_031713.047|INFO|Get_page_or_load.bgn|title=Special:XowaWikis|
     0|20160918_031713.347|INFO|Get_page_or_load.bgn|title=Main Page|
     0|20160918_031713.351|INFO|Get_page_or_load.load|
     0|20160918_031713.353|INFO|Get_page_or_load.end|
     0|20160918_031713.356|INFO|Get_page_or_load.bgn|title=Main Page|
     0|20160918_031714.296|INFO|Get_page_or_load.bgn|title=Special:XowaWikis|
     0|20160918_031714.301|INFO|Get_page_or_load.load|
     0|20160918_031714.312|INFO|Get_page_or_load.end|
     0|20160918_031714.317|INFO|Get_page_or_load.bgn|title=Special:XowaWikis|
     0|20160918_031715.795|INFO|Get_page_or_load.bgn|title=Main Page|
     0|20160918_031715.804|INFO|Get_page_or_load.load|
     0|20160918_031715.812|INFO|Get_page_or_load.end|
     0|20160918_031715.814|INFO|Get_page_or_load.bgn|title=Main Page|
     0|20160918_031717.822|INFO|Get_page_or_load.bgn|title=Special:XowaLog|
     0|20160918_031717.896|INFO|Get_page_or_load.load|
     0|20160918_031717.911|INFO|Get_page_or_load.end|
     0|20160918_031717.920|INFO|Get_page_or_load.bgn|title=Special:XowaLog|
     0|20160918_031719.384|INFO|Get_page_or_load.bgn|title=Special:XowaWikis?cmd=add&file=/storage/extSdCard/Android/data/org.xowa/en.wikipedia.org-core.xowa|
     0|20160918_031719.733|INFO|Get_page_or_load.load|
     0|20160918_031719.742|INFO|Get_page_or_load.end|
     0|20160918_031719.747|INFO|Get_page_or_load.bgn|title=Special:XowaWikis?cmd=add&file=/storage/extSdCard/Android/data/org.xowa/en.wikipedia.org-core.xowa|
     0|20160918_031720.363|INFO|Get_page_or_load.bgn|title=Special:XowaFileBrowser?path=/storage/extSdCard/Android/data/org.xowa/&dir cmd=xodir|
     0|20160918_031720.425|INFO|Get_page_or_load.load|
     0|20160918_031720.434|INFO|Get_page_or_load.end|
     0|20160918_031720.442|INFO|Get_page_or_load.bgn|title=Special:XowaFileBrowser?path=/storage/extSdCard/Android/data/org.xowa/&dir cmd=xodir|
     0|20160918_031830.258|INFO|Get_page_or_load.bgn|title=Special:XowaFileBrowser?path=/storage/extSdCard/Android/data/&dir cmd=xodir|
     0|20160918_031830.302|INFO|Get_page_or_load.load|
     0|20160918_031830.310|INFO|Get_page_or_load.end|
     0|20160918_031830.320|INFO|Get_page_or_load.bgn|title=Special:XowaFileBrowser?path=/storage/extSdCard/Android/data/&dir cmd=xodir|
     0|20160918_031831.567|INFO|Get_page_or_load.bgn|title=Special:XowaFileBrowser?path=/storage/extSdCard/Android/&dir cmd=xodir|
     0|20160918_031831.570|INFO|Get_page_or_load.load|
     0|20160918_031831.574|INFO|Get_page_or_load.end|
     0|20160918_031831.578|INFO|Get_page_or_load.bgn|title=Special:XowaFileBrowser?path=/storage/extSdCard/Android/&dir cmd=xodir|
     0|20160918_031833.117|INFO|Get_page_or_load.bgn|title=Special:XowaFileBrowser?path=/storage/extSdCard/&dir cmd=xodir|
     0|20160918_031833.148|INFO|Get_page_or_load.load|
     0|20160918_031833.168|INFO|Get_page_or_load.end|
     0|20160918_031833.180|INFO|Get_page_or_load.bgn|title=Special:XowaFileBrowser?path=/storage/extSdCard/&dir cmd=xodir|
     0|20160918_031834.048|INFO|Get_page_or_load.bgn|title=Special:XowaFileBrowser?path=/storage/&dir cmd=xodir|
     0|20160918_031834.055|INFO|Get_page_or_load.load|
     0|20160918_031834.064|INFO|Get_page_or_load.end|
     0|20160918_031834.067|INFO|Get_page_or_load.bgn|title=Special:XowaFileBrowser?path=/storage/&dir cmd=xodir|
     0|20160918_031834.855|INFO|Get_page_or_load.bgn|title=Special:XowaFileBrowser?path=/&dir cmd=xodir|
     0|20160918_031834.908|INFO|Get_page_or_load.load|
     0|20160918_031834.912|INFO|Get_page_or_load.end|
     0|20160918_031834.918|INFO|Get_page_or_load.bgn|title=Special:XowaFileBrowser?path=/&dir cmd=xodir|
     0|20160918_031835.776|INFO|Get_page_or_load.bgn|title=Special:XowaFileBrowser?path=/data/&dir cmd=xodir|
     0|20160918_031835.780|INFO|Get_page_or_load.load|
     0|20160918_031835.787|INFO|Get_page_or_load.end|
     0|20160918_031835.791|INFO|Get_page_or_load.bgn|title=Special:XowaFileBrowser?path=/data/&dir cmd=xodir|
     0|20160918_031836.990|INFO|Get_page_or_load.bgn|title=Special:XowaFileBrowser?dir cmd=xodir&path=/|
     0|20160918_031837.048|INFO|Get_page_or_load.load|
     0|20160918_031837.055|INFO|Get_page_or_load.end|
     0|20160918_031837.063|INFO|Get_page_or_load.bgn|title=Special:XowaFileBrowser?dir cmd=xodir&path=/|
     0|20160918_031838.172|INFO|Get_page_or_load.bgn|title=Special:XowaDownloadCentral|
     0|20160918_031838.187|INFO|conn_open|url=/storage/extSdCard/Android/data/org.xowa/files/xowa/bin/any/xowa/addon/bldr/central/bldr_central.data_db.xowa|
     0|20160918_031838.226|INFO|task_mgr.load_or_init.bgn|
     0|20160918_031838.251|INFO|Get_page_or_load.load|
     0|20160918_031838.258|INFO|Get_page_or_load.end|
     0|20160918_031838.261|INFO|Get_page_or_load.bgn|title=Special:XowaDownloadCentral|
     0|20160918_031839.074|INFO|task_mgr.reload.bgn|
     0|20160918_031846.688|INFO|Get_page_or_load.bgn|title=Special:XowaRootDir|
     0|20160918_031846.715|INFO|Get_page_or_load.load|
     0|20160918_031846.719|INFO|Get_page_or_load.end|
     0|20160918_031846.732|INFO|Get_page_or_load.bgn|title=Special:XowaRootDir|
     0|20160918_031846.735|INFO|Get_page_or_load.bgn|title=Special:XowaRootDir|
     0|20160918_031849.364|INFO|Get_page_or_load.bgn|title=Special:XowaDownloadCentral|
     0|20160918_031849.366|INFO|task_mgr.load_or_init.bgn|
     0|20160918_031849.379|INFO|Get_page_or_load.load|
     0|20160918_031849.399|INFO|Get_page_or_load.end|
     0|20160918_031849.404|INFO|Get_page_or_load.bgn|title=Special:XowaDownloadCentral|
     0|20160918_031849.591|INFO|task_mgr.reload.bgn|
     0|20160918_031901.798|INFO|Get_page_or_load.bgn|title=Special:XowaWikis|
     0|20160918_031901.803|INFO|Get_page_or_load.load|
     0|20160918_031901.817|INFO|Get_page_or_load.end|
     0|20160918_031901.833|INFO|Get_page_or_load.bgn|title=Special:XowaWikis|
     0|20160918_031901.837|INFO|Get_page_or_load.bgn|title=Special:XowaWikis|
     0|20160918_031926.002|INFO|Get_page_or_load.bgn|title=Special:XowaFileBrowser?path=/|
     0|20160918_031926.045|INFO|Get_page_or_load.load|
     0|20160918_031926.050|INFO|Get_page_or_load.end|
     0|20160918_031926.074|INFO|Get_page_or_load.bgn|title=Special:XowaFileBrowser?path=/|
     0|20160918_031926.079|INFO|Get_page_or_load.bgn|title=Special:XowaFileBrowser?path=/|
     0|20160918_031929.972|INFO|Get_page_or_load.bgn|title=Special:XowaFileBrowser?path=/storage/&dir cmd=|
     0|20160918_031929.977|INFO|Get_page_or_load.load|
     0|20160918_031929.981|INFO|Get_page_or_load.end|
     0|20160918_031929.987|INFO|Get_page_or_load.bgn|title=Special:XowaFileBrowser?path=/storage/&dir cmd=|
     0|20160918_031929.992|INFO|Get_page_or_load.bgn|title=Special:XowaFileBrowser?path=/storage/&dir cmd=|
     0|20160918_031932.225|INFO|Get_page_or_load.bgn|title=Special:XowaFileBrowser?path=/storage/extSdCard/&dir cmd=|
     0|20160918_031932.246|INFO|Get_page_or_load.load|
     0|20160918_031932.271|INFO|Get_page_or_load.end|
     0|20160918_031932.304|INFO|Get_page_or_load.bgn|title=Special:XowaFileBrowser?path=/storage/extSdCard/&dir cmd=|
     0|20160918_031932.331|INFO|Get_page_or_load.bgn|title=Special:XowaFileBrowser?path=/storage/extSdCard/&dir cmd=|
     0|20160918_031936.231|INFO|Get_page_or_load.bgn|title=Special:XowaFileBrowser?path=/storage/extSdCard/Android/&dir cmd=|
     0|20160918_031936.239|INFO|Get_page_or_load.load|
     0|20160918_031936.243|INFO|Get_page_or_load.end|
     0|20160918_031936.250|INFO|Get_page_or_load.bgn|title=Special:XowaFileBrowser?path=/storage/extSdCard/Android/&dir cmd=|
     0|20160918_031936.252|INFO|Get_page_or_load.bgn|title=Special:XowaFileBrowser?path=/storage/extSdCard/Android/&dir cmd=|
     0|20160918_031937.795|INFO|Get_page_or_load.bgn|title=Special:XowaFileBrowser?path=/storage/extSdCard/Android/data/&dir cmd=|
     0|20160918_031937.832|INFO|Get_page_or_load.load|
     0|20160918_031937.858|INFO|Get_page_or_load.end|
     0|20160918_031937.871|INFO|Get_page_or_load.bgn|title=Special:XowaFileBrowser?path=/storage/extSdCard/Android/data/&dir cmd=|
     0|20160918_031937.887|INFO|Get_page_or_load.bgn|title=Special:XowaFileBrowser?path=/storage/extSdCard/Android/data/&dir cmd=|
     0|20160918_031941.909|INFO|Get_page_or_load.bgn|title=Special:XowaFileBrowser?path=/storage/extSdCard/Android/data/org.xowa/&dir cmd=|
     0|20160918_031941.947|INFO|Get_page_or_load.load|
     0|20160918_031941.951|INFO|Get_page_or_load.end|
     0|20160918_031941.960|INFO|Get_page_or_load.bgn|title=Special:XowaFileBrowser?path=/storage/extSdCard/Android/data/org.xowa/&dir cmd=|
     0|20160918_031941.965|INFO|Get_page_or_load.bgn|title=Special:XowaFileBrowser?path=/storage/extSdCard/Android/data/org.xowa/&dir cmd=|
     0|20160918_032010.579|INFO|Get_page_or_load.bgn|title=Special:XowaWikis?cmd=add&file=/storage/extSdCard/Android/data/org.xowa/en.wikipedia.org-core.xowa|
     0|20160918_032010.581|INFO|conn_open|url=/storage/extSdCard/Android/data/org.xowa/en.wikipedia.org-core.xowa|
     0|20160918_032010.632|INFO|conn_open|url=/storage/extSdCard/Android/data/org.xowa/en.wikipedia.org-text-ns.000.xowa|
     0|20160918_032010.673|INFO|conn_open|url=/storage/extSdCard/Android/data/org.xowa/en.wikipedia.org-text-ns.000-db.002.xowa|
     0|20160918_032010.686|INFO|conn_open|url=/storage/extSdCard/Android/data/org.xowa/en.wikipedia.org-text-ns.000-db.003.xowa|
     0|20160918_032010.694|INFO|conn_open|url=/storage/extSdCard/Android/data/org.xowa/en.wikipedia.org-text-ns.000-db.004.xowa|
     0|20160918_032010.707|INFO|conn_open|url=/storage/extSdCard/Android/data/org.xowa/en.wikipedia.org-text-ns.000-db.005.xowa|
     0|20160918_032010.721|INFO|conn_open|url=/storage/extSdCard/Android/data/org.xowa/en.wikipedia.org-text-ns.000-db.006.xowa|
     0|20160918_032010.737|INFO|conn_open|url=/storage/extSdCard/Android/data/org.xowa/en.wikipedia.org-text-ns.000-db.007.xowa|
     0|20160918_032010.751|INFO|conn_open|url=/storage/extSdCard/Android/data/org.xowa/en.wikipedia.org-text-ns.000-db.008.xowa|
     0|20160918_032010.771|INFO|conn_open|url=/storage/extSdCard/Android/data/org.xowa/en.wikipedia.org-text-ns.000-db.009.xowa|
     0|20160918_032010.952|INFO|conn_open|url=/storage/extSdCard/Android/data/org.xowa/en.wikipedia.org-xtn.search.core.xowa|
     0|20160918_032010.995|INFO|conn_open|url=/storage/extSdCard/Android/data/org.xowa/en.wikipedia.org-file-core.xowa|
     0|20160918_032011.021|INFO|conn_open|url=/storage/extSdCard/Android/data/org.xowa/en.wikipedia.org-file-user.xowa|
     0|20160918_032011.081|INFO|Get_page_or_load.load|
     0|20160918_032011.085|INFO|Get_page_or_load.end|
     0|20160918_032011.091|INFO|Get_page_or_load.bgn|title=Special:XowaWikis?cmd=add&file=/storage/extSdCard/Android/data/org.xowa/en.wikipedia.org-core.xowa|
     0|20160918_032011.093|INFO|Get_page_or_load.bgn|title=Special:XowaWikis?cmd=add&file=/storage/extSdCard/Android/data/org.xowa/en.wikipedia.org-core.xowa|
     0|20160918_032012.664|INFO|Get_page_or_load.bgn|title=Main Page|
     0|20160918_032012.685|INFO|conn_open|url=/storage/extSdCard/Android/data/org.xowa/en.wikipedia.org-core.xowa|
     0|20160918_032012.702|INFO|conn_open|url=/storage/extSdCard/Android/data/org.xowa/en.wikipedia.org-text-ns.000.xowa|
     0|20160918_032012.748|INFO|conn_open|url=/storage/extSdCard/Android/data/org.xowa/en.wikipedia.org-text-ns.000-db.002.xowa|
     0|20160918_032012.761|INFO|conn_open|url=/storage/extSdCard/Android/data/org.xowa/en.wikipedia.org-text-ns.000-db.003.xowa|
     0|20160918_032012.767|INFO|conn_open|url=/storage/extSdCard/Android/data/org.xowa/en.wikipedia.org-text-ns.000-db.004.xowa|
     0|20160918_032012.779|INFO|conn_open|url=/storage/extSdCard/Android/data/org.xowa/en.wikipedia.org-text-ns.000-db.005.xowa|
     0|20160918_032012.792|INFO|conn_open|url=/storage/extSdCard/Android/data/org.xowa/en.wikipedia.org-text-ns.000-db.006.xowa|
     0|20160918_032012.804|INFO|conn_open|url=/storage/extSdCard/Android/data/org.xowa/en.wikipedia.org-text-ns.000-db.007.xowa|
     0|20160918_032012.816|INFO|conn_open|url=/storage/extSdCard/Android/data/org.xowa/en.wikipedia.org-text-ns.000-db.008.xowa|
     0|20160918_032012.834|INFO|conn_open|url=/storage/extSdCard/Android/data/org.xowa/en.wikipedia.org-text-ns.000-db.009.xowa|
     0|20160918_032013.019|INFO|conn_open|url=/storage/extSdCard/Android/data/org.xowa/en.wikipedia.org-xtn.search.core.xowa|
     0|20160918_032013.048|INFO|conn_open|url=/storage/extSdCard/Android/data/org.xowa/en.wikipedia.org-file-core.xowa|
     0|20160918_032013.057|INFO|conn_open|url=/storage/extSdCard/Android/data/org.xowa/en.wikipedia.org-file-user.xowa|
     0|20160918_032013.090|INFO|Get_page_or_load.load|
     0|20160918_032013.091|INFO|Get_page_or_load.end|
     0|20160918_032013.098|INFO|Get_page_or_load.bgn|title=Main Page|
     0|20160918_032013.102|INFO|Get_page_or_load.load|
     0|20160918_032013.105|INFO|Get_page_or_load.end|
     0|20160918_032013.108|INFO|Get_page_or_load.bgn|title=Main Page|
     0|20160918_032013.114|INFO|Get_page_or_load.load|
     0|20160918_032013.118|INFO|Get_page_or_load.end|
     0|20160918_032015.297|INFO|Get_page_or_load.bgn|title=Special:XowaWikis?cmd=add&file=/storage/extSdCard/Android/data/org.xowa/en.wikipedia.org-core.xowa|
     0|20160918_032015.769|INFO|Get_page_or_load.load|
     0|20160918_032015.773|INFO|Get_page_or_load.end|
     0|20160918_032015.778|INFO|Get_page_or_load.bgn|title=Special:XowaWikis?cmd=add&file=/storage/extSdCard/Android/data/org.xowa/en.wikipedia.org-core.xowa|
     0|20160918_032030.132|INFO|Get_page_or_load.bgn|title=Main Page|
     0|20160918_032030.166|INFO|conn_open|url=/storage/extSdCard/Android/data/org.xowa/en.wikipedia.org-core.xowa|
     0|20160918_032030.181|INFO|conn_open|url=/storage/extSdCard/Android/data/org.xowa/en.wikipedia.org-text-ns.000.xowa|
     0|20160918_032030.255|INFO|conn_open|url=/storage/extSdCard/Android/data/org.xowa/en.wikipedia.org-text-ns.000-db.002.xowa|
     0|20160918_032030.277|INFO|conn_open|url=/storage/extSdCard/Android/data/org.xowa/en.wikipedia.org-text-ns.000-db.003.xowa|
     0|20160918_032030.284|INFO|conn_open|url=/storage/extSdCard/Android/data/org.xowa/en.wikipedia.org-text-ns.000-db.004.xowa|
     0|20160918_032030.299|INFO|conn_open|url=/storage/extSdCard/Android/data/org.xowa/en.wikipedia.org-text-ns.000-db.005.xowa|
     0|20160918_032030.313|INFO|conn_open|url=/storage/extSdCard/Android/data/org.xowa/en.wikipedia.org-text-ns.000-db.006.xowa|
     0|20160918_032030.327|INFO|conn_open|url=/storage/extSdCard/Android/data/org.xowa/en.wikipedia.org-text-ns.000-db.007.xowa|
     0|20160918_032030.340|INFO|conn_open|url=/storage/extSdCard/Android/data/org.xowa/en.wikipedia.org-text-ns.000-db.008.xowa|
     0|20160918_032030.361|INFO|conn_open|url=/storage/extSdCard/Android/data/org.xowa/en.wikipedia.org-text-ns.000-db.009.xowa|
     0|20160918_032030.604|INFO|conn_open|url=/storage/extSdCard/Android/data/org.xowa/en.wikipedia.org-xtn.search.core.xowa|
     0|20160918_032030.642|INFO|conn_open|url=/storage/extSdCard/Android/data/org.xowa/en.wikipedia.org-file-core.xowa|
     0|20160918_032030.652|INFO|conn_open|url=/storage/extSdCard/Android/data/org.xowa/en.wikipedia.org-file-user.xowa|
     0|20160918_032030.690|INFO|Get_page_or_load.load|
     0|20160918_032030.699|INFO|Get_page_or_load.end|
     0|20160918_032030.712|INFO|Get_page_or_load.bgn|title=Main Page|
     0|20160918_032030.717|INFO|Get_page_or_load.load|
     0|20160918_032030.724|INFO|Get_page_or_load.end|
     0|20160918_032030.733|INFO|Get_page_or_load.bgn|title=Main Page|
     0|20160918_032030.738|INFO|Get_page_or_load.load|
     0|20160918_032030.740|INFO|Get_page_or_load.end|
     0|20160918_032120.723|INFO|Get_page_or_load.bgn|title=Special:XowaLog|
     0|20160918_032120.828|INFO|Get_page_or_load.load|
     0|20160918_032120.833|INFO|Get_page_or_load.end|
     0|20160918_032120.840|INFO|Get_page_or_load.bgn|title=Special:XowaLog|
     0|20160918_032120.847|INFO|Get_page_or_load.bgn|title=Special:XowaLog|
     0|20160918_032242.229|INFO|Get_page_or_load.bgn|title=Special:XowaLog?cmd=email&file=20160918 111632|
     0|20160918_032242.297|INFO|Get_page_or_load.load|
     0|20160918_032242.304|INFO|Get_page_or_load.end|
     0|20160918_032242.346|INFO|Get_page_or_load.bgn|title=Special:XowaLog?cmd=email&file=20160918 111632|
     0|20160918_032242.355|INFO|Get_page_or_load.bgn|title=Special:XowaLog?cmd=email&file=20160918 111632|
     0|20160918_032724.647|INFO|Get_page_or_load.bgn|title=Special:XowaLog|
     0|20160918_032724.670|INFO|Get_page_or_load.load|
     0|20160918_032724.676|INFO|Get_page_or_load.end|
     0|20160918_032724.683|INFO|Get_page_or_load.bgn|title=Special:XowaLog|
     0|20160918_032726.108|INFO|Get_page_or_load.bgn|title=Main Page|
     0|20160918_032726.113|INFO|Get_page_or_load.load|
     0|20160918_032726.116|INFO|Get_page_or_load.end|
     0|20160918_032726.118|INFO|Get_page_or_load.bgn|title=Main Page|
     0|20160918_032730.743|INFO|Get_page_or_load.bgn|title=Special:XowaLog|
     0|20160918_032730.766|INFO|Get_page_or_load.load|
     0|20160918_032730.775|INFO|Get_page_or_load.end|
     0|20160918_032730.807|INFO|Get_page_or_load.bgn|title=Special:XowaLog|
     0|20160918_032730.812|INFO|Get_page_or_load.bgn|title=Special:XowaLog|
     0|20160918_032732.176|INFO|Get_page_or_load.bgn|title=Special:XowaLog?cmd=email&file=20160918 111632|

**Comment by gnosygnu** [comment]
Hi! Thanks for the well-detailed question and the log file!

The short answer is that you actually need HTML dbs (<code>-html-</code>) not Wikitext dbs (<code>-text-</code>). Please download the urls listed below, or better yet, use Download Central (the blue down arrow icon). Download Central will download all the urls for you, unzip them, and move them into the right location

A longer answer follows. Let me know if you need more info. Thanks!

* Your log file shows that your files are Wikitext files. For example, see https://gist.github.com/gnosygnu/82633760e86c96a2da4f97254be00943#file-issue_83_android_setup-L42
* XOWA Android can only use HTML dbs. XOWA desktop can use both HTML and Wikitext dbs. For more info, you can read http://xowa.org/home/wiki/App/Databases/Overview.html
* Finally, keep in mind that the URLs below are for 2016-08. I'll be pushing 2016-09 in the next few days.

Hope this helps

```
https://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2016-08_core.zip
https://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2016-08_html.zip
https://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2016-08_html_db.002.zip
https://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2016-08_html_db.003.zip
https://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2016-08_html_db.004.zip
https://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2016-08_html_db.005.zip
https://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2016-08_html_db.006.zip
https://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2016-08_html_db.007.zip
https://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2016-08_html_db.008.zip
https://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2016-08_html_db.009.zip
https://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2016-08_html_db.010.zip
https://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2016-08_html_db.011.zip
https://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2016-08_html_db.012.zip
https://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2016-08_html_db.013.zip
https://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2016-08_html_db.014.zip
https://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2016-08_html_db.015.zip
https://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2016-08_html_db.016.zip
https://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2016-08_html_db.017.zip
https://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2016-08_html_db.018.zip
https://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2016-08_xtn.search.core.zip
```

**Comment by mikemasi** [comment]
OK, Thank you.

**Comment by mikemasi** [comment]
That brings things to 27GB from 18GB...  I'm guessing this has to do with the mentioned problem with slowness with on-the-fly conversion of db content to html, so you are pre-building the html.
Might I suggest putting a comment stating what you said above here:
http://xowa.org/home/wiki/App/Import/English_Wikipedia.html
and also here: https://archive.org/details/Xowa_enwiki_latest
so people don't download the wikitext db files and expect them to work on Android?
Thank you again, especially for your prompt reply.
Mike

**Comment by gnosygnu** [comment]
Cool. Thanks for the follow-up

> That brings things to 27GB from 18GB... I'm guessing this has to do with the mentioned problem with slowness with on-the-fly conversion of db content to html, so you are pre-building the html.

Yup. The HTML databases are larger because the Wikitext is generally more succinct -- especially for templates.

> Might I suggest putting a comment stating what you said above here:
> http://xowa.org/home/wiki/App/Import/English_Wikipedia.html
> and also here: https://archive.org/details/Xowa_enwiki_latest

No problem. I updated them now by just explicitly adding the URLs. Let me know if you had something else in mind

> Thank you again, especially for your prompt reply.

My pleasure. Thank you for the feedback!
