### ISSUE TITLE
Xowa torrent download

### ISSUE THREAD

**Issue by amatula11** [gnosygnu/xowa#84]
So I had multiple issues with importing the files/pictures through Xowa so looking through the site, I came across the torrent (455 gb) and it looked like this had all the photos and pages in it along with other wikis. So I downloaded it, and what is the next step? Do I extract all the files (highlighting everything and right clicking> drop down menu appears saying extract all) to the root file of the original Xowa program with the jar file in it? a little more info is I have it all on an external hard drive and it is not on my normal C drive

**Comment by gnosygnu** [comment]
Hi! Thanks for the detailed question.

Yup, the torrent currently weighs in at 455 GB. Most of these are old files, and I'm trying to get archive.org to move them.

For all intents and purposes, you only need the files listed here: https://gist.github.com/gnosygnu/bce3f1b5efbd70fc460cac1c87e9ffc5 . Most BitTorrent files will allow you to selectively download files, so try to pick only the files you're interested in.

When you're done downloading them, you should move them to C:\xowa\wiki\en.wikipedia.org . For example, you should have a file called C:\xowa\wiki\en.wikipedia.org\en.wikipedia.org-core.xowa.

All other wikis follow a similar pattern, where the files go into wiki\wiki_domain. If you're downloading wiktionary, then they need to go to C:\xowa\wiki\en.wiktionary.org . 

Hope this helps. Thanks!

**Comment by amatula11** [comment]
Thank you for such a quick reply.  Does the torrent have the photos as well?

**Comment by gnosygnu** [comment]
Sorry! I missed this reply a week ago, and didn't notice it till now. My apologies!

Yes, the torrent does have images. The gist link above breaks it down into 3 sections:
* The main bulk set from 2016-06
* Updates for 2016-07
* Updates for 2016-08

If you download all the links in those three sections, you'll have all the images for English Wikipedia.

Let me know if that makes sense. Thanks!

**Comment by gnosygnu** [comment]
Hi! I'm marking this issue closed for now. Sorry again about the late reply. Let me know if you still need other info, and I'll reopen the issue. Thanks!
