### ISSUE TITLE
Pressing backspace key on search box

### ISSUE THREAD

**Issue by GoblinLegislator** [gnosygnu/xowa#841]
![Untitled](https://user-images.githubusercontent.com/76570449/107718518-664c2700-6cd6-11eb-8c8d-fcc2e8bc545b.jpg)

**Comment by gnosygnu** [comment]
Hey. Thanks for the report and sorry for the slow resolution on my side.

I made a fix for the issue and it will be part of the next release. In the meantime, I like to give credit to users who report issues. There will be a line in the next XOWA change log with something like this `Gui: Fix NullPointerException when pressing backspace on empty search box [#841] {reported by anonymous}`. Let me know if you'd like to be referred to by a nickname or would rather remain anonymous.

Thanks again!

**Comment by ghost** [comment]
Nice. Just say use **NijazM**, my previous username.
