### ISSUE TITLE
gnosyyyyyyyy

### ISSUE THREAD

**Issue by and00r** [gnosygnu/xowa#86]
hi

**Comment by gnosygnu** [comment]
Hi. I'm not sure what this issue is about. I'm marking it off-topic for now, and will close it in a few days. Let me know if there was something specific you wanted to discuss. Thanks.

**Comment by and00r** [comment]
its definitely off topic. wooooooooooooooo

**Comment by gnosygnu** [comment]
Ok. Thanks for clarifying. I'm going to mark it closed then. Let me know if there's anything else.

**Comment by and00r** [comment]
lol its ok
