### ISSUE TITLE
Use Rembulan (a Lua 5.3 for the JVM) instead of LuaJ?

### ISSUE THREAD

**Issue by mjanicek** [gnosygnu/xowa#89]
I noticed you use LuaJ to run the Wikipedia Lua scripts. I would be very curious to see whether my project Rembulan (over at https://github.com/mjanicek/rembulan) may be of any help! I've written it with use-cases such as XOWA in mind. I'll just copy the first paragraph of the "About" section here for your convenience:

> Rembulan is an implementation of Lua 5.3 for the Java Virtual Machine (JVM), written in pure Java with minimal dependencies. The goal of the Rembulan project is to develop a correct, complete and scalable Lua implementation for running sandboxed Lua programs on the JVM.

It should be an advancement over LuaJ in several aspects. Although some of those might not be directly applicable to Wikipedia Lua scripts (e.g., true coroutines, Lua 5.3 support), I think Rembulan might still be useful since it allows you to limit the time spent executing a given script ("CPU accounting").

Plus, an application like XOWA might be exactly the stress-test Rembulan needs! 😉

**Comment by gnosygnu** [comment]
Hi! First, Rembulan looks very cool. Congrats on a very nice project there!

I would definitely be interested in another Lua engine for XOWA. Obviously, having more options is better than having fewer. ;) More to the point though, you are correct in your estimate of "CPU accounting". I would say that 85% or more of XOWA parsing time is spent in Luaj. As a rough (outdated) benchmark, I used to be able to parse all of English Wikipedia in about 12 hours without Scribunto. Now it takes 80 hours.

I also think that XOWA would be an excellent use case for Rembulan. There are 5+ million pages in English Wikipedia. There are more pages in other languages (German; French; Russian) and other types (notably, Wiktionary). All these wikis / pages use Lua and use them extensively. If Rembulan can handle all the Lua calls in them, then I think you have a pretty well-stress-tested library. ;)

With that said, I think it would be difficult for XOWA to use Rembulan. The primary reason is on the MediaWiki side. Scribunto only supports 5.1 and there are known issues for 5.2. 5.3 would probably add even more issues, as it looks like Lua breaks other features between 5.3 and 5.2 (despite the minor version number upgrade, backward compatibility is not guaranteed). I list more reference below.

Last time, I had a lot of problems getting Luaj (which is 5.2) to work with Scribunto. In the end, I had to do two things:
* Make a number of backports to add 5.1 behavior to 5.2. For example, I added back string.gfind and table.maxn. 
    * There's a partial list here: https://www.mediawiki.org/wiki/Extension:Scribunto/Lua_5.2_changes.
    * I recompiled the luaj jar and distribute an XOWA-flavored version. The source is here: https://github.com/gnosygnu/luaj_xowa
* Change some general Scribunto scripts to work. This involved tinkering with the .lua scripts in https://github.com/wikimedia/mediawiki-extensions-Scribunto/tree/master/engines/LuaStandalone 
    * I ended up creating variants for Luaj: bin/any/xowa/xtns/Scribunto/engines/LuaJ/* (sorry, in the XOWA package; no github link)

Needless to say, this wasn't an easy process, and involved a lot of research / debugging.

If you do want to go that route, and are willing to tinker around with XOWA and Scribunto, here's what you would need to do:
* Integrate a new Lua Engine into XOWA. You'd probably want to look at these classes and replace them with calls to Rembulan:
   * https://github.com/gnosygnu/xowa/blob/master/400_xowa/src/gplx/xowa/xtns/scribunto/engines/luaj/Luaj_server.java
   * https://github.com/gnosygnu/xowa/blob/master/400_xowa/src/gplx/xowa/xtns/scribunto/engines/luaj/Luaj_engine.java
* (Probably) Adjust the scripts in bin/any/xowa/xtns/Scribunto/engines/LuaJ/*
* View home/wiki/Diagnostics/Scribunto/All. (See http://xowa.org/home/wiki/Diagnostics/Scribunto/All)
* Run a full parse of a wiki based on http://xowa.org/home/wiki/Dev/Command-line/Thumbs. The console output will complain about any Lua errors (as well as general XOWA ones)

I'm definitely willing to help in any ways, but please keep in mind that my time is stretched. Also, my Lua is definitely not up to your level. :)

Hope this helps. Thanks!

----
Reference:
* The following Wikimedia threads on Scribunto and 5.2 support
    * https://lists.wikimedia.org/pipermail/wikitech-l/2014-July/077576.html
    * https://lists.wikimedia.org/pipermail/wikitech-l/2014-July/077586.html
    * https://lists.wikimedia.org/pipermail/wikitech-l/2014-July/077608.html
* The canceled patch to migrate Scribunto from 5.1 to 5.2
    * https://gerrit.wikimedia.org/r/#/c/139479/

Some worthwhile excerpts from the latter. Keep in mind that Tim Starling is the author of Scribunto. My impression is that he is the primary software architect at Wikimedia.
```
Like I said at the start of this project, maybe in a decade or so. Unless there is some actual reason to want to do it?

For some background material about why I don't like the idea of moving to Lua 5.2, you could read:

http://lua-users.org/lists/lua-l/2012-02/msg00127.html
```

**Comment by gnosygnu** [comment]
I'm marking the issue answered for now. Let me know if you have any questions about Lua integration. I really would like Rembulan to be integrated with XOWA, but it's going to require a lot of time to get a 5.3 library to work with Scribunto (5.1). I'm marking this as a future enhancement for now, and will probably close in several days.

Let me know if there's anything else. Thanks.

**Comment by mjanicek** [comment]
Sorry for the late reply! Thank you for your kind words and for the pointers!

Just let me start with:

> maybe in a decade or so

Now that's what I call long-term planning...!

I've looked a little bit into this: I think the step from 5.2 to 5.3 is somewhat less drastic than from 5.1 to 5.2 which you've done with LuaJ. Apart from the standard library functions (which I think could  be emulated / (re)written), there are three other things:
* Lua 5.1 uses `setfenv` and `getfenv` for accessing global variables, while 5.2+ use the `_ENV` upvalue. You probably had to deal with this in your LuaJ-based solution, and possibly it isn't very relevant for Scribunto.
* Lua 5.3 has an integer type, whereas in =< 5.2, all numbers are floating-point. In my experience this is a mostly backward-compatible change, but may introduce very subtle bugs.
* Lua 5.3's `__eq` metamethod has a slightly different meaning compared to 5.2 and 5.1. But again, this might not be an issue in Scribunto.

But unfortunately I have to agree with your assessment that at this point, this issue involves a non-trivial effort. I'll add an issue to Rembulan to keep this in mind, let it gestate for a bit and revisit later. I'll probably need to buy myself a new hard drive to give it a proper test run, though! 😄

**Comment by gnosygnu** [comment]
Cool. Thanks for the breakdown of 5.3 vs 5.2

I'll definitely keep Rembulan in mind for a future enhancement. If Scribunto ever does move to 5.3, then I'll definitely integrate Rembulan into XOWA as an alternate Lua engine. In the meantime, I'll slate it for whenever I have the time (which honestly may be a while)

Let me know if there's anything else. Otherwise, I'll close the issue out in a few days.

Thanks!

**Comment by mjanicek** [comment]
Not at the moment -- I'll get back to you if anything changes. Thanks!

**Comment by gnosygnu** [comment]
Cool. Thanks for the follow-up and the ticket. I'll mark this ticket closed and revisit at a later date.
