### ISSUE TITLE
Is there a way to make HTTP requests to XOWA?

### ISSUE THREAD

**Issue by diugalde** [gnosygnu/xowa#91]
I would like to use curl to get pages hosted in xowa.

**Comment by gnosygnu** [comment]
Hi! Thanks for the interest in XOWA!

Yes, you can use curl to get pages from XOWA using HTTP server. Try the following:
* Launch XOWA from the console with <code>java -jar xowa_linux_64.jar --app_mode http_server</code>
* Launch another console and run any of the following:
   * For the home wiki: <code>curl http://localhost:8080</code>
   * For a page in English Wikipedia: <code>curl http://localhost:8080/en.wikipedia.org/wiki/Earth
</code>

Let me know if you have any other questions. Thanks!

**Comment by gnosygnu** [comment]
I'm going to mark this issue closed for now. Let me know if there's anything else and I'll reopen it. Thanks!

**Comment by diugalde** [comment]
Thank you very much, that was exactly what I needed.
